### ISSUE TITLE
CRIU fails to restore with ssh sessions - /dev/ptmx

### ISSUE THREAD

**Issue by federeghe** [xemul/criu#102]
As I previously posted in mailing list, I found this problem trying to checkpoint the `orted` daemon of open mpi. Now I found a simpler test code: http://pastebin.com/Np7Akqjg

Steps to reproduce the problem:

- open a ssh session on the target host
- `criu dump -j -t 2222 -D directory`
- open another ssh session on the target host (do not close the previous session!)
- `criu restore -j -D directory`

The error reported is:

    2222: Error (tty.c:531): tty: Unable to open dev/ptmx with specified index 1
    2222: Error (tty.c:917): tty: Can't open 2 (index 1): No such file or directory
    Error (cr-restore.c:1264): 2222 killed by signal 9
    Error (cr-restore.c:1995): Restoring FAILED.

**Comment by xemul** [comment]
In your restore command you use different -D directory. Is it a misprint?

**Comment by federeghe** [comment]
Yes sorry, it's a misprint, corrected.

**Comment by cyrillos** [comment]
When we can't open ptmx with specified index in most cases it means that the pts we're about to use is already used by someone else. Look, if you're migrating some application at least devpts filesystem should be mounted with newinstance option. Mind to show "lsof | grep pts/" on both nodes with program running on the source node?

**Comment by xemul** [comment]
@cyrillos , note, that the -j option is in the game. The tty should be inherited from current session, shouldn't it?

**Comment by cyrillos** [comment]
@xemul yes, but there is a _master_ peer opened, masters are never inherited with -j option, only salves are. To inherit master peer from somewhere else one need to pass --inherit-fd @avagin has been developed (not sure if these commits are included into current repo).

**Comment by cyrillos** [comment]
@xemul Note the testcase @federeghe provided -- he opens new fresh pair of pty devices, one points to /dev/ptmx (which is maser) another to /dev/ptsX (which is slave). And on new machine, where we're migrating to, we try to open this pair again, but someone else already borrowed the indices needed.

**Comment by xemul** [comment]
Ah, in simple words -- there's a tty indices conflict?

**Comment by cyrillos** [comment]
@xemul yes, someone else already took this pair on the destination node. For containers we always run them new own devpts, thus on restore new devpts mounted and pairs are restored there.

**Comment by xemul** [comment]
@federeghe , I guess this is not the only conflict you would meet. Another one would be pid conflict, when the process you'll try to restore will have its PID busy by some other task. Is it possible to run your apps in namespaces, so that we could fix these IDs conflicts?

**Comment by federeghe** [comment]
Yes, we have already unshared the PID namespace. Have we to remount the devpts?

(Note that this conflict happens not exclusively during migration, but also in the same machine if f.i. we open a new ssh session)

**Comment by cyrillos** [comment]
Yes, new devpts it preferred.

**Comment by xemul** [comment]
OK, so since this is not really CRIU but, but a configuration problem, I'm closing the issue.

**Comment by federeghe** [comment]
Yes, sorry, I haven't had the chance to test it yet, if the problem won't resolve I'll reopen the bug.

**Comment by federeghe** [comment]
@xemul @cyrillos 

It seems that remount /dev/pts has no effects, it re-creates the same previous /dev/pts/*, even if it is in _unshared_ context. This means that if f.i. /dev/pts/0 is owned by another shell then criu cannot restore a process that uses /dev/pts/0.

**Comment by cyrillos** [comment]
@federeghe Look, the logic used in CRIU is pretty simple -- when it obtain pty reference it look up for mount information too, that said if there some ref to mount point laying outside of application scope we might fail on restore. The option here  might be to use --inherit-fd for terminals but I fear it wont be the only problem you face. Why don't run properly created container via lxc, docker, virtuozzo or something like that? Or it's a primary target to implement minimal working environment for specific application migration?

**Comment by federeghe** [comment]
Yes, our goal is to implement a "migration" of Open MPI processes, minimizing the impact on Open MPI infrastructure. I think that implements containers will cause other problems and performance degradation.
Yes, our goal is to implement a "migration" of Open MPI processes, minimizing the impact on Open MPI infrastructure. I think that implements containers will cause other problems and performance degradation.

Anyway, if we disable pty support in Open MPI, the migration works, so if the problem is not resolvable, we will maintain this limitation (I think that pty support is not really necessary in most mpi applications).

**Comment by cyrillos** [comment]
I see. So then we need to find a way. Letme think, I guess we might try out migration with inherited fd. I'll back to this issue today evening and ping you, ok?

**Comment by cyrillos** [comment]
Oh, @federeghe I'm sorry for my absence :( Been so busy. Hopefully I'll back in Monday and we continue working on the issue, ok?

**Comment by xemul** [comment]
@federeghe , to get the truly _new_ devpts instance, you should mount it with -o newinstance option :)

**Comment by cyrillos** [comment]
Yes, it should be done on destination node. But I guess @federeghe is looking for minimal environment/container which would work for him. So that both devtmpfs and devpts should be mounted properly and /dev/ptmx would point to /dev/pts/ptmx as a symlink.

**Comment by federeghe** [comment]
Argh! I forgot the newinstance option! I'll retry this evening and I'll let you know :) (Should I remount also devtmpfs?)

**Comment by cyrillos** [comment]
I hope not. Just make sure (if plain newinstance option won't help), that /dev/ptmx points to /dev/pts/ptmx

**Comment by federeghe** [comment]
Ok, /dev/pts is now clean (it contains only the /dev/pts/ptmx), however:

(00.025951)   5505: tty: open driver ptmx id 0xa index 1 (master 1 sid 0 pgrp 0 inherit 0)
(00.026024)   5505: tty: 		ptmx opened with index 0
(00.026065)   5505: tty: 		ptmx opened with index 1
(00.026070)   5505: tty: ptmx opened with index 1
(00.026173)   5505: Error (files-reg.c:1273): Can't open file dev/pts/1 on restore: No such file or directory
(00.026180)   5505: Error (files-reg.c:1216): Can't open file dev/pts/1: No such file or directory
(00.026185)   5505: Error (tty.c:782): tty: Can't open slave dev/pts/1: No such file or directory

I'm little confused because the log said "ptmx opened with index 1" but the file does not exist.

I know that this is not a strictly criu-related problem, but I'm sure that you know more about this than me :)

**Comment by cyrillos** [comment]
:-) Looks that devpts is still not mounted with newinstance flag. @federeghe let me explain a bit how this done from inside: there is two points on devpts filesystem -- /dev/ptmx and /dev/pts/$N. Every time you open pty pair (by literally open(/dev/ptmx)) the kernel creates appropriate slave peer in /dev/pts/. Say you open(ptmx) for first time -- the kernel creates master and slave peers with index 1. So that /dev/pts/1 appears. This is usual scenario on the  node. But with newinstance option the things become a bit more complicated -- every new mount of such fs provides you /dev/pts/ptmx device and when you open it the new slave peer get appeared. Thus from the log above it seems that we've opened /dev/ptmx which belong another devpts fs, not the one you mounted with neinstance option.

**Comment by cyrillos** [comment]
mount -t devpts -o newinstance lxcpts /dev/pts
mount -o bind /dev/pts/ptmx /dev/ptmx

**Comment by cyrillos** [comment]
This example from https://lwn.net/Articles/297311/

**Comment by cyrillos** [comment]
So if mounted as above every time we open /dev/ptmx -- we open pty devices from the _new_ devpts we've just mounted and criu should be happy.

**Comment by federeghe** [comment]
Ok, I tried with bash commands and it works :+1: thus, there are some problems with my C code, I'm checking it

**Comment by federeghe** [comment]
I fixed the mount options and now it works! Thank you guys @cyrillos @xemul ! 

If someone needs the C code, see here: http://pastebin.com/8SWUVNKM

**Comment by cyrillos** [comment]
@federeghe Great! Have fun! :-)

**Comment by xemul** [comment]
@federeghe you're always welcome!
