### ISSUE TITLE
add join-namespace flag to criu restore?

### ISSUE THREAD

**Issue by x1022as** [xemul/criu#109]
For now criu restore will inherit parent's Namespaces.  Is it possible to add a new restore flag like --join-namespace for user to specify which namespace to join, like:
```criu restore --join-namespace /proc/xxx/ns/net ... ...```

maybe restore process will call setns() syscall to achieve this(not familiar with criu, so not sure about this)

I think this feature will be flexible and useful : )

Thanks!

ping @xemul

**Comment by xemul** [comment]
@x1022as yup, this is possible :) Would you be able to propose a patch for that? It would be really helpful, I'd really like to get this till the next release, but the time is tight and I need to plan for what to code first.

**Comment by x1022as** [comment]
Hi Pavel,

I am a newbie to criu. But I'd like to have a try.
I don't know when is the next release? will make a plan as soon as possible.

any update will be informed here :)

Thanks

- Deng Guangxing


在 2016/1/30 22:24, Pavel Emelyanov 写道:

**Comment by xemul** [comment]
@x1022as , the next release is Mar 7, but don't hurry too much. After this date the release schedule will be modified to release new features as soon as possible.

**Comment by x1022as** [comment]
Thanks Pavel, I'll try to find out a proper way to achieve this. A plan will go first

在 2016/2/1 21:27, Pavel Emelyanov 写道:

**Comment by xemul** [comment]
The --join-ns option is committed with 2cf17cd83b0bed8f8c754fccd7c1e19bd22539fc into 2.5
