### ISSUE TITLE
CID 157797 (#1 of 1): Explicit null dereferenced (FORWARD_NULL)

### ISSUE THREAD

**Issue by avagin** [xemul/criu#110]
```
2799static struct thread_creds_args *
2800rst_prep_creds_args(CredsEntry *ce, unsigned long *prev_pos)
2801{
2802        unsigned long this_pos = rst_mem_cpos(RM_PRIVATE);
2803        struct thread_creds_args *args;
2804
    	1. Condition !verify_cap_size(ce), taking false branch
2805        if (!verify_cap_size(ce)) {
2806                pr_err("Caps size mismatch %d %d %d %d\n",
2807                       (int)ce->n_cap_inh, (int)ce->n_cap_eff,
2808                       (int)ce->n_cap_prm, (int)ce->n_cap_bnd);
2809                return ERR_PTR(-EINVAL);
2810        }
2811
2812
2813        args = rst_mem_alloc_cont(sizeof(*args), RM_PRIVATE);
    	2. Condition !args, taking false branch
2814        if (!args)
2815                return ERR_PTR(-ENOMEM);
2816
2817        args->cap_last_cap = kdat.last_cap;
2818        memcpy(&args->creds, ce, sizeof(args->creds));
2819
    	3. Condition ce->lsm_profile, taking true branch
2820        if (ce->lsm_profile || opts.lsm_supplied) {
2821                char *rendered, *profile;
2822
2823                profile = ce->lsm_profile;
    	4. Condition opts.lsm_supplied, taking true branch
2824                if (opts.lsm_supplied)
2825                        profile = opts.lsm_profile;
2826
    	5. Condition validate_lsm(profile) < 0, taking false branch
2827                if (validate_lsm(profile) < 0)
2828                        return ERR_PTR(-EINVAL);
2829
    	6. Condition profile, taking true branch
2830                if (profile) {
2831                        size_t lsm_profile_len;
2832                        char *lsm_profile;
2833
    	7. write_zero_model: Passing &rendered to render_lsm_profile, which sets rendered to NULL. [show details]
    	8. Condition render_lsm_profile(profile, &rendered), taking false branch
2834                        if (render_lsm_profile(profile, &rendered))
2835                                return ERR_PTR(-EINVAL);
2836
2837                        args->mem_lsm_profile_pos = rst_mem_cpos(RM_PRIVATE);
    	
CID 157797 (#1 of 1): Explicit null dereferenced (FORWARD_NULL)
9. var_deref_model: Passing null pointer rendered to strlen, which dereferences it.

```

To: @tych0

**Comment by tych0** [comment]
On Fri, Feb 05, 2016 at 10:49:50AM -0800, Andrew Vagin wrote:
> ```2799static struct thread_creds_args *
> 2800rst_prep_creds_args(CredsEntry *ce, unsigned long *prev_pos)
> 2801{
> 2802        unsigned long this_pos = rst_mem_cpos(RM_PRIVATE);
> 2803        struct thread_creds_args *args;
> 2804
>     	1 Condition !verify_cap_size(ce), taking false branch
> 2805        if (!verify_cap_size(ce)) {
> 2806                pr_err("Caps size mismatch %d %d %d %d\n",
> 2807                       (int)ce->n_cap_inh, (int)ce->n_cap_eff,
> 2808                       (int)ce->n_cap_prm, (int)ce->n_cap_bnd);
> 2809                return ERR_PTR(-EINVAL);
> 2810        }
> 2811
> 2812
> 2813        args = rst_mem_alloc_cont(sizeof(*args), RM_PRIVATE);
>     	2 Condition !args, taking false branch
> 2814        if (!args)
> 2815                return ERR_PTR(-ENOMEM);
> 2816
> 2817        args->cap_last_cap = kdatlast_cap;
> 2818        memcpy(&args->creds, ce, sizeof(args->creds));
> 2819
>     	3 Condition ce->lsm_profile, taking true branch
> 2820        if (ce->lsm_profile || optslsm_supplied) {
> 2821                char *rendered, *profile;
> 2822
> 2823                profile = ce->lsm_profile;
>     	4 Condition optslsm_supplied, taking true branch
> 2824                if (optslsm_supplied)
> 2825                        profile = optslsm_profile;
> 2826
>     	5 Condition validate_lsm(profile) < 0, taking false branch
> 2827                if (validate_lsm(profile) < 0)
> 2828                        return ERR_PTR(-EINVAL);
> 2829
>     	6 Condition profile, taking true branch
> 2830                if (profile) {
> 2831                        size_t lsm_profile_len;
> 2832                        char *lsm_profile;
> 2833
>     	7 write_zero_model: Passing &rendered to render_lsm_profile, which sets rendered to NULL [show details]
>     	8 Condition render_lsm_profile(profile, &rendered), taking false branch
> 2834                        if (render_lsm_profile(profile, &rendered))

I think this is actually a false positive; there's no way for it to
take the false branch here when rendered is still set to NULL
according to the implementation of render_lsm_profile.

That said, I think I see a way to fix it so coverity won't complain,
so I'll send that patch.

**Comment by avagin** [comment]
> I think this is actually a false positive;
This is possible. I decided to show it to you, because it looks suspicious for me too.

I found that val will be NULL, if profile is "unconfined". Now I've found that we don't write "unconfined" in images.
