### ISSUE TITLE
Help Wanted: Error (ptrace.c:64): suspending seccomp failed: Invalid argument

### ISSUE THREAD

**Issue by tobwiens** [xemul/criu#112]
Hello, 

I got some problems with Docker and CRIU. 

I get the following error:
```
Error response from daemon: Cannot checkpoint container efeb8933df00: criu failed: type NOTIFY errno 0
log file: /var/lib/docker/0.0/containers/efeb8933df00bd28f8370c794d0043226c44a7f880ca8d01d5b8a976af3af136/criu.work/dump.log
```

dump.log
```
(00.000196) ========================================
(00.000199) Dumping processes (pid: 52159)
(00.000202) ========================================
(00.000205) Running pre-dump scripts
(00.000220)     RPC
(00.000591) Found anon-shmem device at 5
(00.000655) Reset 52428's dirty tracking
(00.004741)  ... done
(00.004822) Dirty track supported on kernel
(00.004923) Found task size of 7ffffffff000
(00.004949) irmap: Searching irmap cache in work dir
(00.004975) No irmap-cache image
(00.004980) irmap: Searching irmap cache in parent
(00.004992) irmap: No irmap cache
(00.005084) cpu: fpu:1 fxsr:1 xsave:1
(00.005281) vdso: Parsing at 7ffd923f3000 7ffd923f5000
(00.005288) vdso: PT_LOAD p_vaddr: 0
(00.005291) vdso: DT_HASH: 120
(00.005294) vdso: DT_STRTAB: 268
(00.005296) vdso: DT_SYMTAB: 160
(00.005299) vdso: DT_STRSZ: 5e
(00.005302) vdso: DT_SYMENT: 18
(00.005304) vdso: nbucket 3 nchain b bucket 7ffd923f3128 chain 7ffd923f3134
(00.005310) vdso: rt [vdso] 7ffd923f3000-7ffd923f5000 [vvar] 7ffd923f1000-7ffd923f3000
(00.005391) Writing image inventory (version 1)
(00.005618) Add pid ns 1 pid 52428
(00.005630) Add net ns 2 pid 52428
(00.005639) Add ipc ns 3 pid 52428
(00.005647) Add uts ns 4 pid 52428
(00.005655) Add mnt ns 5 pid 52428
(00.005664) Add user ns 6 pid 52428
(00.005668) cg: Dumping cgroups for 52428
(00.005715) cg:  `- New css ID 1
(00.005721) cg:     `- [blkio] -> [/system.slice]
(00.005724) cg:     `- [cpu,cpuacct] -> [/system.slice]
(00.005726) cg:     `- [cpuset] -> [/system.slice]
(00.005729) cg:     `- [devices] -> [/system.slice/docker.service]
(00.005731) cg:     `- [freezer] -> [/system.slice]
(00.005734) cg:     `- [hugetlb] -> [/system.slice]
(00.005736) cg:     `- [memory] -> [/system.slice]
(00.005739) cg:     `- [name=systemd] -> [/system.slice/docker.service]
(00.005742) cg:     `- [net_cls,net_prio] -> [/system.slice]
(00.005744) cg:     `- [perf_event] -> [/system.slice]
(00.005747) cg: Set 1 is criu one
(00.006014) Error (ptrace.c:64): suspending seccomp failed: Invalid argument
(00.006038) Unfreezing tasks into 1
(00.006043)     Unseizing 52159 into 1
(00.006047) Error (ptrace.c:54): Unable to detach from 52159: No such process
(00.006052) Unlock network
(00.006056) Unfreezing tasks into 1
(00.006058)     Unseizing 52159 into 1
(00.006061) Error (ptrace.c:54): Unable to detach from 52159: No such process
(00.006098) Error (cr-dump.c:1641): Dumping FAILED.
```

The CRIU version is 1.8

Here is what I did
Ubuntu 14.04.3
- Made the docker experimental binary
- Execute the binary inside the docker build container docker-dev:cr-combined. When executing docker checkpoint [Container-ID] it get the above error.

- I also installed criu on the host machine
- Ran the experimental docker daemon
- I get the same error as above

Ubuntu 15.10:
- Ran into the exact same problem on Ubuntu 15.10

So I ran it in 4 different setups, on Ubuntu 14.04.3, on Ubuntu 15.10, on Ubuntu 15.10 in the docker-criu Ubuntu 14.04 container and on Ubuntu 14.04.3 in the docker-criu Ubuntu 14.04 container. And I get always the same error.

When I dump the process without Docker:
```
criu dump -t 52159Error (ptrace.c:64): suspending seccomp failed: Invalid argument
Error (ptrace.c:54): Unable to detach from 52159: No such process
Error (ptrace.c:54): Unable to detach from 52159: No such process
Error (cr-dump.c:1641): Dumping FAILED.
```

So I tried to validate if CRIU works in general with:
```
nohup ./test.sh &
```
Then closed the terminal which I created the process with. 
Then I get the process id of test.sh
```
criu dump -t 43301
Warn  (arch/x86/crtools.c:133): Will restore 63207 with interrupted system call
Error (pstree.c:260): The root process 43301 is not a session leader. Consider using --shell-job option
Error (cr-dump.c:1641): Dumping FAILED.
```

So I thought the parent process ID will solve that issue:
but no luck with that:
```
criu dump -t 9103
Warn  (ptrace.c:82): Unable to interrupt task: 62803 (Operation not permitted)
Error (ptrace.c:187): The criu itself is within dumped tree.
Warn  (ptrace.c:82): Unable to interrupt task: 62803 (Operation not permitted)
Error (ptrace.c:187): The criu itself is within dumped tree.
Warn  (ptrace.c:82): Unable to interrupt task: 62803 (Operation not permitted)
Error (ptrace.c:187): The criu itself is within dumped tree.
Warn  (ptrace.c:82): Unable to interrupt task: 62803 (Operation not permitted)
Error (ptrace.c:187): The criu itself is within dumped tree.
Warn  (ptrace.c:82): Unable to interrupt task: 62803 (Operation not permitted)
Error (ptrace.c:187): The criu itself is within dumped tree.
Warn  (ptrace.c:82): Unable to interrupt task: 62803 (Operation not permitted)
Error (ptrace.c:187): The criu itself is within dumped tree.
Error (ptrace.c:54): Unable to detach from 9103: No such process
Error (ptrace.c:54): Unable to detach from 9182: No such process
Error (ptrace.c:54): Unable to detach from 9196: No such process
Error (ptrace.c:54): Unable to detach from 9208: No such process
Error (ptrace.c:54): Unable to detach from 9222: No such process
Error (ptrace.c:54): Unable to detach from 9231: No such process
Error (ptrace.c:54): Unable to detach from 9240: No such process
```

The I added the --shell-job option as suggested by criu:
```
criu dump -t 43301 --shell-job option
Warn  (arch/x86/crtools.c:133): Will restore 65029 with interrupted system call
```
Seems to work, now restore:
```
criu restore
 65029: Error (cr-restore.c:1343): Requested sid 42198 doesn't match inherited 82579
 43301: Error (cr-restore.c:1262): 65029 exited, status=1
Error (cr-restore.c:1995): Restoring FAILED.
Error (cr-restore.c:1264): 43301 killed by signal 9
```

1) Is CRIU wrong installed in all the setups? I use the installation procedure inside the docker-criu Dockerfile. For Ubuntu 15.10, I changed some dependencies. 
2) What do I miss? 
3) How can I solve this?

Thanks for your help.

**Comment by xemul** [comment]
Let's resolve one problem per issue :) The original one is

    (00.006014) Error (ptrace.c:64): suspending seccomp failed: Invalid argument

this means, that seccomp support is not present in the kernel, you can check this by running

    criu check

would you?

**Comment by tobwiens** [comment]
Thank you. I agree, I thought it might be connected.

```
criu check
Error (cr-check.c:634): Kernel doesn't support PTRACE_O_SUSPEND_SECCOMP
Error (cr-check.c:683): Dumping seccomp filters not supported: Input/output error
```

**Comment by tobwiens** [comment]
Thank you very much, I found the solution. :+1:
add --security-opt seccomp:unconfined to the docker run command.

That way seccomp is deactivated for that specific container and CRIU is able to dump it to disk.

**Comment by Fuzzyma** [comment]
I will leave this here:
On ubuntu 14.04 with Kernel 4.2.0-42-generic `criu check --all` prints `Looks good`. 
Checkpointing doenst work anyway without `--security-opt seccomp:unconfined`

**Comment by xemul** [comment]
Cc @tych0

**Comment by tych0** [comment]
Sorry, I'm confused; is the problem with seccomp or something else?

The 4.2 kernel is too old and doesn't have seccomp checkpoint support. You can install the `linux-generic-lts-xenial` kernel to get a newer kernel, though.

**Comment by Fuzzyma** [comment]
It's only about criu check not reporting this error. It just prints okay and doesn't say that a newer kernel is needed

**Comment by tych0** [comment]
Hmm. Where did you get the kernel from? You mention that it doesn't work; does it fail before checkpointing the seccomp filters? I'm wondering if your kernel has the backported patches.

**Comment by Fuzzyma** [comment]
Can't say from my current place. It was installed via apt get. I think
something like linux-generic-wizy or so. I will check that when I am home.
I wrote down the command I used.

Tycho Andersen <notifications@github.com> schrieb am Di., 02.08.2016, 16:44:

**Comment by tych0** [comment]
Ok, I just looked and `linux-generic-lts-wily` has the seccomp patches in it, so if that's where you got the kernel, it has support for this, which is why it says "looks good". Likely your checkpoint is failing for other reasons, so it would be good to sort those out (probably in a new issue)

**Comment by Fuzzyma** [comment]
Yes thats exactly the one I used. 
I wrote it here because I get the same error in the log:

```
(00.019236) Error (ptrace.c:64): suspending seccomp failed: Invalid argument
(00.019314) Unlock network
(00.019329) Unfreezing tasks into 1
(00.019383)     Unseizing 32058 into 1
(00.019398) Error (ptrace.c:54): Unable to detach from 32058: No such process
(00.019568) Error (cr-dump.c:1614): Dumping FAILED.
```

However - If this is worth a new issue I will raise it

**Comment by xemul** [comment]
@Fuzzyma , sure, new issue is definitely worth raising.
