### ISSUE TITLE
Error CRIU restore because pid not matched

### ISSUE THREAD

**Issue by zlcherish** [xemul/criu#113]
Now I 'm trying to dump and restore on the different hosts.Occasionally,when i restore a process with criu, get the error in restore log:
    pie: Error (pie/restorer.c:407): Thread pid mismatch 31/30
    pie: Error (pie/restorer.c:454): Restorer abnormal termination for 16>
Any help? Thank you.

**Comment by avagin** [comment]
You can try to restore processes in a new pid namespace.
https://criu.org/When_C/R_fails

**Comment by zlcherish** [comment]
Can you tell me the detailes of how to restore processes in a new pid namespace? Use the "unshare -p --fork" command? It does not work on my host. I get the error:
unshare: invalid option -- 'p'
Because '-p' is not a valid option. Why? My docker containers running on ubuntu 14.04. And the valid options:
Options:
 -h, --help           usage information (this)
 -m, --mount       unshare mounts namespace
 -u, --uts             unshare UTS namespace (hostname etc)
 -i, --ipc              unshare System V IPC namespace
 -n, --net            unshare network namespace
I am waiting for your help.Thank you.

**Comment by zlcherish** [comment]
Can you tell me the detailes of how to restore processes in a new pid namespace? Use the "unshare -p --fork" command? It does not work on my host. I get the error:
unshare: invalid option -- 'p'
Because '-p' is not a valid option. Why? My docker containers running on ubuntu 14.04. And the valid options:
Options:
-h, --help usage information (this)
-m, --mount unshare mounts namespace
-u, --uts unshare UTS namespace (hostname etc)
-i, --ipc unshare System V IPC namespace
-n, --net unshare network namespace
I am waiting for your help.Thank you.
@avagin

**Comment by xemul** [comment]
@zlcherish , the unshare tool you have it too old.
As another option, you might be interested in this patchset: https://lists.openvz.org/pipermail/criu/2015-December/023995.html

It would unshare the restored stuff into the namespacecs you want. It's not yet merged, but will be some day. There are some issues with it, feel free to join the discussion on the mailing list.

**Comment by zlcherish** [comment]
@xemul About what time it will be merged? I need it now. 
And now,if I restore a process twice,I will be successful. I don't know why,but it is extremely useful.

**Comment by xemul** [comment]
@zlcherish , there are three issues with this set that are still not resolved

1. user namespace is not supported for unshare
2. dump of what was restored into --unshare context won't work
3. no tests for this mode

If this suits you, I think I can merge the existing patch-set right after 2.0 release.

**Comment by xemul** [comment]
Duplicate for #108
