### ISSUE TITLE
make install failure

### ISSUE THREAD

**Issue by Andrew-Machen** [xemul/criu#114]
I am trying to build criu from source, found in this git repository. I have followed the instruction on criu.org, and successfully ran 'make'. However, 'sudo make install' gives me the following error:

...
running install_scripts
changing mode of local/bin/crit to 755
running install_egg_info
Removing local/lib/python2.7/dist-packages/crit-0.0.1.egg-info
Writing local/lib/python2.7/dist-packages/crit-0.0.1.egg-info
  INSTALL 
mkdir: missing operand
Try 'mkdir --help' for more information.
Makefile.install:4: recipe for target 'install-criu' failed
make: *** [install-criu] Error 1

Looking at the Makefiles it looks like the variables DESTDIR, SBINDIR, etc... are not being defined. Have I missed an install step?

I am attempting this on Lubuntu 15.10

**Comment by xemul** [comment]
Cc @cyrillos . Presumably this is what you're currently working on.

**Comment by cyrillos** [comment]
Already sent a patch. [PATCH] build: Bring install back to life
