### ISSUE TITLE
Path for prev images dir should always be relative

### ISSUE THREAD

**Issue by KKoukiou** [xemul/criu#116]
Hi, 
i am trying to do incremental dumps to checkpoint an lxc container and then restore it on another host . The pre-dump and dump parts, all  finish successfully but the restore phase fails with the following error:
"(00.243143)   2014: Error (page-read.c:75): No parent for snapshot pagemap"
That only happens when the "pages_skipped_parent" value in the crit-decoded stats-dump file is not zero. Otherwise restore is succesfull. Also restore succeeds when not doing incremental dumps.
I attach the 2 pre-dump.logs, the 3rd dump.log , the failing restore.log, and the decoded pagemap-2014.img files for the three dumps respectively which if I get right are the one to blame.

System information follows (same on both hosts):
The container was created with "lxc-create -t ubuntu -n u1 -- -r trusty -a amd64" and it is running a memory intensive simple c program.
~# uname -r 
4.2.0-23-generic

~# criu --version 
Version: 1.8
GitID: v1.8-211-gef074d3

~# dpkg -s lxc | grep Version
Version: 1.1.5-0ubuntu0.15.10.3

~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily

Do you have any idea what's going wrong?
Katerina

[pagemap-2014-1.txt](https://github.com/xemul/criu/files/144225/pagemap-2014-1.txt)
[pagemap-2014-2.txt](https://github.com/xemul/criu/files/144229/pagemap-2014-2.txt)
[pagemap-2014-3.txt](https://github.com/xemul/criu/files/144227/pagemap-2014-3.txt)
[pre-dump_1.txt](https://github.com/xemul/criu/files/144228/pre-dump_1.txt)
[pre-dump_2.txt](https://github.com/xemul/criu/files/144226/pre-dump_2.txt)
[dump_3.txt](https://github.com/xemul/criu/files/144223/dump_3.txt)
[restore.txt](https://github.com/xemul/criu/files/144224/restore.txt)

**Comment by xemul** [comment]
How do directories with dumps look like? In the 2nd one there should be a "parent" link pointing to the 1st one.

**Comment by KKoukiou** [comment]
I have different directories for each dump iteration. In each checkpoint directory apart from the first iteration's, there is a "parent" symbolic link pointing to the previous checkpoint directory like this  :
~#  file /var/lib/lxc/trusty11/checkpoint/2/parent
/var/lib/lxc/trusty11/checkpoint/2/parent: symbolic link to /var/lib/lxc/trusty11/checkpoint/1/

**Comment by xemul** [comment]
OK, so the log says that:
> 2014: Opened page read 2 (parent 0)
which means that the pagemap's parent is not found.

What's there in /var/lib/lxc/trusty11/checkpoint/1 and /var/lib/lxc/trusty11/checkpoint/2 directories? Can you show the ls -l output on both?

**Comment by KKoukiou** [comment]
I have overwritten the previous directories, so I send information about a new one iterative dump, with exact the same error on restore.
There are 2 directories , one for the pre-dump phase and one for the final dump.
I attach the logs and the decoded images for pagemap-1.img as before ,and the show the output of ls -la for the two dirs.
The error now is :
(00.801229)      1: Opened page read 1 (parent 0)
(00.801241)      1: pr1 Read 55b1a6b03000 1 pages
(00.801253)      1: 	pr1 Read page from self 55b1a6b03000/0
(00.804615)      1: Error (page-read.c:75): No parent for snapshot pagemap

[pagemap-1_pre-dump.txt](https://github.com/xemul/criu/files/148570/pagemap-1_pre-dump.txt)
[pagemap-1_dump.txt](https://github.com/xemul/criu/files/148569/pagemap-1_dump.txt)

[pre-dump.txt](https://github.com/xemul/criu/files/148556/pre-dump.txt)
[dump.txt](https://github.com/xemul/criu/files/148558/dump.txt)
[restore.txt](https://github.com/xemul/criu/files/148559/restore.txt)

#The directory 1 is for thhe pre-dump , the 2 is for the final-dump.
root@xenon7:/var/lib/lxc/trusty13/checkpoint# ls
1  2
root@xenon7:/var/lib/lxc/trusty13/checkpoint/1# ls -la
total 269212
drwxr-xr-x 2 root root       740 Feb 26 18:12 .
drwx------ 4 root root        80 Feb 26 18:12 ..
-rw-r--r-- 1 root root        53 Feb 26 18:12 irmap-cache
-rw-r--r-- 1 root root       337 Feb 26 18:12 pagemap-1.img
-rw-r--r-- 1 root root       461 Feb 26 18:12 pagemap-1082.img
-rw-r--r-- 1 root root       254 Feb 26 18:12 pagemap-1447.img
-rw-r--r-- 1 root root       296 Feb 26 18:12 pagemap-1661.img
-rw-r--r-- 1 root root       184 Feb 26 18:12 pagemap-1752.img
-rw-r--r-- 1 root root      2068 Feb 26 18:12 pagemap-1753.img
-rw-r--r-- 1 root root       131 Feb 26 18:12 pagemap-1754.img
-rw-r--r-- 1 root root       201 Feb 26 18:12 pagemap-1794.img
-rw-r--r-- 1 root root       201 Feb 26 18:12 pagemap-1796.img
-rw-r--r-- 1 root root       201 Feb 26 18:12 pagemap-1798.img
-rw-r--r-- 1 root root       187 Feb 26 18:12 pagemap-1800.img
-rw-r--r-- 1 root root       187 Feb 26 18:12 pagemap-1802.img
-rw-r--r-- 1 root root       224 Feb 26 18:12 pagemap-589.img
-rw-r--r-- 1 root root       266 Feb 26 18:12 pagemap-774.img
-rw-r--r-- 1 root root       436 Feb 26 18:12 pagemap-817.img
-rw-r--r-- 1 root root       224 Feb 26 18:12 pagemap-998.img
-rw-r--r-- 1 root root   1040384 Feb 26 18:12 pages-1.img
-rw-r--r-- 1 root root 268537856 Feb 26 18:12 pages-10.img
-rw-r--r-- 1 root root    110592 Feb 26 18:12 pages-11.img
-rw-r--r-- 1 root root    176128 Feb 26 18:12 pages-12.img
-rw-r--r-- 1 root root    172032 Feb 26 18:12 pages-13.img
-rw-r--r-- 1 root root    176128 Feb 26 18:12 pages-14.img
-rw-r--r-- 1 root root    176128 Feb 26 18:12 pages-15.img
-rw-r--r-- 1 root root    176128 Feb 26 18:12 pages-16.img
-rw-r--r-- 1 root root    266240 Feb 26 18:12 pages-2.img
-rw-r--r-- 1 root root    217088 Feb 26 18:12 pages-3.img
-rw-r--r-- 1 root root    442368 Feb 26 18:12 pages-4.img
-rw-r--r-- 1 root root    245760 Feb 26 18:12 pages-5.img
-rw-r--r-- 1 root root    561152 Feb 26 18:12 pages-6.img
-rw-r--r-- 1 root root   2359296 Feb 26 18:12 pages-7.img
-rw-r--r-- 1 root root    241664 Feb 26 18:12 pages-8.img
-rw-r--r-- 1 root root    249856 Feb 26 18:12 pages-9.img
-rw------- 1 root root    447626 Feb 26 18:12 pre-dump.log
-rw-r--r-- 1 root root        41 Feb 26 18:12 stats-dump

root@xenon7:/var/lib/lxc/trusty13/checkpoint/2# ls -la
total 265380
drwxr-xr-x 2 root root      3400 Feb 26 18:12 .
drwx------ 4 root root        80 Feb 26 18:12 ..
-rw-r--r-- 1 root root      1225 Feb 26 18:12 cgroup.img
-rw-r--r-- 1 root root       860 Feb 26 18:12 core-1.img
-rw-r--r-- 1 root root       831 Feb 26 18:12 core-1082.img
-rw-r--r-- 1 root root       546 Feb 26 18:12 core-1085.img
-rw-r--r-- 1 root root       543 Feb 26 18:12 core-1086.img
-rw-r--r-- 1 root root       546 Feb 26 18:12 core-1087.img
-rw-r--r-- 1 root root       881 Feb 26 18:12 core-1447.img
-rw-r--r-- 1 root root       885 Feb 26 18:12 core-1661.img
-rw-r--r-- 1 root root       864 Feb 26 18:12 core-1752.img
-rw-r--r-- 1 root root       839 Feb 26 18:12 core-1753.img
-rw-r--r-- 1 root root       854 Feb 26 18:12 core-1754.img
-rw-r--r-- 1 root root       838 Feb 26 18:12 core-1820.img
-rw-r--r-- 1 root root       838 Feb 26 18:12 core-1822.img
-rw-r--r-- 1 root root       838 Feb 26 18:12 core-1824.img
-rw-r--r-- 1 root root       832 Feb 26 18:12 core-1825.img
-rw-r--r-- 1 root root       838 Feb 26 18:12 core-1828.img
-rw-r--r-- 1 root root       868 Feb 26 18:12 core-589.img
-rw-r--r-- 1 root root       861 Feb 26 18:12 core-774.img
-rw-r--r-- 1 root root       839 Feb 26 18:12 core-817.img
-rw-r--r-- 1 root root       868 Feb 26 18:12 core-998.img
-rw------- 1 root root    618253 Feb 26 18:12 dump.log
-rw-r--r-- 1 root root       100 Feb 26 18:12 eventpoll.img
-rw-r--r-- 1 root root        57 Feb 26 18:12 fdinfo-10.img
-rw-r--r-- 1 root root        44 Feb 26 18:12 fdinfo-11.img
-rw-r--r-- 1 root root        44 Feb 26 18:12 fdinfo-12.img
-rw-r--r-- 1 root root        44 Feb 26 18:12 fdinfo-13.img
-rw-r--r-- 1 root root        44 Feb 26 18:12 fdinfo-14.img
-rw-r--r-- 1 root root        44 Feb 26 18:12 fdinfo-15.img
-rw-r--r-- 1 root root        44 Feb 26 18:12 fdinfo-16.img
-rw-r--r-- 1 root root        44 Feb 26 18:12 fdinfo-17.img
-rw-r--r-- 1 root root       200 Feb 26 18:12 fdinfo-2.img
-rw-r--r-- 1 root root        92 Feb 26 18:12 fdinfo-3.img
-rw-r--r-- 1 root root        92 Feb 26 18:12 fdinfo-4.img
-rw-r--r-- 1 root root       152 Feb 26 18:12 fdinfo-5.img
-rw-r--r-- 1 root root        80 Feb 26 18:12 fdinfo-6.img
-rw-r--r-- 1 root root        56 Feb 26 18:12 fdinfo-7.img
-rw-r--r-- 1 root root       116 Feb 26 18:12 fdinfo-8.img
-rw-r--r-- 1 root root        56 Feb 26 18:12 fdinfo-9.img
-rw-r--r-- 1 root root        25 Feb 26 18:12 filelocks.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-1.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-1082.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-1447.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-1661.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-1752.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-1753.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-1754.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-1820.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-1822.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-1824.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-1825.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-1828.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-589.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-774.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-817.img
-rw-r--r-- 1 root root        18 Feb 26 18:12 fs-998.img
-rw-r--r-- 1 root root        50 Feb 26 18:12 ghost-file-1.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-1.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-1082.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-1447.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-1661.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-1752.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-1753.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-1754.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-1820.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-1822.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-1824.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-1825.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-1828.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-589.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-774.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-817.img
-rw-r--r-- 1 root root        32 Feb 26 18:12 ids-998.img
-rw-r--r-- 1 root root       312 Feb 26 18:12 ifaddr-8.img
-rw-r--r-- 1 root root       266 Feb 26 18:12 inetsk.img
-rw-r--r-- 1 root root       233 Feb 26 18:12 inotify.img
-rw-r--r-- 1 root root        38 Feb 26 18:12 inventory.img
-rw-r--r-- 1 root root       249 Feb 26 18:12 ip6tables-8.img
-rw-r--r-- 1 root root        77 Feb 26 18:12 ipcns-var-9.img
-rw-r--r-- 1 root root       713 Feb 26 18:12 iptables-8.img
-rw-r--r-- 1 root root      2707 Feb 26 18:12 mm-1.img
-rw-r--r-- 1 root root      3153 Feb 26 18:12 mm-1082.img
-rw-r--r-- 1 root root      1036 Feb 26 18:12 mm-1447.img
-rw-r--r-- 1 root root      2150 Feb 26 18:12 mm-1661.img
-rw-r--r-- 1 root root      1178 Feb 26 18:12 mm-1752.img
-rw-r--r-- 1 root root       824 Feb 26 18:12 mm-1753.img
-rw-r--r-- 1 root root       853 Feb 26 18:12 mm-1754.img
-rw-r--r-- 1 root root      1417 Feb 26 18:12 mm-1820.img
-rw-r--r-- 1 root root      1417 Feb 26 18:12 mm-1822.img
-rw-r--r-- 1 root root      1417 Feb 26 18:12 mm-1824.img
-rw-r--r-- 1 root root      1417 Feb 26 18:12 mm-1825.img
-rw-r--r-- 1 root root      1417 Feb 26 18:12 mm-1828.img
-rw-r--r-- 1 root root      1572 Feb 26 18:12 mm-589.img
-rw-r--r-- 1 root root      1840 Feb 26 18:12 mm-774.img
-rw-r--r-- 1 root root      3420 Feb 26 18:12 mm-817.img
-rw-r--r-- 1 root root      1605 Feb 26 18:12 mm-998.img
-rw-r--r-- 1 root root      4022 Feb 26 18:12 mountpoints-11.img
-rw-r--r-- 1 root root       173 Feb 26 18:12 netdev-8.img
-rw-r--r-- 1 root root       154 Feb 26 18:12 netlinksk.img
-rw-r--r-- 1 root root       128 Feb 26 18:12 netns-8.img
-rw-r--r-- 1 root root       198 Feb 26 18:12 packetsk.img
-rw-r--r-- 1 root root       746 Feb 26 18:12 pagemap-1.img
-rw-r--r-- 1 root root       759 Feb 26 18:12 pagemap-1082.img
-rw-r--r-- 1 root root       300 Feb 26 18:12 pagemap-1447.img
-rw-r--r-- 1 root root       430 Feb 26 18:12 pagemap-1661.img
-rw-r--r-- 1 root root       222 Feb 26 18:12 pagemap-1752.img
-rw-r--r-- 1 root root      2098 Feb 26 18:12 pagemap-1753.img
-rw-r--r-- 1 root root       191 Feb 26 18:12 pagemap-1754.img
-rw-r--r-- 1 root root       187 Feb 26 18:12 pagemap-1820.img
-rw-r--r-- 1 root root       187 Feb 26 18:12 pagemap-1822.img
-rw-r--r-- 1 root root       201 Feb 26 18:12 pagemap-1824.img
-rw-r--r-- 1 root root       187 Feb 26 18:12 pagemap-1825.img
-rw-r--r-- 1 root root       187 Feb 26 18:12 pagemap-1828.img
-rw-r--r-- 1 root root       470 Feb 26 18:12 pagemap-589.img
-rw-r--r-- 1 root root       384 Feb 26 18:12 pagemap-774.img
-rw-r--r-- 1 root root       540 Feb 26 18:12 pagemap-817.img
-rw-r--r-- 1 root root       382 Feb 26 18:12 pagemap-998.img
-rw-r--r-- 1 root root    729088 Feb 26 18:12 pages-1.img
-rw-r--r-- 1 root root 268443648 Feb 26 18:12 pages-10.img
-rw-r--r-- 1 root root     12288 Feb 26 18:12 pages-11.img
-rw-r--r-- 1 root root    176128 Feb 26 18:12 pages-12.img
-rw-r--r-- 1 root root    176128 Feb 26 18:12 pages-13.img
-rw-r--r-- 1 root root    176128 Feb 26 18:12 pages-14.img
-rw-r--r-- 1 root root    176128 Feb 26 18:12 pages-15.img
-rw-r--r-- 1 root root    172032 Feb 26 18:12 pages-16.img
-rw-r--r-- 1 root root     98304 Feb 26 18:12 pages-2.img
-rw-r--r-- 1 root root     57344 Feb 26 18:12 pages-3.img
-rw-r--r-- 1 root root     12288 Feb 26 18:12 pages-4.img
-rw-r--r-- 1 root root    102400 Feb 26 18:12 pages-5.img
-rw-r--r-- 1 root root    126976 Feb 26 18:12 pages-6.img
-rw-r--r-- 1 root root      8192 Feb 26 18:12 pages-7.img
-rw-r--r-- 1 root root     36864 Feb 26 18:12 pages-8.img
-rw-r--r-- 1 root root      8192 Feb 26 18:12 pages-9.img
lrwxrwxrwx 1 root root        35 Feb 26 18:12 parent -> /var/lib/lxc/trusty13/checkpoint/1/
-rw-r--r-- 1 root root        64 Feb 26 18:12 pipes-data.img
-rw-r--r-- 1 root root       216 Feb 26 18:12 pipes.img
-rw-r--r-- 1 root root       303 Feb 26 18:12 pstree.img
-rw-r--r-- 1 root root      4394 Feb 26 18:12 reg-files.img
-rw-r--r-- 1 root root        28 Feb 26 18:12 remap-fpath.img
-rw-r--r-- 1 root root       116 Feb 26 18:12 route-8.img
-rw-r--r-- 1 root root       120 Feb 26 18:12 route6-8.img
-rw-r--r-- 1 root root      1106 Feb 26 18:12 sigacts-1.img
-rw-r--r-- 1 root root       912 Feb 26 18:12 sigacts-1082.img
-rw-r--r-- 1 root root       752 Feb 26 18:12 sigacts-1447.img
-rw-r--r-- 1 root root       780 Feb 26 18:12 sigacts-1661.img
-rw-r--r-- 1 root root       786 Feb 26 18:12 sigacts-1752.img
-rw-r--r-- 1 root root       752 Feb 26 18:12 sigacts-1753.img
-rw-r--r-- 1 root root       752 Feb 26 18:12 sigacts-1754.img
-rw-r--r-- 1 root root       791 Feb 26 18:12 sigacts-1820.img
-rw-r--r-- 1 root root       791 Feb 26 18:12 sigacts-1822.img
-rw-r--r-- 1 root root       791 Feb 26 18:12 sigacts-1824.img
-rw-r--r-- 1 root root       791 Feb 26 18:12 sigacts-1825.img
-rw-r--r-- 1 root root       791 Feb 26 18:12 sigacts-1828.img
-rw-r--r-- 1 root root       824 Feb 26 18:12 sigacts-589.img
-rw-r--r-- 1 root root       824 Feb 26 18:12 sigacts-774.img
-rw-r--r-- 1 root root       783 Feb 26 18:12 sigacts-817.img
-rw-r--r-- 1 root root       824 Feb 26 18:12 sigacts-998.img
-rw-r--r-- 1 root root        41 Feb 26 18:12 signalfd.img
-rw-r--r-- 1 root root        41 Feb 26 18:12 stats-dump
-rw-r--r-- 1 root root      1133 Feb 26 18:12 tmpfs-dev-43.tar.gz.img
-rw-r--r-- 1 root root       295 Feb 26 18:12 tmpfs-dev-47.tar.gz.img
-rw-r--r-- 1 root root      1623 Feb 26 18:12 tmpfs-dev-49.tar.gz.img
-rw-r--r-- 1 root root        97 Feb 26 18:12 tmpfs-dev-50.tar.gz.img
-rw-r--r-- 1 root root        96 Feb 26 18:12 tmpfs-dev-51.tar.gz.img
-rw-r--r-- 1 root root        96 Feb 26 18:12 tmpfs-dev-53.tar.gz.img
-rw-r--r-- 1 root root      1716 Feb 26 18:12 tty-info.img
-rw-r--r-- 1 root root       248 Feb 26 18:12 tty.img
-rw-r--r-- 1 root root      1015 Feb 26 18:12 unixsk.img
-rw-r--r-- 1 root root        30 Feb 26 18:12 utsns-10.img

**Comment by xemul** [comment]
Strange. The parent images are not openable for some reason.The criu/page-read.c's code in open_page_read_at() calls try_open_parent() which opens "parent" link (which is there) then checks for failure with ENOENT code and only in this case proceeds with NULL parent.

@KKoukiou what would be easier for you, if I provide you patches with extended logging or ask you to strace the criu restore command?

**Comment by KKoukiou** [comment]
I used to restore with lxc-checkpoint -r, but under strace this gives me a different restore.log with error 

(00.045280) PID: real 13915 virt 1
(00.048817) Error (cr-restore.c:1961): Can't attach to init: Operation not permitted
(00.049416) Warn  (cr-restore.c:2107): Unable to wait 13915: No child processes(00.087845) Error (files-reg.c:463):  `- XFail [/dev/null.cr.1.ghost] ghost: No such file or directory

This happens when i use the -f flag to strace also forked processes. Without it,the strace output is not usefull. 
The command  run is (without the -f flag) : 
`root@xenon8:~/lxc# strace -o strace.txt -s 150 lxc-checkpoint -r -n trusty13 -D /var/lib/lxc/trusty13/checkpoint/2 -vvvvvv
lxc-checkpoint: lxccontainer.c: do_lxcapi_restore: 3876 restore process died
Restoring trusty13 failed.`
I here is the [strace.txt](https://github.com/xemul/criu/files/149117/strace.txt)  without the -f flag , though i think its not useful. 
So is there another way to right strace criu restore process? Otherwise, I can try the patches.

**Comment by KKoukiou** [comment]
I tried to strace with the actual criu command and gives me the restore.log as normal with the "No parent for snapshot pagemap" error. So, when I run 
`# strace -o log -f -T criu restore ...` I get this log file [strace.txt](https://github.com/xemul/criu/files/149122/strace.txt)

**Comment by xemul** [comment]
The strace.txt seem to only have the parent process traces. In particular the write system call writing the "No parent for snapshot pagemap" is not there.

**Comment by xemul** [comment]
OK, would you try with this patch, -v4 option for criu and report back the restore.log file: https://gist.github.com/xemul/381389c02b4c173ae2ca

**Comment by KKoukiou** [comment]
Sorry for the delay, here is  the restore.log :
[restore-debug.txt](https://github.com/xemul/criu/files/151020/restore-debug.txt)

**Comment by xemul** [comment]
Ah, here it is:

    (00.244577)      1: Try open parent for 1, dfd 1022
    (00.244985)      1:  `- no parent (parent) symlink

this means that the opening the "parent" symlink ended up with ENOENT. This happens since the symlink target is absolute path that is not visible in the mount namespace the task #1 has recently jumped into.

Can you fix the parent symlink to have target literally "../1" (dot dot slash one) rather than what it is now and try again?

**Comment by KKoukiou** [comment]
That was it! Thank you!

**Comment by xemul** [comment]
@tych0 , presumably it's an issue for LXC/LXD -- the --prev-images-dir path should be relative, not absolute for incremental dumps.

**Comment by tych0** [comment]
@xemul yes, although I don't think lxc or lxd has any code that actually uses our `->migrate` API call which provides pre-dump dirs yet, so I'm not sure where that path came from. @KKoukiou, do you have some code you wrote using liblxc directly?

**Comment by KKoukiou** [comment]
The path came from the --prev-images-dir from the criu dump command. There I had an absolute path to the previous checkpoint directory. So I just used the criu tool directly (I mean criu (pre-)dump and criu restore...) to iteratively checkpoint and restore the container.

**Comment by xemul** [comment]
Ah, I see :) OK, then I'll close this bug as there's not much we can do here. And there's also a patch on the mailing list that warns users on dump when absolute path is used.
