### ISSUE TITLE
git criu does not compile on the daily Ubuntu server Xenial (16.04)

### ISSUE THREAD

**Issue by ayourtch** [xemul/criu#117]
Trying to compile cry on a fresh install of Xenial ubuntu-server daily build. Using the base install (from iso downloaded off http://cdimage.ubuntu.com/ubuntu-server/daily/current/) with ssh server enabled,  
and the following additional command for the rest of the packages:

sudo apt install build-essential libprotobuf-dev libprotobuf-c0-dev protobuf-c-compiler protobuf-compiler python-protobuf autoconf curl g++ libtool pkg-config

Following the install,  performed the "git clone https://github.com/xemul/criu"

Then "make" within the criu directory fails as follows:

  CC       images/opts.o
  CC       images/seccomp.o
  CC       images/binfmt-misc.o
  CC       images/time.o
  LINK     images/built-in.o
  GEN      include/config.h
  GEN      include/version.h
  DEP      pie/piegen/main.d
pie/piegen/main.c:16:22: fatal error: compiler.h: No such file or directory
compilation terminated.
  DEP      pie/piegen/elf-x86-64.d
In file included from pie/piegen/elf-x86-64.c:16:0:
pie/piegen/elf.c:15:29: fatal error: asm-generic/int.h: No such file or directory
compilation terminated.
  DEP      pie/piegen/elf-x86-32.d
In file included from pie/piegen/elf-x86-32.c:16:0:
pie/piegen/elf.c:15:29: fatal error: asm-generic/int.h: No such file or directory
compilation terminated.
  CC       pie/piegen/elf-x86-32.o
In file included from pie/piegen/elf-x86-32.c:16:0:
pie/piegen/elf.c:15:29: fatal error: asm-generic/int.h: No such file or directory
compilation terminated.
/home/ayourtch/criu/scripts/nmk/scripts/rules.mk:53: recipe for target 'pie/piegen/elf-x86-32.o' failed
make[2]: *** [pie/piegen/elf-x86-32.o] Error 1
Makefile:108: recipe for target 'pie/piegen/built-in.o' failed
make[1]: *** [pie/piegen/built-in.o] Error 2
Makefile:120: recipe for target 'criu/criu' failed
make: *** [criu/criu] Error 2

By the looks of it is seems like the issue is related to the search paths in GCC for the similarly named files (i.e. adding export USERCFLAGS="-I `pwd`/criu/include" changes the errors to be about absent definition of strncpy.

**Comment by ayourtch** [comment]
criu-1.8 release fails to compile with the same messages, so it must be something specific to the Xenial environment, possibly a bug or behaviour change somewhere.

**Comment by tych0** [comment]
Huh, something must have changed in xenial, I'm using older gccs from xenial just fine, but you're right that a xenial-daily image breaks compiles. I'll take a look.

**Comment by cyrillos** [comment]
@ayourtch Could you please run make V=1 and show the output?

**Comment by tych0** [comment]
```
make -r -R -f /home/ubuntu/criu/scripts/nmk/scripts/main.mk makefile=Makefile obj=images all
make -r -R -f /home/ubuntu/criu/scripts/nmk/scripts/main.mk makefile=Makefile obj=images images/built-in.o
make[1]: 'images/built-in.o' is up to date.
make -C criu all
echo "v1.8-399-g60404df" > ../.gitid
echo "/* Autogenerated, do not edit */"			 > include/version.h
echo "#ifndef __CR_VERSION_H__"				>> include/version.h
echo "#define __CR_VERSION_H__"				>> include/version.h
echo "#define CRIU_VERSION \"2.0\""		>> include/version.h
echo "#define CRIU_VERSION_MAJOR " 2	>> include/version.h
echo "#define CRIU_VERSION_MINOR " 0	>> include/version.h
echo "#define CRIU_GITID \"v1.8-399-g60404df\""			>> include/version.h
echo "#endif /* __CR_VERSION_H__ */"			>> include/version.h
CC=gcc LD=ld CFLAGS="  -O2 -g -Wall -Werror -DCONFIG_X86_64 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE  -DCONFIG_X86_64 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DCONFIG_HAS_SELINUX" make -r -R -f /home/ubuntu/criu/scripts/nmk/scripts/main.mk makefile=Makefile obj=pie/piegen pie/piegen/built-in.o
gcc -M -MT pie/piegen/elf-x86-64.d -MT pie/piegen/elf-x86-64.o -O2 -g -Wall -Werror -DCONFIG_X86_64 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DCONFIG_X86_64 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DCONFIG_HAS_SELINUX -iquote pie/piegen pie/piegen/elf-x86-64.c -o pie/piegen/elf-x86-64.d
In file included from pie/piegen/elf-x86-64.c:16:0:
pie/piegen/elf.c:15:29: fatal error: asm-generic/int.h: No such file or directory
compilation terminated.
gcc -M -MT pie/piegen/elf-x86-32.d -MT pie/piegen/elf-x86-32.o -O2 -g -Wall -Werror -DCONFIG_X86_64 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DCONFIG_X86_64 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DCONFIG_HAS_SELINUX -iquote pie/piegen pie/piegen/elf-x86-32.c -o pie/piegen/elf-x86-32.d
In file included from pie/piegen/elf-x86-32.c:16:0:
pie/piegen/elf.c:15:29: fatal error: asm-generic/int.h: No such file or directory
compilation terminated.
gcc -c -O2 -g -Wall -Werror -DCONFIG_X86_64 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DCONFIG_X86_64 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DCONFIG_HAS_SELINUX -iquote pie/piegen pie/piegen/elf-x86-32.c -o pie/piegen/elf-x86-32.o
In file included from pie/piegen/elf-x86-32.c:16:0:
pie/piegen/elf.c:15:29: fatal error: asm-generic/int.h: No such file or directory
compilation terminated.
/home/ubuntu/criu/scripts/nmk/scripts/rules.mk:53: recipe for target 'pie/piegen/elf-x86-32.o' failed
make[2]: *** [pie/piegen/elf-x86-32.o] Error 1
Makefile:119: recipe for target 'pie/piegen/built-in.o' failed
make[1]: *** [pie/piegen/built-in.o] Error 2
Makefile:120: recipe for target 'criu' failed
make: *** [criu] Error 2
```

**Comment by cyrillos** [comment]
Weird, a number of CFLAGS get ripped off :(
