### ISSUE TITLE
cg: Failed closing cpuset//newroot/cpuset.cpu_exclusive: Invalid argument

### ISSUE THREAD

**Issue by avagin** [xemul/criu#118]
------------------------ grep Error ------------------------
(00.024384) Error (cgroup.c:1201): cg: Failed closing cpuset//newroot/cpuset.cpu_exclusive: Invalid argument
(00.032961) Error (cr-restore.c:1304): 38 killed by signal 9
(00.033120) Error (cr-restore.c:2130): Restoring FAILED.
------------------------ ERROR OVER ------------------------
##################################### FAIL #####################################

https://travis-ci.org/xemul/criu/jobs/111734534

Cc: @tych0

**Comment by avagin** [comment]
https://ci.openvz.org/view/CRIU/job/CRIU-x86_64/1246/console
```
======================== Run zdtm/static/cgroup03 in h =========================
Start test
Test is SUID
./cgroup03 --pidfile=cgroup03.pid --outfile=cgroup03.out --dirname=cgroup03.test
Cleaning cgclean.cKI2rT
Run criu dump
Running zdtm/static/cgroup03.hook(--pre-restore)
Run criu restore
=[log]=> dump/zdtm/static/cgroup03/24/1/restore.log
------------------------ grep Error ------------------------
(00.004887) Error (cgroup.c:1189): cg: Failed closing cpuset//newroot/cpuset.cpus: Invalid argument
(00.004893) Error (cgroup.c:1345): cg: Restoring special cpuset props failed!
------------------------ ERROR OVER ------------------------
################ Test zdtm/static/cgroup03 FAIL at CRIU restore ################
```

**Comment by avagin** [comment]
@tych0, could you take a look at this issue?

**Comment by tych0** [comment]
On Mon, Feb 29, 2016 at 08:25:26AM -0800, Andrew Vagin wrote:
> @tych0, could you take a look at this issue?

Whoops, thanks for the ping. Yes, I'll try to take a look today.

**Comment by tych0** [comment]
Do you have the full restore log for this failed test somewhere that I can look at?

**Comment by avagin** [comment]
@tych0 I forwarded you an report from Jenkins. report.tar.gz contains all logs and images.

**Comment by tych0** [comment]
```
(00.004808) cg: Created cgroup dir cpuset//newroot
(00.004830) cg: Restore special cpuset props
(00.004834) cg: Restoring cgroup property value [0-1] to [cpuset//newroot/cpuset.cpus]
(00.004887) Error (cgroup.c:1189): cg: Failed closing cpuset//newroot/cpuset.cpus: Invalid argument
(00.004893) Error (cgroup.c:1345): cg: Restoring special cpuset props failed!
```

So the value looks reasonable (0-1) assuming that the test box has two cores, which I suppose it does since the test suite won't actually change hosts.

According to the man page, the only other reason you'd get EINVAL is because the cgroup has attached tasks. Based on the log this criu thinks it just created it, but is there some other CRIU test suite running that's entering this cgroup before we set the property?

**Comment by avagin** [comment]
Jenkins runs "./test/zdtm.py run --all --report report --parallel 4"

**Comment by avagin** [comment]
If you look at the history https://ci.openvz.org/view/CRIU/job/CRIU-x86_64/, you can it fails no each time.

**Comment by tych0** [comment]
Hmm, so --parallel should be okay since there is only one test entering newroot. Are there multiple jenkins builders running the suite at once sometimes?

**Comment by avagin** [comment]
But the first message in this thread is about an issue which is reproduced each time in Travis. It maybe another problem.

**Comment by avagin** [comment]
@tych0 We don't jenkins jobs concurrently.

**Comment by tych0** [comment]
Ok, as for the travis one, I'm not really sure what's going on there. I wonder if travis sets some cpusets somewhere and that is screwing things up?

**Comment by avagin** [comment]
@tych0 I don't know. I'm fixing another bug right now...

**Comment by tych0** [comment]
Np, sorry, just thinking out loud :). Looks like they do set some cpusets,

https://github.com/travis-ci/worker/blob/master/backend/docker.go#L66

**Comment by tych0** [comment]
Ok, I don't /think/ it can fail writing 0 to cpuset.cpus_exclusive, so it must be writing 1, and since travis uses cpusets, presumably there are cousin cpusets with a similar allocation which is why this fails.

I'll wait for https://lists.openvz.org/pipermail/criu/2016-February/025892.html to be applied to check for sure, though.

**Comment by Snorch** [comment]
Just for history, if I run this test on criu-dev (v3.15+) and on Fedora32, I still have an error:
```
./test/zdtm.py run -t zdtm/static/cgroup02
...
Error (criu/cgroup.c:1360): cg: Failed writing 1 to cpuset//newroot/cpuset.cpu_exclusive: Invalid argument'
...
```
The workaround here is to disable exclusive, which probably is what we do in our test environments:
```
echo 0 | tee /sys/fs/cgroup/cpuset/cpuset.{cpu,mem}_exclusive
...
```
