### ISSUE TITLE
Cannot build criu v2.0 from source

### ISSUE THREAD

**Issue by tswift242** [xemul/criu#135]
I'm running kernel version 3.19.8 on Ubuntu 14.04. I'm grabbing the criu v2.0 sources from https://github.com/xemul/criu/archive/v2.0.tar.gz and extracting them. I install the following dependencies required by criu through apt-get: bsdmainutils build-essential libprotobuf-c0-dev libprotobuf-dev protobuf-compiler protobuf-c-compiler libnl-3-200 asciidoc. When I then try to build the sources using "make", I get the following error:

"Makefile:69: *** "Make sure 'libpthread libprotobuf-c libnl-3' libraries are installed".  Stop."

The full output of make is attached. What's odd about this is that not only have I verified those libraries are installed, but if I do the exact same steps to build the criu v1.8 source, it succeeds. So I can build criu 1.8 but not 2.0.

[criu-v2.0_build_failure.txt](https://github.com/xemul/criu/files/165908/criu-v2.0_build_failure.txt)

**Comment by xemul** [comment]
Presumably you need all the mentioned libraries with -dev suffix. Like libpthread-dev, libnl-3-dev (or libnl-dev, not sure) and alike.

Cc @cyrillos

**Comment by cyrillos** [comment]
from scripts/travis-tests

apt-get install -qq protobuf-c-compiler libprotobuf-c0-dev libaio-dev libprotobuf-dev protobuf-compiler python-ipaddr libcap-dev libnl-3-dev

**Comment by xemul** [comment]
@cyrillos would you check the Installation page on wiki to be up-to-date, please?

**Comment by cyrillos** [comment]
sure

**Comment by cyrillos** [comment]
I think we migh add some make help-devel target into Makefile which would simply print out current dependency list. Hm?

**Comment by tswift242** [comment]
I'm now trying to make sure I have the -dev libraries installed too. Installing libnl-3-dev got me further through the build, but now the failure is "namespaces.c:12:28: fatal error: sys/capability.h: No such file or directory". I'm continuing to look into this.

One thing that confused me is that I was able to build criu 1.8 with the same set of libraries I have now, on the same machine. The last modified date of the installation page on the wiki was 2/25; I would've expected that to be more recent if the build dependencies changed in between 1.8 and 2.0.

**Comment by xemul** [comment]
@cyrillos Makes already print smth like this, don't they?

@tswift242 for capability.h you need libpcap-dev package (if I'm not mistaken with the name). And with 2.0 we've extended the set of dependencies, yes, now criu needs more stuff to get built. And the not update wiki is our fault :( we'll fix it shortly, thanks for spotting this.

**Comment by cyrillos** [comment]
@xemul Not exactly

LIBS			:= -lrt -lpthread -lprotobuf-c -ldl -lnl-3
REQ-LIBS-NAMES          := libpthread libprotobuf-c libnl-3

#
# Make sure all required libs are installed
ifneq ($(MAKECMDGOALS),clean)
        ifneq ($(shell sh -c                                                            \
                        'TMP="$(OUTPUT)$(TMPOUT).$$$$";                                 \
                        echo "int main(int argc, char *argv[]) { return 0; }" |         \
                        "$(CC)" -x c - $(LIBS) -o "$$TMP" > /dev/null 2>&1 && echo y;   \
                        rm -f "$$TMP"'),y)
                $(error "Make sure '$(REQ-LIBS-NAMES)' libraries are installed")
        endif
endif

IOW it prints some deps but not in the clear form suitable for regular users :)

**Comment by cyrillos** [comment]
From updated WIKI

Other deps

libnl3 and libnl3-devel (RPM distros) or libnl-3-dev (DEB distros) for network operations.
libcap and libcap-devel (RPM distros) or libcap-dev (DEB distros) for work with capabilities.
python-ipaddr is used by CRIT to pretty-print ip.

If libbsd available, CRIU will be compiled with setproctitle() support. It will allow to make process titles of service workers to be more verbose.

The iproute2 tool version 3.5.0 or higher is needed for dumping network namespaces. The latest one can be cloned from iproute2. It should be compiled and a path to ip written in the environment variable CR_IP_TOOL.

If you would like to use make test you should install libaio-devel.

**Comment by tswift242** [comment]
@xemul @cyrillos Got it to build now with the additional dependencies. Thanks! Yea, it might be helpful to update that that REQ-LIBS-NAMES list.

**Comment by xemul** [comment]
Cool, thanks :) @cyrillos , plz tune what has been discussed so far.
