### ISSUE TITLE
Can not dump ubuntu wily lxc container

### ISSUE THREAD

**Issue by chenhaiq** [xemul/criu#138]
When dump lxc container with ubuntu wily (15.10) image using cmd:
lxc-checkpoint -n wily3 -D /root/dump -vvv -l TRACE -s

It hits this error:
(00.006219) Error (mount.c:717): mnt: 207:./sys/fs/cgroup/systemd/lxc/wily3 is overmounted

This is because the the container has two cgroup entries:

root@wily3:/# mount|grep systemd
cgroup on /sys/fs/cgroup/systemd/lxc/wily3 type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)

The second one is a sub directory of the first one, and caused the error.

**Comment by xemul** [comment]
Cc @tych0

**Comment by tych0** [comment]
Hi,

On Tue, Mar 15, 2016 at 08:32:59PM -0700, Chen Hai Quan wrote:
> When dump lxc container with ubuntu wily (15.10) image using cmd:
> lxc-checkpoint -n wily3 -D /root/dump -vvv -l TRACE -s
> 
> It hits this error:
> (00.006219) Error (mount.c:717): mnt: 207:./sys/fs/cgroup/systemd/lxc/wily3 is overmounted
> 
> This is because the the container has two cgroup entries:
> 
> root@wily3:/# mount|grep systemd
> cgroup on /sys/fs/cgroup/systemd/lxc/wily3 type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
> cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd)
> 
> The second one is a sub directory of the first one, and caused the error.

When I've seen this before, usually it means you're using an old lxcfs
on a kernel which supports cgroup namespaces. Can you post the kernel
version, liblxc, and lxcfs versions you're using? /proc/self/mountinfo
from inside the container would also be handy.

**Comment by chenhaiq** [comment]
Linux ubuntu 4.4.5-040405-generic #201603091931 SMP Thu Mar 10 00:34:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
ii  liblxc1                            2.0.0~rc10-0ubuntu2~ubuntu15.10.1~ppa1 amd64        Linux Containers userspace tools (library)
ii  lxcfs                              2.0.0~rc4-0ubuntu1~ubuntu15.10.1~ppa1  amd64        FUSE based filesystem for LXC


#cat mountinfo
295 147 253:1 /var/lib/lxc/wily3/rootfs / rw,relatime master:1 - ext4 /dev/vda1 rw,errors=remount-ro,data=ordered
296 295 0:68 / /dev rw,relatime - tmpfs none rw,size=492k,mode=755
297 295 0:67 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
298 299 0:67 /sys/net /proc/sys/net rw,nosuid,nodev,noexec,relatime - proc proc rw
299 297 0:67 /sys /proc/sys ro,nosuid,nodev,noexec,relatime - proc proc rw
300 297 0:67 /sysrq-trigger /proc/sysrq-trigger ro,nosuid,nodev,noexec,relatime - proc proc rw
301 295 0:69 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
302 301 0:69 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs rw
303 302 0:69 / /sys/devices/virtual/net rw,relatime - sysfs sysfs rw
304 303 0:69 /devices/virtual/net /sys/devices/virtual/net rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
305 302 0:37 / /sys/fs/fuse/connections rw,relatime master:27 - fusectl fusectl rw
306 302 0:7 / /sys/kernel/debug rw,relatime master:25 - debugfs debugfs rw
307 302 0:12 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime master:8 - securityfs securityfs rw
308 302 0:24 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime master:11 - pstore pstore rw
309 296 0:66 / /dev/mqueue rw,relatime - mqueue mqueue rw
310 302 0:70 / /sys/fs/cgroup ro,nosuid,nodev,noexec - tmpfs cgroup_root ro,size=10240k,mode=755
311 310 0:34 /lxc/wily3 /sys/fs/cgroup/blkio/lxc/wily3 rw,nosuid,nodev,noexec,relatime master:22 - cgroup cgroup rw,blkio
312 310 0:33 /lxc/wily3 /sys/fs/cgroup/devices/lxc/wily3 rw,nosuid,nodev,noexec,relatime master:21 - cgroup cgroup rw,devices
313 310 0:32 /lxc/wily3 /sys/fs/cgroup/hugetlb/lxc/wily3 rw,nosuid,nodev,noexec,relatime master:20 - cgroup cgroup rw,hugetlb,release_agent=/run/cgmanager/agents/cgm-release-agent.hugetlb
314 310 0:31 /lxc/wily3 /sys/fs/cgroup/freezer/lxc/wily3 rw,nosuid,nodev,noexec,relatime master:19 - cgroup cgroup rw,freezer
315 310 0:30 /lxc/wily3 /sys/fs/cgroup/memory/lxc/wily3 rw,nosuid,nodev,noexec,relatime master:18 - cgroup cgroup rw,memory
316 310 0:29 /lxc/wily3 /sys/fs/cgroup/pids/lxc/wily3 rw,nosuid,nodev,noexec,relatime master:17 - cgroup cgroup rw,pids,release_agent=/run/cgmanager/agents/cgm-release-agent.pids
317 310 0:28 /lxc/wily3 /sys/fs/cgroup/cpu,cpuacct/lxc/wily3 rw,nosuid,nodev,noexec,relatime master:16 - cgroup cgroup rw,cpu,cpuacct
318 310 0:27 /lxc/wily3 /sys/fs/cgroup/cpuset/lxc/wily3 rw,nosuid,nodev,noexec,relatime master:15 - cgroup cgroup rw,cpuset,clone_children
319 310 0:26 /lxc/wily3 /sys/fs/cgroup/perf_event/lxc/wily3 rw,nosuid,nodev,noexec,relatime master:14 - cgroup cgroup rw,perf_event,release_agent=/run/cgmanager/agents/cgm-release-agent.perf_event
320 310 0:25 /lxc/wily3 /sys/fs/cgroup/net_cls,net_prio/lxc/wily3 rw,nosuid,nodev,noexec,relatime master:13 - cgroup cgroup rw,net_cls,net_prio
321 310 0:23 /lxc/wily3 /sys/fs/cgroup/systemd/lxc/wily3 rw,nosuid,nodev,noexec,relatime master:10 - cgroup cgroup rw,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd
322 297 0:42 /proc/cpuinfo /proc/cpuinfo rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
323 297 0:42 /proc/diskstats /proc/diskstats rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
324 297 0:42 /proc/meminfo /proc/meminfo rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
325 297 0:42 /proc/stat /proc/stat rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
326 297 0:42 /proc/swaps /proc/swaps rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
327 297 0:42 /proc/uptime /proc/uptime rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
328 310 0:42 /cgroup/blkio /sys/fs/cgroup/blkio rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
329 310 0:42 /cgroup/cpu,cpuacct /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
330 310 0:42 /cgroup/cpuset /sys/fs/cgroup/cpuset rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
331 310 0:42 /cgroup/devices /sys/fs/cgroup/devices rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
332 310 0:42 /cgroup/freezer /sys/fs/cgroup/freezer rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
333 310 0:42 /cgroup/hugetlb /sys/fs/cgroup/hugetlb rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
334 310 0:42 /cgroup/memory /sys/fs/cgroup/memory rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
335 310 0:42 /cgroup/name=systemd /sys/fs/cgroup/systemd rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
336 310 0:42 /cgroup/net_cls,net_prio /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
337 310 0:42 /cgroup/perf_event /sys/fs/cgroup/perf_event rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
338 310 0:42 /cgroup/pids /sys/fs/cgroup/pids rw,nosuid,nodev,relatime master:98 - fuse.lxcfs lxcfs rw,user_id=0,group_id=0,allow_other
156 296 0:71 / /dev/pts rw,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=666
157 296 0:72 / /dev/shm rw,nosuid,nodev - tmpfs tmpfs rw
158 295 0:73 / /run rw,nosuid,nodev - tmpfs tmpfs rw,mode=755
159 158 0:74 / /run/lock rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,size=5120k
160 296 0:75 / /dev/hugepages rw,relatime - hugetlbfs hugetlbfs rw

**Comment by hallyn** [comment]
Please show the contents of /usr/share/lxcfs/lxc.mount.hook

**Comment by chenhaiq** [comment]
# cat /usr/share/lxcfs/lxc.mount.hook
#!/bin/sh -e

# /proc files
if [ -d /var/lib/lxcfs/proc/ ]; then
    for entry in /var/lib/lxcfs/proc/*; do
        [ -e "${LXC_ROOTFS_MOUNT}/proc/$(basename $entry)" ] || continue
        mount -n --bind $entry ${LXC_ROOTFS_MOUNT}/proc/$(basename $entry)
    done
fi


# Allow nesting lxcfs
if [ -d ${LXC_ROOTFS_MOUNT}/var/lib/lxcfs/ ]; then
    mount -n --bind /var/lib/lxcfs ${LXC_ROOTFS_MOUNT}/var/lib/lxcfs/
fi

# no need for lxcfs cgroups if we have cgroup namespaces
[ -n "$LXC_CGNS_AWARE" ] && [ -f /proc/self/ns/cgroup ] && exit 0

# Don't mess with containers that don't have /sys/fs/cgroup configured
# (lxc.mount.auto = cgroup:mixed)
if touch ${LXC_ROOTFS_MOUNT}/sys/fs/cgroup/lxcfs; then
    rm ${LXC_ROOTFS_MOUNT}/sys/fs/cgroup/lxcfs
else
    exit 0
fi

# /sys/fs/cgroup files
if [ -d "${LXC_ROOTFS_MOUNT}/sys/fs/cgroup" ]; then
    if [ -d /var/lib/lxcfs/cgroup ]; then
        for entry in /var/lib/lxcfs/cgroup/*; do
            DEST=$(basename $entry)
            if [ "$DEST" = "name=systemd" ]; then
                DEST="systemd"
            fi

            if mountpoint -q ${LXC_ROOTFS_MOUNT}/sys/fs/cgroup/$DEST; then
                continue
            fi

            if [ ! -d ${LXC_ROOTFS_MOUNT}/sys/fs/cgroup/$DEST ]; then
                mkdir ${LXC_ROOTFS_MOUNT}/sys/fs/cgroup/$DEST
            fi

            mount -n --bind $entry ${LXC_ROOTFS_MOUNT}/sys/fs/cgroup/$DEST

            # make sure that cpu,cpuacct shows up as cpu and cpuacct
            # separately, else systemd is unhappy
            if echo $DEST | grep -q ","; then
                arr=$(echo $DEST | tr "," "\n")
                for single in $arr
                do
                    if [ ! -L ${LXC_ROOTFS_MOUNT}/sys/fs/cgroup/$single ]; then
                        ln -s $DEST ${LXC_ROOTFS_MOUNT}/sys/fs/cgroup/$single
                    fi
                done
            fi
        done
    fi
fi

exit 0

**Comment by chenhaiq** [comment]
checkpoint works, after I append below lines into config file
```
lxc.mount.auto = cgroup:mixed
lxc.autodev = 1
lxc.kmsg = 0
lxc.include = /usr/share/lxc/config/common.conf.d/00-lxcfs.conf
```
