### ISSUE TITLE
[Docker] Fail when restoring dummy apache server running in Docker

### ISSUE THREAD

**Issue by andreituicu** [xemul/criu#140]
Hello,

I hope that this is the appropriate place to open this issue. I am trying to checkpoint and restore a simple apache server running in docker, but the restore fails and the reported errors only say that the threads were killed.

```
docker run -d -p 8080:80 --security-opt seccomp:unconfined --name apache httpd
docker checkpoint apache
docker restore apache
```

Kernel version: 4.4.0-10-generic
CRIU version: 2.0 GitID: v2.0-44-gef4dbeb
Docker version: Docker version 1.10.0-dev, build cec56b2, experimental

Dump log: https://gist.github.com/andreituicu/7f7949c330a4522d76c7#file-dump-log
Restore log: https://gist.github.com/andreituicu/7f7949c330a4522d76c7#file-restore-log

Please let me know if you need any more information.

Thank you for the help,
Andrei

**Comment by xemul** [comment]
Cc @boucher 
I see no errors in restore log. What do you mean by 'reported errors'?

**Comment by andreituicu** [comment]
Hi, @xemul ,

I was referring to these three lines at the end of the restore log (just because they are prefixed with Error). The reason I opened this issue is, because as you said I don't see any actual errors. I'm sorry for the confusion. :)

```
(00.618751) Error (cr-restore.c:1307): 6663 killed by signal 19
(00.618775) Error (cr-restore.c:1307): 6663 killed by signal 19
(00.618865) Error (cr-restore.c:2137): Restoring FAILED.
```

**Comment by boucher** [comment]
I'm able to checkpoint/restore this container successfully following the commands you posted. Is this failing every time, or just sometimes?

**Comment by andreituicu** [comment]
Hello, @boucher,

It fails every time at restore. It never failed for me at checkpoint.

**Comment by avagin** [comment]
```
pie: Restoring scheduler params 0.0.0
pie: Task 9  exited, status= 11
(00.618751) Error (cr-restore.c:1307): 6663 killed by signal 19
(00.618775) Error (cr-restore.c:1307): 6663 killed by signal 19
(00.618865) Error (cr-restore.c:2137): Restoring FAILED.
```

```
        pr_info("Task %d %s %d\n", siginfo->si_pid, r, siginfo->si_status);

        futex_abort_and_wake(&task_entries->nr_in_progress);
        /* sa_restorer may be unmaped, so we can't go back to userspace*/
        sys_kill(sys_getpid(), SIGSTOP);
```

**Comment by avagin** [comment]
The task 9 was segfaulted. @andreituicu, could you collect a core file for criu?

**Comment by andreituicu** [comment]
@avagin, I can't seem to be able to find any core dump 
Core dumps are enabled and I can generate one running for example 
```
sleep 10 &
killall -SIGSEGV sleep
```

@boucher I've just been able to successfully restore the container once, but after that it crashed again every time.

**Comment by avagin** [comment]
@andreituicu could you collect strace for criu restore? For that you need to execute strace for docker daemon before executing docker restore:
strace -fo /tmp/strace.log -s 256 -p [PID_OF_DOCKER_DAEMON]

**Comment by andreituicu** [comment]
@avagin Thanks for the help. You can find the strace log here: https://gist.github.com/andreituicu/5ae628b6d3ee4fe2c4cf#file-strace-log

**Comment by avagin** [comment]
I forgot that we use the restore-sibling option and strace can't be used in this case. Could you try out to use perf instead of strace:
perf trace -o /tmp/perf-criu.log -p [PID_OF_DOCKER_DAEMON]

**Comment by andreituicu** [comment]
@avagin: You can find the perf log here: https://gist.github.com/andreituicu/18bc21b4d0e8bbe90702#file-perf-criu-log

**Comment by avagin** [comment]
It doesn't contain information about criu processes.

**Comment by avagin** [comment]
@andreituicu  you can try to add the -a option

**Comment by andreituicu** [comment]
@boucher : I think I've missed adding some errors that the docker daemon is reporting on restore:
```
WARN[0042] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/0.0/containers/4bf8452bfd7cda433b2347458364a44c60bd922cd4583a073effa4054323a57e/shm: invalid argument
failed to umount /var/lib/docker/0.0/containers/4bf8452bfd7cda433b2347458364a44c60bd922cd4583a073effa4054323a57e/mqueue: invalid argument 
ERRO[0042] Error unmounting container 4bf8452bfd7cda433b2347458364a44c60bd922cd4583a073effa4054323a57e: not mounted 
ERRO[0042] Handler for POST /v1.22/containers/apache5/restore returned error: Cannot restore container apache5: cantstart: Cannot start container 4bf8452bfd7cda433b2347458364a44c60bd922cd4583a073effa4054323a57e: criu failed: type NOTIFY errno 0
log file: /var/lib/docker/0.0/containers/4bf8452bfd7cda433b2347458364a44c60bd922cd4583a073effa4054323a57e/criu.work/restore.log
``` 
Are these of any help?
 
@avagin: I already tried it. perf closes imediately with exit code 243 if I add the -a option.

@all: I am running docker from a VirtualBox Ubuntu machine. Would it be of any help if I upload it somewhere? I find it strange that it works with simple bash scripts and with nginx, but not with apache.

**Comment by avagin** [comment]
@andreituicu, can you build criu with this patch:
https://github.com/avagin/criu/commit/b5daa9a11a47dc31df418496fa44a95f259928e2

and show us restore.log?

**Comment by andreituicu** [comment]
@avagin , applied the patch, here is the log: https://gist.github.com/andreituicu/5677915adad45d64ef65#file-restore-debug-log

**Comment by avagin** [comment]
```
8 pie: vdso: Remap dumpee 0x10f000 -> 0x7ffe6fdcc000
8 pie: Restoring scheduler params 0.0.0
8 pie: Error (pie/restorer.c:414): 
1 pie: Task 8  exited, status= 4
```
```
414:        pr_err("\n");
415:        if (restore_nonsigframe_gpregs(&args->gpregs))
416:                return -1;
417:        pr_err("\n");
```
Cc: @cyrillos

**Comment by cyrillos** [comment]
Thanks for report, will take a look.

**Comment by cyrillos** [comment]
@andreituicu Could you please upload your images somewhere?

**Comment by andreituicu** [comment]
Hi @cyrillos,
You can find the a tar with the image here: https://www.dropbox.com/s/wtp63djph5nvf0c/apacheimage.tar?dl=0

**Comment by cyrillos** [comment]
Thanks. Been looking into fs|gs_bases but they are pretty valid in your images. Continue...

**Comment by avagin** [comment]
@andreituicu Could you show dmesg from this host? It should contain information about segfaulted processes.

**Comment by cyrillos** [comment]
I suspect this might be msr-writting procedure related. If I understand correctly you're running guest under VirtualBox? Could you please run it under KVM or real hardware? Is there a way to fetch your virtualbox image?

**Comment by andreituicu** [comment]
@avagin : you can find the dmesg log for all the 3 commands here: https://gist.github.com/andreituicu/5ac8fe110eee7345c226#file-dmesg-log , but I don't see anything useful there.

@cyrillos : Yes, I am running guest under VirtualBox, I've uploaded the image for that machine here: https://drive.google.com/file/d/0Bz4oADNI4d8-Tk1ieGFSSHhONzg/view?usp=sharing . Unfortunately, I don't have a machine running Linux without virtualisation. I will try to run under KVM and come back with the results.

**Comment by cyrillos** [comment]
Thank you! I suspect it's VB issue, but better been proven. I'll try to play with your VB image. Could you please provide commands you run inside VB to checkpoint and restore?

**Comment by andreituicu** [comment]
I am always running the same three commands:
```
docker run -d -p 8080:80 --security-opt seccomp:unconfined --name apache httpd
docker checkpoint apache
docker restore apache
```
What I did forgot  to mention is the login password, which is: password. :)

**Comment by cyrillos** [comment]
Thanks! Gonna try to convert ova to qcow2 and play as well.

**Comment by cyrillos** [comment]
When I try to run docker it yields "Can not connect to docker daemon" Is there some other command to be run before starting "run" action?

**Comment by andreituicu** [comment]
@cyrillos Yes, sorry. You need to open another terminal and run
`sudo docker daemon`
Also all the commands for docker need to be used with sudo.

**Comment by cyrillos** [comment]
OK, thanks! I managed to reproduce. Gimme some time to figure out what is happening there.

**Comment by cyrillos** [comment]
I noted that there is make 4.1, and we already has issue with it. Hopefully it's not compile-time issue. Continue investigating...

**Comment by andreituicu** [comment]
@cyrillos Just a note: if you make changes in the source and recompile it, you will need to manually copy the binary to the path for docker to use it. I think I used /usr/local/bin

**Comment by cyrillos** [comment]
@adrianreber already did. I usually simply setup a symlink into the compiled criu laying inside source code tree.

**Comment by andreituicu** [comment]
I wanted to make sure I don't waist any of your time. :)

**Comment by cyrillos** [comment]
OK, this is a problem with linking of criu/arch/x86/restorer.c, if I merge it into PIE code directly then everything works fine.

Need to figure out where exactly instructions get screwed on assembler level.

**Comment by avagin** [comment]
I decided to print an address of restore_nonsigframe_gpregs, but I can't compile criu with this simple patch. It is compiled on my fedora host without errors.
```
restorer_blob: Error (pie/piegen/elf.c:469): Unsupported relocation
pie/Makefile:72: recipe for target 'pie/restorer-blob.h' failed
make[2]: *** [pie/restorer-blob.h] Error 1
make[2]: Leaving directory '/home/andrei/criu/criu'
Makefile:160: recipe for target 'pie' failed
make[1]: *** [pie] Error 2
make[1]: Leaving directory '/home/andrei/criu/criu'
Makefile:123: recipe for target 'criu' failed
make: *** [criu] Error 2
root@valhala:/home/andrei/criu# git diff
diff --git a/criu/pie/restorer.c b/criu/pie/restorer.c
index 1ac5e7e..07ff6af 100644
--- a/criu/pie/restorer.c
+++ b/criu/pie/restorer.c
@@ -411,6 +411,7 @@ static int restore_thread_common(struct thread_restore_args *args)
 
        restore_sched_info(&args->sp);
 
+       pr_err("%p\n", restore_nonsigframe_gpregs);
        if (restore_nonsigframe_gpregs(&args->gpregs))
                return -1;
 
```

**Comment by cyrillos** [comment]
There is a new type of relocations

000000000000008c R_X86_64_REX_GOTPCRELX  restore_nonsigframe_gpregs-0x0000000000000004

I'm trying to figure out how to disable it.

**Comment by cyrillos** [comment]
andrei@valhala:~/criu$ sudo apt show binutils
Package: binutils
Version: 2.26-7ubuntu2
--
while on fedora we have 2.25.

**Comment by avagin** [comment]
@andreituicu, could you try out this patch https://github.com/avagin/criu/commit/f808e590e096bcfcf6a2c527191c929d85f7b12a. I think it should fix this bug. Thank you for the help.

**Comment by cyrillos** [comment]
@avagin sigh, it was a long journey until we've found that restorer blob get screwed due to a reason other than pie-code generation :/

**Comment by avagin** [comment]
@cyrillos you had an idea to make restore-blob read-only. I think it's a good idea. Actually I found the root course of this bug, when I protected the first page of restore-blob.

**Comment by cyrillos** [comment]
@avagin yes, i've been dumping the blob with relocations applied and discovered that we've had some trash there instead of real code.

**Comment by andreituicu** [comment]
@avagin @cyrillos : Thank you guys very much for your help! I've applied the patch and everything seems to be ok. Up until the last minute I thought that maybe the problem it's due to some misconfiguration that I did and I'm waisting everyones time. :)
I'm going to let you close this issue when you think it's appropriate. Please let me know when you don't longer need the machine, so I can remove it from the drive, but there is  no rush.
Thanks again,
Andrei

**Comment by cyrillos** [comment]
@adrianreber Thanks a huge for report and help in providing the VM image! We no longer need it, so feel free to remove. I think Andrew will make a patch with proper changelog and we merge it asap.
