### ISSUE TITLE
[Docker] Containers remain connected to the network bridge after remove

### ISSUE THREAD

**Issue by andreituicu** [xemul/criu#143]
Again, not sure if this is the right place to report this problem. :)
 Containers remain connected to the network bridge after remove if they were in Checkpointed state.

```
docker run -d -p 8080:80 --security-opt seccomp:unconfined --name apache httpd
docker checkpoint apache
docker rm apache
```

Now if I run again: 
`docker run -d -p 8080:80 --name apache httpd`
I get:
`docker: Error response from daemon: Conflict. A container with name "apache" is already connected to network bridge...`

And if I change the name
`docker run -d -p 8080:80 --name apache2 httpd`
I get:
`docker: Error response from daemon: failed to create endpoint apache2 on network bridge: Bind for 0.0.0.0:8080 failed: port is already allocated`

Kernel version: 4.4.0-10-generic
CRIU version: 2.0 GitID: v2.0-44-gef4dbeb + commit 8c28556
Docker version: Docker version 1.10.0-dev, build cec56b2, experimental

**Comment by xemul** [comment]
Cc @boucher and @SaiedKazemi

**Comment by boucher** [comment]
It is a bug, but I think we should close it. Support for CRIU in Docker is being completely rewritten and the current branch is dead.

**Comment by xemul** [comment]
OK. @andreituicu  I'll close the bug as @boucher suggests then.
