### ISSUE TITLE
After using CRIU, why were the container's memory and blkio use greatly reduced? 

### ISSUE THREAD

**Issue by nomadlena** [xemul/criu#144]
Hello, I'm using CRIU to do some experiments on LXC containers. I found that after using CRIU on containers, the memory use and BlkIO use shown by lxc-info were significantly smaller than they were before being checkpointed/restored. 
For example, I had a container c7 that's running postgresql before using CRIU:
Name: c7
State: RUNNING
PID:8423
IP: 10.0.3.231
CPU use: 7.54 seconds
BlkIO use: 177.18 MiB
Memory use: 166.65 MiB
KMem use: 0 bytes
Link: vethW6529H
   TX bytes: 130.96KiB
   RX bytes: 8.91 MiB
   Total bytes: 9.03 MiB

After using CRIU on this container, this is what I've got from lxc-info -n c7:
Name: c7
State: RUNNING
PID:12071
IP: 10.0.3.231
CPU use: 0.90 seconds
BlkIO use: 0 bytes
Memory use: 6.07 MiB
KMem use: 0 bytes
Link: vethNS0V0B
   TX bytes: 648 bytes
   RX bytes: 4.58 KiB
   Total bytes: 5.22 KiB

This happened to almost every container with different types of applications. It seems that applications can be restored from the point where they got checkpointed. So what could cause this reduction? I appreciate any response. Thanks!!!

**Comment by xemul** [comment]
I guess the stats are taken from cgroup files, aren't they? The reason for this is due to the whole container gets recreated from scratch and the stats are zeroed on restore. Not 100% sure what's the best way to deal with it. Apparently kernel guys won't be happy if we come with an API to set these values to some initials.

Cc @tych0

**Comment by nomadlena** [comment]
Hello, thanks for the reply. I thought CRIU was supposed to restore the container from where they got stopped. If the container got started from scratch, would that make the application inside the container restart instead of resume? I tried CRIU on a container running a terminal game ninvaders inside of it and unfortunately after restore, the game couldn't resume and somehow the installation package got lost after CRIU. I was wondering in what cases can CRIU actually resume the applications instead of restarting  them? Thanks!

**Comment by xemul** [comment]
@nomadlena I wasn't completely accurate in my words.
Most of the stuff is restored from where they were stopped, e.g. application memory, registers, open files, etc. So is for containers, but some bits are recreated from scratch, because there's no API in the kernel to fix this. Statistics is one of such examples.

**Comment by nomadlena** [comment]
Hello Pavel, thanks! This time the answer is much more relieving. :) I'm running tomcat web server in one of my LXC containers and databases like mongoDB and postgresql in others. These type of applications usually can be restored. Is this correct? Also I found that CRIU cannot dump containers with mysql running inside, but it can dump the ones with mongoDB and postgresql. Just like the case with terminal games, which particular parts of these applications that make CRIU unable to dump? Is it some drivers or ...? Thank you for your patience!

**Comment by xemul** [comment]
@nomadlena CRIU restores all applications. There can be some bits that we've missed, but we haven't been reported back about anything like this so far.

About inability to dump MySQL -- dump.log with error would be helpful.

**Comment by nomadlena** [comment]
@xemul  Thank you!!! I'm closing this issue now. :)
