### ISSUE TITLE
binfmt_misc.c:133: write magic_file (errno = 22 (Invalid argument))

### ISSUE THREAD

**Issue by avagin** [xemul/criu#149]
====================== Run zdtm/static/binfmt_misc in ns =======================
Start test
Test is SUID
./binfmt_misc --pidfile=binfmt_misc.pid --outfile=binfmt_misc.out --dirname=binfmt_misc.test
The test failed (0, 1)
Makefile:282: recipe for target 'binfmt_misc.pid' failed
make: *** [binfmt_misc.pid] Error 1
################## Test zdtm/static/binfmt_misc FAIL at start ##################
Test output: ================================
18:03:33.594:     4: string: :magic_file:M:9:\x73\x51\xff\x4a\xec\x29\xcd\xba\xab\xf2::/bin/interpreter:OCP
18:03:33.594:     4: FAIL: binfmt_misc.c:133: write magic_file (errno = 22 (Invalid argument))
18:03:33.594:     3: ERR: test.c:204: Test exited unexpectedly with code 1

https://ci.openvz.org/job/CRIU/job/criu-patchwork/35/console

**Comment by avagin** [comment]
Cc: @tkhai

Kirill, could you take a look

**Comment by tkhai** [comment]
Registration of a new magic may fail if a namesake already exists.

Does the test machine have binfmt_misc virtualized? If not so, two binfmt_misc going in parallel may fail.

For the case we execute several binfmt_misc tests in the only container I'll send a patch

**Comment by avagin** [comment]
Here was an entry with the same name. I think it was not deleted when something failed. Now everything works as expected.
