### ISSUE TITLE
[DOC] licap-dev dependency

### ISSUE THREAD

**Issue by federeghe** [xemul/criu#152]
I noticed that `libcap-dev` (on ubuntu) is needed to build criu2.1 because it contains sys/capability.h included in namespaces.c. 

I tried to add it to the wiki page, but even if I have an account I get:
`Some parts of the edit form did not reach the server; double-check that your edits are intact and try again.`

Cheers,
Federico

**Comment by xemul** [comment]
Cc @kolyshkin . Kir, would you look at what's going on with our wiki, please.

**Comment by xemul** [comment]
I've put the <code>libcap-dev</code> in the deps list on wiki, thanks @federeghe
