### ISSUE TITLE
dev/console doesn't have a proper root mount

### ISSUE THREAD

**Issue by washraf** [xemul/criu#153]
I have tried it and I have an error
I am using Ubunu 14.04 
runc version 0.1.0
commit: ae0fc15b1e969b06fa575638d234feaa1596d69c
spec: 0.6.0-dev 
criu --version
Version: 2.1
GitID: v2.1-11-g5559727
The test image is based on busy box.

walid@ubuntu:~/busyboxTest$ sudo runc checkpoint test
criu failed: type NOTIFY errno 0
log file: /run/runc/test/criu.work/dump.log
walid@ubuntu:~/busyboxTest$ sudo tail /run/runc/test/criu.work/dump.log
(00.009367) mnt: Inspecting sharing on 80 shared_id 0 master_id 0 (@./dev)
(00.009369) mnt: Inspecting sharing on 79 shared_id 0 master_id 0 (@./proc)
(00.009371) mnt: Inspecting sharing on 78 shared_id 0 master_id 0 (@./)
(00.009376) Error (mount.c:740): mnt: 98:./dev/console doesn't have a proper root mount
(00.009380) Unlock network
(00.009383) Running network-unlock scripts
(00.009393) 	RPC
(00.014699) Unfreezing tasks into 1
(00.014715) 	Unseizing 37109 into 1
(00.014773) Error (cr-dump.c:1614): Dumping FAILED.

**Comment by xemul** [comment]
Cc @boucher

**Comment by boucher** [comment]
I'm not sure what is needed to support this, but I think @avagin knows.

**Comment by washraf** [comment]
@boucher  I have found this https://github.com/docker/containerd/issues/201#issuecomment-211457069.
And Accordingly i turned off the two options and it works with busy box ... i will try it and report back to.
and way thanks :+1: 
P.s. What difference does it make on having no terminals ?

**Comment by boucher** [comment]
You need a terminal to have an interactive container session, but there
shouldn't be any need for one with a typical backgrounded/daemonized docker
container that you'd have for any server.

**Comment by washraf** [comment]
I tried these options with an Ubuntu image running a very simple count to infinity script.
Its taking forever to checkpoint and to restore (restoring for 5 mins till now).
Have you done any experiments or benchmarks for these operations ?

p.s. I am using a virtual machine running.

**Comment by washraf** [comment]
**Apparently it doesn't restore the process**
This is the Steps i did was as follows:

1. root@ubuntu:~/myubuntutest# runc start walid
2. root@ubuntu:~/myubuntutest# runc exec walid ps

```
 PID TTY          TIME CMD
    1 ?        00:00:00 sh
    6 ?        00:00:00 ps
```

3. root@ubuntu:~/myubuntutest# runc exec walid /script.sh
4. root@ubuntu:~/myubuntutest# runc exec walid ps

  ```
PID TTY          TIME CMD
    1 ?        00:00:00 sh
   12 ?        00:00:00 script.sh
   24 ?        00:00:00 sleep
   25 ?        00:00:00 ps
```

5. root@ubuntu:~/myubuntutest# runc checkpoint walid 

6. root@ubuntu:~/myubuntutest# runc restore walid

7. root@ubuntu:~/myubuntutest# runc exec walid ps

 ```
 PID TTY          TIME CMD
    1 ?        00:00:00 sh
   21 ?        00:00:00 ps
```
Why didn't it checkpoint and restore these processes ?

**Comment by xemul** [comment]
@washraf , @boucher , what do you think would be the best to do here -- close and forget, or ask @avagin to suggest how to handle terminal in docker c/r?

**Comment by boucher** [comment]
I'm not sure I actually follow the issue in this thread. The /dev/console thing is definitely missing, but @washraf I don't see how the runc exec stuff is related. CRIU/docker will only checkpoint the init process of the container, not any process running inside it.

**Comment by washraf** [comment]
@boucher @xemul I already made my script the init process and it worked fine since then and my problem was solved, but the important question is that do you need to track all the processes inside this container either parented by the init process or not (which applies to any terminal created processes).
If you need this as feature keep this issue open; if not close it.

**Comment by xemul** [comment]
Hmm... OK, since the original problem was at least workarounded, let's keep this closed. At least for a while.

**Comment by avagin** [comment]
https://github.com/containerd/containerd/issues/201#issuecomment-211457069
