### ISSUE TITLE
Unkown file lock

### ISSUE THREAD

**Issue by washraf** [xemul/criu#154]
I am using criu with runc and after a couple of checkpoint and restarts this error appears.
$ tail -13 /run/runc/walid/criu.work/dump.log 
```
(00.001468) lockinfo: 5:2 1 1215 00:10:12156 0 EOF
(00.001477) lockinfo: 6:2 1 750 00:10:11956 0 EOF
(00.001481) lockinfo: 7:-1 0 1415 08:01:1977585 0 EOF
(00.001482) Error (proc_parse.c:1967): Unknown file lock: 7: LEASE  ACTIVE    READ  1415 08:01:1977585 0 EOF
!
(00.001493) Unlock network
(00.001496) Unfreezing tasks into 1
(00.001497) 	Unseizing 50138 into 1
(00.001540) 	Unseizing 50192 into 1
(00.001555) Error (cr-dump.c:1614): Dumping FAILED.
```
The containers runs a count to infinity script that writes to a file every second. and the checkpoint doesn't work again till i delete this file.

**Comment by xemul** [comment]
Can you attach full dump.log from the failed run?

**Comment by washraf** [comment]
(00.000048) mnt: Added /sys/fs/cgroup/cpuset:/sys/fs/cgroup/cpuset ext mount mapping
(00.000064) mnt: Added /sys/fs/cgroup/cpu:/sys/fs/cgroup/cpu ext mount mapping
(00.000066) mnt: Added /sys/fs/cgroup/cpuacct:/sys/fs/cgroup/cpuacct ext mount mapping
(00.000067) mnt: Added /sys/fs/cgroup/memory:/sys/fs/cgroup/memory ext mount mapping
(00.000069) mnt: Added /sys/fs/cgroup/devices:/sys/fs/cgroup/devices ext mount mapping
(00.000070) mnt: Added /sys/fs/cgroup/freezer:/sys/fs/cgroup/freezer ext mount mapping
(00.000071) mnt: Added /sys/fs/cgroup/net_cls:/sys/fs/cgroup/net_cls ext mount mapping
(00.000072) mnt: Added /sys/fs/cgroup/blkio:/sys/fs/cgroup/blkio ext mount mapping
(00.000074) mnt: Added /sys/fs/cgroup/perf_event:/sys/fs/cgroup/perf_event ext mount mapping
(00.000075) mnt: Added /sys/fs/cgroup/net_prio:/sys/fs/cgroup/net_prio ext mount mapping
(00.000076) mnt: Added /sys/fs/cgroup/hugetlb:/sys/fs/cgroup/hugetlb ext mount mapping
(00.000077) mnt: Added /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd ext mount mapping
(00.000079) ========================================
(00.000080) Dumping processes (pid: 53734)
(00.000081) ========================================
(00.000082) Running pre-dump scripts
(00.000091) 	RPC
(00.000382) Pagemap is fully functional
(00.000415) Found anon-shmem device at 4
(00.000420) Reset 53842's dirty tracking
(00.000472)  ... done
(00.000502) Dirty track supported on kernel
(00.000583) Found task size of 7ffffffff000
(00.000622) irmap: Searching irmap cache in work dir
(00.000638) No irmap-cache image
(00.000640) irmap: Searching irmap cache in parent
(00.000643) irmap: No irmap cache
(00.000667) cpu: fpu:1 fxsr:1 xsave:1
(00.000766) vdso: Parsing at 7ffcb19fb000 7ffcb19fd000
(00.000770) vdso: PT_LOAD p_vaddr: 0
(00.000771) vdso: DT_HASH: 120
(00.000773) vdso: DT_STRTAB: 268
(00.000774) vdso: DT_SYMTAB: 160
(00.000775) vdso: DT_STRSZ: 5e
(00.000777) vdso: DT_SYMENT: 18
(00.000778) vdso: nbucket 3 nchain b bucket 7ffcb19fb128 chain 7ffcb19fb134
(00.000783) vdso: rt [vdso] 7ffcb19fb000-7ffcb19fd000 [vvar] 7ffcb19fd000-7ffcb19ff000
(00.000864) Perparing image inventory (version 1)
(00.000887) Add pid ns 1 pid 53842
(00.000894) Add net ns 2 pid 53842
(00.000898) Add ipc ns 3 pid 53842
(00.000902) Add uts ns 4 pid 53842
(00.000907) Add mnt ns 5 pid 53842
(00.000912) Add user ns 6 pid 53842
(00.000915) Add cgroup ns 7 pid 53842
(00.000917) cg: Dumping cgroups for 53842
(00.000956) cg:  `- New css ID 1
(00.000961) cg:     `- [blkio] -> [/user/1000.user/c2.session] [0]
(00.000962) cg:     `- [cpu] -> [/user/1000.user/c2.session] [0]
(00.000964) cg:     `- [cpuacct] -> [/user/1000.user/c2.session] [0]
(00.000965) cg:     `- [cpuset] -> [/] [0]
(00.000967) cg:     `- [devices] -> [/user/1000.user/c2.session] [0]
(00.000968) cg:     `- [freezer] -> [/user/1000.user/c2.session] [0]
(00.000969) cg:     `- [hugetlb] -> [/user/1000.user/c2.session] [0]
(00.000970) cg:     `- [memory] -> [/user/1000.user/c2.session] [0]
(00.000971) cg:     `- [name=systemd] -> [/user/1000.user/c2.session] [0]
(00.000973) cg:     `- [net_cls] -> [/user/1000.user/c2.session] [0]
(00.000974) cg:     `- [net_prio] -> [/user/1000.user/c2.session] [0]
(00.000975) cg:     `- [perf_event] -> [/user/1000.user/c2.session] [0]
(00.000976) cg: Set 1 is criu one
(00.001225) Seized task 53734, state 1
(00.001250) Collected (4 attempts, 0 in_progress)
(00.001271) Seized task 53839, state 0
(00.001650) Collected (4 attempts, 0 in_progress)
(00.001664) Collected (4 attempts, 0 in_progress)
(00.001668) Collected 53839 in 1 state
(00.001678) Collected (3 attempts, 0 in_progress)
(00.001682) Collected 53734 in 1 state
(00.001693) Will take pid namespace in the image
(00.001695) Add pid ns 8 pid 53734
(00.001700) Will take ipc namespace in the image
(00.001701) Add ipc ns 9 pid 53734
(00.001704) Will take uts namespace in the image
(00.001705) Add uts ns 10 pid 53734
(00.001716) Will take mnt namespace in the image
(00.001717) Add mnt ns 11 pid 53734
(00.001738) Lock network
(00.001804) lockinfo: 1:1 0 3068 08:01:290127 128 128
(00.001809) lockinfo: 2:1 0 3068 08:01:290125 1073741826 1073742335
(00.001814) lockinfo: 3:1 0 3057 08:01:290127 128 128
(00.001817) lockinfo: 4:1 0 3057 08:01:290125 1073741826 1073742335
(00.001819) lockinfo: 5:2 1 1215 00:10:12156 0 EOF
(00.001826) lockinfo: 6:2 1 750 00:10:11956 0 EOF
(00.001830) lockinfo: 7:-1 0 1415 08:01:1977840 0 EOF
(00.001831) Error (proc_parse.c:1967): Unknown file lock: 7: LEASE  ACTIVE    READ  1415 08:01:1977840 0 EOF
!
(00.001843) Unlock network
(00.001846) Unfreezing tasks into 1
(00.001847) 	Unseizing 53734 into 1
(00.001891) 	Unseizing 53839 into 1
(00.001898) Error (cr-dump.c:1614): Dumping FAILED.

**Comment by xemul** [comment]
Ah, got it. It's actually a duplicate for #39

**Comment by washraf** [comment]
Could you explain the reason of the error ?

**Comment by xemul** [comment]
There are several types of locks in Linux. 4 if I'm not mistaken -- locks, posix locks, ofd locks and leases. CRIU only supports first two types. And there's a lease lock held on a file in your case.

**Comment by washraf** [comment]
Could the fact that i am using an external NFS storage make such locking, if so what makes it faults some times and some times not ??

**Comment by xemul** [comment]
This is a problem with old kernel API -- it only provided locks info globally and criu failed sometimes when unrelated task used unsupported lock. On newer kernels (4.1 and above) the info about locks is shown per-process so we can (and do) use smarter decision making.

**Comment by xemul** [comment]
@washraf have you had chance to try on newer kernel?

**Comment by washraf** [comment]
No, You can close it till i get back to you.
Thanks for your time :)

**Comment by washraf** [comment]
I have tried it and It works without any error. Thanks very much.
I will close this issue, I have another and I will open another issue with it :D
