### ISSUE TITLE
criu isn't recompiled after changing criu/arch/x86/crtools.c

### ISSUE THREAD

**Issue by avagin** [xemul/criu#163]
[root@fc22-vm criu]# touch criu/arch/x86/crtools.c 
[root@fc22-vm criu]# make
make[1]: Entering directory '/root/git/criu'
make[1]: Leaving directory '/root/git/criu'
make[1]: Entering directory '/root/git/criu'
make[1]: 'images/built-in.o' is up to date.
make[1]: Leaving directory '/root/git/criu'
make[1]: Entering directory '/root/git/criu/criu'
make[2]: Entering directory '/root/git/criu/criu'
make[2]: Leaving directory '/root/git/criu/criu'
make[2]: Entering directory '/root/git/criu/criu'
  DEP      arch/x86/crtools.d
  CC       arch/x86/crtools.o
  LINK     arch/x86/crtools.built-in.o
make[2]: Leaving directory '/root/git/criu/criu'
make[2]: Entering directory '/root/git/criu/criu'
make[2]: Leaving directory '/root/git/criu/criu'
make[2]: Entering directory '/root/git/criu/criu'
make[2]: Leaving directory '/root/git/criu/criu'
make[2]: Entering directory '/root/git/criu/criu'
make[2]: Leaving directory '/root/git/criu/criu'
make[1]: Leaving directory '/root/git/criu/criu'
make[1]: Entering directory '/root/git/criu/lib'
  GEN      lib-py
make[2]: Entering directory '/root/git/criu/lib/py'
make[3]: Entering directory '/root/git/criu/lib/py/images'
make[3]: Leaving directory '/root/git/criu/lib/py/images'
make[2]: Leaving directory '/root/git/criu/lib/py'
make[1]: Leaving directory '/root/git/criu/lib'

**Comment by xemul** [comment]
Cc @cyrillos

**Comment by cyrillos** [comment]
The fix is sent out. Thanks for report.
