### ISSUE TITLE
criu fails to checkpoint container

### ISSUE THREAD

**Issue by rajasec** [xemul/criu#17]
With Ubuntu 15.04 (Kernel 3.19)
I've tried the checkpoint with runc
(00.123993)     165: 2c:/sys @ ./proc/sys
(00.123996)     238: 20:/user.slice/user-1000.slice/session-c2.scope/runc @ ./sys/fs/cgroup/hugetlb
(00.123999)     237: 1f:/user.slice/user-1000.slice/session-c2.scope/runc @ ./sys/fs/cgroup/memory
(00.124002)     236: 1e:/user.slice/user-1000.slice/session-c2.scope/runc @ ./sys/fs/cgroup/net_cls,net_prio
(00.124005)     235: 1d:/user.slice/user-1000.slice/session-c2.scope/runc @ ./sys/fs/cgroup/cpu,cpuacct
(00.124007)     234: 1c:/user.slice/user-1000.slice/session-c2.scope/runc @ ./sys/fs/cgroup/perf_event
(00.124010)     233: 1b:/user.slice/user-1000.slice/session-c2.scope/runc @ ./sys/fs/cgroup/blkio
(00.124012)     232: 1a:/user.slice/user-1000.slice/session-c2.scope/runc @ ./sys/fs/cgroup/cpuset
(00.124015)     231: 19:/user.slice/user-1000.slice/session-c2.scope/runc @ ./sys/fs/cgroup/freezer
(00.124017)     230: 18:/user.slice/user-1000.slice/session-c2.scope/runc @ ./sys/fs/cgroup/devices
(00.124020)     229: 16:/user.slice/user-1000.slice/session-c2.scope @ ./sys/fs/cgroup/systemd
(00.124022)     228: 32:/ @ ./sys/fs/cgroup
(00.124024) Something is mounted on top of ./sys/fs/cgroup
(00.124085) Error (mount.c:1005): Can't create a temporary directory: Read-only file system
(00.124210) Unlock network
(00.124214) Running network-unlock scripts
(00.124224)     RPC
(00.124325) Unfreezing tasks into 1
(00.124330)     Unseizing 8159 into 1
(00.124376) Error (cr-dump.c:1947): Dumping FAILED.

**Comment by xemul** [comment]
Known issue :) #10
