### ISSUE TITLE
Criu dump fails (when mounts exist with nsroot= as option)

### ISSUE THREAD

**Issue by KKoukiou** [xemul/criu#172]
I am trying to dump a linux container, but dump fails with:

> Error (mount.c:746): mnt: 195:./run/lxcfs/controllers/name=systemd doesn't have a proper root mount

That is mounted like this:
` name=systemd on /run/lxcfs/controllers/name=systemd type cgroup (rw,relatime,name=systemd,nsroot=/)`

This error started since that nsroot field appeared in cgroup mounts, and I think it is related to this fix http://lxr.free-electrons.com/source/Documentation/cgroups/cgroups.txt?v=3.15.
I provide attached the whole mount cmd output for cgroups, and the dump.log.
some info: 
I have tested with criu Version: 2.0-2ubuntu3, and criu-dev GitID: v2.2-326-g15c3d68, 
on ubuntu 16.04 with 4.4.0-21-generic.
Any idea ?
ps: I have seen some patches, ( in the kernel, and criu) but these are for the restore process.
Thanks,
Katerina
[dump.txt](https://github.com/xemul/criu/files/309366/dump.txt)
[mounts.txt](https://github.com/xemul/criu/files/309367/mounts.txt)

**Comment by xemul** [comment]
Cc @tych0 and @avagin

**Comment by tych0** [comment]
On Fri, Jun 10, 2016 at 09:26:30AM -0700, Katerina Koukiou wrote:
> I am trying to dump a linux container, but dump fails with:
> 
> > Error (mount.c:746): mnt: 195:./run/lxcfs/controllers/name=systemd doesn't have a proper root mount
> 
> That is mounted like this:
> ` name=systemd on /run/lxcfs/controllers/name=systemd type cgroup (rw,relatime,name=systemd,nsroot=/)`
> 
> This error started since that nsroot field appeared in cgroup mounts, and I think it is related to this fix http://lxr.free-electrons.com/source/Documentation/cgroups/cgroups.txt?v=3.15.
> I provide attached the whole mount cmd output for cgroups, and the dump.log.
> some info: 
> I have tested with criu Version: 2.0-2ubuntu3, and criu-dev GitID: v2.2-326-g15c3d68, 
> on ubuntu 16.04 with 4.4.0-21-generic.
> Any idea ?
> ps: I have seen some patches, ( in the kernel, and criu) but these are for the restore process.
> Thanks,

Hmm, both of these should have
20f5024ac9cca9c5ea3faa694e89342ff0bb7661, which should fix this issue.

Do you not have a name=systemd controller on the host?

**Comment by KKoukiou** [comment]
Well, it was my fault, not a criu bug. I had done something odd when starting the container, maybe with the configuration; I didn't mention it before but, I had used a customized libvirt-lxc binary  to start the container, and not lxc tools (lxc-start). Anyway, I cannot reproduce the bug now, so I mark the issue as closed.
Sorry for that,
Katerina
