### ISSUE TITLE
Restore fails when using symlink'd image files

### ISSUE THREAD

**Issue by tswift242** [xemul/criu#173]
I'm doing C/R of a Docker container. When I create a "copy" of the criu image where every file in the copy image directory is a symlink to the corresponding original image file, and use this copy image for the restore, the restore fails with:

"Error (cr-restore.c:752): Unexpected EOF 1".

This happens early on, during the post-setup-namespaces scripts phase. The full restore.log is attached. If I use the original image directory, the restore succeeds. I've reproduced this issue with a simple busybox container, as below:
1. docker run -d busybox /bin/sh -c 'while true; do sleep 5; done'
2. docker checkpoint --image-dir=/mnt/criu.image <containerId>
3. mkdir /mnt/criu.image-copy && for file in /mnt/criu.image/*; do ln -s $file /mnt/criu.image-copy/$(basename $file); done
4. docker create busybox /bin/sh -c 'while true; do sleep 5; done'
5. docker restore --force=true --image-dir=/mnt/criu.image-copy <containerId>

Step 5 will fail with the above error. Note, if I do "docker restore --force=true --image-dir=/mnt/criu.image <containerId>", this succeeds. I'm using CRIU v2.2 on Linux 4.4.6.

Another error I've seen when using symlink'd image files is "Error (util.c:542): Can't read link of fd -404: No such file or directory." I see this when my application has a ghost file (which it does by default); when I prevent the ghost file from being created and then do C/R, I see the same restore failure as the busybox container. The surrounding snippet in the restore log in the case of a ghost file is:

"1: Opening ghost file 0x1 for tmp/jna--1071123326/jna6703529655346764888.tmp
1: No ghost-file-1.img image
1: Error (util.c:542): Can't read link of fd -404: No such file or directory
1: Error (protobuf.c:75): Unexpected EOF on (null)"

Again, even with a ghost file, the C/R of my application succeeds when I use the original, non-symlink'd image files.

As for motivation, my use case it that I need to use CRIT to modify a few things in the image each time before I do a restore (see https://github.com/xemul/criu/issues/167). In order to support concurrent restores, I planned to have each restore use its own copy of the image. However, my application is very large and so the resulting image is over 1GB in size. So a hard copy takes too long. Since I'm only modifying 1 or 2 files, I planned to symlink all the copy image files to the original image files, then hard copy and modify just the file or two I need to change. Trying this approach led me to this issue.

[busybox_sym_restore.txt](https://github.com/xemul/criu/files/309581/busybox_sym_restore.txt)

**Comment by avagin** [comment]
openat(image_dir_fd, image_name) is used to open images from another mount namespace. This way doesn't work for absolute symlinks.

**Comment by xemul** [comment]
@avagin , but image_name is a path with single component in it. Why would openat() fail in this case?

**Comment by avagin** [comment]
@xemul I think you don't understand the use case. Here each image file is a symlink, so when we call openat(img_dir, image_name), the kernel reads the symlink, but resolves it in the current mount namespace. As a workaround for this problem I can suggest to create relative symlinks:
```
 mkdir /mnt/criu.image-copy && for file in /mnt/criu.image/*; do ln -s ../criu.image/$(basename $file) /mnt/criu.image-copy/$(basename $file); done
```

**Comment by xemul** [comment]
Ah, I see.

@tswift242 , the symlinks to particular image files is not something, that can be easily supported due to "different mount namespaces" issue. So I'd like to close this issue with wontfix, but we're still open to fix whatever else is required to help you do what you want to.

Said that, would hardlinking the images work for you?

CRIU also supports (to some extent) stacking the images, you can put parent-> link into the image dir, so criu will use info from several images to restore. However, this stacking only works for memory images, not for the rest. If there's a strong need for that, we can try to extend stacking on other images.
