### ISSUE TITLE
Can not dump lxc container with a simple loop script

### ISSUE THREAD

**Issue by chenhaiq** [xemul/criu#174]
dump failed for a lxc container running a script from https://criu.org/Simple_loop
```
(00.004587) Collected 10656 in 1 state
(00.004599) Will take pid namespace in the image
(00.004605) Add pid ns 8 pid 10656
(00.004613) Will take net namespace in the image
(00.004619) Add net ns 9 pid 10656
(00.004627) Will take ipc namespace in the image
(00.004633) Add ipc ns 10 pid 10656
(00.004641) Will take uts namespace in the image
(00.004646) Add uts ns 11 pid 10656
(00.004653) Will take mnt namespace in the image
(00.004659) Add mnt ns 12 pid 10656
(00.004668) Will take cgroup namespace in the image
(00.004674) Add cgroup ns 13 pid 10656
(00.004863) Error (namespaces.c:403): Can't dump nested cgroup namespace for 25861
(00.004872) Error (namespaces.c:649): Can't make cgroup id
```
[full log](https://pek3a.qingstor.com/oc-storage/dump.log)

criu is executed by lxc-checkpoint in:
```
/usr/sbin/criu dump --tcp-established --file-locks --link-remap --manage-cgroups --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /pitrix/data/container/i-gb6mmfct/dump -o /pitrix/data/container/i-gb6mmfct/dump/dump.log -vvvvvv -t 10656 --freeze-cgroup /sys/fs/cgroup/freezer///lxc/i-gb6mmfct-1 --force-irmap --leave-running

```

The process 25861 is test.sh:
```
# ps -C test.sh
  PID TTY          TIME CMD
25861 ?        00:00:00 test.sh
```
it is a script like this:
```
$ cat > test.sh <<-EOF
#!/bin/sh
while :; do
    sleep 1
    date
done
EOF
$ chmod +x test.sh

# run the script
lxc-attach -n <lxc name>
setsid ./test.sh  < /dev/null &> test.log &
```

My env:
```
ubuntu 16.04
kernel 4.4.0-23-generic

ii  liblxc1                            2.0.1-0ubuntu1~ubuntu16.04.1~ppa1 amd64        Linux Containers userspace tools (library)
ii  lxc                                2.0.1-0ubuntu1~ubuntu16.04.1~ppa1 all          Transitional package for lxc1
ii  lxc-common                         2.0.1-0ubuntu1~ubuntu16.04.1~ppa1 amd64        Linux Containers userspace tools (common tools)
ii  lxc-templates                      2.0.1-0ubuntu1~ubuntu16.04.1~ppa1 amd64        Linux Containers userspace tools (templates)
ii  lxc1                               2.0.1-0ubuntu1~ubuntu16.04.1~ppa1 amd64        Linux Containers userspace tools
ii  lxcfs                              2.0.1-0ubuntu1~ubuntu16.04.1~ppa1 amd64        FUSE based filesystem for LXC
ii  python3-lxc                        2.0.1-0ubuntu1~ubuntu16.04.1~ppa1 amd64        Linux Containers userspace tools (Python 3.x bindings)

```

**Comment by xemul** [comment]
Cc @tych0

**Comment by tych0** [comment]
Hi Chen,

On Tue, Jun 14, 2016 at 08:44:18PM -0700, Chen Hai Quan wrote:
> dump failed for a lxc container running a script from https://criu.org/Simple_loop
> ```
> (00.004587) Collected 10656 in 1 state
> (00.004599) Will take pid namespace in the image
> (00.004605) Add pid ns 8 pid 10656
> (00.004613) Will take net namespace in the image
> (00.004619) Add net ns 9 pid 10656
> (00.004627) Will take ipc namespace in the image
> (00.004633) Add ipc ns 10 pid 10656
> (00.004641) Will take uts namespace in the image
> (00.004646) Add uts ns 11 pid 10656
> (00.004653) Will take mnt namespace in the image
> (00.004659) Add mnt ns 12 pid 10656
> (00.004668) Will take cgroup namespace in the image
> (00.004674) Add cgroup ns 13 pid 10656
> (00.004863) Error (namespaces.c:403): Can't dump nested cgroup namespace for 25861
> (00.004872) Error (namespaces.c:649): Can't make cgroup id
> ```
> [full log](https://pek3a.qingstor.com/oc-storage/dump.log)
> 
> criu is executed by lxc-checkpoint in:
> ```
> /usr/sbin/criu dump --tcp-established --file-locks --link-remap --manage-cgroups --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /pitrix/data/container/i-gb6mmfct/dump -o /pitrix/data/container/i-gb6mmfct/dump/dump.log -vvvvvv -t 10656 --freeze-cgroup /sys/fs/cgroup/freezer///lxc/i-gb6mmfct-1 --force-irmap --leave-running
> 
> ```
> 
> The process 25861 is test.sh:
> ```
> # ps -C test.sh
>   PID TTY          TIME CMD
> 25861 ?        00:00:00 test.sh
> ```
> it is a script like this:
> ```
> $ cat > test.sh <<-EOF
> #!/bin/sh
> while :; do
>     sleep 1
>     date
> done
> EOF
> $ chmod +x test.sh
> 
> # run the script
> lxc-attach -n <lxc name>
> setsid ./test.sh  < /dev/null &> test.log &

Interesting, I would have expected you to get the error about not all
tasks being a child of init, but somehow I can't find where CRIU
generates that error message.

In any case, lxc-attach runs tasks not as the child of init, and I
guess it uses unshare() instead of setns() to match the cgroup ns for
the container, which is why you're getting the "nested" error (which
is wrong, it really should be "different" I guess).

Anyway, IIRC, I don't think it's supported to dump containers where
not all tasks are children of init. You could install sshd in the
container, ssh to it and run the script, and it should dump just fine.

Tycho

**Comment by chenhaiq** [comment]
@tych0 yes, it works if I run the script via ssh.
