### ISSUE TITLE
Trying to checkpoint mysql container criu failed: type NOTIFY errno 0. Docker version 1.10.0-dev

### ISSUE THREAD

**Issue by Vallari-Mehta** [xemul/criu#176]
docker run --name mysql2 -e MYSQL_ROOT_PASSWORD=root -d mysql
docker checkpoint mysql2

Error:
ERRO[1237] Handler for POST /v1.22/containers/mysql2/checkpoint returned error: Cannot checkpoint container mysql2: criu failed: type NOTIFY errno 0

docker version

Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   cec56b2
 Built:        Fri Feb 12 23:11:36 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   cec56b2
 Built:        Fri Feb 12 23:11:36 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by avagin** [comment]
What is the kernel version here?

**Comment by avagin** [comment]
Could you show an output for "sudo criu check --all"?

Here is a similar problem: https://lists.openvz.org/pipermail/criu/2014-April/013425.html

**Comment by Vallari-Mehta** [comment]
criu check --all command is not supported. Can I provide you specific details?

criu check -V
Version: 2.0

Kernel version 3.12.49-11 
SUSE Linux Enterprise Server 12 SP1

**Comment by avagin** [comment]
This kernel is too old.
AIO mappings are supported starting with 3.19.

e4a0d3e72	aio: Make it possible to remap aio ring	3.19
https://criu.org/Upstream_kernel_commits

**Comment by Vallari-Mehta** [comment]
Is there a workaround?

**Comment by avagin** [comment]
It's what I found in the mail list:
```
> Dumping a MySQL daemon started with the following my.cnf succeds:
> 
> [mysqld]
> innodb_use_native_aio = false
```

**Comment by Vallari-Mehta** [comment]
I was able to checkpoint and restore my MySQL container using your suggestion. :)
Thank you so much avagin. Really appreciate your help.
