### ISSUE TITLE
fail to restore jvm with large physical memory

### ISSUE THREAD

**Issue by EddiePi** [xemul/criu#179]
I have done some test on dumping and restoring jvm with small physical memory. CRIU works well.
But when I'm trying to restore jvm with large physical memory ( 2G ~ 4G), CRIU starts to fail with the following errors. 

The first time execute the `restore` command after `dump`, it shows as follow:
`pie: Error (pie/restorer.c:442): Thread pid mismatch 9844/9843`
`pie: Error (pie/restorer.c:488): Restorer abnormal termination for 984>`
`pie: 2`
`Error (cr-restore.c:2226): Restoring FAILED.`
 
Then when I try to `restore` **again**, it shows another error as follow:
`10175: Error (files-reg.c:1524): Can't open file tmp/hsperfdata_user/10175 on restore: No such file or directory`
`10175: Error (files-reg.c:1466): Can't open file tmp/hsperfdata_user/10175: No such file or directory`
`10175: Error (cr-restore.c:699): Can't fixup fd`
`Error (cr-restore.c:2226): Restoring FAILED.`

The larger the physical memory is, the more likely CRIU restore would fail.

jvm with large logical memory and small physical memory can be dump and restore successfully. And don't worry about the machine. Its total memory size is 128G.

My CRIU version is 2.2. OS is Ubuntu Server 15.10.

Can anyone help with it? **Or explain the essence of this issue?** 

Thanks!

**Comment by xemul** [comment]
Hi,

The first error means, that CRIU couldn't restore the thread's PID, since it was already busy. You can resolve this by unsharing the pid namespace before restoring the tree, or by using the --unshare option of criu (in criu-dev branch currently).

The 2nd error means, that a file (or directory) named tmp/hsperfdata_user/10175 was removed. Probably this is due to error from previous restore. Would you show the log files and contents of 'reg-files.img' image file (decode it with crit show reg-files.img)?

**Comment by EddiePi** [comment]
Hi @xemul , thanks to reply. I cannot solve the first problem by simply unsharing the pid namespace.

before I execute `restore`, I execute `sudo unshare -p --fork` as written in the doc on _criu.org_. But a new problem occur:
`Error (util.c:780): Can't read pme for pid 14: Bad address`

Here is another error information when I tried to restore a jvm with about 2G physical memory without unsharing the pid namespace:
`pie: Error (pie/restorer.c:442): Thread pid mismatch 32649/32645`
`pie: Error (pie/restorer.c:442): Thread pid mismatch 32656/32652`
`pie: Error (pie/restorer.c:488): Restorer abnormal termination for 326>`
`pie: Error (pie/restorer.c:442): Thread pid mismatch 32655/32651`
`pie: Error (pie/restorer.c:442): Thread pid mismatch 32658/32654`
`pie: Error (pie/restorer.c:442): Thread pid mismatch 32653/32649`
`pie: Error (pie/restorer.c:442): Thread pid mismatch 32650/32646`
`pie: Error (pie/restorer.c:442): Thread pid mismatch 32660/32656`
`pie: Error (pie/restorer.c:442): Thread pid mismatch 32662/32658`
`pie: Error (pie/restorer.c:488): Restorer abnormal termination for 326>`
`pie: 44`
`pie: Error (pie/restorer.c:488): Restorer abnormal termination for 326>`
`pie: Error (pie/restorer.c:442): Thread pid mismatch 32663/32659`
`pie: 44`
`pie: Error (pie/restorer.c:442): Thread pid mismatch 32664/32660`
`pie: Error (pie/restorer.c:488): Restorer abnormal termination for 326>`
`pie: Error (pie/restorer.c:488): Restorer abnormal termination for 326>`
`pie: 44`
`pie: 44`
`pie: Error (pie/restorer.c:488): Restorer abnormal termination for 326>`
`pie: 44`
`pie: Error (pie/restorer.c:442): Thread pid mismatch 32665/32661`
`pie: Error (pie/restorer.c:488): Restorer abnormal termination for 326>`
`pie: 44`
`pie: Error (pie/restorer.c:442): Thread pid mismatch 32666/32662`
`pie: Error (pie/restorer.c:488): Restorer abnormal termination for 326>`
`pie: 44`
`Error (cr-restore.c:2226): Restoring FAILED.`

I notice that some pid appear on both side of the slash. Is this an issue?


For the second problem, I do not find the log file in the img directory. The reg.files.img is as follow:
{
    "magic": "REG_FILES", 
    "entries": [
        {
            "id": 1, 
            "flags": "O_RDWR | O_LARGEFILE", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/dev/pts/24"
        }, 
        {
            "id": 2, 
            "flags": "O_LARGEFILE | 0x80000", 
            "pos": 58442542, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/usr/lib/jvm/jdk1.7.0_71/jre/lib/rt.jar", 
            "size": 62552900
        }, 
        {
            "id": 3, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/usr/lib/jvm/jdk1.7.0_71/bin/java", 
            "size": 7718
        }, 
        {
            "id": 4, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/usr/lib/locale/locale-archive", 
            "size": 1607664
        }, 
        {
            "id": 5, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/usr/lib/jvm/jdk1.7.0_71/jre/lib/amd64/libzip.so", 
            "size": 123434
        }, 
        {
            "id": 6, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/lib/x86_64-linux-gnu/libnss_files-2.21.so", 
            "size": 51736
        }, 
        {
            "id": 7, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/lib/x86_64-linux-gnu/libnss_nis-2.21.so", 
            "size": 47616
        }, 
        {
            "id": 8, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/lib/x86_64-linux-gnu/libnsl-2.21.so", 
            "size": 97224
        }, 
        {
            "id": 9, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/lib/x86_64-linux-gnu/libnss_compat-2.21.so", 
            "size": 35688
        }, 
        {
            "id": 10, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/usr/lib/jvm/jdk1.7.0_71/jre/lib/amd64/libjava.so", 
            "size": 219961
        }, 
        {
            "id": 11, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/usr/lib/jvm/jdk1.7.0_71/jre/lib/amd64/libverify.so", 
            "size": 65437
        }, 
        {
            "id": 12, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/lib/x86_64-linux-gnu/librt-2.21.so", 
            "size": 31680
        }, 
        {
            "id": 13, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/lib/x86_64-linux-gnu/libm-2.21.so", 
            "size": 1084840
        }, 
        {
            "id": 14, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/usr/lib/jvm/jdk1.7.0_71/jre/lib/amd64/server/libjvm.so", 
            "size": 15219002
        }, 
        {
            "id": 15, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/lib/x86_64-linux-gnu/libc-2.21.so", 
            "size": 1869392
        }, 
        {
            "id": 16, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/lib/x86_64-linux-gnu/libdl-2.21.so", 
            "size": 14592
        }, 
        {
            "id": 17, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/usr/lib/jvm/jdk1.7.0_71/lib/amd64/jli/libjli.so", 
            "size": 106366
        }, 
        {
            "id": 18, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/lib/x86_64-linux-gnu/libpthread-2.21.so", 
            "size": 142080
        }, 
        {
            "id": 19, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/lib/x86_64-linux-gnu/ld-2.21.so", 
            "size": 154376
        }, 
        {
            "id": 20, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/tmp/hsperfdata_user/32644", 
            "size": 32768
        }, 
        {
            "id": 21, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/home/user/testwordspace/allocationTestJava/src"
        }, 
        {
            "id": 22, 
            "flags": "", 
            "pos": 0, 
            "fown": {
                "uid": 0, 
                "euid": 0, 
                "signum": 0, 
                "pid_type": 0, 
                "pid": 0
            }, 
            "name": "/"
        }
    ]
}

**Comment by xemul** [comment]
@EddiePi , the "Can't read PME" error appears, because after plain unshare -p --fork you happen to have /proc describing the previous pid namespace. Although there's a bug in CRIU about this (thanks :) ), it's not recommended to have pid namespace unshared w/o mount namespace. I'll fix the documentation, the "unshare -p -m --fork --mount-proc" is recommended instead.

**Comment by xemul** [comment]
@EddiePi , what do you mean by "some pid appear on both side of the slash"?

**Comment by EddiePi** [comment]
@xemul Thanks! The process can be restored correctly in the new pid namespace now.

Sorry, I did not make myself clear about "some pid appear on both side of the slash". For example, in the following error information:
pie: Error (pie/restorer.c:442): Thread pid mismatch **32649**/32645
pie: Error (pie/restorer.c:442): Thread pid mismatch 32656/32652
pie: Error (pie/restorer.c:488): Restorer abnormal termination for 326>
pie: Error (pie/restorer.c:442): Thread pid mismatch 32655/32651
pie: Error (pie/restorer.c:442): Thread pid mismatch 32658/32654
pie: Error (pie/restorer.c:442): Thread pid mismatch 32653/**32649**

process '**32649**' appears twice. 
I inspected the process tree of the program before dumping and found that process 32649 (and also 32650, 32651,...) are child processes of the parent process. After dumping, I inspected the processes in the system but found no process with pid 32649 (or any pid of the child processes). Then I executed restoring and the 'pid mismatch error' appeared. This error only occurs when I try to restore jvm with large physical memory. A jvm with small physical memory or a C++ process with large physical memory can both be restored successfully (in the same pid namespace). I used to wonder whether criu restores a child process twice? But it works well in a new pid namespace. So what if I really want to restore the process in the same namespace? What did I miss?

**Comment by xemul** [comment]
@EddiePi , the pid conflict are indeed confusing :) The thing is that it's enough for a single pid conflict to make the snow-ball effect -- one thread cannot get its pid and occupies some other's one. This other does the same and so on.

The very first pid conflict can happen when you restore into existing pid namespace for any reason, e.g. systemd notices some activity and spawns a thread to check (it does so). So restoring  into the existing pid namespace is highly not recommended. We're developing the --unshare option for this. It's in the criu-dev branch, hopefully will hit the master one soon.

**Comment by EddiePi** [comment]
@xemul thanks for your explanation! It's really helpful.
