### ISSUE TITLE
alpine: arch/x86/syscalls/syscall32.c:84:74: warning: right shift count >= width of type

### ISSUE THREAD

**Issue by avagin** [xemul/criu#181]
https://travis-ci.org/avagin/criu/jobs/141226345

```
  GEN      arch/x86/sys-exec-tbl-32.c
arch/x86/syscalls/syscall32.c: In function 'sys_pread':
arch/x86/syscalls/syscall32.c:84:74: warning: right shift count >= width of type [-Wshift-count-overflow]
  return sys_pread64(fd, ubuf, count, (u32)(pos & 0xffffffffu), (u32)(pos >> 32));
                                             
```

**Comment by avagin** [comment]
```
  CC       pie/util.o
In file included from arch/x86/compat/vdso-pie-compat.c:7:0:
/criu/criu/include/parasite-vdso.h: In function 'vdso_put_mark':
/criu/criu/include/parasite-vdso.h:49:32: warning: large integer implicitly truncated to unsigned type [-Woverflow]
 #define VDSO_MARK_SIGNATURE_V2 (0x4f53447675697263ULL) /* Magic number (criuvDSO) */
                                ^
/criu/criu/include/parasite-vdso.h:56:18: note: in expansion of macro 'VDSO_MARK_SIGNATURE_V2'
  m->signature  = VDSO_MARK_SIGNATURE_V2;
                  ^
In file included from pie/compat/parasite-vdso-compat.c:17:0:
/criu/criu/include/parasite-vdso.h: In function 'vdso_put_mark':
/criu/criu/include/parasite-vdso.h:49:32: warning: large integer implicitly truncated to unsigned type [-Woverflow]
 #define VDSO_MARK_SIGNATURE_V2 (0x4f53447675697263ULL) /* Magic number (criuvDSO) */
                                ^
/criu/criu/include/parasite-vdso.h:56:18: note: in expansion of macro 'VDSO_MARK_SIGNATURE_V2'
  m->signature  = VDSO_MARK_SIGNATURE_V2;
```

**Comment by avagin** [comment]
gcc -c -O2 -g -Wall -Werror -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -fno-strict-aliasing -iquote /criu/criu/include -iquote /criu/images -
iquote /criu/criu/pie -iquote /criu/criu/arch/x86 -iquote /criu/criu/arch/x86/include -iquote /criu/ -I/usr/include/libnl3 -fno-pic -m32 -DCR_NOGLIBC -DCONFIG
_X86_32 arch/x86/syscalls/syscall32.c -o arch/x86/syscalls/syscall32.o

We compile with -m32 (for i386), so it's probably about the multiarch support in Alpine

Cc: @adrianreber

**Comment by avagin** [comment]
Alpine LInux doesn't have the multiarch support. @0x7f454c46, can we do 32-bit compatible C/R to be optional?

**Comment by 0x7f454c46** [comment]
Sure we can do 32-bit C/R optional -- adding not only kdat feature that tests kernel for the support, but also adding compile-time test with -m32 and note that build visible to user somehow. I also thought about some refactor and adding CONFIG_COMPAT build definition, so it can go with it.
Did I got you right, is this desired?

**Comment by 0x7f454c46** [comment]
So, with this refactor, I can mark it in criu-check like "compiled without multilib support -- no 32-bit C/R" and so we can drop dependency on gcc-multilib compiler and libc-mulitilib, making them optional for 32-bit C/R.

**Comment by avagin** [comment]
@0x7f454c46 are you going to fix this issue?

**Comment by 0x7f454c46** [comment]
If this is still valid about absent of -m32 support -- yes, I will prepare patches on this/next week on top of Make-fixes patches set, which is currently in the maillist.

**Comment by xemul** [comment]
So :) Have we fixed this or have we not?

**Comment by 0x7f454c46** [comment]
I'm on CONFIG_COMPAT right now -- sorry for the delay, will send patches as soon, as they got ready.
