### ISSUE TITLE
Can not see incremental effect if page-server is used

### ISSUE THREAD

**Issue by zhichao-cao** [xemul/criu#183]
When I use incremental dump with page-server to checkpoint mysql(1GB memory usage), it always send the whole memory pages to page-server(about 1GB page images). So the time for each dump and final dump(no leave-running) is nearly the same time, and there is no incremental effect which is shown in incremental dump without page-server. Mysqlslap is running during the test and memory changes are similar between each dump.

**Host A**
ID=`lsof -p $PID|grep /var/lib/mysql/mysql.sock|awk '{print $8}'`
echo $ID
time criu dump -t $PID --images-dir /root/page/21/ --page-server --address 192.168.110.2 --port 8787 --leave-running --track-mem --shell-job --file-locks --tcp-established --ext-unix-sk=$ID
sleep 5
time criu dump -t $PID --images-dir /root/page/22/ --page-server --address 192.168.110.2 --port 8787 --leave-running --track-mem --shell-job --file-locks --tcp-established --ext-unix-sk=$ID --prev-images-dir ../21/
sleep 5
time criu dump -t $PID --images-dir /root/page/23/ --page-server --address 192.168.110.2 --port 8787 --leave-running --track-mem --shell-job --file-locks --tcp-established --ext-unix-sk=$ID --prev-images-dir ../22/
sleep 5
time criu dump -t $PID --images-dir /root/page/24/ --page-server --address 192.168.110.2 --port 8787 --track-mem --shell-job --file-locks --tcp-established --ext-unix-sk=$ID --prev-images-dir ../23/

**The script on host B page-server**(with or without --auto-dedup, the time is nearly the same)
#!/bin/bash
echo 'page server 1'
criu page-server --images-dir /root/page/21/ --port 8787
echo 'page server 2'
criu page-server --images-dir /root/page/21/ --port 8787
echo 'page server 3'
criu page-server --images-dir /root/page/21/ --port 8787
echo 'page server 4'
criu page-server --images-dir /root/page/21/ --port 8787
echo 'finished'

**testing result**
incremental dump without page-server(1G memory to be dumped)
   1st ---------2rd ------------3rd -----------last
3.982s------0.608s--------0.615s -------0.568s

Incremental dump with page-server (1GB memory to be dumped)
    1st ---------2rd ------------3rd -----------last
4.015s-------3.865s-------3.978s -------4.028s

The script is listed, is there anything I did wrong or I miss the options?

**Comment by xemul** [comment]
Try to use --prev-images-dir for page-server too.

**Comment by zhichao-cao** [comment]
@xemul It works, thank you!
