### ISSUE TITLE
[PATCH] Add missing "proto2" syntax marker to .proto files

### ISSUE THREAD

**Issue by hartwork** [xemul/criu#184]
Hi!

Please consider to `git-am` the patch attached to address warnings from proto-c of protobuf 3.x.
If this way of sharing patches is inconvenient to you, please let me know.

Best, Sebastian
[0001-Add-missing-proto2-syntax-marker.patch.txt](https://github.com/xemul/criu/files/344110/0001-Add-missing-proto2-syntax-marker.patch.txt)

**Comment by xemul** [comment]
Yup, patch is applied to criu-dev branch. I'll push one to master soon. But next time, PLEASE, submit patches into the criu@openvz.org mailing list for wider review :)

**Comment by hartwork** [comment]
I found it at ea7c09e6114ee66f9180bd182f221edeeaa9f773 . Thanks!
I'll keep the mailing list in mind. Best, Sebastian
