### ISSUE TITLE
Executable file descriptor is closed too early or not duped during restore if executable itself is a --external and inherited

### ISSUE THREAD

**Issue by kikosha** [xemul/criu#186]
I dump/restore a process tree that is being executed in a chroot. The root process executable file remains outside of the chroot so I provide it as an external file (`--external file[xxx:xxxxxxx]`). Later, when I try to restore the process I provide this executable as an inherited file descriptor (this file is physically present inside the chroot). By trial and error I found out that I have to provide it as --inherit-fd in three versions simultaneously, lets take `/bin/java` for example:
inode: 26220292 and mountId 310, opened with file descriptor 45 (I manually open a new file descriptor so as to provide it to the restore process)
In dump command I provide: 
`--external file[136:1901704]`
In restore command I provide: 
`fd[45]:usr/share/javaAppletEngine/bin/java  --inherit-fd fd[45]:ile[136:1901704]   --inherit-fd fd[45]:file[136:1901704]`

the 'ile:' and 'file:' versions are provided since there seem to be a bug that cuts of the first char of the path to make a relative path, but in case of this notation it is a mistake.

The restore goes well until it gets to `cr-restore.c: restore_one_alive_task, prepare_mm(pid, ta)` call. When it tries to call `open_reg_by_id(mm->exe_file_id)` it discovers that its file descriptor was already closed during the `inherit_fd_fini` step and it was not duped as other fd's were. 
I noticed that there is an option to increase remap users count for special files and there is even a comment about this in `files-reg.c`:
```
struct file_desc *try_collect_special_file(u32 id, int optional)
{
	struct file_desc *fdesc;

	/*
	 * Files dumped for vmas/exe links can have remaps
	 * configured. Need to bump-up users for them, otherwise
	 * the open_path() would unlink the remap file after
	 * the very first open.
	 */
```
but that does not happen. 

Finally, the restore process exists with:
```

(00.272358)     14: Inherit fd file[136:1901704] -> 45 has been closed
(00.272378)     14: Error (files-reg.c:1553): Can't open file ile[136:1901704] on restore: No such file or directory
(00.272383)     14: Error (files-reg.c:1494): Can't open file ile[136:1901704]: No such file or directory
(00.272388)     14: restore_one_alive_task for pid 14 resulted with -1

```

Apparently, the path `ile[136:1901704]`  does not exist in the file system, while `usr/share/javaAppletEngine/bin/java ` does, but it is not used.

**Comment by xemul** [comment]
Cc @avagin

**Comment by avagin** [comment]
I think here is a problem that you set the inherite-fd option a few times for the same descriptor (45).

**Comment by xemul** [comment]
@kikosha , can you confirm @avagin 's suggestion?

**Comment by xemul** [comment]
OK, if the problem is still here -- feel free to re-open the issue.
