### ISSUE TITLE
Docker - After restoring MySQL Container: Cannot connect 

### ISSUE THREAD

**Issue by klesgidis** [xemul/criu#19]
I run a Docker MySQL Container. I C/R the container without any errors. 

When I try to reconnect to it after restore, I get the message:
```
ERROR 2003 (HY000): Can't connect to MySQL server on 'xxx.xx.x.x' (111)
```
If I stop and start the container, I can reconnect

**Comment by xemul** [comment]
Where do you get this message from?

**Comment by klesgidis** [comment]
Trying to connect to mysql from my host
```
mysql -h<container_ip> -uroot -p
```
I enter my password and receive the above message.

**Comment by klesgidis** [comment]
@xemul I found what it was causing the problem.. My stupidity!! :P

When you C/R a container the IP of the container changes! So I was using the old IP address. Sorry for the spam! 

You can close it.. Or delete it ! :P Sorry again
