### ISSUE TITLE
building on OpenSuse Leap 42.1 - crti.o: unrecognized relocation (0x2a) in section `.init'

### ISSUE THREAD

**Issue by billpage** [xemul/criu#190]
wspage@suse:~/criu> uname -r
4.1.26-21-default

wspage@suse:~/criu> make
...
make[1]: Entering directory '/home/wspage/criu'
make[1]: Leaving directory '/home/wspage/criu'
make[1]: Entering directory '/home/wspage/criu'
make[1]: 'images/built-in.o' is up to date.
make[1]: Leaving directory '/home/wspage/criu'
make[1]: Entering directory '/home/wspage/criu/criu'
Makefile:53: "Couldn't find some of the required libraries"
Makefile:54: "Make sure the following packages are installed"
Makefile:55: "RPM based distros: protobuf protobuf-c protobuf-c-devel protobuf-compiler protobuf-devel protobuf-python libnl3-devel libcap-devel"
Makefile:56: "DEB based distros: libprotobuf-dev libprotobuf-c0-dev protobuf-c-compiler protobuf-compiler python-protobuf libnl-3-dev libcap-dev"
Makefile:57: "To run tests the following packages are needed"
Makefile:58: "RPM based distros: libaio-devel"
Makefile:59: "DEB based distros: libaio-dev"
Makefile:60: *** "Compilation aborted".  Stop.
make[1]: Leaving directory '/home/wspage/criu/criu'
Makefile:193: recipe for target 'criu' failed
make: *** [criu] Error 2

--

wspage@suse:~/criu> zypper se protobuf-c protobuf-c-devel protobuf-compiler protobuf-devel protobuf-python libnl3-devel libcap-devel
Loading repository data...
Reading installed packages...

S | Name                | Summary                                      | Type   
--+---------------------+----------------------------------------------+--------
i | libcap-devel        | Development files for libcap                 | package
i | libnl3-devel        | Libraries and headers for libnl              | package
i | libnl3-devel-32bit  | Libraries and headers for libnl              | package
i | libprotobuf-c-devel | C bindings for Google's Protocol Buffers     | package
i | libprotobuf-c1      | C bindings for Google's Protocol Buffers     | package
i | protobuf-c          | C bindings for Google's Protocol Buffers     | package
i | protobuf-devel      | Header files, libraries and development do-> | package

I modified 'criu/Makefile' to capture output of the test:
...
# Make sure all required libs are installed
ifneq ($(MAKECMDGOALS),clean)
ifneq ($(MAKECMDGOALS),mrproper)
        ifneq ($(shell sh -c                                                            \
                        'TMP="$(OUTPUT)$(TMPOUT).$$$$";                                 \
                        echo "int main(int argc, char *argv[]) { return 0; }" |         \
                        "$(CC)" -x c - $(LIBS) -o "$$TMP" > test.log 2>&1 && echo y;   \
                        rm -f "$$TMP"'),y)
                $(warning "Couldn't find some of the required libraries")
                $(warning "Make sure the following packages are installed")
...

produces

wspage@suse:~/criu/criu> cat test.log
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: /usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/crti.o: unrecognized relocation (0x2a) in section `.init'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld: final link failed: Bad value

--

This happens with both the 2.4 tarball and the current git repository.

**Comment by xemul** [comment]
Cc @cyrillos

**Comment by cyrillos** [comment]
Will take a look, thanks.

**Comment by cyrillos** [comment]
This is not a criu problem but rather libc/binutils
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808205

**Comment by xemul** [comment]
But the original bug is about suse, not debian :)

**Comment by cyrillos** [comment]
It it about system libs, which started to use new kind of relocations. Note that it has nothing to do with criu itself, it's issue of building environment.

**Comment by xemul** [comment]
OK. @billpage is there an updated version of binutils available in your setup?

**Comment by billpage** [comment]
I have

--

wspage@suse:~/criu-2.4> ld -v
GNU ld (GNU Binutils; openSUSE Leap 42.1) 2.25.0
wspage@suse:~/criu-2.4> gcc --version
gcc (SUSE Linux) 4.8.5
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

--

which I believe are standard for OpenSuSE 42.1

wspage@suse:~/criu-2.4> cat /etc/os-release
NAME="openSUSE Leap"
VERSION="42.1"
VERSION_ID="42.1"
PRETTY_NAME="openSUSE Leap 42.1 (x86_64)"
ID=opensuse
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:opensuse:42.1"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://opensuse.org/"
ID_LIKE="suse"

**Comment by cyrillos** [comment]
libc version please?

**Comment by billpage** [comment]
Sorry.

wspage@suse:~/criu-2.4> ldd --version
ldd (GNU libc) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by cyrillos** [comment]
does it happen if you try to build some silly "hello work" from command line gcc -o hello hello.c, where hello.c simply does printf("Hello")?

**Comment by billpage** [comment]
Oh. I am sorry. There is something strange in my system ...

wspage@suse:~> cat hello.c
/* hello.c: display a message on the screen */

#include <stdio.h>

main()
{
        printf("hello, world\n");
}

wspage@suse:~> gcc hello.c
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld:
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../lib64/crti.o: unrecognized
relocation (0x2a) in section `.init'
/usr/lib64/gcc/x86_64-suse-linux/4.8/../../../../x86_64-suse-linux/bin/ld:
final link failed: Bad value
collect2: error: ld returned 1 exit status

--

Sorry to waste your time.  I will investigate further and let you know.

**Comment by cyrillos** [comment]
Yes, you need to fixup your build environment first.

**Comment by cyrillos** [comment]
@xemul close the issue please, it has nothing to do with criu itself

**Comment by xemul** [comment]
Hm... OK. @billpage , if you still need help -- feel free to re-open it and ask more questions.
