### ISSUE TITLE
[criu-dev] zdtm/static/helper_zombie_child fails

### ISSUE THREAD

**Issue by Snorch** [xemul/criu#193]
https://ci.openvz.org/job/CRIU/view/All/job/CRIU-x86_64/branch/criu-dev/617/consoleFull

    ================== Run zdtm/static/helper_zombie_child in ns ===================
    Start test
    ./helper_zombie_child --pidfile=helper_zombie_child.pid --outfile=helper_zombie_child.out
    Run criu dump
    Run criu restore
    =[log]=> dump/zdtm/static/helper_zombie_child/31/1/restore.log
    ------------------------ grep Error ------------------------
    (00.158261) Error (criu/cr-restore.c:1104): 57 exited, status=1
    (00.158392) Error (criu/cr-restore.c:1989): Restoring FAILED.
    ------------------------ ERROR OVER ------------------------
    ########## Test zdtm/static/helper_zombie_child FAIL at CRIU restore ###########

Same on VZ7: https://ci.openvz.org/job/CRIU/job/CRIU-virtuozzo/branch/criu-dev/154/consoleFull

It seem, new test introduced in commit https://github.com/xemul/criu/commit/117f40fb7d04 causes these.

**Comment by Snorch** [comment]
@tych0 @avagin

**Comment by avagin** [comment]
Date: Sat, 23 Jul 2016 02:44:52 +0300                                                                                                                         
From: Andrey Vagin <avagin@openvz.org>                                                                                                                        
Subject: [PATCH] [v4] restore: handle the case where zombies are reparented
