### ISSUE TITLE
Support transit TCP states

### ISSUE THREAD

**Issue by koliaskostas** [xemul/criu#194]
Goal: Take snapshots of a running apache-docker container every given interval (e.g., every 5 seconds).

Problem: Docker will gladly take checkpoints when there are no requests however, it will respond with an error (_Error response from daemon: Cannot checkpoint container apch-01: criu failed: type NOTIFY errno 0_) when requests occur.

Environment:
Distro --> Ubuntu Server 16.04 (inside a Virtualbox VM)
Kernel --> 4.4.0-31-generic
Docker --> 1.10.0-dev, build cec56b2, experimental 

Procedure:
**sudo ./docker --host unix:///var/run/docker-dev.sock pull tutum/apache-php**

**sudo ./docker --host unix:///var/run/docker-dev.sock run --name apch-01 -p 80:80 -d tutum/apache-ph**p
# with no clients

**sudo ./docker --host unix:///var/run/docker-dev.sock checkpoint --image-dir=/tmp/chpt-01 --work-dir=/home/costas/log-01 --leave-running apch-01**

Log
[dump1.log.tar.gz](https://github.com/xemul/criu/files/381934/dump1.log.tar.gz)
# with clients

**sudo ./docker --host unix:///var/run/docker-dev.sock checkpoint --image-dir=/tmp/chpt-02 --work-dir=/home/costas/log-02 --leave-running apch-01**

Log
[dump2.log.tar.gz](https://github.com/xemul/criu/files/381935/dump2.log.tar.gz)

The client requests are emulated by using ab.
**sudo ab -c 1 -t 60 -n 5000 http://192.168.56.104/**
I had similar problems though by using curl iteratively.

**Comment by xemul** [comment]
(00.012538) Error (sk-inet.c:152): In-flight connection (l) for 55b9
(00.012599) ----------------------------------------
(00.012604) Error (cr-dump.c:1303): Dump files (pid: 2711) failed with -1


That's known problem. Unfortunately we still don't live migrate TCP connections that are neither CLOSED nor ESTABLISHED.

There's an option called --skip-in-flight that workarounds it by skipping such sockets (clients will receive RST).

**Comment by koliaskostas** [comment]
Just to make sure we are on the same page, you mean using --skip-in-light option when using CRIU to docker externally right?

**Comment by xemul** [comment]
@koliaskostas , yes. Natively AFAIK there's no such option in docker checkpoint action.

**Comment by xemul** [comment]
So. There has been some work from @avagin to support transit TCP states. Let's track it here :)

**Comment by koliaskostas** [comment]
@xemul Hey, is it included in the latest commit c031417?

**Comment by xemul** [comment]
@koliaskostas , unfortunately no :( Kernel patching is needed for this, not only criu.

**Comment by xemul** [comment]
In issue #62 @avagin provides the links on kernel changes:
https://github.com/avagin/linux-task-diag/tree/tcp-v3
https://github.com/avagin/criu/tree/tcp-closing-states

**Comment by koliaskostas** [comment]
So, I experimented both with the old CRIU version and the experimental settings mentioned by xemul.
I didn't notice any significant changes.


## Experiment 1
---------------------

**Problem**:
Trying to take a checkpoint on a running apache server (no docker this time). The tool ab is used to simulate a flood of incoming requests. CRIU only sparsely manages to succeed to take a checkpoint.

**Environment**:
kernel 4.4.0-36-generic
criu 2.4
apache 2.4.18 (Ubuntu)

**Procedure**:
On host:
sudo ab -c 100 -n 500000 -s 120 http://192.168.56.102/
where in the corresponding IP I have the server on a virtualbox vm with the characteristics mentioned in the environment section.

On guest:
./criu/criu/criu dump --tree $apache_pid --images-dir $images_dir"/"$counter --work-dir $work_dir"/"$counter --log-file $log_dir"/"$counter"/log.dat" --skip-in-flight --tcp-established --leave-running -vvv

**Result**:
[exp1.tar.gz](https://github.com/xemul/criu/files/470914/exp1.tar.gz)


## Experiment 2
---------------------

**Environment**:
kernel 4.8.0-rc3 (compiled the kernel provided by the link)
criu 2.5 (compiled the criu version provided by the link)
apache 2.4.18 (Ubuntu)

**Procedure**:
Same as the previous

**Results**:
[exp2.tar.gz](https://github.com/xemul/criu/files/470915/exp2.tar.gz)


## Question
----------------

What kind of work has been done with respect to transactional TCP connections?
Are there any new options that I am not aware of in the newer "experimental" version that I was suggested to use?

**Comment by avagin** [comment]
There are closed sockets which were connected somewhere. Coud you try out this patch:
```
diff --git a/criu/sk-inet.c b/criu/sk-inet.c
index f4bc519..3c92e83 100644
--- a/criu/sk-inet.c
+++ b/criu/sk-inet.c
@@ -200,7 +200,7 @@ static struct inet_sk_desc *gen_uncon_sk(int lfd, const struct fd_parms *p, int
                }
        } else if (ret == 0) {
                pr_err("Name resolved on unconnected socket\n");
-               goto err;
+//             goto err;
        }
 
        sk->sd.ino = p->stat.st_ino;
```

**Comment by avagin** [comment]
@koliaskostas Pls, ignore my previous comment. It was a workaround. I've implemented support of the TCP_CLOSE state for tcp sockets. You can find all changes in my repos:
https://github.com/avagin/linux-task-diag/tree/tcp-v3
https://github.com/avagin/criu/tree/tcp-closing-states

And you need to set the --skip-in-flight option for criu.

**Comment by koliaskostas** [comment]
Either I didn't understand by what you mean "set the --skip-in-flight option" for criu or something was not implemented properly in that version of criu.

I do 
sudo ./criu/criu/criu dump --tree $apache_pid --images-dir $images_dir --work-dir $work_dir --log-file $log_file --skip-in-flight --tcp-established --leave-running -vvv

and I get unrecognized option --skip-in-flight

**Comment by xemul** [comment]
This option has appeared in 2.4. Which version do you use?

**Comment by koliaskostas** [comment]
OK sorry I bad apparently I cloned from a wrong link.
Dumping seems to be doing fine even under huge server stress.
I haven't finished all the use-cases/experiments but I'll let you know when I do.

However, I get an error when trying to restore. Maybe it's the wrong arguments I am using. Will experiment a little more and open a different thread if the problem persists.

**Comment by xemul** [comment]
https://lists.openvz.org/pipermail/criu/2016-November/033546.html

This is more-or-less final set. After fixing some nitpicks we'll merge it :)

Also need this kernel patch http://git.kernel.org/?p=linux/kernel/git/davem/net-next.git;a=commit;h=319b0534b9

@avagin , AFAIU the patch is in net-next. Has it hit Linus' tree? Would you update the wiki page with this info? :)

**Comment by avagin** [comment]
I think it will be pushed into Linus' tree in the next merge window (4.10).

**Comment by xemul** [comment]
OK, the patches are in 2.10. Released :) Have fun!
