### ISSUE TITLE
PTY device file owner lost on restore

### ISSUE THREAD

**Issue by tswift242** [xemul/criu#198]
My application runs as an unprivileged user inside a Docker container and creates a PTY device. The PTY device file's owner is not retained on restore, however. On restore, the owner is set to root, which prevents my application from accessing the PTY. Here's the before:

root@2449f6f5f633:/# ls -l /dev/pts
total 0
crw--w---- 1 unprivileged_user tty  136, 0 Aug  3 14:54 0
crw-rw-rw- 1 root   root   5, 2 Aug  3 14:53 ptmx

Here's the after:

root@2449f6f5f633:/# ls -l /dev/pts
total 0
crw--w---- 1 root tty  136, 0 Aug  3 15:11 0
crw-rw-rw- 1 root root   5, 2 Aug  3 15:11 ptmx

I'm building CRIU from the master branch (Version: 2.4, GitID: v2.4-242-gbf101e8), which is supposed to have a fix for "Mode was lost for PTY device file on restore" based on the CRIU 2.4 release notes, which I'm guessing corresponds to commit 8ba6372. However, I still see this issue. I'm attaching the dump and restore logs (slightly altered).

One thing I see in the logs is:

type devpts source devpts mnt_id 102 s_dev 0x2d / @ ./dev/pts flags 0x20000a options gid=5,mode=620,ptmxmode=666

which seems to indicate uid isn't kept track of for this?

[dump.txt](https://github.com/xemul/criu/files/399856/dump.txt)
[restore.txt](https://github.com/xemul/criu/files/399857/restore.txt)

**Comment by cyrillos** [comment]
I'll take a look, once time permit

**Comment by cyrillos** [comment]
Could you please try
---
[cyrill@uranus criu] git diff
diff --git a/criu/tty.c b/criu/tty.c
index ec09f30d9d8d..64575194c567 100644
--- a/criu/tty.c
+++ b/criu/tty.c
@@ -1035,6 +1035,9 @@ static int pty_open_ptmx(struct tty_info *info)
 
        pty_restore_queued_data(info->link, master);
 
+       if (rst_file_params(master, info->tfe->fown, info->tfe->flags))
+               goto err;
+
        if (info->tie->locked)
                lock_pty(master);

**Comment by cyrillos** [comment]
Nope, drop it

**Comment by cyrillos** [comment]
OK, the key problem is that credentials are restored a way more later then we open tty peers. And the kernel takes current_fsuid() from CRIU itself which is running under root permission. I don't see an easy way to fix the for a while. Gimme sometime, maybe I find a way...

**Comment by cyrillos** [comment]
@tswift242 Could you please try the [patch](https://gist.github.com/cyrillos/4f42d023cd53d056175dddb249fbff7e) and check the results? The patch is on top of current **criu-dev** branch

**Comment by tswift242** [comment]
@cyrillos Yep, that fixed it. Thanks! Any chance this will make it into the next release?

**Comment by cyrillos** [comment]
I hope so ;) I'll send the fixes in "official" way.

**Comment by cyrillos** [comment]
https://lists.openvz.org/pipermail/criu/2016-August/030822.html

**Comment by tswift242** [comment]
Awesome. Thanks!!

**Comment by tswift242** [comment]
@cyrillos Any updates on this?

**Comment by cyrillos** [comment]
yes, currently reworking the series. Hopefully will send today.

**Comment by tswift242** [comment]
Great, thanks!

**Comment by cyrillos** [comment]
@tswift242 Mind to give it a shot please? https://lists.openvz.org/pipermail/criu/2016-August/031242.html

**Comment by tswift242** [comment]
@cyrillos Yep, that patch also fixes the issue. Thanks!

**Comment by cyrillos** [comment]
Thanks for testing!
