### ISSUE TITLE
Failed to checkpoint docker container when created without seccomp:unconfined

### ISSUE THREAD

**Issue by Fuzzyma** [xemul/criu#199]
See #112 where this issue started.
**Summary:**
I run `Ubuntu 14.04` with kernel `4.2.0-42-generic` which I have installed with the `linux-generic-lts-wily package`. I have `criu 2.4` self compiled and run (also self compiled) `docker 1.12.0-dev, build 8f993ef, experimental` from bouchers branch here: https://github.com/boucher/docker/tree/docker-checkpoint-restore

tych0 mentioned that the wily package has the seccomp patches and thats why `criu check` prints `All good`. However my container cant be checkpointed without failing:

```
Error response from daemon: Cannot checkpoint container bb: rpc error: code = 2 desc = exit status 1: "criu failed: type NOTIFY errno 0\nlog file: /var/lib/docker/containers/b9962aba6a257b4bc97fb5b66ef8f42aba280d032af6a342694e067c0d56fb53/checkpoints/myCheck/criu.work/dump.log\n"
```

I created a gist with the dump.log [here](https://gist.github.com/Fuzzyma/e3a09d7a101aed7f36ec0b2a8c9908e5)

However applying `--security-opt seccomp:unconfined` to `docker create` fixes this issue

PS: Exact ubuntu version:
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Comment by tych0** [comment]
Can you try the `linux-generic-lts-xenial` kernel and see if this also reproduces with that kernel?

**Comment by Fuzzyma** [comment]
I installed `linux-generic-lts-xenial` and now have `4.4.0-31-generic` as kernel.

**No error** when creating a checkpoint. Looks like this kernel is working

**Comment by tych0** [comment]
Ok; host shouldn't matter, I suspect something got screwed up in the backport. As wily (and its kernel) are technically EOL, I think I'll punt on this one for now. We can close this, though, as it's not a CRIU bug.

**Comment by Fuzzyma** [comment]
thats ok from my side

**Comment by xemul** [comment]
Thanks everybody :)
