### ISSUE TITLE
Support C/R of frozen cgroup

### ISSUE THREAD

**Issue by klesgidis** [xemul/criu#20]
If I pause a container
```
docker pause <container_name>
```
and then try to checkpoint it
```
docker checkpoint <container_name>
```
checkpoint stalls...
From another terminal I am trying to unpause
```
docker unpause <container_name>
```
and it also stalls.

**Comment by xemul** [comment]
Seem to be Docker issue. @SaiedKazemi , @boucher would you please help here?

**Comment by SaiedKazemi** [comment]
Which Docker version are you using?  Also, what is the container you're running?  Can you send us the exact commands on how you started your server and the containers?

**Comment by klesgidis** [comment]
Docker 
```
Client:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   c74defa-dirty
 Built:        Wed Aug  5 23:15:11 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.8.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   c74defa-dirty
 Built:        Wed Aug  5 23:15:11 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```
I tested in a MySQL and a Postgre SQL (both official) containers. I run:
```
docker run -d --name <container_name> mysql:5.7
```
and then the commands that I specified on the first post. 

I didn't do anything to start the docker server. 
<code>sudo service docker start</code> (I'm not sure if you asking something else about it)

Thanks for the response..

**Comment by boucher** [comment]
Have you gotten checkpoint/restore to work at all on your system?

Out of curiosity, can I ask what the use case is for pausing the container before checkpointing it?

Also, could you try updating your build of Docker? There have been changes in my checkpoint/restore branch since the git hash shown in this version.

**Comment by klesgidis** [comment]
Yes C/R is working on my system. 

There isn't any use case. I was just messing around and noticed this attitude.. I decide to say it here if you haven't noticed it yet.

I am updating my current build of docker right now and I 'll let you know..

Thanks

**Comment by boucher** [comment]
Ok, thanks for letting us know. I don't actually know much about how docker
pause works, so it will require some looking into.

On Fri, Aug 14, 2015 at 9:20 AM, Kyriakos Lesgidis <notifications@github.com

**Comment by SaiedKazemi** [comment]
@xemul @klesgidis 
I just tested pausing (freezing) a shell process and then checkpointing it (i.e., no Docker) and CRIU hung.  Here is what I did:

[Terminal A]
/bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 3; done'

[Terminal B]
mkdir /sys/fs/cgroup/freezer/0
ps -efl | grep -w sh
echo 7042 > /sys/fs/cgroup/freezer/0/tasks
echo FROZEN > /sys/fs/cgroup/freezer/0/freezer.state
criu dump -v4 -D /tmp -o dump.log -j -t 7042

[Terminal C]
ps -efl | grep criu
strace -p 6449
Process 6449 attached
wait4(6355, 

Unless I am missing something, it seems to be a CRIU issue.  Any idea?

**Comment by avagin** [comment]
CRIU can't attach by ptrace() to frozen processes.
Recently, I added the freeze-cgroup option, it should be used for paused containers.

**Comment by xemul** [comment]
@avagin CRIU can attach with ptrace, this is what we do in your patches :) CRIU cannot run parasite in them, but this can be addressed by extending the freeze-seize-unfreeze-run logic you've introduced.

**Comment by xemul** [comment]
8b04551c48b5e35d0f7ade05a7873c148cb784cd
