### ISSUE TITLE
Error (criu/files-reg.c:1189): Can't link dev/null.cr.1.ghost -> dev/null: File exists

### ISSUE THREAD

**Issue by demisgomes** [xemul/criu#201]
I use CRIU since 1.6 version. But, when I installed CRIU 2.4 version with LXC in a 3.13.0-24 gerneric kernel, Ubuntu 14,04, I have the following error:

 Error (criu/files-reg.c:1189): Can't link dev/null.cr.1.ghost -> dev/null: File exists

All restore.log:
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bootps
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
Warn  (criu/cr-restore.c:849): Set CLONE_PARENT | CLONE_NEWPID but it might cause restore problem,because not all kernels support such clone flags combinations!
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
RTNETLINK answers: File exists
     1: Warn  (criu/sk-unix.c:1333): sk unix: Can't unlink stale socket 0x3762 peer 0 (name /run/udev/control dir -)
     1: Warn  (criu/sk-unix.c:1333): sk unix: Can't unlink stale socket 0x3dda peer 0 (name /dev/log dir -)
     1: Error (criu/files-reg.c:1189): Can't link dev/null.cr.1.ghost -> dev/null: File exists

And CRIU fails in remove files in /sys/fs directory:

lxc-checkpoint: criu-testcgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/cpuset//lxc/criu-test
lxc-checkpoint: criu-testcgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/cpu//lxc/criu-test
lxc-checkpoint: criu-testcgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/cpuacct//lxc/criu-test
lxc-checkpoint: criu-testcgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/memory//lxc/criu-test
lxc-checkpoint: criu-testcgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/devices//lxc/criu-test
lxc-checkpoint: criu-testcgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/freezer//lxc/criu-test
lxc-checkpoint: criu-testcgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/blkio//lxc/criu-test
lxc-checkpoint: criu-testcgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/perf_event//lxc/criu-test
lxc-checkpoint: criu-testcgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/hugetlb//lxc/criu-test
lxc-checkpoint: criu-testcgfsng.c: recursive_destroy: 983 Error destroying /sys/fs/cgroup/systemd//lxc/criu-test

dump.log do not has errors.

What can be happened? Many issues that I had was answered here. I hope this is also.

Thanks!

**Comment by xemul** [comment]
Do you restore a container from image? Can you remove $ct_root/dev/null.cr.1.ghost file and try to restore again?

**Comment by demisgomes** [comment]
Thanks for response.
I am restoring container from the files generated by command:
lxc-checkpoint -s -n criu-test -D /tmp/checkpoint

Restore is made with:
lxc-checkpoint -s -n criu-test -D /tmp/checkpoint

I do not find /dev/null.cr.1.ghost file in any place.

**Comment by xemul** [comment]
OK. Can you then collect restore logs with -v4 option? I'm not sure how to do it via lxc-checkpoint though.  @tych0 , would you help us?

**Comment by tych0** [comment]
Yes, just add the `-v` flag to restore, and it will give you a `restore.log` in the checkpoint directory that is criu's -v4 output.

**Comment by demisgomes** [comment]
Here is the restore.log generated with -v flag:

http://notepad.cc/restore_criu_log

**Comment by xemul** [comment]
@demisgomes the notepad.cc name doesn't resolve :(

**Comment by demisgomes** [comment]
Try access in this link: https://www.dropbox.com/s/13lurx5vs0prrjo/restore.log?dl=0
The file is very large and I cannot make a upload in pastebin.

**Comment by xemul** [comment]
OK, this one opens fine :) Yes, there are errors in logs, but AFAIS they are harmless (anyway thanks for them, we'll relax it to warnings). Does restore fail? I see it works from the logs.

**Comment by xemul** [comment]
@demisgomes , any news on this?

**Comment by demisgomes** [comment]
Sorry for the delay. I updated the kernel, reinstalled LXC and CRIU, I made a clone of older CRIU version but restore still failing. Perhaps may be a problem in LXC mount rather CRIU. I run the same steps on another machine and works. I do not know what happened, but I can seek other possibilities to explain it. 

Thanks for the help!

**Comment by xemul** [comment]
OK, so as I said above -- the restore.log you provided only contain error message, but doesn't seem to end u with error. If you'd be able to provide failing log that'd be helpful.

**Comment by demisgomes** [comment]
What file corresponds to failing log?  In dump directory I only see the dump.log and restore.log .

**Comment by xemul** [comment]
Failing log is the log of operation that failed (exited with non-zero code). If it's restore, then it should be restore.log.

**Comment by xemul** [comment]
@demisgomes , do you have any news about it?

**Comment by demisgomes** [comment]
No @xemul . The restore.log and dump.log have the same information provided before. I installed the LXC and CRIU in another computer and worked, and I am using it. 

Thanks for the help! You can close this issue.
