### ISSUE TITLE
Can't dump ghost file

### ISSUE THREAD

**Issue by MarkGavalda** [xemul/criu#202]
Latest Ubuntu 16.04 with 4.4.0-34-generic and linux-image-extra. Trying 'lxc move' live migration with latest CRIU compiled from git clone:

Version: 2.4
GitID: v2.4-81-gc44683c

```
error: Error transferring container data: migration dump failed
(02.580327) Error (files-reg.c:702): Can't dump ghost file /tmp/tcFhOS3I of 16777216 size, increase limit
(02.580330) Error (cr-dump.c:1203): Collect mappings (pid: 10609) failed with -1
(02.586107) Error (cr-dump.c:1614): Dumping FAILED.
```

**Comment by tych0** [comment]
On Tue, Aug 09, 2016 at 02:47:31PM -0700, Mark Gavalda wrote:
> Latest Ubuntu 16.04 with 4.4.0-34-generic and linux-image-extra. Trying 'lxc move' live migration with latest CRIU compiled from git clone:
> 
> Version: 2.4
> GitID: v2.4-81-gc44683c
> 
> ```
> error: Error transferring container data: migration dump failed
> (02.580327) Error (files-reg.c:702): Can't dump ghost file /tmp/tcFhOS3I of 16777216 size, increase limit
> (02.580330) Error (cr-dump.c:1203): Collect mappings (pid: 10609) failed with -1
> (02.586107) Error (cr-dump.c:1614): Dumping FAILED.
> ```

We've bumped this limit in the git master version of LXD, but haven't
managed to backport it to xenial yet. If you want to build from
source, you should be able to work around this. It's not a criu bug,
though.
