### ISSUE TITLE
(00.015801) Error (criu/page-xfer.c:246): Hole 0x7ffd07635000/16384 not found in parent

### ISSUE THREAD

**Issue by avagin** [xemul/criu#203]
```
================== Run zdtm/static/socket-tcpbuf-local in uns ==================
Start test
./socket-tcpbuf-local --pidfile=socket-tcpbuf-local.pid --outfile=socket-tcpbuf-local.out
Run criu dump
Run criu dump
Run criu dump
Run criu dump
=[log]=> dump/zdtm/static/socket-tcpbuf-local/185/4/dump.log
------------------------ grep Error ------------------------
(00.015799) Error (criu/pagemap.c:185): Missing 7ffd07635000 in parent pagemap, current iov: base=7ffd07636000,len=8192
(00.015801) Error (criu/page-xfer.c:246): Hole 0x7ffd07635000/16384 not found in parent
(00.015821) Error (criu/mem.c:427): Can't dump page with parasite
(00.019794) Error (criu/cr-dump.c:1680): Dumping FAILED.
------------------------ ERROR OVER ------------------------
############ Test zdtm/static/socket-tcpbuf-local FAIL at CRIU dump ############
```

**Comment by avagin** [comment]
Cc: @adrianreber

**Comment by avagin** [comment]
It was broken in 101e3ba49d0801511a50241a3e2f6ce17f7641a4
```
            criu-14374 [001] .... 87163.223559: tracing_mark_write: __parasite_dump_pages_seized
            criu-14374 [001] .... 87163.224637: tracing_mark_write: step 4 -- clean up
 socket-tcpbuf6--14132 [000] d... 87163.224801: __do_page_fault <-do_page_fault
 socket-tcpbuf6--14132 [000] d... 87163.226051: __do_page_fault <-do_page_fault
            criu-14374 [001] .... 87163.226755: tracing_mark_write: task_reset_dirty_track
```
https://gist.github.com/avagin/f75568a14f9da66c48161a7051aa122d

**Comment by avagin** [comment]
To: @fbocharov

**Comment by avagin** [comment]
CRIU dumped pages, but a few pages have been changed before calling task_reset_dirty_track

**Comment by avagin** [comment]
I reproduced this bug with perf trace -F all. It shows a moment where a page fault was triggered.
```
  6975.479 ( 0.004 ms): gettid(arg0: 4, arg1: 139697201459712, arg2: 24, arg3: 139697201483784, arg4: 139697196322670, arg5: 0) = 24
  6975.489 ( 0.005 ms): write(fd: 8, buf: 0x7f0dca125788, count: 53                           ) = 53
  6975.497 ( 0.004 ms): close(fd: 7<socket:[1173800]>                                         ) = 0
  6975.514 ( 0.007 ms): close(fd: 8                                                           ) = 0
18446718803895.934 ( 0.000 ms): minfault [0x8] => 0x7ffddb143058 (?.)
18446718803895.934 ( 0.000 ms): minfault [0x219d] => 0x7ffddb142f78 (?.)
  6975.826 ( 0.212 ms): rt_sigreturn(arg0: 139697201483784, arg1: 139697201502088, arg2: 53, arg3: 139697201452189, arg4: 139697201501835, arg5: 0) ...
  6975.834 ( 0.008 ms): gettid(arg0: 3, arg1: 139697201459958, arg2: 4, arg3: 4, arg4: 4, arg5: 0) = 24
  6975.945 ( 0.009 ms): write(fd: -1, buf: 0x7ffddb142f08, count: 36                          ) = -1 EBADF Bad file descriptor
  6976.041 ( 0.020 ms): munmap(addr: 0x7f0dca118000, len: 57344                               ) = 0
18446718803895.934 ( 0.000 ms): minfault [copy_page_to_iter+0x8f] => 0x7ffddb14407f (?k)
  9211.115 (2220.576 ms): read(fd: 4<socket:[1164403]>, buf: 0x7ffddb143080, count: 4096        ) = 4096
  9211.222 ( 0.080 ms): read(fd: 4<socket:[1164403]>, buf: 0x7ffddb143080, count: 4096        ) = 4096
  9211.384 ( 0.095 ms): read(fd: 4<socket:[1164403]>, buf: 0x7ffddb143080, count: 4096        ) = 4096
  9211.437 ( 0.023 ms): read(fd: 4<socket:[1164403]>, buf: 0x7ffddb143080, count: 4096        ) = 4096
  9211.493 ( 0.022 ms): read(fd: 4<socket:[1164403]>, buf: 0x7ffddb143080, count: 4096        ) = 4096
  9211.577 ( 0.023 ms): read(fd: 4<socket:[1164403]>, buf: 0x7ffddb143080, count: 4096        ) = 4096
  9211.612 ( 0.020 ms): read(fd: 4<socket:[1164403]>, buf: 0x7ffddb143080, count: 4096        ) = 4096
```

```
=[log]=> dump/zdtm/static/socket-tcpbuf-local/24/57/dump.log
------------------------ grep Error ------------------------
(00.026988) Error (criu/pagemap.c:185): Missing 7ffddb142000 in parent pagemap, current iov: base=7ffddb143000,len=8192
(00.026990) Error (criu/page-xfer.c:246): Hole 0x7ffddb142000/16384 not found in parent
(00.027104) Error (criu/mem.c:437): Can't dump page with parasite
(00.042402) Error (criu/cr-dump.c:1680): Dumping FAILED.
------------------------ ERROR OVER ------------------------
############ Test zdtm/static/socket-tcpbuf-local FAIL at CRIU dump ############
Wait for zdtm/static/socket-tcpbuf-local to die for 0.100000
##################################### FAIL #####################################
```

**Comment by avagin** [comment]
Cc:  @rppt

**Comment by avagin** [comment]
From: @rppt 
> I think I've got him.
> Apparently, there is a race between parasite pushing something to
> not-yet-mapping page on dumpee stack and task_reset_dirty_track.
> The scenario seems to be something like this:
> * Iteration N:
>   - dump memory, the page at STACK_END - 4 * PAGE_SIZE is not present,
> so it's silently skipped by generate_iovs
>   - parasite executes some code that causes kernel to map the page at
> STACK_END - 4 * PAGE_SIZE
>   - kernel maps the page at STACK_END - 4 * PAGE_SIZE, marks if dirty
> | soft_dirty
>   - dump_one_task calls task_reset_dirty_track
>   - the kernel resets soft_dirty for the page at STACK_END - 4 * PAGE_SIZE
> * Iteration N + 1
>   - generate_iov sees a page at STACK_END - 4 * PAGE_SIZE that has
> PME_PRESENT set, but PME_SOFT_DIRTY cleared
>   - the page is considered to be in the parent snapshot
>   - crush

**Comment by rppt** [comment]
I wonder if there is anything that prevents moving `cr_dump_shmem` before going over `dump_one_task`?
Then we can reset soft dirty immediately after dumping private memory and still we'll be able to track shared memory changes

**Comment by avagin** [comment]
[PATCH] parasite: don't use a process stack to unmap a parasite blob

**Comment by avagin** [comment]
We need to reopen this issue:
https://travis-ci.org/criupatchwork/criu/jobs/153714892

**Comment by rppt** [comment]
what about reverting 101e3ba49d0801511a50241a3e2f6ce17f7641a4 (mem: reset SOFT_DIRTY bits after dumping of all vmas in the process) and adding something like this:

<pre>
diff --git a/criu/cr-dump.c b/criu/cr-dump.c
index ea1e356..e6fa441 100644
--- a/criu/cr-dump.c
+++ b/criu/cr-dump.c
@@ -1775,6 +1775,10 @@ int cr_dump_tasks(pid_t pid)
 	if (collect_seccomp_filters() < 0)
 		goto err;

+	ret = cr_dump_shmem();
+	if (ret)
+		goto err;
+
 	for_each_pstree_item(item) {
 		if (dump_one_task(item))
 			goto err;
@@ -1813,10 +1817,6 @@ int cr_dump_tasks(pid_t pid)
 	if (ret)
 		goto err;
 
-	ret = cr_dump_shmem();
-	if (ret)
-		goto err;
-
 	ret = fix_external_unix_sockets();
 	if (ret)
 		goto err;
</pre>

**Comment by xemul** [comment]
Cc @eabatalov

**Comment by rppt** [comment]
Relatively easy way to reproduce is to run the loops below from different consoles (thanks to  @avagin):
<pre>
while :; do python test/zdtm.py run -t zdtm/static/socket-tcpbuf6-local
--snap --pre 30 -f uns   || break; done

while :; do python test/zdtm.py run -t zdtm/static/socket-tcpbuf-local
--snap --pre 30 -f uns   || break; done
</pre>

**Comment by eabatalov** [comment]
@rppt your fix wouldn't work as is. If we move cr_dump_shmem() call to the place before dump_one_task() we won't dump anything because in dump_one_task() we collect information about shmem vmas of each ps tree process (calling add_shmem_area()). Ashmem is global resource so we need info from all the processes. After we've collected all the infos we can do shmem dumping.

Also it looks like we can simply revert 101e3ba49d0801511a50241a3e2f6ce17f7641a4 to fix this bugs and allow parasite to do some editing of dumpee addresses. Yes, this is rudicolous. The description of this patch is so good and it looks like we still need it but It looks like this patch was needed for one of the first versions of the whole patchset but now when page states are stored in own criu bitmaps this dependence on pagemap bits resetting moment has disappeared.

I'll investigate the posibility to revert this patch further, test it and send the results here in the thread.

**Comment by eabatalov** [comment]
Yes we can revert this 101e3ba49d0801511a50241a3e2f6ce17f7641a4 commit. It isn't really needed. It was introduced in v0 of the patchset and wasn't needed in v1 already (I blame myself).
I've sent patch to criu ML with detailed explanation. Simple git revert hasn't worked for me (merge conflict is introduced).
Also this bug isn't reproduced on my machine at all (even with recent scripts from rppt). So we need a long testing to be sure that everything is ok after the revert.
