### ISSUE TITLE
How CRIU restore whole LXC container? Why restore time is not too impacted by size of memory states?

### ISSUE THREAD

**Issue by demisgomes** [xemul/criu#214]
I am writing an article which analyzes the restore time of CRIU in LXC. I observed that, despite the increase of img files size, the restore time (the time referring to run lxc-checkpoint -r ) is the same, about 0.3 sec. The state size (all img and log files) vary between 37 MB and 228 MB. 

This time can be explained through the mode which CRIU restore the container. However, despite know that CRIU saves and restore memory context, I would know more details about the checkpoint and restore process. I believe that my hypothesis that I wrote in the article is not conclusively. So, if possible, I would like to know how CRIU restore the whole container, to explain adequately to my advisor and write correctly in the article. 

Thank for help!

**Comment by tych0** [comment]
On Thu, Sep 08, 2016 at 03:01:37PM -0700, Demis Gomes wrote:
> I am writing an article which analyzes the restore time of CRIU in LXC. I observed that, despite the increase of img files size, the restore time (the time referring to run lxc-checkpoint -r ) is the same, about 0.3 sec. The state size (all img and log files) vary between 37 MB and 228 MB. 

200 MB isn't very much for modern computers, especially if you're
saving the state to a tmpfs or something. What if you increase the
size to something like 1GB or more? You might see more variance.

> This time can be explained through the mode which CRIU restore the container. However, despite know that CRIU saves and restore memory context, I would know more details about the checkpoint and restore process. I believe that my hypothesis that I wrote in the article is not conclusively. So, if possible, I would like to know how CRIU restore the whole container, to explain adequately to my advisor and write correctly in the article. 

It might be helpful to ask specific questions; CRIU does a lot of
complicated things to restore containers :)

**Comment by demisgomes** [comment]
Thanks for the response, Tycho. I am comparing the restore made by CRIU and by an application when it receives the state via JSON. In application, a state size of 25 MB increases significantly the restore time, but in CRIU, an increase of 200 MB practically is not influenced. 

You could give a short answer of how CRIU resume the processes saved in memory states? This answer would very helpful!

**Comment by xemul** [comment]
@demisgomes , we have a lot of articles describing how criu works here: https://criu.org/Category:Under_the_hood

For your case (memory restore) it seems good to start with this one:
https://criu.org/Memory_dumping_and_restoring

and then proceed with the 'See also' section :)

If any question about the article itself arises -- feel free to ask more questions.

**Comment by kolyshkin** [comment]
I suggest to close this one, and also remind people to not use the issue tracker for general questions -- we do have a mailing list for that.

**Comment by xemul** [comment]
Good idea :)
