### ISSUE TITLE
Update doc for new --leave-stopped option on restore

### ISSUE THREAD

**Issue by tswift242** [xemul/criu#215]
The CRIU v2.6 release notes mention a new --leave-stopped option for restore. When I look at the criu.txt documentation, it only mentions a --leave-stopped option for checkpoint.

**Comment by xemul** [comment]
Cc @kolyshkin :)

**Comment by xemul** [comment]
Heh, but the https://criu.org/CLI/opt/--leave-stopped says about restore :)
@kolyshkin , would you update the man page with this, please :)

**Comment by kolyshkin** [comment]
Good catch @tswift242! Patch sent to the mailing list: https://lists.openvz.org/pipermail/criu/2016-October/032227.html

**Comment by kolyshkin** [comment]
Oops, my bad. https://lists.openvz.org/pipermail/criu/2016-October/032228.html
