### ISSUE TITLE
Link-remap files are not dumped with Docker C/R

### ISSUE THREAD

**Issue by keyolk** [xemul/criu#219]
Hello
I'm trying to use docker-1.10-dev from here(https://github.com/boucher/docker/releases)
But failed with below error

```
...
(00.017076) ========================================
(00.017078) Dumping task (pid: 15485)
(00.017079) ========================================
(00.017080) Obtaining task stat ...
(00.017101)
(00.017103) Collecting mappings (pid: 15485)
(00.017104) ----------------------------------------
(00.017194) Dumping path for -3 fd via self 10 [/var/lib/docker/0.0/aufs/diff/e0dda1e1edc005dcbebc076dcf232b952fbc15853491bb33792780777e2736ba/bin/sh]
(00.017232) Error (criu/files-reg.c:725): Can't create link remap for /var/lib/docker/0.0/aufs/diff/e0dda1e1edc005dcbebc076dcf232b952fbc15853491bb33792780777e2736ba/bin/sh. Use link-remap option.
(00.017246) Error (criu/cr-dump.c:1209): Collect mappings (pid: 15485) failed with -1
(00.017271) Unlock network
(00.017274) Running network-unlock scripts
(00.017275)     RPC
(00.023066) Unfreezing tasks into 1
(00.023097)     Unseizing 15485 into 1
(00.023109)     Unseizing 15509 into 1
(00.023130) Error (criu/cr-dump.c:1627): Dumping FAILED.
```

what I did 

```
docker run -d --name=np busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
docker checkpoint np
```

```
 docker version
Client:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   cec56b2
 Built:        Fri Feb 12 23:11:36 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.10.0-dev
 API version:  1.22
 Go version:   go1.5.2
 Git commit:   cec56b2
 Built:        Fri Feb 12 23:11:36 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

How could I solve the issue ?

**Comment by xemul** [comment]
Cc @boucher. The thing is about absence of --link-remap option to CRIU which needs care :)
https://criu.org/Invisible_files

**Comment by boucher** [comment]
How does link-remap work: do you specify specific map pairs (like the external flag)?

**Comment by xemul** [comment]
No, you just give the --link-remap option to CRIU and after dump you'll have a file left by CRIU in container root which should be kept there till restore.

**Comment by boucher** [comment]
Is there any reason not to always pass that flag?

**Comment by xemul** [comment]
Yes, there are many cases. E.g. if you want to do a snapshot to get back to later, the --link-remap will be a bad choice. By passing --link-remap to CRIU you tell it "I let you leave part of the state outside of the images/ directory and will take care of it myself". It's like --tcp-established and --file-locks -- if you leave unattended what was left around you after dump the restore will get broken.

**Comment by xemul** [comment]
Actually, dumping a link-remap heavily depends on the root FS commit (issue #289) -- unless we do the commit we cannot use the --link-remap, otherwise the link remap files will (might) get lost.
