### ISSUE TITLE
Docker - After restoring tomcat container, cannot connect to it

### ISSUE THREAD

**Issue by klesgidis** [xemul/criu#22]
Guys sorry for the continuous issues and thanks for all the support..
Docker 
```
Client:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   59c375a-dirty
 Built:        Fri Aug 14 17:11:58 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   59c375a-dirty
 Built:        Fri Aug 14 17:11:58 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
```
CRIU
```
Version: 1.6
GitID: v1.6-163-g231b61d
```
I run the following sequence 
```
$> docker run -d --name tomcat1 tomcat:8.0
$> docker checkpoint --image-dir ~/Desktop/cr_migrations/tomcat/memory --work-dir ~/Desktop/logs/tomcat tomcat1
$> docker export tomcat1 > ~/Desktop/cr_migrations/tomcat/fs.tar
$> docker import --change "ENV PATH /usr/local/tomcat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" --change "ENV LANG C.UTF-8" --change "ENV JAVA_VERSION 7u79" --change "ENV JAVA_DEBIAN_VERSION 7u79-2.5.5-1~deb8u1" --change "ENV CATALINA_HOME /usr/local/tomcat" --change "ENV TOMCAT_MAJOR 8" --change "ENV TOMCAT_VERSION 8.0.24" --change "ENV TOMCAT_TGZ_URL https://www.apache.org/dist/tomcat/tomcat-8/v8.0.24/bin/apache-tomcat-8.0.24.tar.gz" --change "CMD [\"catalina.sh\", \"run\"]" --change "EXPOSE 8080" --change "WORKDIR /usr/local/tomcat" - tomcat:kyriakos < ~/Desktop/cr_migrations/tomcat/fs.tar
$> docker create --name tomcat2 tomcat:kyriakos
$> docker restore --force=true --allow-tcp=true --allow-ext-unix=true --image-dir ~/Desktop/cr_migrations/tomcat/memory --work-dir ~/Desktop/logs/tomcat tomcat2
```
and I have 
```
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
86bba1f8977d        tomcat:kyria        "catalina.sh run"   About a minute ago   Up About a minute   8080/tcp            tomcat2
```
with 
```
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "172.17.0.10",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
```

When I type <code>172.17.0.10:8080</code> in my browser, I cannot connect to the restored container. 

Thanks

Edit: I also tried to C/R with the default actions
```
$> docker checkpoint tomcat1
$> docker restore tomcat1
```
and I had the same results.
In addition, if it helps, when I do <code>docker top tomcat2</code> I receive
```
Error response from daemon: [8] System error: open /sys/fs/cgroup/devices/docker/dfae7ff5796cc879232038d6f6ef75114e710aa9e9fc0f6438fa8d4267c32313/cgroup.procs: no such file or directory
```

**Comment by xemul** [comment]
Has the IP address of the container changed?

**Comment by klesgidis** [comment]
Yes the restore container has a new IP

**Comment by xemul** [comment]
Then connect can fail since all the internals have the ip changed -- routing, addresses, sockets binding (if any).

**Comment by klesgidis** [comment]
As I know, you can not assign an IP to a docker container. So how it could be ever possible to C/R a container that it could be referenced with its IP from the outside?

**Comment by xemul** [comment]
Well, I don't have good experience with docker network management. Maybe @avagin or @boucher can help?

**Comment by boucher** [comment]
Networking is a known issue right now. I believe you'll find that the IP isn't the issue, but, assuming it's the only issue for a moment, here is the workaround I'm using for this problem:

> docker exec --privileged <container id> bash
>> ip addr add <new docker provided ip> dev eth0

Theoretically, you should also drop the old ip. There are two problems with this though: the first is the exec --privileged support hasn't yet been merged into my branch (I'll try and get that done soon), and the second is that obviously this is a shitty way to do things. 

Network support is the last thing needed to finish up the initial checkpoint/restore support. It's being worked on, and discussed a bit in the PR (https://github.com/docker/docker/pull/13602). Once it's done this problem should go away entirely.

**Comment by klesgidis** [comment]
@xemul thanks for the help.. Sorry, but I didn't catch you.. How and when do you use <code>docker exec --privileged bash</code> and <code>ip addr add dev eth0</code>?

**Comment by xemul** [comment]
I  believe the last question is to @boucher :)

**Comment by klesgidis** [comment]
Ouppss! Yes you're right! Sorry :P Although, also thank you for your help!

**Comment by boucher** [comment]
You use docker exec post restore, in order to change the IP address inside the container back to the one docker expects. (I have just pushed support for exec --privileged to my branch if you rebuild).

**Comment by klesgidis** [comment]
@boucher I managed to <code>exec</code> with the <code>--privileged</code> option, but (unfortunatelly) as you predicted the results are the same. 
So, as I understand there isn't any solution yet about this issue.. Thanks for your help..
P.S. Is there any estimation about when the "Network Support" will be available?

**Comment by klesgidis** [comment]
Another question... (I know I am pain in the ass :P ) In this video https://www.youtube.com/watch?v=HFt9v6yqsXo how Saied Kazemi managed to restore and continue the streaming? I mean he didn't have this network issues? Thanks for your patience..

**Comment by boucher** [comment]
He's using an older version of docker (which is available still here:
https://github.com/SaiedKazemi/docker/releases/tag/v1.5.0)

**Comment by xemul** [comment]
Guys, do we still consider this as an opened issue?

**Comment by klesgidis** [comment]
I think that this is solved by this https://github.com/boucher/docker/pull/15..

**Comment by xemul** [comment]
Cool! Thanks, guys!
