### ISSUE TITLE
 Error (criu/cgroup.c:620): cg: failed walking /proc/self/fd/10/newroot for empty cgroups: No such file or directory

### ISSUE THREAD

**Issue by avagin** [xemul/criu#220]
'''
======================== Run zdtm/static/cgroup02 in h =========================
Start test
Test is SUID
./cgroup02 --pidfile=cgroup02.pid --outfile=cgroup02.out --dirname=cgroup02.test
Run criu dump
=[log]=> dump/zdtm/static/cgroup02/30/1/dump.log
------------------------ grep Error ------------------------
(00.020212) Error (criu/cgroup.c:620): cg: failed walking /proc/self/fd/10/newroot for empty cgroups: No such file or directory
(00.020233) Error (criu/cr-dump.c:1359): Dump core (pid: 30) failed with -1
(00.025465) Error (criu/cr-dump.c:1675): Dumping FAILED.
------------------------ ERROR OVER ------------------------
################# Test zdtm/static/cgroup02 FAIL at CRIU dump ##################
Send the 9 signal to  30
Wait for zdtm/static/cgroup02(30) to die for 0.100000
'''
https://ci.openvz.org/job/CRIU/job/CRIU-x86_64/branch/criu-dev/1007/console

**Comment by Snorch** [comment]
[PATCH] zdtm/cgroup02: fix test using ropts instead of opts
