### ISSUE TITLE
Fail to restore apache on different vms

### ISSUE THREAD

**Issue by koliaskostas** [xemul/criu#222]
**Goal**: Migrate a apache process from one vm to another.
**Settings**: Two identical (cloned) vms running ubuntu 16.04 with 4.6.0 kernel (patched) and criu v2.6

**Methodology**: 
On VM_A I do:

`sudo ./criu dump --tree $pid --images-dir $images_dir --work-dir $work_dir --log-file $log_dir"/log.dat" `--leave-stopped -vvv

`scp -r images_dir/ costas@192.168.56.109:/home/costas/`

the checkpoint is successful. Note that for this simple test case I have noone connected or trying to access content on the server.

on VM_B I do:
`sudo ./criu restore --tree $pid --images-dir $images_dir --work-dir $work_dir --log-file $log_dir"/log.dat" -d -vvv`

I get this error:
[restore-fail.log.tar.gz](https://github.com/xemul/criu/files/499110/restore-fail.log.tar.gz)

Also, note that a slightly modified version of the commands above is able to checkpoint and restore successfully a dummy counter script. So, to my understanding I most probably miss some flag. Finally, more flags will be used next (--skip-in-flight etc.) but for this experiment I tried to keep things simple.

**Comment by avagin** [comment]
```
pie: 3176: Error (criu/pie/restorer.c:447): Thread pid mismatch 3176/3173
```

**Comment by avagin** [comment]
CRIU can't restore a required pid because it is already busy. You can resolve this by unsharing the pid namespace before restoring the tree.

You can try to use ./scripts/criu-ns.

**Comment by xemul** [comment]
https://criu.org/CR_in_namespace

**Comment by koliaskostas** [comment]
That is very interesting however, trying to restore with:
`./criu/scripts/criu-ns restore --tree $pid --images-dir $images_dir --work-dir $work_dir --log-file $log_file -d -vvv`
gives:
```
File "./criu/scripts/criu-ns", line 233, in <module>
   res = wrap_restore()
...
...
File "/usr/lib/python2.7/os.py", line 382, in _execvpe
   func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
```

**Comment by xemul** [comment]
What's in the ... ... lines? :) Presumably call to execvp which cannot find criu binary itself ;)

**Comment by xemul** [comment]
@koliaskostas , do you have any news here?

**Comment by koliaskostas** [comment]
@xemul you were basically right.
The problem was that I was using sudo to execute the command and the environmental variables were not set.
Classic novice mistake from my part.
No bug here just a warning to future readers. :)

**Comment by xemul** [comment]
Great :)
