### ISSUE TITLE
criu-dev: criu restore is segfaulted

### ISSUE THREAD

**Issue by avagin** [xemul/criu#228]
```
$ ./runc restore test_cpt --image-path /tmp/imgs/ --work-path /tmp/imfs
criu failed: type NOTIFY errno 0
log file: /tmp/imfs/restore.log

$ cat /tmp/imfs/restore.log | grep -A 3 -B 3 Error
(00.210003)      1: 	call mremap(0x7f8b830b2000, 8192, 8192, MAYMOVE | FIXED, 0x24000)
(00.210042)     16: 	call mremap(0x7f8b830a7000, 8192, 8192, MAYMOVE | FIXED, 0x22000)
(00.210059)     16: 	call mremap(0x7f8b830b2000, 8192, 8192, MAYMOVE | FIXED, 0x24000)
(00.210088) Error (criu/cr-restore.c:1027): 31027 killed by signal 11: Segmentation fault
(00.223415) Error (criu/cr-restore.c:1027): 31027 killed by signal 9: Killed
(00.229063) mnt: Switching to new ns to clean ghosts
(00.229206) uns: calling exit_usernsd (-1, 1)
(00.229268) uns: daemon calls 0x456960 (31013, -1, 1)
(00.229278) uns: `- daemon exits w/ 0
(00.230220) uns: daemon stopped
(00.230230) Error (criu/cr-restore.c:1893): Restoring FAILED.

```
 first bad commit: [6fde3b8c27db32a790254034e73b961683aed0d0] x86: restore TLS
To: @0x7f454c46

**Comment by avagin** [comment]
The kernel doesn't generate a core file...

**Comment by 0x7f454c46** [comment]
Thanks, will check today.

**Comment by 0x7f454c46** [comment]
Hi @avagin, could you check if the patch fixes this problem (if you have a reproducer)?
https://github.com/0x7f454c46/criu/commit/304a1682923b99be66a40c068645542b6c735363
I'll send it to maillist afterwards.

**Comment by 0x7f454c46** [comment]
There will stil stay a question, why the kernel didn't generate a core file - I think it helps much in some circumstances, maybe it's worth to find why.

**Comment by avagin** [comment]
It generates a core file, but its size is zero:)

**Comment by 0x7f454c46** [comment]
Ok, I thought about this some more -- it's ok about core file: restored program may have garbage at TLS, so kernel may not be able to produce valid coredump.
Could you confirm that bug solved with the patch, please? :)

**Comment by avagin** [comment]
I can't reproduce this issue event without this patch. Maybe we have to write a proper test for this functionality...

**Comment by 0x7f454c46** [comment]
Well, I think the bug was in missed check of the number of TLS entries in protobuf images file.
So, it's not in the functionality, rather in using images created before this patch.
The test should dump application before those patches (on master branch) and fail on restore after this one. I think, it's not the kind of tests we have now in zdtm (or am I missing something?).
I'll send this patch to maillist.
