### ISSUE TITLE
Failure restoring container 1.9 experimental cr-combined

### ISSUE THREAD

**Issue by stlalpha** [xemul/criu#23]
Running boucher's docker 1.9 experimental cr-combined fork.

$ docker -v
Docker version 1.9.0-dev, build 2791165-dirty, experimental
$

Success:

All on same host:

1. docker run -d stlalpha/experimental (returns containerid)
2. docker checkpoint [containerid]
3. docker restore [containerid]

Failure:

All on same host:

1. docker run -d stlalpha/experimental (returns containerid)
2. docker checkpoint --image-dir=/home/whatevs/test1 [containerid]
3. docker create stlalpha/experimental (returns dest-containerid)
4. docker start [dest-containerid]
5. docker stop [dest-containerid]
6. docker restore --image-dir=/home/whatevs/test1 --work-dir=/tmp --force [dest-containerid]

Results in the following errors in /tmp/restore.log:

https://gist.github.com/stlalpha/bdafa07af3bfc2d654be

The image I am working with is available on dockerhub (stlalpha/experimental).

Please let me know if I can provide any further detail.  Thank-you!

-jm

**Comment by stlalpha** [comment]
Same procedure succeeds when using stlalpha/experimental-dbonly image.  This image has no sshd and no apache daemon in it.  Same base plus apache fails, same base plus ssh fails.

**Comment by xemul** [comment]
Can you show full restore log, please? And which version (gitid?) version of criu do you play with?

**Comment by stlalpha** [comment]
criu git id: 0ac4c13e600db83d40b283296e8b8b011ccaf675

Full restore log of stlalpha/experimental from above procedure:

https://gist.github.com/stlalpha/de283c5c2cbc71b50ed2

**Comment by xemul** [comment]
The file /tmp/sshd-stdout---supervisor-f77QHv.log inside container is missing.

**Comment by stlalpha** [comment]
I'll mod supervisord to not reference the file - so I can understand - how did you make that determination from the logs?  Thank-you!

**Comment by xemul** [comment]
$ cat restore.log | fgrep Err
(01.615693)      1: Error (files-reg.c:1091): Can't open file tmp/sshd-stdout---supervisor-f77QHv.log on restore: No such file or directory
(01.615713)      1: Error (files-reg.c:1034): Can't open file tmp/sshd-stdout---supervisor-f77QHv.log: No such file or directory
(01.644186) Error (cr-restore.c:1933): Restoring FAILED.

:)

**Comment by stlalpha** [comment]
lol - retrying

**Comment by stlalpha** [comment]
Thank-you - after explicitey remapping stderr and stdout for the offending child processes to something outside of /tmp (the default) - it checkpoints and restores fine.
