### ISSUE TITLE
i386/i686 CRIU

### ISSUE THREAD

**Issue by azaa13** [xemul/criu#236]
Hi, 
already downloaded criu 2.7 then cloned from xemul/criu(that was successful) only Make
in my machine, couldn't executed Make command, gives me error,, 

my kernel version 4.4.2 then i try to install criu 2.7
i upload my error, pls correct my mistake 
tnx 
![same](https://cloud.githubusercontent.com/assets/23059639/19696192/c49054b6-9b03-11e6-87b9-7b59a4a1ad92.png)
![same2](https://cloud.githubusercontent.com/assets/23059639/19696199/c9b0ce1c-9b03-11e6-82f3-630c3d859c57.png)

**Comment by 0x7f454c46** [comment]
Hi, @azaa13, please, check out wiki installation page:
https://criu.org/Installation#Distribution_Packages
I guess, we can improve this failure by adding tests for the installed packages like we have for libs.
Maybe worth doing, not sure.

**Comment by xemul** [comment]
@azaa13 , have you succeeded in installing criu? Do you need more help from us?

**Comment by azaa13** [comment]
HI, no still gives me error, i installed those packages, but couldnt :(

**Comment by xemul** [comment]
Try to run 'make mrproper' after updating packages and show the compilation errors.

**Comment by azaa13** [comment]
![screenshot from 2016-11-06 01-49-22](https://cloud.githubusercontent.com/assets/23059639/20033292/515f9b82-a3c3-11e6-9d10-0c874c2d033f.png)
after make mrproper, then i make again, then got this error. what to do next?

**Comment by 0x7f454c46** [comment]
Is it 64-bit ubuntu?
Because 32-bit native build isn't supported.

**Comment by azaa13** [comment]
32bit

**Comment by 0x7f454c46** [comment]
Sorry, but I'm not sure if we have plans to support native 32-bit builds :(
We have plans to support 32-bit compat on 64-bit kernels, but not native AFAIK.

**Comment by azaa13** [comment]
![screenshot from 2016-11-06 02-24-10](https://cloud.githubusercontent.com/assets/23059639/20033522/16fc3f68-a3c8-11e6-98cf-1c39f9972bb8.png)

**Comment by xemul** [comment]
Architecture: i686

@azaa13 , CRIU on Intel is 64-bit only. Making it 32-bit is in plans, but not in urgent. If you're willing to participate, you're welcome, we will definitely help answering and reviewing patches.

**Comment by azaa13** [comment]
ok tnx,

**Comment by xemul** [comment]
Issue #43 will cover 32bit tasks on x8664 CPUs. Supporting 32bit CPUs ... well ... I'll close this one for a while until someone volunteers to write support for it :)

Anybody?
