### ISSUE TITLE
Inconsistent restore failure with CG_MODE_FULL - boucher cr-combined + hk + criu-current

### ISSUE THREAD

**Issue by stlalpha** [xemul/criu#24]
During the first try of a container restore with CG_MODE_FULL I get a failure with:

(00.000856) Collecting 37/21 (flags 0)
(00.000878)  `- ... done
(00.000905) cg: Preparing cgroups yard (cgroups restore mode 0x4)
(00.000957) cg: Opening .criu.cgyard.LsVKLt as cg yard
(00.000967) cg:         Making controller dir .criu.cgyard.LsVKLt/cpuset (cpuset)
(00.001031) cg: Created cgroup dir cpuset/system.slice/docker-404a13eab68e35753ee2c66f636aa727aa2c9a7723671d25cc9ffb0ede574178.scope
(00.001074) Error (cgroup.c:978): cg: Failed closing cpuset/system.slice/docker-404a13eab68e35753ee2c66f636aa727aa2c9a7723671d25cc9ffb0ede574178.scope/cpuset.cpus: Invalid argument
(00.001079) Error (cgroup.c:1083): cg: Restoring special cpuset props failed!

The second restore try - same parameters, same images, same container, same binaries - gets a successful result.  Any ideas?

Full restore log here: https://gist.github.com/6e84bae4e5c165491d1f

Thanks!

**Comment by stlalpha** [comment]
We've submitted a patch to help address this - currently under discussion

**Comment by xemul** [comment]
If I get things right this is fixed by 19dbe25918d5e61f60de498d380e5c25123c9fa3
