### ISSUE TITLE
cannot checkpoint a runc container when running with -d flag

### ISSUE THREAD

**Issue by yanadsl** [xemul/criu#240]
Using criu 2.7 and newest runc

use `runc spec` to generate `config.json` and change `"terminal" = false` and `"readonly"= false`

However , I can't checkpoint if i run with `runc run -d`

I only run an easy shell script to count number when starting container

Here's the error message

```
root@compute1:/opencontainers# runc checkpoint --work-path /opencontainers opencontainers
criu failed: type NOTIFY errno 0
log file: /opencontainers/dump.log
```

and the Error in dump.log
`Error (files-reg.c:1101): Can't lookup mount=21 for fd=0 path=/dev/pts/0`

full [dump.log](https://gist.github.com/yanadsl/be32cab2ea3e8d9ce57c7d4d2c6c7f15)

**Comment by xemul** [comment]
Cc @boucher and @avagin

**Comment by boucher** [comment]
I don't have any ideas offhand, perhaps @avagin will.

**Comment by adrianreber** [comment]
This is known. runc will in future versions correctly close stdin/stdout. They are not yet doing this. Workaround is: runc start container-name -d &> /dev/null  < /dev/null

**Comment by yanadsl** [comment]
Thanks for reply , since its a known issue and there's a workaround , I think I should close this.
