### ISSUE TITLE
Restore cmd on container failed 

### ISSUE THREAD

**Issue by dineshputchala** [xemul/criu#241]
Used "docker-1.10.0-dev" from https://github.com/boucher/docker/releases/tag/v1.10_2-16-16-experimental

[root@host~]# docker checkpoint ol
ol

[root@host~]# docker restore ol
Error response from daemon: Cannot restore container ol: cantstart: Cannot start container 05d60ad89e87ba1ceeb805537cddae0f1ab27cd000ee2f188b96acfa53ea3177: criu failed: type NOTIFY errno 0
log file: /var/lib/docker/0.0/containers/05d60ad89e87ba1ceeb805537cddae0f1ab27cd000ee2f188b96acfa53ea3177/criu.work/restore.log
Error: failed to restore one or more containers

Attached the restore.txt to this issue.

Could you please tell me how to resolve this error ?

[restore.txt](https://github.com/xemul/criu/files/577299/restore.txt)

**Comment by xemul** [comment]
(00.345752)      1: Warn  (libnetlink.c:65): ERROR -17 reported by netlink
(00.345771)      1: Error (net.c:488): can not restore link(00.351784) Error (cr-restore.c:1895): Restoring FAILED.


-17 is EEXISTS

What if you wait after dump for ... 2-3 seconds and try to restore again?

**Comment by dineshputchala** [comment]
will try ...
