### ISSUE TITLE
"Error response from daemon: page not found" from docker checkpoint 

### ISSUE THREAD

**Issue by dineshputchala** [xemul/criu#242]
Used "docker-1.10.0-dev" from https://github.com/boucher/docker/releases/tag/v1.10_2-16-16-experimental

Replaced /usr/bin/docker with docker-1.10.0-dev from above link and restarted the daemon and also tried by rebooting machine,

bash-4.1$ docker -v
Docker version 1.10.0-dev, build cec56b2, experimental

docker run -d --name looper  busybox    /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'

bash-4.1$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
b7a08a61897b        busybox             "/bin/sh -c 'i=0; whi"   13 minutes ago      Up 13 minutes     

bash-4.1$ docker inspect looper | grep "Status"
            "Status": "running",

bash-4.1$ docker checkpoint --help

Usage:  docker checkpoint [OPTIONS] CONTAINER
Checkpoint one or more running containers

  --help             Print usage
  --image-dir        directory for storing checkpoint image files
  --leave-running    leave the container running after checkpoint
  --work-dir         directory for storing log file

bash-4.1$ docker checkpoint looper
Error response from daemon: page not found
Error: failed to checkpoint one or more containers

All other command are working except checkpoint.

Could you tell me how I can resolve this issue ?

**Comment by xemul** [comment]
Would you show the dump.log file?

**Comment by HelenHarman** [comment]
I have just installed the experimental version of docker, and I also receive this error message.  Is there a fix for this? And where is the dump.log file located?

**Comment by xemul** [comment]
Cc @avagin and @boucher. Dump file is typically put by Docker daemon into /var/lib/docker.

**Comment by boucher** [comment]
The path to the dump file should be included in the checkpoint error message.

**Comment by HelenHarman** [comment]
My Docker version is 1.13.0-rc2, but my dockerd is version 1.12.3. experimental.
Which I guess is causing the page not found? If so, how do I update dockerd?
I installed Docker1.13 on clean machine, so not sure how it picked up dockerd 1.12.  

ps. There is no dump.log within the /var/lib/docker directory tree.

**Comment by boucher** [comment]
Yes, there won't be a dump if you don't even make it to the criu stage,
which will be the case if using an incompatible docker daemon.

**Comment by HelenHarman** [comment]
Everything now on correct version, and it is now working.
Sorry for the none existent issue.

**Comment by xemul** [comment]
Thanks, @boucher :)
