### ISSUE TITLE
Error building source code

### ISSUE THREAD

**Issue by dineshputchala** [xemul/criu#247]
Downloaded source code from ,
https://github.com/boucher/docker/releases/tag/v1.10_2-16-16-experimental

Tried to build the source code , but I see some timeout errors, Could you please take a look and let me know how to resolve these errors ?

bash-4.1$ cd docker-docker-checkpoint-restore
bash-4.1$ DOCKER_EXPERIMENTAL=1
bash-4.1$ ls
AUTHORS             Dockerfile.simple   VENDORING.md  container      hack             opts            runconfig
CHANGELOG.md        Dockerfile.windows  VERSION       contrib        image            pkg             utils
CONTRIBUTING.md     LICENSE             api           daemon         integration-cli  plugin          vendor
Dockerfile          MAINTAINERS         builder       distribution   layer            profiles        volume
Dockerfile.aarch64  Makefile            cli           dockerversion  libcontainerd    project
Dockerfile.armhf    NOTICE              cliconfig     docs           man              reference
Dockerfile.ppc64le  README.md           client        errors         migrate          registry
Dockerfile.s390x    ROADMAP.md          cmd           experimental   oci              restartmanager
bash-4.1$ make
mkdir bundles
mkdir -p .go-pkg-cache/gopath .go-pkg-cache/vendor .go-pkg-cache/goroot-linux_amd64_netgo
docker build   -t "docker-dev" -f "Dockerfile" .
Sending build context to Docker daemon 42.75 MB
Step 1 : FROM debian:jessie
jessie: Pulling from library/debian
386a066cd84a: Pull complete
Digest: sha256:c1ce85a0f7126a3b5cbf7c57676b01b37c755b9ff9e2f39ca88181c02b985724
Status: Downloaded newer image for debian:jessie
 ---> 73e72bf822ca
Step 2 : RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61        || apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
 ---> Running in 8cb246330662
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.cuVN9poD3j --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server p80.pool.sks-keyservers.net
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error

Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.FiHnyqoV28 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
gpg: requesting key F6B0FC61 from hkp server pgp.mit.edu
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
The command '/bin/sh -c apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61     || apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61' returned a non-zero code: 2
make: *** [build] Error 2

bash-4.1$ docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                      PORTS                                            NAMES
8cb246330662        73e72bf822ca                 "/bin/sh -c 'apt-key "   18 minutes ago      Exited (2) 14 minutes ago                                                    small_hopper

bash-4.1$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
debian              jessie              73e72bf822ca        8 days ago          123 MB

**Comment by xemul** [comment]
That's build of Docker, not CRIU :) You should probably ask this question at Docker issues page, not here.
