### ISSUE TITLE
Can't open sysctl net/ipv6/conf/all/accept_ra_min_hop_limit: No such file or dorectory

### ISSUE THREAD

**Issue by xiaozhazi** [xemul/criu#248]
When I use criu to restore my docker container, It shows errors as shown below.
![image](https://cloud.githubusercontent.com/assets/4612045/20548948/cb2cabe2-b162-11e6-9d1a-ca56849baa27.png)
My conmmand is : 
criu restore --tree 55276 --images-dir dump --shell-job --ext-mount-map /sys/fs/cgroup/memory:/sys/fs/cgroup/memory --ext-mount-map /sys/fs/cgroup/devices:/sys/fs/cgroup/devices --ext-mount-map /sys/fs/cgroup/freezer:/sys/fs/cgroup/freezer --ext-mount-map /sys/fs/cgroup/net_cls:/sys/fs/cgroup/net_cls --ext-mount-map /sys/fs/cgroup/perf_event:/sys/fs/cgroup/perf_event --ext-mount-map /sys/fs/cgroup/net_prio:/sys/fs/cgroup/net_prio --ext-mount-map /sys/fs/cgroup/hugetlb:/sys/fs/cgroup/hugetlb --ext-mount-map /etc/hosts:/etc/hosts --ext-mount-map /etc/hostname:/etc/hostname --ext-mount-map /etc/resolv.conf:/etc/resolv.conf --ext-mount-map /sys/fs/cgroup/blkio:/sys/fs/cgroup/blkio --ext-mount-map /sys/fs/cgroup/cpuacct:/sys/fs/cgroup/cpuacct --ext-mount-map /sys/fs/cgroup/cpu:/sys/fs/cgroup/cpu --ext-mount-map /sys/fs/cgroup/cpuset:/sys/fs/cgroup/cpuset --ext-mount-map /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd

found that in my destination node, don't have the /proc/sys/net/ipv6/conf/all/accept_ra_min_hop_limit file，and cann't create this file.
Is there something wrong in my linux kernel?

**Comment by xiaozhazi** [comment]
sorry for interrupt, It is about the linux kernel version.  Linux version is 4.2.0-36 in the source node, 4.2.0-27 in the destination node. But 4.2.0-27 has not include the /proc/sys/net/ipv6/conf/all/accept_ra_min_hop_limit yet. update the destination node kernel, it solved.

**Comment by xemul** [comment]
Cc @Snorch

**Comment by Snorch** [comment]
@xemul The problem when we can not restore some sysctl can arise not only when we migrating from newer kernel to older one where we do not have some sysctl from new kernel. For instance we have accept_ra_rtr_pref(Accept Router Preference in Routing Advertisement) sysctl which can be dissabled in kernel config if CONFIG_IPV6_ROUTER_PREF is dissabled. But what if migrating container does not care about full restore of all sysctls, e.g. user knows Routing Advertisement is not used in CT and same container works fine on both nodes?

To address these problem we can add some option to allow transparent skip of missing sysctls on restore adding CTL_FLAGS_OPTIONAL to sysctl request, is that OK?

**Comment by xemul** [comment]
I think OK, but ... tend to think that we'd better have a CLI option telling CRIU that missing ctls on restore is OK.
