### ISSUE TITLE
Support seccomp filter

### ISSUE THREAD

**Issue by rajasec** [xemul/criu#25]
@xemul 
With the latest runc where seccomp was introduced, I tried to do the criu of container

Got the following dump log messages

(00.002859) Error (proc_parse.c:826): SECCOMP_MODE_FILTER not currently supported
(00.002899) Error (proc_parse.c:839): Error parsing proc status file
Looks like as per the code, seccomp filter is not supported.
if (cr->seccomp_mode == SECCOMP_MODE_FILTER) {
                                pr_err("SECCOMP_MODE_FILTER not currently supported\n");
                                goto err_parse;
                        }
Is the seccomp filter available in the latest criu ?

**Comment by xemul** [comment]
@rajasec , no, @tych0 is still working on it, hopefully we'll have something in 1.8 (this winter).

**Comment by huikang** [comment]
@xemul  My runC version is 
```
/root/runc --version
runc version 0.3
```
Then runC checkpoint fails due to 
```
00.001844) Error (proc_parse.c:827): SECCOMP_MODE_FILTER not currently supported
(00.001855) Error (proc_parse.c:840): Error parsing proc status file
(00.001917) Unfreezing tasks into 1
(00.001931) 	Unseizing 12919 into 1
(00.001951) Error (ptrace.c:43): Unable to detach from 12919: No such process
(00.001963) Unlock network
(00.001974) Unfreezing tasks into 1
(00.001980) 	Unseizing 12919 into 1
(00.001985) Error (ptrace.c:43): Unable to detach from 12919: No such process
(00.002037) Error (cr-dump.c:1625): Dumping FAILED.
```
Is this the same problem as @rajasec observed? Thanks.

**Comment by tych0** [comment]
On Tue, Oct 20, 2015 at 11:48:36AM -0700, huikang wrote:
> @xemul  My runC version is 
> ```
> /root/runc --version
> runc version 0.3
> ```
> Then runC checkpoint fails due to 
> ```
> 00.001844) Error (proc_parse.c:827): SECCOMP_MODE_FILTER not currently supported
> (00.001855) Error (proc_parse.c:840): Error parsing proc status file
> (00.001917) Unfreezing tasks into 1
> (00.001931) 	Unseizing 12919 into 1
> (00.001951) Error (ptrace.c:43): Unable to detach from 12919: No such process
> (00.001963) Unlock network
> (00.001974) Unfreezing tasks into 1
> (00.001980) 	Unseizing 12919 into 1
> (00.001985) Error (ptrace.c:43): Unable to detach from 12919: No such process
> (00.002037) Error (cr-dump.c:1625): Dumping FAILED.
> ```
> Is this the same problem as @rajasec observed? Thanks.

Yes. I'm currently building what is (hopefully) the last version of
this patchset for the kernel, so it should go in soon.

**Comment by huikang** [comment]
@tych0 When I remove the section of sec comp section in container's runtime.json, it seems bypass the problem. But the checkpoint still fails due to 
```
00.003794) mnt: Inspecting sharing on 81 shared_id 0 master_id 0 (@./)
(00.003800) Error (mount.c:709): mnt: 101:./dev/console doesn't have a proper root mount
(00.003807) Unlock network
(00.003815) Running network-unlock scripts
(00.003824) 	RPC
(00.004175) Unfreezing tasks into 1
(00.004186) 	Unseizing 13013 into 1
(00.004289) Error (cr-dump.c:1625): Dumping FAILED.
```
@tych0 @avagin do you have any idea? Thanks.

**Comment by xemul** [comment]
The /dev/console issue is discussed in issue #76

**Comment by rajasec** [comment]
@huikang 
/dev/console issue from runc is tracked via
https://github.com/opencontainers/runc/issues/87

**Comment by xemul** [comment]
OK, but this issue is about seccomp :) Which is EINPROGRESS by @tych0

**Comment by xemul** [comment]
BTW, it's now complete. Kernel support is in 4.4 and CRIU support is since v2.0
