### ISSUE TITLE
System reboots after running "docker checkpoint create <container_name> <check_point_name>" for 1.13.0

### ISSUE THREAD

**Issue by dineshputchala** [xemul/criu#250]
bash-4.2$ which docker
/bin/docker

Downloaded 1.13 binaries from https://experimental.docker.com/builds/Linux/x86_64/docker-latest.tgz

Copied below files from above unzipped file to /bin where docker 1.12 version is already present.

bash-4.2$ ls
completion  docker  docker-containerd  docker-containerd-ctr  docker-containerd-shim  docker-init  docker-proxy  docker-runc  dockerd

bash-4.2$ /usr/local/packages/aime/install/run_as_root "/sbin/criu check"
Looks good.

Modified the below file to start the docker in experimental mode,

bash-4.2$ cat /etc/sysconfig/docker

# /etc/sysconfig/docker

# Modify these options if you want to change the way the docker daemon runs
OPTIONS='--selinux-enabled --experimental'
..
..

bash-4.2$ docker -v
Docker version 1.13.0-rc2, build 1f9b3ef

docker run -d --name looper --security-opt seccomp:unconfined busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
8e519f90b964ac65fc7c008924626c79def9ecd5ed484e3e7cd23ebbca17106a

docker checkpoint create looper chk2

Above command is hanging and system is rebooting immediately.

ls /var/lib/docker/container/f9d3cd05f5a7aa2b58f3ae11cb0312462984e197d5bfbe14e3e099da1dddbe4c

checkpoints     f9d3cd05f5a7aa2b58f3ae11cb0312462984e197d5bfbe14e3e099da1dddbe4c-json.log  hostname  resolv.conf       shm
config.v2.json  hostconfig.json                                                            hosts     resolv.conf.hash

ls -al containers/f9d3cd05f5a7aa2b58f3ae11cb0312462984e197d5bfbe14e3e099da1dddbe4c/checkpoints/ck1/criu.work/dump.log

-rw------- 1 root root 0 Nov 28 14:12 
containers/f9d3cd05f5a7aa2b58f3ae11cb0312462984e197d5bfbe14e3e099da1dddbe4c/checkpoints/ck1/criu.work/dump.log

Just after running above command I see below o/p in /var/log/messages,

tail -f /var/log/messages

Nov 28 14:11:37 adc01iau systemd: Starting Cleanup of Temporary Directories...
Nov 28 14:11:37 adc01iau systemd: Started Cleanup of Temporary Directories.
Nov 28 14:12:15 adc01iau kernel: Bits 55-60 of /proc/PID/pagemap entries are about to stop being page-shift some time soon. See the linux/Documentation/vm/pagemap.txt for details.
Nov 28 14:12:15 adc01iau kernel: The pagemap bits 55-60 has changed their meaning! See the linux/Documentation/vm/pagemap.txt for details.
Nov 28 14:12:15 adc01iau kernel: ip6_tables: (C) 2000-2006 Netfilter Core Team
Nov 28 14:12:15 adc01iau kernel: cgroup: new mount options do not match the existing superblock, will be ignored

Could you tell me how to resolve this issue ?

**Comment by xemul** [comment]
Hm... Maybe it's better to ask this question on Docker issues page?
Ccing @boucher and @avagin

**Comment by boucher** [comment]
I don't really have any ideas. I can tell you that running criu in production, we used to occasionally run into soft lockups and would be forced to reboot the machine, but I don't think we've seen that behavior in a long time.

**Comment by dineshputchala** [comment]
ok, thanks !
