### ISSUE TITLE
FAIL: cgroup03.c:105: mode for cgroup03.test/zdtmtst/test doesn't match (40600)

### ISSUE THREAD

**Issue by xemul** [xemul/criu#253]
https://travis-ci.org/xemul/criu/jobs/181306447

**Comment by kolyshkin** [comment]
Got the same failure:

======================== Run zdtm/static/cgroup03 in h =========================
Start test
Test is SUID
./cgroup03 --pidfile=cgroup03.pid --outfile=cgroup03.out --dirname=cgroup03.test
Cleaning cgclean.S1FdHP
Cleaning cgclean.0k06E8
Running zdtm/static/cgroup03.hook(--post-start)
Running zdtm/static/cgroup03.hook(--pre-dump)
Run criu dump
Running zdtm/static/cgroup03.hook(--pre-restore)
Run criu restore
Running zdtm/static/cgroup03.hook(--post-restore)
Send the 15 signal to  33
Wait for zdtm/static/cgroup03(33) to die for 0.100000
################ Test zdtm/static/cgroup03 FAIL at result check ################
Test output: ================================
00:17:43.950:    33: FAIL: cgroup03.c:105: mode for cgroup03.test/zdtmtst/test doesn't match (40600)
 (errno = 11 (Resource temporarily unavailable))
 <<< ================================
Running zdtm/static/cgroup03.hook(--clean)

For details, see https://travis-ci.org/criupatchwork/criu/jobs/181822437

**Comment by kolyshkin** [comment]
@tych0 maybe you can take a look?

**Comment by tych0** [comment]
On Wed, Dec 07, 2016 at 12:37:35AM -0800, Kirill Kolyshkin wrote:
> @tych0 maybe you can take a look?

Yes, I can, but probably not until next week :(

**Comment by kolyshkin** [comment]
Got yet another one: https://travis-ci.org/criupatchwork/criu/jobs/182176186

======================== Run zdtm/static/cgroup03 in h =========================
Start test
Test is SUID
./cgroup03 --pidfile=cgroup03.pid --outfile=cgroup03.out --dirname=cgroup03.test
Cleaning cgclean.xRarY4
Cleaning cgclean.jWYy0k
Running zdtm/static/cgroup03.hook(--post-start)
Running zdtm/static/cgroup03.hook(--pre-dump)
Run criu dump
Running zdtm/static/cgroup03.hook(--pre-restore)
Run criu restore
Running zdtm/static/cgroup03.hook(--post-restore)
Send the 15 signal to  33
Wait for zdtm/static/cgroup03(33) to die for 0.100000
################ Test zdtm/static/cgroup03 FAIL at result check ################
Test output: ================================
04:17:24.509:    33: FAIL: cgroup03.c:105: mode for cgroup03.test/zdtmtst/test doesn't match (40600)
 (errno = 11 (Resource temporarily unavailable))

**Comment by avagin** [comment]
Why do we restore perms for a cgroup even if it exists?
```
                if (faccessat(cg, paux, F_OK, 0) < 0) {
...
                } else {
...
                        if (!(opts.manage_cgroups & CG_MODE_NONE) &&
                            prepare_dir_perms(cg, paux, e->dir_perms) < 0)
                                return -1;

```

**Comment by tych0** [comment]
On Thu, Dec 08, 2016 at 07:42:39PM -0800, Andrew Vagin wrote:
> Why do we restore perms for a cgroup even if it exists?

Because the restore can fail if we don't, e.g. if a task had a cgroup
directory open and the perms on the existing one were wrong.
