### ISSUE TITLE
Restore failed

### ISSUE THREAD

**Issue by dineshputchala** [xemul/criu#255]
Used "docker-1.10.0-dev" from https://github.com/boucher/docker/releases/tag/v1.10_2-16-16-experimental

Started a db container,

bash-4.2$ docker checkpoint oradb
oradb

Checkpoint is done without any error.

Waited for 10-15 minutes and then tried to restore,

bash-4.2$ docker restore oradb
Error response from daemon: Cannot restore container oradb: cantstart: Cannot start container c5a32629f87848780545e6da87874d44c7bdfd15f88263760b06dbed89364f3e: criu failed: type NOTIFY errno 0
log file: /var/lib/docker/0.0/containers/c5a32629f87848780545e6da87874d44c7bdfd15f88263760b06dbed89364f3e/criu.work/restore.log
Error: failed to restore one or more containers

Restore operation on container is failing with above error,

Last few lines of dump.log is as follows, Please take a look !

..
..

(01.254218)   1830:             Create fd for 6
(01.254238)   1786:             Create fd for 6
pie: 1788:      mmap(0x7f2c27a39000 -> 0x7f2c27a3a000, 0x1 0x11 82)
(01.254254)   1894: Going to chroot into ./self/fd/9
pie: 2137: Remap 0x7fa53abbb000->0x7fe372a31000 len 0x235000
(01.263508)   1776: Parsed 7fa5218f2000-7fa53a7b2000 vma
(01.328117) Error (cr-restore.c:978): 3127 killed by signal 9: Killed
(01.338278) Switching to new ns to clean ghosts
(01.344246) Error (cr-restore.c:1840): Restoring FAILED.

**Comment by xemul** [comment]
> (01.328117) Error (cr-restore.c:978): 3127 killed by signal 9: Killed

That's the first error I see, but it doesn't give a glue why task 3127 died. Would you show full restore.log?

**Comment by xemul** [comment]
Ping, @dineshputchala

**Comment by xemul** [comment]
OK, if the issue is still there -- feel free to re-open one.

**Comment by dineshputchala** [comment]
log
