### ISSUE TITLE
Question about libcriu license

### ISSUE THREAD

**Issue by jaeguk** [xemul/criu#263]
Hello, criu guys.

I'm trying to use criu to speed up some application in embedded device.
I liked your achievements about criu very much over the work.
But opensource license team said libcriu linking can occur some problem about license.
He said rpc.pb-c.c and rpc.pb-c.h generated by rpc.proto can be applied GPL about process linking libcriu . Because it doesn't exist in /lib folder mentioned from comments in COPYING file.
Do you think it can be problem ( GPL not LGPL about libcriu linking )?

Thanks.

**Comment by xemul** [comment]
Actually we don't have rpc.pb-c.* files in sources :) They are generated from the rpc.proto, so AFAIU the result can be linked anywhere.

**Comment by jaeguk** [comment]
Thanks for your answer!
My question is whether rpc.proto is GPL or LGPL when libcriu is built with it. 

Thanks

**Comment by xemul** [comment]
rpc.proto is GPL, but why is it a problem? It's not a file your code links with.

**Comment by jaeguk** [comment]
When libcriu.so is built,  rpc.pb-c.h, rpc.pb-c.c generated from rpc.proto is used, isn't it? 
Our opensoure license team worried aboout it.
Don't we need to worry about libcriu use rpc.pb-c.*?

Thanks

**Comment by xemul** [comment]
@jaeguk , yes libcriu.so is built using files generated from rpc.proto file, but I see no problems with it. You can use the resulting library as fully LGPL licensed.

**Comment by jaeguk** [comment]
Ok, Thanks for your help.
