### ISSUE TITLE
docker\runc - checkpoint\restore fails - signal 11: Segmentation fault - (criu/sk-unix.c:710)

### ISSUE THREAD

**Issue by iprimo** [xemul/criu#266]
Hi,
I am using CRIU\Docker\runc in my test env; and using xpra (virtual x-server) to connect to containers. 
The following error randomly shows up after check-pointing a container with xpra dis-connected.

(01.945944)     45: Restoring children in alien sessions:
(01.945950)     45: Restoring 45 to 45 sid
(01.946036)     45: Restoring children in our session:
(01.946171)     45: Restoring 45 to 45 pgid
(02.242557)    301: Error (criu/cr-restore.c:1012): 149 killed by signal 11: Segmentation fault
(02.266203) Error (criu/cr-restore.c:1012): 12248 killed by signal 9: Killed
(02.287635) mnt: Switching to new ns to clean ghosts
(02.287737) Error (criu/cr-restore.c:1893): Restoring FAILED.

 Runc reproducing steps:

	On hosting servers:
		Create runc container folder
			    mkdir container_x
			    cd  container_x
			    mkdir rootfs    
			    mkdir checkpoint
		Start container:
		    runc run abcd
	
	Inside container: (these ports are on host IP)
		    xpra start :300 --start=xclock --bind-tcp=0.0.0.0:2223

	On remote host using GUI App in container:
		    xpra attach tcp:192.168.134.138:2223
		    xpra detach tcp:192.168.134.138:2223

2 checkpoint approaches

	On Hosting server    (without --ext-unix-sk)
		    runc checkpoint --tcp-established  --image-path=/home/checkpoint/ --work-path=/home/checkpoint/ abcd  
		    runc restore --tcp-established --image-path=/home/checkpoint/ --work-path=/home/checkpoint/ abcd

	On Hosting server    (with --ext-unix-sk)
		    runc checkpoint --tcp-established --ext-unix-sk --image-path=/home/checkpoint/ --work-path=/home/checkpoint/ abcd  
		    runc restore --tcp-established --ext-unix-sk --image-path=/home/checkpoint/ --work-path=/home/checkpoint/ abcd

'

Please note both above check point approaches failures are very random. First few attempts normally works well, however, after the first failure all other tries fail too.  
The same steps were tired with Firefox on (docker and runc); the result is the same as error in the link below which could Not be resolved: http://forum.odin.com/threads/snapshot-creation-fail-at-virutozzo-7.338164/

------------------- Docker 

'
(00.961065) cg: Writing CG image
(00.961115) sk unix: Dumping external sockets
(00.961118) sk unix:    Dumping extern: ino 0x1130a peer_ino 0x1130b family    1 type    1 state  1 name (null)
(00.961126) sk unix:    Dumped extern: id 0x24 ino 0x1130a peer 0 type 2 state 10 name 0 bytes
(00.961129) sk unix:    Ext stream not supported: ino 0x1130a peer_ino 0x1130b family    1 type    1 state  1 name (null)
(00.961131) Error : sk unix: Can't dump half of stream unix connection.
(00.961193) Unlock network

Docker reproducing steps:
'
On Host:
		docker run  --security-opt seccomp:unconfined --name abcd_abcd -p 2222:22 -p 2223:23 -id xpra_apache_installed

Inside container:
	docker exec abcd_abcd xpra start :2229 --start=xclock --bind-tcp=0.0.0.0:23

Using GUI apps inside container from remote host:
	xpra attach tcp:192.168.134.139:2223

Checkpoint - On the host: (Docker version 1.2) -> After restore Container losses network connectivity
	docker checkpoint --work-dir=/home/administrator/checkpoint --image-dir=/home/administrator/checkpoint abcd_abcd
	docker restore --work-dir=/home/administrator/checkpoint --image-dir=/home/administrator/checkpoint abcd_abcd

Checkpoint - On the host: (Docker version 1.3)
	docker checkpoint create abcd_abcd chp_02
	docker start --checkpoint chp_02 abcd_abcd

-------------------------

My env:
        root..# docker --version
        Docker version 1.13.0-rc4, build 88862e7
        root..# runc --version
        runc version 1.0.0-rc2
        spec: 1.0.0-rc2-dev
        root..# criu --version
        Version: 2.9
        GitID: v2.9-56-ga48c533

Inside container xpra (X-server)
xpra --version
     xpra v1.0-r14532

Docker and Runc logs attached.

[runc_restore.txt](https://github.com/xemul/criu/files/686636/runc_restore.txt)
[docker_restore.txt](https://github.com/xemul/criu/files/686637/docker_restore.txt)

**Comment by xemul** [comment]
OK, so the main problem is:
    (02.242557) 301: Error (criu/cr-restore.c:1012): 149 killed by signal 11: Segmentation fault

Looking at runc_restore.txt I see that task 149 gets restored and its last message is
    (01.468572)    149: cg:   `-> pids//user.slice/user-1000.slice/abcd_1/tasks

If I give you a patch, will you be able to re-build CRIU and check again?

Cc @cyrillos for the help how to build CRIU with debugingo and get core file from crash.

**Comment by cyrillos** [comment]
Building with debug info is simple, just run make DEBUG=1. As to get crash core -- it depends on system settings which is distro specific.

http://man7.org/linux/man-pages/man5/core.5.html

Look into /proc/sys/kernel/core_pattern first and then look if you run abrt daemon or anything else.

**Comment by xemul** [comment]
@cyrillos , thanks. @iprimo , if you could also get the .core file and find out the crash-stack with gdb, that'd be really helpful!

**Comment by iprimo** [comment]
@xemul and @cyrillos thanks for your replies.

@xemul sure I can rebuild CRIU with the new patch.

As requested, tried the same steps with make DEBUG =1, 

As previously mentioned, the problem is random and for some unknown reason, today toke much longer to regenerate it. (just a few days ago, the error was all over the place!).

On the other-hand, "Can't dump ghost file /dev/shm/org.chromium.4gbeQt" error was very common this time and appreciate if you could advise how I can get around it. ( runc does not have --ghost-limit feature in checkpoint options)

There was some issues with getting core_dump enabled, will try it again and post the files.

Both log files are attached.

[CRIU _ size dump issue.txt](https://github.com/xemul/criu/files/693406/CRIU._.size.dump.issue.txt)
[Debug enabled _ signal 11 _ Segmentation fault.txt](https://github.com/xemul/criu/files/693407/Debug.enabled._.signal.11._.Segmentation.fault.txt)

**Comment by xemul** [comment]
@iprimo , the issue with ghost file is its size, 17Mb which is bigger than default CRIU limit. You can change it by hands, the constant is sources is DEFAULT_GHOST_LIMIT.

And looking forward to the core image.

**Comment by xemul** [comment]
I've created an issue to set up the ghost limit via environment (#269)

**Comment by cyrillos** [comment]
Why? We've a command line option for that already. 

criu/crtools.c:"  --ghost-limit size    limit max size of deleted file contents inside image\n"

**Comment by cyrillos** [comment]
Ah, there is no runc option for that. env var indeed might be an option then

**Comment by xemul** [comment]
@cyrillos , we do, but when used via Docker CLI one cannot specify one :)

**Comment by iprimo** [comment]
Hi,
I managed to regenerate the problem, but there is no core dump getting generated. (http://stackoverflow.com/questions/6152232/how-to-generate-core-dump-file-in-ubuntu)
Is there any other way I can help you guys to resolve this issue ?

Just wondering if you can help me with the following questions ?

1. Is there any container migration solution available at the moment? (Live or Offline)

2. To restore a checkpoint container on another host, other than checkpoint images what else has to be transfered across? I tried transfering container folder and checkpoint images, but there was a few errors coming up. (to test this , the following VM was used: https://atlas.hashicorp.com/kimh/boxes/criu)

3. I managed to find --ghost-limit in the following locations, however, changing them dose not seem to resolve the fore mentioned issue. Can you please advise where this value could be changed (runcs & docker)

cat /home/vagrant/criu/protobuf/rpc.proto | grep ghost
cat /home/vagrant/criu/test/rpc/rpc.proto | grep ghost
cat /usr/local/include/criu/rpc.proto | grep ghost

Thanks

[restore.txt](https://github.com/xemul/criu/files/705919/restore.txt)

**Comment by xemul** [comment]
@iprimo , answering your questions :)

0. To resolve the issue, since there's no core file, let's try with the patches. Which CRIU version do you use?
1. Ready-to-use container migration solution is not yet there. We're working on the p.haul extension to CRIU that will make it happen. You're welcome to join :) https://lists.openvz.org/pipermail/criu/2016-December/034354.html
2. For live migration you need container root filesystem and images. That's it.
3. The --ghost-limit is CRIU option. Absence of this in rpc.proto signs that the version is too old, here it is in current 2.10:

# cat images/rpc.proto | fgrep -A2 -B2 ghost

	optional criu_cg_mode		manage_cgroups_mode = 34;
	optional uint32			ghost_limit	= 35 [default = 0x100000];
	repeated string			irmap_scan_paths = 36;
	repeated string			external	= 37;

**Comment by cyrillos** [comment]
@iprimo Hi! You know I wonder why we have segfault there. Could you please share your images somewhere so I would fetch and look into.

**Comment by iprimo** [comment]
@xemul Many thanks for your answers, they were a great help ! :)

I certainly can apply any patches provided and provide you with the outcome. My CRIU version is: 2.9 (GitID: v2.9-56-ga48c533)

-------

Regarding restoring containers on a second box, I am encountering the following error on the second box: ( Docker version: 1.13.0-rc4, CRIU Version: 2.9)

:/var/lib/docker/containers# docker start --checkpoint chp_02 abcd_abcd
Error response from daemon: No such container: abcd_abcd
:/var/lib/docker/containers# docker start --checkpoint chp_02 49f357d5...
Error response from daemon: No such container: 49f357d5...

Both boxes have the required images and I transfer the content of "/var/lib/docker/containers/49f357d5.." folder from first box to the second.  (if I am correct that is what you meant by contaner root files)

It seems Docker daemon is not aware of existence of the newly transfered container. Is there a way to let docker know to accept hosting of the new container ?

----
May I ask, how can I use the TCP-Established \ Unix-socket feature of CRIU in Docker ? The applications I am developing to work with Docker C\R are network\socket based apps those features are a great help !



@cyrillos : The image is available on docker-hub iprimo/guiossh_08:v0.0004_xnext_and_fluxbox_installed

**Comment by cyrillos** [comment]
Thank you! Will take a look on images hopefully today.

**Comment by cyrillos** [comment]
@iprimo hmm. not sure how to fetch them via web interface?

**Comment by iprimo** [comment]
@cyrillos NP,
Please find the packaged image in the following URL.
https://drive.google.com/file/d/0BzP4ZiHsOGPGZGN4M2I5anh4djA/view?usp=sharing
Thanks

**Comment by cyrillos** [comment]
Thanks a huge! Will try to fetch today.

**Comment by cyrillos** [comment]
Hmm. I tried to play with it but these are bunch of docker overlayfs layers. I guess better would be the following:
 - do the ordinary dump
 - but for restore you might try to do the following: move criu executable to some criu.exec and make criu as an executable script which would run "strace -o criu-restore.log -s 256 -f criu.exec with arguments from the shell (shift $* or something like that). That should create criu-restore.log file which we could take a look on and try to figure out where SIGSEGV happened.

**Comment by cyrillos** [comment]
@iprimo another option might be if you give me access to the VM I would try to figure out.

**Comment by iprimo** [comment]
Hi @cyrillos ,
Thanks for your reply
I tried to re-built the image with new updates and latest patches, it seems the problem has resolved itself.
I dig more and open a new case if it comes back.
Thanks for your efforts and follow ups.
