### ISSUE TITLE
Docker restoring with --force option failed

### ISSUE THREAD

**Issue by kimh** [xemul/criu#27]
I'm experimenting the migration of docker container from one host to another and encountered a bit strange error.

Here is what I did.

Run a container on host A and checkpoint.

```
$ docker run -d --name np busybox:latest /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'

$ docker checkpoint --image-dir=/tmp/np np
```

Then move `/tmp/np` to host B and tried restoring like this.

```
$ docker restore --force=true --image-dir=/tmp/$container --work-dir /tmp/something $(docker create --name=$container busybox)
````

The above restoring failed with the following error in restore.log.

```
(00.102727)      1: cg: Move into 2
(00.102735)      1: cg:   `-> blkio//docker/9dccf569f5b1005e9fbc4770030243704b8e3cb27e5ede62de1286835374f067/tasks
(00.102773)      1: cg:   `-> cpu//docker/9dccf569f5b1005e9fbc4770030243704b8e3cb27e5ede62de1286835374f067/tasks
(00.102864)      1: cg:   `-> cpuacct//docker/9dccf569f5b1005e9fbc4770030243704b8e3cb27e5ede62de1286835374f067/tasks
(00.102896)      1: cg:   `-> cpuset//docker/9dccf569f5b1005e9fbc4770030243704b8e3cb27e5ede62de1286835374f067/tasks
(00.103063)      1: Error (cgroup.c:901): cg: Can't move into cpuset//docker/9dccf569f5b1005e9fbc4770030243704b8e3cb27e5ede62de1286835374f067/tasks (-1/0): No space left on device
(00.107453) Error (cr-restore.c:1933): Restoring FAILED.
```

Here is the full [restore.log](https://gist.github.com/kimh/32c8ec30dd700bdeb072).

The strange thing is that the restoration will succeed if I run the command ( `docker run -d --name np busybox:latest /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'`) on host B. And all subsequent restoration will succeed.

**Comment by kimh** [comment]
Actually, I found that I need to run at least a container on host B before doing any restoration. Maybe this is a bug with docker?

**Comment by xemul** [comment]
The ENOSPC from cpuset cgrpup attach means that special props were not restored. Looks like issue #16 . @cyrillos would you take a look at ... both :) please.

**Comment by cyrillos** [comment]
@xemul sure, will take a look tonight or tomorrow (actually I thought it's fixed in commit 19dbe259)

**Comment by xemul** [comment]
@cyrillos , not it's another issue. The commit you mention is about restoring root cgroups, while this problem _seem_ to be in missed special props restore for existing directories.

**Comment by cyrillos** [comment]
@xemul The question is would it be correct to restore special props if they already exist? I've created a patch for that but I really doubt that we should. cpuset is special and what's worse the number of cpus might varies between machines. That said I think such parameters should be set up by "resume" script from the docker itself or vzctl in case of openvz.

https://gist.github.com/cyrillos/cec00f63d2b397d721ce

Here is a patch which restores cpuset unconditionally but as I said I think this souldn't be done by criu itself. @tych0, @avagin  opinions ?

**Comment by xemul** [comment]
Well, primary question -- is it the case we're dealing with? Can we at least have a patch that checks this and prints respective messages in the logs? Because right now it's not clear from logs what do we do with cgroups on restore :)

**Comment by cyrillos** [comment]
In this patch we will print if we've restored special props. And I think it because of the lack of the restore cpuset. Look into the log

(00.000902) cg: Preparing cgroups yard (cgroups restore mode 0x4)
(00.000971) cg: Opening .criu.cgyard.dUuKQf as cg yard
(00.000998) cg:         Making controller dir .criu.cgyard.dUuKQf/cpuset (cpuset)
(00.001029) cg: Determined cgroup dir cpuset/docker/9dccf569f5b1005e9fbc4770030243704b8e3cb27e5ede62de1286835374f067 already exist

The criu doesn't touch cpuset because it's already here, so depending on current configuration it might have no cpuset assiged at all, in result we can't move the task into.

**Comment by xemul** [comment]
OK, the cgroups not properly configured before restore is discussed in issue #16
