### ISSUE TITLE
Criu : suspending seccomp failed: invalid argument

### ISSUE THREAD

**Issue by yamen94** [xemul/criu#270]
I followed the steps in this tutorial:
http://rhelblog.redhat.com/2016/12/08/container-live-migration-using-runc-and-criu/comment-page-1/#comment-14673

when I reach the part of 
runc checkpoint rhel7-httpd
i got the following error:
criu failed: type NOTIFY errno 0
log file: /run/runc/rhel7-httpd/criu.work/dump.log

the dump.log file is like that:

(00.000052) mnt: Added /var/www/html:/var/www/html ext mount mapping
(00.000116) ========================================
(00.000126) Dumping processes (pid: 4255)
(00.000131) ========================================
(00.000139) Running pre-dump scripts
(00.000143) 	RPC
(00.001692) Pagemap is fully functional
(00.002005) Found anon-shmem device at 4
(00.002035) Reset 5088's dirty tracking
(00.002164)  ... done
(00.002242) Dirty track supported on kernel
(00.003069) Found task size of 7ffffffff000
(00.003620) irmap: Searching irmap cache in work dir
(00.003658) No irmap-cache image
(00.003670) irmap: Searching irmap cache in parent
(00.003693) irmap: No irmap cache
(00.003756) cpu: fpu:1 fxsr:1 xsave:1
(00.004132) vdso: Parsing at 7ffcbe5fe000 7ffcbe600000
(00.004148) vdso: PT_LOAD p_vaddr: ffffffffff700000
(00.004153) vdso: DT_HASH: ffffffffff700120
(00.004157) vdso: DT_STRTAB: ffffffffff700268
(00.004161) vdso: DT_SYMTAB: ffffffffff700160
(00.004165) vdso: DT_STRSZ: 5e
(00.004169) vdso: DT_SYMENT: 18
(00.004173) vdso: nbucket 3 nchain b bucket 7ffcbe5fe128 chain 7ffcbe5fe134
(00.004188) vdso: rt [vdso] 7ffcbe5fe000-7ffcbe600000 [vvar] ffffffffffffffff-ffffffffffffffff
(00.004383) Perparing image inventory (version 1)
(00.004462) Add pid ns 1 pid 5088
(00.004479) Add net ns 2 pid 5088
(00.004493) Add ipc ns 3 pid 5088
(00.004511) Add uts ns 4 pid 5088
(00.004524) Add mnt ns 5 pid 5088
(00.004542) Add user ns 6 pid 5088
(00.004553) Add cgroup ns 7 pid 5088
(00.004563) cg: Dumping cgroups for 5088
(00.004648) cg:  `- New css ID 1
(00.004661) cg:     `- [blkio] -> [/user.slice] [0]
(00.004667) cg:     `- [cpuacct,cpu] -> [/user.slice] [0]
(00.004671) cg:     `- [cpuset] -> [/] [0]
(00.004675) cg:     `- [devices] -> [/user.slice] [0]
(00.004679) cg:     `- [freezer] -> [/] [0]
(00.004684) cg:     `- [hugetlb] -> [/] [0]
(00.004688) cg:     `- [memory] -> [/user.slice] [0]
(00.004692) cg:     `- [name=systemd] -> [/user.slice/user-1000.slice/session-1.scope] [0]
(00.004696) cg:     `- [net_prio,net_cls] -> [/] [0]
(00.004701) cg:     `- [perf_event] -> [/] [0]
(00.004705) cg:     `- [pids] -> [/] [0]
(00.004709) cg: Set 1 is criu one
(00.008038) Error (ptrace.c:64): suspending seccomp failed: Invalid argument
(00.008080) Unlock network
(00.008113) Unfreezing tasks into 1
(00.008118) 	Unseizing 4255 into 1
(00.008126) Error (ptrace.c:54): Unable to detach from 4255: No such process
(00.008157) Error (cr-dump.c:1598): Dumping FAILED.

any help please ??
i am using redhat enterprise linux 7.3 
kernel 3.10

**Comment by adrianreber** [comment]
Try to remove the seccomp entries from your config.json. Older versions of oci-runtime-tool didn't generate the seccomp rules for runc.

**Comment by xemul** [comment]
@yamen94 , your kernel doesn't have required API. Try running criu check --all

**Comment by yamen94** [comment]
@adrianreber Is there a new of oci-runtime-tool ?

**Comment by yamen94** [comment]
@xemul yes when I run it I know there is errors 
Kernal doesn't support PTRACE_0_SUSPEND_SECCOMP
 But Iam not good with dealing with kernels so I don't know the solution

**Comment by yamen94** [comment]
And how could I change in the kernel config file

**Comment by xemul** [comment]
@yamen94 https://kernelnewbies.org/KernelBuild , but I think that fixing oci config not to generate seccomp rules would be easier.
