### ISSUE TITLE
runc - overlayfs - criu failed: type NOTIFY errno 0 

### ISSUE THREAD

**Issue by iprimo** [xemul/criu#274]
Hi,
I am trying to run a runc container using overlayfs. The container checkpoint fails with "criu failed: type NOTIFY errno 0" .
I have attached the dump files with "Debug" 1" in addition of the steps taken to setup overlayfs mount point and commands to checkpoint the container.
There was no core dump generated by the host.
I appreciate if you could assist.
Thanks
[dump.txt](https://github.com/xemul/criu/files/720872/dump.txt)
[steps_simplified.txt](https://github.com/xemul/criu/files/720871/steps_simplified.txt)

**Comment by xemul** [comment]
@iprimo , this is a known issue :( #136 
We'll try to speed things up with fixing it.
Cc @avagin
