### ISSUE TITLE
alpine: Error (compel/src/lib/infect-rpc.c:72): Command 66 for daemon failed with -1

### ISSUE THREAD

**Issue by avagin** [xemul/criu#276]
```
========================== Run zdtm/static/env00 in h ==========================
Start test
./env00 --pidfile=env00.pid --outfile=env00.out --envname=ENV_00_TEST
Run criu dump
=[log]=> dump/zdtm/static/env00/32/1/dump.log
------------------------ grep Error ------------------------
(00.043112) Error (criu/util.c:670): exited, status=3
pie: 32: Error (criu/pie/parasite.c:76):
pie: 32: Error (criu/pie/parasite.c:78): -22
(00.071762) Error (compel/src/lib/infect-rpc.c:72): Command 66 for daemon failed with -1
(00.071895) Error (criu/mem.c:464): Can't dump page with parasite
(00.074380) Error (criu/cr-dump.c:1673): Dumping FAILED.
------------------------ ERROR OVER ------------------------
################### Test zdtm/static/env00 FAIL at CRIU dump ###################
```
https://travis-ci.org/avagin/criu/builds/195068801

**Comment by avagin** [comment]
The next patch fixes the issue, but I don't understand where is an exact reason.
https://github.com/avagin/criu/commit/ff8777b3628eae6b7cc98c7b925cf88508dd3aa8

Cc: @cyrillos @0x7f454c46

**Comment by avagin** [comment]
I tried to initialize msg_flags and iov_len, but it isn't enough.
https://travis-ci.org/avagin/criu/builds/195084525

**Comment by 0x7f454c46** [comment]
https://travis-ci.org/0x7f454c46/criu/builds/195189779
Look at dat shiny-shit :)
https://github.com/0x7f454c46/criu/commit/fe15dd6e8d34333061a3ff80222a8aff17c1f587

**Comment by 0x7f454c46** [comment]
Musl introduced paddings with:
http://git.musl-libc.org/cgit/musl/commit/arch/x86_64/bits/socket.h?id=7168790763cdeb794df52be6e3b39fbb021c5a64
and
http://git.musl-libc.org/cgit/musl/commit/?id=96107564e2eabbc13800fe7a7d930b67216d0805

**Comment by richfelker** [comment]
sendmsg and recvmsg perform the zeroing of the padding before passing the structure to the kernel. If it's not working, the bug must be something more subtle.

**Comment by 0x7f454c46** [comment]
@richfelker that's code, that is used in PIE - parasite, injected inside a process - it can't use libraries wrappers around syscalls and thus does raw syscalls. Still, CRIU uses structure defines from libc everywhere, including syscalls for PIE.

**Comment by richfelker** [comment]
In that case you just need to zero-fill the storage for the msghdr structures before setting them up.

**Comment by 0x7f454c46** [comment]
Yep, the whole header or paddings.

**Comment by richfelker** [comment]
Needs to be whole structure. The paddings do not have public names.
