### ISSUE TITLE
Container restored but network is no longer accessible. Using --network=host option.

### ISSUE THREAD

**Issue by HelenHarman** [xemul/criu#277]
Running the instructions on: https://github.com/docker/docker/blob/master/experimental/checkpoint-restore.md
But with --network=host in the run command: 
> docker run --security-opt=seccomp:unconfined --network=host --name cr -d busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 

Container is restored but network/internet is no longer accessible (machine can not be pinged). 

System:
- Virtual Machine: Ubuntu 16.04
- Kernel: 4.10
- Criu: 2.10
- Docker 1.13

I have attached the restore.log file.
[restore.txt](https://github.com/xemul/criu/files/729040/restore.txt)

**Comment by xemul** [comment]
Actually Docker keeps CRIU away from network namespace C/R :) so I guess we need additional info regarding what exactly was restore and some help from @boucher and @avagin .

**Comment by xemul** [comment]
@HelenHarman , can you get into the host somehow and type 'ip a l' and 'ip r l' after the restore?

**Comment by xemul** [comment]
@HelenHarman , is this still an issue?

**Comment by xemul** [comment]
OK, if the issue is still there, feel free to re-open one.
