### ISSUE TITLE
Add ability to close all TCP sockets rather than C/R them

### ISSUE THREAD

**Issue by xemul** [xemul/criu#280]
As discussed in issue #271 , it's tempting to just drop (close) all TCP sockets rather than trying to mess with them. The proposed in the issues patch is an exampled of how to do it.

**Comment by ISilence** [comment]
@xemul, it seems to be done (ref 2c37042821906f013634e305899cb25ff1a5a7b1)

**Comment by xemul** [comment]
Yup, thanks!
