### ISSUE TITLE
iterative migration

### ISSUE THREAD

**Issue by ramy150** [xemul/criu#281]
dear all the community
so i'm actually doing a live migration with lxc/lxd
but i have a real problem when i use the dump command

####################################################
root@ubuntu:/home/onos# criu dump -t 2287 --images-dir /root/image/ --leave-stopped
Error (criu/mount.c:948): mnt: Mount 352 ./dev/console (master_id: 3 shared_id: 0) has unreachable sharing. Try --enable-external-masters.
Error (criu/cr-dump.c:1636): Dumping FAILED.

**Comment by tych0** [comment]
Hi,

Don't use manual dump. The same advice applies as in: https://github.com/lxc/lxd/issues/2838

**Comment by ramy150** [comment]
Hi tych0,

i posted this issue

Best regards,

________________________________
De : Tycho Andersen <notifications@github.com>
Envoyé : mardi 7 février 2017 23:49
À : xemul/criu
Cc : ramy150; Author
Objet : Re: [xemul/criu] iterative migration (#281)


Hi,

Don't use manual dump. The same advice applies as in: lxc/lxd#2838<https://github.com/lxc/lxd/issues/2838>

**Comment by xemul** [comment]
@ramy150 , @tych0 says that calling criu directly is not good idea when dumping LXC container, since there are tons of options that should be specified. Use lxc tools for checkpoints, it will prepare all those options for you.

**Comment by ramy150** [comment]
Thanks pavel but I already try to do it and the lxc-checkpoint - r didn't work


Sent from my iPhone

On Feb 13, 2017, at 8:21 PM, Pavel Emelyanov <notifications@github.com<mailto:notifications@github.com>> wrote:


@ramy150<https://github.com/ramy150> , @tych0<https://github.com/tych0> says that calling criu directly is not good idea when dumping LXC container, since there are tons of options that should be specified. Use lxc tools for checkpoints, it will prepare all those options for you.

**Comment by xemul** [comment]
OK, you just posted the results of criu dump command.

And since lxc-checkpoint doesn't work, would you show the restore.log file?

**Comment by ramy150** [comment]
[restore.txt](https://github.com/xemul/criu/files/772101/restore.txt)

**Comment by ramy150** [comment]
[debug.txt](https://github.com/xemul/criu/files/772110/debug.txt)
 and there is the debug file obtained from lxc-chechpoint -l DEBUG

**Comment by xemul** [comment]
What version of criu do you use?

**Comment by ramy150** [comment]
criu -- version
version: 2.9

**Comment by xemul** [comment]
OK. It looks like some problem with --external options as passed by LXC. The error is here:
    (00.085534)      1: mnt:        Mounting mqueue @./dev/mqueue (0)
    (00.085538)      1: mnt:        Bind mqueue to ./dev/mqueue
    (00.085555)      1: Error (criu/mount.c:1978): mnt: Can't mount at ./dev/mqueue: No such file or directory

which means the mount("mqueue", "/dev/mqueue", MS_BIND) failed with ENOENT. Of course it did :) there's no such path as just "mqueue".

The mountpoint itself is marked with external as seen from this log string

    Will mount 381 from mqueue (E)

and the entry itself is

    type mqueue source mqueue mnt_id 383 s_dev 0x11 / @ ./dev/mqueue flags 0x280000 options

@tych0 , how can we get the options with which LXC tools call CRIU?

**Comment by tych0** [comment]
On Mon, Feb 13, 2017 at 11:40:35AM -0800, Pavel Emelyanov wrote:
> OK. It looks like some problem with --external options as passed by LXC. The error is here:
>     (00.085534)      1: mnt:        Mounting mqueue @./dev/mqueue (0)
>     (00.085538)      1: mnt:        Bind mqueue to ./dev/mqueue
>     (00.085555)      1: Error (criu/mount.c:1978): mnt: Can't mount at ./dev/mqueue: No such file or directory
> 
> which means the mount("mqueue", "/dev/mqueue", MS_BIND) failed with ENOENT. Of course it did :) there's no such path as just "mqueue".
> 
> The mountpoint itself is marked with external as seen from this log string
> 
>     Will mount 381 from mqueue (E)
> 
> and the entry itself is
> 
>     type mqueue source mqueue mnt_id 383 s_dev 0x11 / @ ./dev/mqueue flags 0x280000 options
> 
> @tych0 , how can we get the options with which LXC tools call CRIU?

They're in the log,

 lxc-checkpoint 20160213183111.417 INFO     lxc_criu - criu.c:exec_criu:572 - execing: /usr/sbin/criu restore --tcp-established --file-locks --link-remap --manage-cgroups=full --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /var/lib/lxc/u1/checkpoint -o /var/lib/lxc/u1/checkpoint/restore.log --cgroup-root name=systemd:/lxc/u1 --cgroup-root net_cls,net_prio:/lxc/u1 --cgroup-root freezer:/lxc/u1 --cgroup-root blkio:/lxc/u1 --cgroup-root hugetlb:/lxc/u1 --cgroup-root cpu,cpuacct:/lxc/u1 --cgroup-root cpuset:/lxc/u1 --cgroup-root pids:/lxc/u1 --cgroup-root devices:/lxc/u1 --cgroup-root memory:/lxc/u1 --cgroup-root perf_event:/lxc/u1 -vvvvvv --ext-mount-map sys/fs/fuse/connections:/sys/fs/fuse/connections --ext-mount-map sys/kernel/debug:/sys/kernel/debug --ext-mount-map sys/kernel/security:/sys/kernel/security --ext-mount-map sys/fs/pstore:/sys/fs/pstore --ext-mount-map dev/mqueue:mqueue --root /usr/lib/x86_64-linux-gnu/lxc --restore-detached --restore-sibling --ext-mount-map console: --external veth[eth0]:veth3KRTND@lxcbr0

Looks like it passed an mqueue mount, but somehow it didn't get detected as external?

Cheers,

Tycho

**Comment by xemul** [comment]
It has :)

    --ext-mount-map dev/mqueue:mqueue

this means, that the mountpoint marked as "dev/mqueue" in the image should be bind-mount-ed from "mqueue" path from host :)

**Comment by tych0** [comment]
Right, good point. That should all be generated based on the paths in the container's config. @ramy150 can you post the config on both the checkpoint and restoring host?

**Comment by ramy150** [comment]
it's the same in the two host 
[cnfig.txt](https://github.com/xemul/criu/files/777947/cnfig.txt)
[cnfig2.txt](https://github.com/xemul/criu/files/777946/cnfig2.txt)

**Comment by tych0** [comment]
Ah, from `/usr/share/lxc/config/ubuntu.common.conf`:

```
lxc.mount.entry = mqueue dev/mqueue mqueue rw,relatime,create=dir,optional 0 0
```

I think this is a bug in liblxc: it shouldn't specify this as an external mount because it isn't one. Can you test if this patch works for you? https://github.com/tych0/lxc/commit/19d2422b99df72e6fc8f794c630687cb2740a20b

**Comment by ramy150** [comment]
great @tych0  tested and the patch works thanks a lot (y)
commands how apply the patch in order to test


[Commands.txt](https://github.com/xemul/criu/files/783380/Commands.txt)
