### ISSUE TITLE
PID mismatch on fork() (race with another fork-er) in Travis runs

### ISSUE THREAD

**Issue by kolyshkin** [xemul/criu#282]
From https://travis-ci.org/criupatchwork/criu/jobs/200233261

=================== Run zdtm/transition/socket_loop00 in h ====================
Start test
./socket_loop00 --pidfile=socket_loop00.pid --outfile=socket_loop00.out
Run criu dump
Run criu restore
=[log]=> dump/zdtm/transition/socket_loop00/26/1/restore.log
------------------------ grep Error ------------------------
(00.005360) Error (criu/cr-restore.c:1360): Pid 27 do not match expected 26
(00.005424) Error (criu/cr-restore.c:2015): Restoring FAILED.
------------------------ ERROR OVER ------------------------
########### Test zdtm/transition/socket_loop00 FAIL at CRIU restore ############

NOTE that the next Travis job failed at the very beginning because of ENOSPACE, so it might be related (see https://travis-ci.org/criupatchwork/criu/jobs/200233263).

**Comment by kolyshkin** [comment]
I think I had a few more cases like this during this time. The last one is today:

===================== Run zdtm/static/unlink_fstat03 in h ======================
Start test
./unlink_fstat03 --pidfile=unlink_fstat03.pid --outfile=unlink_fstat03.out --filename=unlink_fstat03.test
Run criu dump
Forcing 6 fault
Run criu restore
Forcing 6 fault
=[log]=> dump/zdtm/static/unlink_fstat03/33/1/restore.log
------------------------ grep Error ------------------------
(00.020144) Error (criu/cr-restore.c:2059): Restoring FAILED.
------------------------ ERROR OVER ------------------------
Run criu restore
=[log]=> dump/zdtm/static/unlink_fstat03/33/1/restore.log
------------------------ grep Error ------------------------
(00.006460) Error (criu/cr-restore.c:1353): Pid 35 do not match expected 33
(00.006520) Error (criu/cr-restore.c:2059): Restoring FAILED.
------------------------ ERROR OVER ------------------------
############# Test zdtm/static/unlink_fstat03 FAIL at CRIU restore #############

See https://travis-ci.org/kolyshkin/criu/jobs/211919542

**Comment by kolyshkin** [comment]
=== Run 1/1 ================ zdtm/static/unlink_fstat03

===================== Run zdtm/static/unlink_fstat03 in h ======================
make[2]: Nothing to be done for `default'.
Start test
make[2]: Nothing to be done for `default'.
./unlink_fstat03 --pidfile=unlink_fstat03.pid --outfile=unlink_fstat03.out --filename=unlink_fstat03.test
Run criu dump
Forcing 6 fault
Run criu restore
Forcing 6 fault
=[log]=> dump/zdtm/static/unlink_fstat03/24/1/restore.log
------------------------ grep Error ------------------------
(00.028976) Error (criu/cr-restore.c:2059): Restoring FAILED.
------------------------ ERROR OVER ------------------------
Run criu restore
=[log]=> dump/zdtm/static/unlink_fstat03/24/1/restore.log
------------------------ grep Error ------------------------
(00.005903) Error (criu/cr-restore.c:1353): Pid 26 do not match expected 24
(00.005961) Error (criu/cr-restore.c:2059): Restoring FAILED.
------------------------ ERROR OVER ------------------------
############# Test zdtm/static/unlink_fstat03 FAIL at CRIU restore #############

I'll add some debug diagnostics and try to re-reproduce the issue again

**Comment by avagin** [comment]
Here are two reasons why we can see this issue.

This issue is reproduced only for cases when a test is running in a host pidns.

1. So it may be a race between criu restore and the init process. The init process has to collect zombies. criu restore restores processes with specified pids. The race is that criu restore can be executed when zombies have not been collected yet.
https://travis-ci.org/criupatchwork/criu/jobs/200233261

2. The second case is more probable. We call criu restore with the --fault option and then we call it without this option. The first criu process modifies ns_last_pid, so the second process can get a PID of one of the restored processes.

**Comment by xemul** [comment]
a7281b11fd6e31d654e2ace387fe6677dff86fa6
