### ISSUE TITLE
Live migration of a jboss/wildfly container - criu dump failed

### ISSUE THREAD

**Issue by rjah-tuc** [xemul/criu#283]
Hello,

I've tried to live migrate a wildfly-container to another host [like described here](https://circleci.com/blog/checkpoint-and-restore-docker-container-with-criu/). The example with the np container works well. When I replace the example with a simple jboss/wildfly container, I just received this error when criu tries to restore the container on the other host :
`Error response from daemon: Cannot restore container <CONTAINER-ID>: criu failed: type NOTIFY errno 0
Error: failed to restore one or more containers`

Because I didn't found a solution to this error, I've compiled the linux kernel like described on the [criu website](https://criu.org/Installation) and [here](http://kimh.github.io/blog/en/criu/experiment-to-suspend-and-resume-docker-container-with-criu/).

After that  `sudo criu check` prints:
`Warn  (criu/libnetlink.c:54): ERROR -2 reported by netlink`
`Warn  (criu/libnetlink.c:54): ERROR -2 reported by netlink`
`Warn  (criu/sockets.c:711): The current kernel doesn't support packet_diag`
`Warn  (criu/libnetlink.c:54): ERROR -2 reported by netlink`
`Warn  (criu/sockets.c:721): The current kernel doesn't support netlink_diag`
`Info  prctl: PR_SET_MM_MAP_SIZE is not supported`
`Looks good.`

`criu --version`
`Version: 2.11`

`docker --version`
`Docker version 1.6.2, build 7c8fca2`

Checkpoint/Restore for an example shell script [example](http://kimh.github.io/blog/en/criu/experiment-to-suspend-and-resume-docker-container-with-criu/) worked very well. But when I want to checkpoint a container `docker run -d --name looper busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'` with `criu dump -t $PID --images-dir /tmp/looper`
I receive this output
`Error (criu/sockets.c:132): Diag module missing (-2)`
`Error (criu/sockets.c:132): Diag module missing (-2)`
`Error (criu/sockets.c:132): Diag module missing (-2)`
`Error (criu/mount.c:701): mnt: 87:./etc/hosts doesn't have a proper root mount`
`Error (criu/cr-dump.c:1641): Dumping FAILED.`

I can't find some solutions with these errors. Is there any known solution to live migrate a wildfly-container?

Thanks in advance

**Comment by xemul** [comment]
So, I see two issues here :) First is jboss restore error and busybox dump error. Let's resolve them individually.

1. Jboss restore error. To go on with this we need to look at restore.log file. Would you attach one? (Cc @avagin , Andrey, where does Docker keep dump and restore log files?)

2. busybox dump. This is much simpler :) The thing is that when trying to dump a Docker container CRIU needs a lot of additional information about so called "external resources", which it typically receives from Docker daemon. In your example you try to dump container "by hands" and do not specify all those options :) So in order to proceed with dumping you should either use docker CLI or pass all the needed options yourself.

In particular the error you see states that the /etc/hosts file is a bind-mount and its source is somewhere on the host. You should use the --external mnt... option for that (https://criu.org/External_bind_mounts)

**Comment by xemul** [comment]
An update :) Logs are kept in directories that looks like /var/lib/docker/containers/<ID>/checkpoints/chp_<NR>/criu.work/dump.log

**Comment by rjah-tuc** [comment]
@xemul Thanks for reply.

1. I've looked for a log file, but there isn't any in suggested location 
![no_log](https://cloud.githubusercontent.com/assets/5921915/23059236/cc9ed214-f4f8-11e6-94c5-00e78d773cf9.JPG)

2. I thought something like this. I try to resolve it.

**Comment by xemul** [comment]
@rjah-tuc , hm... No checkpoints directory indeed :( Cc @boucher for help.

**Comment by rjah-tuc** [comment]
I'm using vagrant boxes for my test system. Can you advise a certain box to use? I'm using "kimh/criu" at the moment with preconfigured criu and docker.

**Comment by xemul** [comment]
It's not about box, it's about finding out where log files from criu are :) Usually they are in /var/lib/docker/... , but maybe in your case it's some different path.

**Comment by boucher** [comment]
@xemul @rjah-tuc The logs will only be kept in docker if you use docker to do the checkpointing, but in your comment above you said you called criu manually (```criu dump -t $PID --images-dir /tmp/looper```). You should instead call ```docker checkpoint create```.

**Comment by rjah-tuc** [comment]
Now I found dump.log on vagrant1 when I'm using  in `docker checkpoint create` `/run/docker/execdriver/native/07ca8bfd30c09811a1bfa9ea0fdb9d45f8c44ba5b46db86f6d286189aa18e275/criu.work/dump.log`

But there is no container folder under same path on vagrant 2 (where to restore).

The whole configuration is running on vagrant machines. Is it might possible that this folder and maybe more are missed on restoring? But the simple loop example from criu website works very well.

**Comment by rjah-tuc** [comment]
I added a copy sequence to duplicate missing folder from vagrant 1 to vagrant 2 before restoring the container. Here is the dump.log 
[dump.log.txt](https://github.com/xemul/criu/files/783297/dump.log.txt)

A restore.log is still missing ...
Error stays 
![restore-error](https://cloud.githubusercontent.com/assets/5921915/23067060/dc4ba3f2-f51d-11e6-9b57-b72956af9ff8.JPG)

**Comment by boucher** [comment]
Could you provide the command you were running?

**Comment by rjah-tuc** [comment]
@boucher 
On vagrant 1`docker run -d --name=mywildfly jboss/wildfly`

Then I'm running a migrate script
`... copy files ...`
then fix criu bug
`vagrant ssh -- 'docker run --name=foo -d $image tail -f /dev/null && docker rm -f foo'`
then restore
`vagrant ssh -- 'docker rm -f $container >/dev/null 2>&1; docker restore --force=true --image-dir=/tmp/docker/$container \'docker create --name=$container $image\''`

with `$container = mywildfly` and `$image = jboss/wildfly`

And the script works fine with the [looper container](https://criu.org/Simple_loop)

**Comment by boucher** [comment]
Could you try using Docker 1.13, which no longer uses the ```docker
restore``` command? It may not make a difference but its worth a shot.

**Comment by xemul** [comment]
@rjah-tuc , do you have any news on this?

**Comment by rjah-tuc** [comment]
@xemul Sorry, have to handle some other actions these days. I'll write a feedback soon

**Comment by xemul** [comment]
OK, let's keep this closed for a while. If the issue is still there even with newer Docker -- feel free to re-open it.
