### ISSUE TITLE
criu  uninstall failed

### ISSUE THREAD

**Issue by cheng362432** [xemul/criu#285]
i want to uninstall the criu, after run the command 'sudo make uninstall',then report error,my system is ubuntu14.04, the criu version is 2.9.
:~/criu$ sudo make uninstall 
make[1]: Entering directory `/home/sdnpc2/criu/Documentation'
 UNINSTALL crit.1
 UNINSTALL criu.8
make[1]: Leaving directory `/home/sdnpc2/criu/Documentation'
make[1]: Entering directory `/home/sdnpc2/criu/lib'
 UNINSTALL libcriu.so
 UNINSTALL pkgconfig/criu.pc
 UNINSTALL crit
make[1]: Leaving directory `/home/sdnpc2/criu/lib'
make[1]: Entering directory `/home/sdnpc2/criu/criu'
make[1]: Circular /home/sdnpc2/criu/criu/include/config.h <- pie dependency dropped.
make[2]: Entering directory `/home/sdnpc2/criu/criu'
/home/sdnpc2/criu/scripts/nmk/scripts/build.mk:76: criu/pie/piegen/Makefile: Not a directory
make[2]: *** No rule to make target `criu/pie/piegen/Makefile'.  Stop.
make[2]: Leaving directory `/home/sdnpc2/criu/criu'
make[1]: *** [criu/pie/piegen/built-in.o] Error 2
make[1]: Leaving directory `/home/sdnpc2/criu/criu'
make: *** [uninstall] Error 2

how can i fix it?

**Comment by xemul** [comment]
Cc @cyrillos and @0x7f454c46

**Comment by xemul** [comment]
and @kolyshkin

**Comment by kolyshkin** [comment]
I'm on it.

Need to
1. Fix it in 2.11 (@xemul does it make sense?)
2. Fix it in criu-dev (in progress)
3. Add a test!

**Comment by xemul** [comment]
@kolyshkin in 2.11 ? ... I don't think it's needed. From my perspective make uninstall is a feature for developers rather that for those who build packages.

**Comment by kolyshkin** [comment]
This particular bug was fixed in criu-dev, but there is another one that needed a fix:
https://github.com/xemul/criu/commit/9af7a3a2ba3130118f4b22cdc5c961aeee54c09a

Finally, I'm going to add a test to both criu-dev and master to make sure we know when we break it.

**Comment by xemul** [comment]
e3f0c52596ac569e86424664a398284aa469c88d
