### ISSUE TITLE
couldn't dump a docker container with 2GB shm size

### ISSUE THREAD

**Issue by thtanaka** [xemul/criu#287]
I have the following container with shared memory created
$ docker exec testshm ipcs -m

------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status
0xd6fcbcea 0          root       644        2147483648 0

How to reproduce:
$ docker run -d --security-opt seccomp:unconfined --name testshm --shm-size="4g" centos /bin/sh -c 'ipcmk -M 2147483648; while true; do sleep 1; done'

Result:
$ docker checkpoint create --checkpoint-dir /tmp/criu testshm checkpoint
Error response from daemon: Cannot checkpoint container testshm: rpc error: code = 2 desc = exit status 1: "criu failed: type NOTIFY errno 0\nlog file: /tmp/criu/checkpoint/criu.work/dump.log\n"

Criu dump log:
https://gist.github.com/thtanaka/6eb5e1456c4186d0d30a64d277394bf7

Criu version:
$ criu --version
Version: 2.11.1
GitID: v2.11.1

It looks like the size that is passed into bwrite() is too large (-ve value).

Is this a known limitation, if so is there anywhere I should look to fix this problem ?

**Comment by xemul** [comment]
(00.284220) bfd: bwrite of size = 4
    (00.284247) rounding up: 2147483648
    (00.284248) bfd: bwrite of size = -2147483648
    (00.284262) Error (criu/image.c:504): Can't write img file: Bad address
    (00.284267) Error (criu/ipc_ns.c:358): Failed to write IPC shared memory data
    (00.284269) Error (criu/ipc_ns.c:497): Failed to write IPC namespace data

You've added some logging to criu, haven't you? :)

As far as the issue itself is concerned -- the reason is that SysV shmem segments are dumped via bfd engine which wasn't supposed to accept 8G writes :) and the problem is here:

    int bwrite(struct bfd *bfd, const void *buf, int size)

the size argument is int and in your case overflows to unsigned value. This is easy to fix, I can cook the patch shortly, but dumping 8G to disk would take time. We'll need to do more work to dump huge segments properly.

**Comment by xemul** [comment]
Here's the fix https://github.com/xemul/criu/commit/8b43b0959420e0e57e74464274975a241e436d6a , would you try one? Optionally, you can fetch the master-sysvshm-fixes branch from this repo, it's 2.11.1 with the fix applied on top.

Also, keep in mind, that this fix would just write the whole shmem segment on disk, this will take time.

**Comment by thtanaka** [comment]
Thanks a lot Pavel for your quick turnaround !  I tested the dump part and it works fine now.
We might need the corresponding read part ? https://gist.github.com/thtanaka/04e5312efa3ff18f10afe09805432192

If there is anything that you might need help in the re-write part, please feel free to let me know.

**Comment by xemul** [comment]
Ah :) Of course! The read part is also important! I will include one in the patch for commit, thank you.
As far as the help is concerned -- the greatest help would be if someone :) contributes the code that does so. If no, then I'll likely ask you to check the fix once I manage to make it myself.
