### ISSUE TITLE
arm/arm64: mremap() for vdso

### ISSUE THREAD

**Issue by hubb0r** [xemul/criu#288]
I have trouble with the following very simple program on AARCH64:

    #include <stdio.h>
    #include <stdlib.h>
    #include <unistd.h>
    #include <signal.h>
    
    unsigned int do_print = 0;
    
    void sig_handler(int signo)
    {
        if(signo == SIGUSR1)
        {
            do_print = 1;
        }
    }
    
    int main(int argc, char *argv[])
    {
        if(signal(SIGUSR1, sig_handler) == SIG_ERR)
        {
            fprintf(stderr, "Couldn't register signal handler!\n");
            exit(1);
        }
        
        while(1)
        {
            if(do_print)
            {
                printf("Test\n");
                fflush(stdout);
                do_print = 0;
            }
            usleep(1000);
        }
    
        return 0;
    }

It is compiled just ordinarily (with -O2 though).

When I start it as follows:

    setsid ./criu_sig_dump < /dev/null > criu_sig_dump_stdout.txt 2> cri_sig_dump_stderr.log

and then do

    kill -USR1 3118

it works just fine and gives me the expected output in criu_sig_dump_stdout.txt.

Now when I checkpoint it like that:

    criu dump --images-dir img --leave-running -t 3118

And then kill it like that

    kill 3118

and then want to restore it

    criu restore --images-dir img_${CRIUPID}_${IMGCOUNT} --prev-images-dir ../img_${CRIUPID}_${LAST_IMGCOUNT} --restore-detached -vvv -o restore.log

it's back running. BUT: When I send another signal with

    kill -USR1 3118

the process dies, with nasty dmesg output:

dmesg
    [ 1542.620423] criu_sig_dump[3118]: unhandled level 1 translation fault (11) at 0x7f7db816c0, esr 0x82000005
    [ 1542.620430] pgd = ffffffc02853e000
    [ 1542.623786] [7f7db816c0] *pgd=0000000000000000
    [ 1542.628007] , *pud=0000000000000000
    [ 1542.628012]
    [ 1542.628013]
    [ 1542.628021] CPU: 1 PID: 3118 Comm: criu_sig_dump Not tainted 4.9.0-xilinx #10
    [ 1542.628022] Hardware name: xlnx,zynqmp (DT)
    [ 1542.628026] task: ffffffc0350e8580 task.stack: ffffffc028674000
    [ 1542.628030] PC is at 0x7f7db816c0
    [ 1542.628033] LR is at 0x7f7db816c0
    [ 1542.628036] pc : [<0000007f7db816c0>] lr : [<0000007f7db816c0>] pstate: 60000000
    [ 1542.628037] sp : 0000007fcccb6980
    [ 1542.628039] x29: 0000007fcccb7bd0 x28: 0000000000000000
    [ 1542.628044] x27: 0000000000000000 x26: 0000000000000000
    [ 1542.628048] x25: 0000000000000000 x24: 0000000000000000
    [ 1542.628052] x23: 0000000000000000 x22: 0000000000000000
    [ 1542.628056] x21: 0000000000410000 x20: 00000000004008f0
    [ 1542.628060] x19: 0000000000410b7c x18: 0000000000000001
    [ 1542.628064] x17: 0000007f8bb336e0 x16: 0000000000000000
    [ 1542.628068] x15: 0000000000000000 x14: 0000000000000055
    [ 1542.628072] x13: 0000000000000000 x12: 00000000000003f3
    [ 1542.628076] x11: 0000000000000055 x10: 0101010101010101
    [ 1542.628080] x9 : 0000007f8bbb3a00 x8 : 0000000000000065
    [ 1542.628084] x7 : 7f7f7f7f7f7f7f7f x6 : 000000001c7c6014
    [ 1542.628088] x5 : 00000000000003e8 x4 : 00000000000003e8
    [ 1542.628092] x3 : 00000000000003e8 x2 : 00000000000f4240
    [ 1542.628096] x1 : 0000000000000001 x0 : 0000000000410000
    [ 1542.628099]

Any ideas? ;-)

Thanks!

**Comment by xemul** [comment]
This looks like a kernel crash :)
Also, your restore command manipulates the --prev-images-dir option, how did you generate one?

Cc @avagin and @0x7f454c46

**Comment by hubb0r** [comment]
I'm on kernel 4.9.0.

And I didn't use any previous images, I guess I just copied the wrong command from my script.

So I did:

criu restore --images-dir img_${CRIUPID}_${IMGCOUNT} --restore-detached -vvv -o restore.log

with IMCOUNT=0 (sorry again, I copied the commands from my script).

Thanks for your help guys!

**Comment by 0x7f454c46** [comment]
Hi @hubb0r, ZDTM tests are broken for a while on arm/aarch64 - IIRC, signals is one of broken test.
I did some patches to fix this and other tests on arm some time ago - not sure if they got into master or if I've sent them at all.
I'll try to find the time to fix it on this week, but I've got quite a lot of work to do. If you want, you can try it yourself - the bug doesn't look very hard to debug and you can learn CRIU's internals if you're interested.
Anyway, the first step to do - check if this is dump or restore error, by inspecting images with crit tool - check that image has established handler for SIGUSR1.

**Comment by xemul** [comment]
@hubb0r , the inspection is done with the [crit tool](https://criu.org/CRIT). And signal handlers all sit in the sigacts-$pid.img (image file)[https://criu.org/Images]

**Comment by hubb0r** [comment]
Unfortunately, I get

Traceback (most recent call last):
  File "/usr/bin/crit", line 2, in <module>
    import argparse
ImportError: No module named argparse

when I run crit. Must be some dependency problem, I will try to iron this out.

The dump is attached in the meantime, if you need it.
[img.tar.gz](https://github.com/xemul/criu/files/821494/img.tar.gz)

**Comment by hubb0r** [comment]
@0x7f454c46 thank you!!!

**Comment by 0x7f454c46** [comment]
Ok, here are some thoughts:
- arm64 doesn't have `__ARCH_HAS_SA_RESTORER`, which means that `struct rt_sigaction_t` defined in criu/arch/aarch64/include/asm/types.h is not completely sane, which still should work as CRIU will save `sa_mask` in `sa_restorer` field in images and pass it back to sigaction on restore. Needs to be fixed, anyway.
- `SA_RESTORER` flag has in kernel other value:
`arch/arm64/include/uapi/asm/signal.h:#define SA_RESTORER        0x04000000`
- The last and I guess the problem of this bug is that `mremap()` for vdso vma doesn't work on arm64 yet. There were patches to fix it but yet were not accepted. So, IIRC, on vdso vma lies sigreturn trampoline where the kernel jumps after `do_signal()` processing. Which means, it will try to jump at the address where CRIU's vdso has lied previously (before remapping).
So, here are possible variants to solve this:
1. disable `VDSO=y` for arm64 in CRIU and disable `CONFIG_VDSO` in kernel (quite radical but will work if the temporary workaround needed).
2. leave CRIU's vdso on the same place, insert jump trampolines from original vdso vma. That will not be always reliable as vdso/vvar vmas can lie on addresses which were used in original application.
3. add `mremap()` for vdso on arm64 support in kernel. That can be done easily in about ~10 lines or so on the top of still-in-development patches set "[RFC PATCH v3 00/11] arm64: Add a compat vDSO" (or on the top of ~two patches from that set).

**Comment by 0x7f454c46** [comment]
And a quick test with your test case shows that my conjecture should be true:
1. Starting criu restore and look for vdso address:
> [root@localhost criu]# ./criu/criu restore -vvvv --shell-job
> (00.000261) Version: 2.10 (gitid v2.0-1203-g65214e4)
> (00.145529) Pagemap is fully functional
> (00.148459) Found task size of 8000000000
> ^Z
> [root@localhost criu]# ps
>   PID TTY          TIME CMD
>  2413 pts/1    00:00:10 bash
> 12154 pts/1    00:00:00 criu
> 12157 pts/1    00:00:00 sh
> 12158 pts/1    00:00:00 ps
> [root@localhost criu]# cat /proc/12154/maps | grep vdso
> 7f8c459000-7f8c45a000 r-xp 00000000 00:00 0                              [vdso]
2. Continue restore, send SIGUSR1:
> [root@localhost criu]# fg
> ./criu/criu restore -vvvv --shell-job
...
> (26.245031) 12147 was trapped
> (26.245324) 12147 is going to execute the syscall 139
> (26.246189) 12147 was stopped
> (26.250849) Parasite syscall_ip at (nil)
> (26.252807) 12147 was trapped
> (26.253117) 12147 is going to execute the syscall 215
> (26.253727) 12147 was stopped
> (26.254096) Running pre-resume scripts
> (26.315323) Writing stats
> (26.339100) Running post-resume scripts
> [root@localhost criu]# kill -SIGUSR1 12147
> [root@localhost criu]# dmesg | tail -n30
> [66352.453576] cgroup: new mount options do not match the existing superblock, will be ignored
> [66362.162089] cgroup: new mount options do not match the existing superblock, will be ignored
> [66417.691158] cgroup: new mount options do not match the existing superblock, will be ignored
> [66457.464366] criu-signal[12147]: unhandled level 1 translation fault (11) at 0x7f8c459510, esr 0x82000005
> [66457.464639] pgd = ffffffc03b8db000
> [66457.464773] [7f8c459510] *pgd=0000000000000000, *pud=0000000000000000
> 
> [66457.469728] CPU: 0 PID: 12147 Comm: criu-signal Not tainted 4.4.47+ #34
> [66457.469879] Hardware name: QEMU QEMU Virtual Machine, BIOS 0.0.0 02/06/2015
> [66457.470069] task: ffffffc01fa75b00 ti: ffffffc03b8c8000 task.ti: ffffffc03b8c8000
> [66457.470285] PC is at 0x7f8c459510
> [66457.470371] LR is at 0x7f8c459510
> [66457.470462] pc : [<0000007f8c459510>] lr : [<0000007f8c459510>] pstate: 60000000
> [66457.470627] sp : 0000007ff60a94f0
> [66457.470722] x29: 0000007ff60aa740 x28: 0000000000000000 
> [66457.470909] x27: 0000000000000000 x26: 0000000000000000 
> [66457.471059] x25: 0000000000000000 x24: 0000000000000000 
> [66457.471254] x23: 0000000000000000 x22: 0000000000000000 
> [66457.471471] x21: 0000000000400710 x20: 0000000000000000 
> [66457.471624] x19: 0000007f7cfed3a8 x18: 0000000000000010 
> [66457.471777] x17: 0000007f7cf37620 x16: 0000000000000000 
> [66457.471928] x15: 0000000000000001 x14: 0000000000000006 
> [66457.472081] x13: 0000000000000000 x12: 0000000000000000 
> [66457.472234] x11: 0000000000000003 x10: 0101010101010101 
> [66457.472404] x9 : 0000000000000000 x8 : 0000000000000065 
> [66457.472560] x7 : 0000000000000000 x6 : 0000000000000000 
> [66457.472719] x5 : 00000000000003e8 x4 : 00000000000003e8 
> [66457.472867] x3 : 00000000000003e8 x2 : 00000000000f4240 
> [66457.473013] x1 : 0000000000000001 x0 : 0000000000410e9c

Here we go, CRIU's vdso is `[7f8c459000-7f8c45a000]` (1), segfault is at `0x7f8c459510`, which should be sigreturn enter.

**Comment by 0x7f454c46** [comment]
There is a patch for arm32 on lkml: https://lkml.org/lkml/2017/4/14/139 (I'll update [Upstream patches](https://criu.org/Upstream_kernel_commits))
Although, we can just enable VDSO=y for arm32, as mremap()ing of vDSO blob doesn't do any harm on arm32 - the different story for arm64.

**Comment by xemul** [comment]
AFAIU the patch is merged (https://patchwork.kernel.org/patch/9681273/), so we can close the issue. Can we?

**Comment by 0x7f454c46** [comment]
Not yet. And we need to do the same for arm64 - the patch adds support only for arm32.

**Comment by 0x7f454c46** [comment]
[[PATCH] arm64/vdso: Support mremap() for vDSO](https://lkml.org/lkml/2017/7/26/638)

**Comment by 0x7f454c46** [comment]
Have run the test from the description - it catches SIGUSR1 just fine after C/R with the mentioned kernel patch.

**Comment by hubb0r** [comment]
Thanks a lot guys! That's very appreciated!

**Comment by xemul** [comment]
So, is the issue resolved? :)

**Comment by 0x7f454c46** [comment]
Yes, when the patch will got into ms.

**Comment by 0x7f454c46** [comment]
In linux-next currently: [739586951b8a](https://git.kernel.org/pub/scm/linux/kernel/git/next/linux-next.git/commit/?id=739586951b8abe381a98797a5e27a0a9336333d6)

**Comment by 0x7f454c46** [comment]
Close this, please - it's merged into 4.14-rc1.

**Comment by hubb0r** [comment]
Thank you!!!
