### ISSUE TITLE
CRIU fails restore with signal 19

### ISSUE THREAD

**Issue by njlow1202** [xemul/criu#297]
Hello,

I'm having trouble restoring a docker container after checkpointing. 

The Dockerfile runs this:

```
FROM ubuntu:latest

# Omitting a bunch of package installations

EXPOSE 10002
CMD xpra start :9999 --start-child='python game.py' --bind-tcp=0.0.0.0:10002; tail -f /dev/null
```
After building the image we run a container, named `game`, like this:

```
docker run -d -p 10002:10002 --name=game --security-opt seccomp:unconfined pygame
```

Since I am using xpra for the virtual x-server I am able to connect and see the game running when I do (on the host):

```
xpra attach tcp:localhost:10002
```
I disconnect from the xpra server and then attempt to checkpoint like this:

```
docker checkpoint create --checkpoint-dir=/tmp game checkpoint
```
I then create a second container named `game-clone` like this:

```
docker create --name=game-clone --security-opt seccomp:unconfined pygame
```
And attempt to start it from the checkpoint like this:

```
docker start --checkpoint-dir=/tmp --checkpoint=checkpoint game-clone
```
At this point it fails. The last lines of the restore log look like this (the rest of the log is attached to this post):

```
(20.442658)pie: 1: Restoring scheduler params 0.0.0
(20.442663)pie: 10: Restoring scheduler params 0.0.0
(20.442664)pie: 1: 1: Restore
dgithu(20.442667)pie: 10: 10: Restored
(20.444468)pie: 1: Task 12  exited, status= 1
(20.444522) Error (criu/cr-restore.c:1012): 20787 killed by signal 19: Stopped (signal)
(20.444537) Error (criu/cr-restore.c:1012): 20787 killed by signal 19: Stopped (signal)
(20.484910) mnt: Switching to new ns to clean ghosts
(20.504957) Error (criu/cr-restore.c:1897): Restoring FAILED.
(20.504980)pie: 10: restoring seccomp mode 0 for 10
(20.505000)pie: 10: restoring lsm profile changeprofile docker-default
```

I would like to restore the container and then attach again with: 
```
xpra attach tcp:localhost:10002
```

I am attempting to restore on the same host machine. The end goal is to restore on a different host while preserving the tcp connection. 

Any ideas as to why there is a signal 19 stopping the restore?

[restoreLog.txt](https://github.com/xemul/criu/files/857060/restoreLog.txt)

**Comment by xemul** [comment]
That's the real reason for failures:

    (20.441864)     62: sk unix: Opening pair slave (id 0x108 ino 0x607312 peer 0x607ed8) on 3
    (20.441870)     12: Error (criu/files-reg.c:1565): Can't open file home/developer/.xpra/Xorg.:9999.log on restore: No such file or directory
    (20.441872)     10:             Create fd for 3
    (20.441871)     11: Found fd 0 (id pipe:[6324691]) in inherit fd list (caller inherit_fd_resolve_clash)
    (20.441876)     12: Error (criu/files-reg.c:1504): Can't open file home/developer/.xpra/Xorg.:9999.log: No such file or directory
    (20.441879)     62:             Create fd for 4
    (20.441880)     10: fsnotify:   Restore 0x1 wd for 00000000
    (20.441881)     62: sk unix: Opening pair slave (id 0x10a ino 0x607313 peer 0x607ed9) on 5
    (20.441882)     11: Inherit fd 0 moved to 4 to resolve clash
    (20.441886)     10: fsnotify:           Restore with path hint 158:proc/sched_debug
    (20.441888)     11:             Create fd for 0
    (20.441900)     11: Error (criu/files-reg.c:1565): Can't open file home/developer/.xpra/:9999.log on restore: No such file or directory
    (20.441902)     11: Error (criu/files-reg.c:1504): Can't open file home/developer/.xpra/:9999.log: No such file or directory
    (20.441905)     10: fsnotify:           Restore inotify watch for 0x00003b:0x00000000000006 (via /proc/self/fd/5 -> /proc/sched_debug)
    (20.441911)     62:             Create fd for 7

you should restore your container on the very same root where you dumped it.

**Comment by xaviermerino** [comment]
Hello again,

In order to preserve the `/home/developer/.xpra/Xorg.:9999.log` on restore @njlow1202 and I decided to **mount a volume** in the container. We thought that might fix the problem since then we would have the same files available on container restore. We are not sure if that's what you meant by restoring the container on the very same root where it was dumped. 

We now **run** the container like this:

```
docker run -p 10002:10002 -v $(pwd)/developer:/home/developer -e USERID=$UID\
 --name=game --security-opt seccomp:unconfined pygame
```

We attach to the xpra server by running this on the host:

```
xpra attach tcp:localhost:10002
```

We are able to **checkpoint** successfully using:

```
docker checkpoint create --checkpoint-dir=$(pwd)/criuCheckpoints game checkpoint
```

We then **create** a new container named `game-clone` with the proper port bindings and a reference to the shared volume (which has the file `/home/developer/.xpra/Xorg.:9999.log`). 

```
docker create -p 10002:10002 -v $(pwd)/developer:/home/developer -e USERID=$UID\
--name=game-clone --security-opt seccomp:unconfined pygame
```
We then **start** the new container from the checkpoint by doing:

```
docker start --checkpoint-dir=$(pwd)/criuCheckpoints --checkpoint=checkpoint game-clone
```

At this point the restoration fails. 

```
30.404536) Error (criu/cr-restore.c:1012): 11042 killed by signal 19: Stopped (signal)
(30.404550) Error (criu/cr-restore.c:1012): 11042 killed by signal 19: Stopped (signal)
(30.452855) mnt: Switching to new ns to clean ghosts
(30.472915) Error (criu/cr-restore.c:1897): Restoring FAILED.
```

Looking for errors in the restore log we found (on line 6856):

```
(30.402736)     12: Error (criu/sk-unix.c:1042): sk unix: Can't bind socket: No such file or directory
```

We are not sure what is causing this. Is there a better way of preserving the files? 

Thanks for your help. :)

[restore.txt](https://github.com/xemul/criu/files/859389/restore.txt)

**Comment by xemul** [comment]
No I don't mean this. You cannot create container FS from scratch and restore on it. In your case some socket file was created by container software _after_ it was started and re-creating the container doesn't bring it back. You should take the _very_ _root_ you dumped it on.

**Comment by njlow1202** [comment]
Thank you for responding. Could you please elaborate about the "very root"? We must not understand what this **root** is referring to. Because we are spawning a new container and trying to start this new container from a checkpoint of the old. Is there any documentation or example you could point us to that illustrates this restoring on the "very same root"? 

Our ultimate goal is to migrate a container from one host to another. Our current idea has been to start a container on one host. Then checkpoint the container and migrate the files to the other host. Finally, we create a new container and start it from the checkpoint on the new host. In essence, we are trying to mimic in some capacity what was done in the demo given here: https://www.youtube.com/watch?v=mL9AFkJJAq0. 

We must not be thinking of how to implement this properly, since we don't understand what "restoring on the same root" means. Your help is much appreciated!

I am tagging my colleague for mention: @xaviermerino

**Comment by xemul** [comment]
> Because we are spawning a new container and trying to start this new container from a checkpoint of the old

This is what I tell you NOT to do. When you create a new container you create a NEW root filesystem for it. In the checkpoint images, however, there are paths to open/maped files as they were in the OLD container. In case any file is present in the old container and is not in the new one, restore will not succeed. This is what you see.

**Comment by njlow1202** [comment]
Okay. Thank you for the clarification @xemul
