### ISSUE TITLE
runc/criu iterative migration

### ISSUE THREAD

**Issue by washraf** [xemul/criu#298]
I am using runc to checkpoint and restore (migrate) a container. I use a container with 2GB memory for testing the speed of the checkpoint and restore.

The result is very large in terms of check point and restart  almost 20 sec. for check and another 20 for restoration which is very large down time for any service.

Is there any way to check point the and restore the container on the remote host iteratively. this way will enable to to do an iterative precopy migration and decrease the downtime ?.

**Comment by xemul** [comment]
Yes. [This](https://github.com/xemul/criu/tree/criu-dev/phaul) is the sample code that uses live migration. The plan is to integrate this into Docker/RunC some day too.

**Comment by adrianreber** [comment]
runc just recently merged support for pre-dumping:

https://github.com/opencontainers/runc/pull/1001

If you use a runc git checkout that should work.

**Comment by AlexandreCassagne** [comment]
@xemul do you have any knowledge of experimental branches/forks of docker with iterative migration?

**Comment by washraf** [comment]
The runc check point has a iterative checkpoint [runc](https://github.com/opencontainers/runc/blob/master/libcontainer/criu_opts_linux.go#L32)
But as far as I know this flag is not adopted in docker it self nor the checkpoint in general.

**Comment by xemul** [comment]
Yup, neither there's native live migration support for docker daemon.
