### ISSUE TITLE
`sudo make install` copies crit and pycriu to wrong place

### ISSUE THREAD

**Issue by ojura** [xemul/criu#309]
Instead of installing in `/usr/...`, a folder `usr` is created in the cloned git folder instead.

Tested on Ubuntu 16.04.2, criu-dev 39c1a95 (also happens on master branch).

Workaround: `sudo make install DESTDIR=/`

**Comment by xemul** [comment]
Cc @cyrillos and (just in case) @kolyshkin

**Comment by ojura** [comment]
The cause is the following line in `lib/Makefile`:

`	$(Q) $(PYTHON_BIN) scripts/crit-setup.py install --root=$(DESTDIR) --prefix=$(PREFIX) --record $(CRIT_SETUP_FILES)`

`DESTDIR` is empty by default (as documented in `INSTALL.md`).

**Comment by kolyshkin** [comment]
This needs to be fixed properly, ie empty DESTDIR should work fine. Seems
like the problem is PREFIX is not absolute. Note that the PREFIX should be
an absolute path (and we might want to add a check that it is).

**Comment by kolyshkin** [comment]
Reproduced locally

**Comment by xemul** [comment]
4669d6330e784feafa9a48185d5b08c3393659be
