### ISSUE TITLE
Can't bind inet socket (id 115): Cannot assign requested address pie: 1: Task 17 exited, status= 1

### ISSUE THREAD

**Issue by kingsin-fzj** [xemul/criu#312]
The specific description of the problem here #[1411](https://github.com/opencontainers/runc/issues/1411)

**Comment by kingsin-fzj** [comment]
error correlation for dump.log:
(00.013457)     type ext4 source /dev/sda1 mnt_id 90 s_dev 0x800001 /home/starnet/.CaR                 /pbxcore/rootfs @ ./ flags 0x200000 options errors=remount-ro,data=ordered

(00.013737)     type ext4 source /dev/sda1 mnt_id 110 s_dev 0x800001 /etc/hosts @ ./etc/hosts flags 0x200001 options errors=remount-ro,data=ordered

 (00.013746)     type ext4 source /dev/sda1 mnt_id 111 s_dev 0x800001 /etc/resolv.conf      @ ./etc/resolv.conf flags 0x200001 options errors=remount-ro,data=ordered

**Comment by xemul** [comment]
Error (criu/sk-inet.c:764): Can't bind inet socket (id 115): Cannot assign requested address

Are you restoring the container with IP address change?

Let's pick one place for this discussion, I prefer the original runc issue. I've put the same comment there.
