### ISSUE TITLE
Compilation error with GCC 6.3.0

### ISSUE THREAD

**Issue by xinhaoyuan** [xemul/criu#315]
Hi,

I encountered the following error when compiling CRIU with GCC 6.3.0:

```
...
  CC       criu/tty.o
  CC       criu/tun.o
  CC       criu/util.o
  CC       criu/uts_ns.o
  CC       criu/vdso-compat.o
  CC       criu/vdso.o
  LINK     criu/built-in.o
  LINK     criu/criu
/usr/bin/ld: criu/arch/x86/crtools.built-in.o: relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

Then I tried `make clean && make CC=gcc-4.8` and everything looks good now.

**Comment by 0x7f454c46** [comment]
Hi @xinhaoyuan, which branch are you building?
I've tried `master`, `criu-dev` with
> [criu]$ gcc --version
> gcc (GCC) 6.3.1 20170306

but it builds good.
Can you provide last lines of `make V=1` then?

**Comment by xinhaoyuan** [comment]
I tried compiling in a clean docker debian:unstable container and it's OK.
I noticed that the host has libc6-i386 and libc6-dev-i386 installed.
Removing them resolved the issue and `make` is able to complete, but I saw new lines in the make output:

```
Note: Building without ia32 C/R, missed package(s):
      libc6-dev-i386 and/or gcc-multilib
```

Maybe there are some problems with ia32 C/R build?

**Comment by 0x7f454c46** [comment]
I'll check it out, thanks for reporting!

**Comment by 0x7f454c46** [comment]
So, the problem seems to be in Debian gcc-6 toolchain.
Here is related bug in Bugzilla: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861085
I've also reproduced it on kernel x86 selftest `sysret_ss_attrs.c`:
```
root@x86-64-debian:~/x86# make /root/x86/sysret_ss_attrs_64
gcc -m64 -o /root/x86/sysret_ss_attrs_64 -O2 -g -std=gnu99 -pthread -Wall  sysret_ss_attrs.c thunks.S -lrt -ldl
/usr/bin/ld: /tmp/ccVOq79r.o: relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:49: recipe for target '/root/x86/sysret_ss_attrs_64' failed
make: *** [/root/x86/sysret_ss_attrs_64] Error 1
```

**Comment by 0x7f454c46** [comment]
So, the toolchain which can't compile kernel's selftest doesn't seem valid for CRIU building.
Still, you can compile it without compat support or on other gcc you've in system.
I've also checked vanilla gcc v6.3.0, but it compiles criu just good. So, it seems to be debian-related bug.

**Comment by 0x7f454c46** [comment]
It also results in autoconf test failure:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836944
So, as the result, I will not look for a workaround for this - let Debian guys fix their tools.

**Comment by xinhaoyuan** [comment]
Thanks for looking into this!

**Comment by xemul** [comment]
@avagin , would you feed this fix into master, please?

**Comment by avagin** [comment]
https://github.com/xemul/criu/commit/37b3e5953b484d2eb5e27b79a80c83bcd24baafd
