### ISSUE TITLE
Error (criu/pagemap.c:491): Can't read async pr bytes (-1 / 32768 read, 81920 off, 3 iovs)

### ISSUE THREAD

**Issue by avagin** [xemul/criu#324]
```
======================== Run zdtm/static/utsname in ns =========================
Start test
Test is SUID
./utsname --pidfile=utsname.pid --outfile=utsname.out
Run criu dump
Run criu restore
=[log]=> dump/zdtm/static/utsname/38/1/restore.log
------------------------ grep Error ------------------------
(00.209876)      1: pr1 Read 7ffd119a8000 4 pages
(00.209877)      1: pr1 Read 7ffd119b6000 2 pages
(00.209879)      1: Read piov iovs 9, from 0, len 114688, first 0x2ab051ab5000:4096
(00.209949)      1: Advanced iov 81920 bytes, 9->3 iovs, 0 tail
(00.209954)      1: Error (criu/pagemap.c:491): Can't read async pr bytes (-1 / 32768 read, 81920 off, 3 iovs)
(00.233156) mnt: Switching to new ns to clean ghosts
(00.245372) Error (criu/cr-restore.c:2099): Restoring FAILED.
------------------------ ERROR OVER ------------------------
################ Test zdtm/static/utsname FAIL at CRIU restore #################
```
https://travis-ci.org/xemul/criu/jobs/244454195

**Comment by avagin** [comment]
@travis-ci starts using a new image of Ubuntu Trusty
https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch

**Comment by xemul** [comment]
Wold you enlighten us -- why image update results in errors from preadv() call?

**Comment by xemul** [comment]
Looks like issue #322, preadv is off-by-one when restoring memory contents.

**Comment by xemul** [comment]
Here's what I have from https://travis-ci.org/xemul/criu/jobs/246091034

1. The faiure is

    1: Read piov iovs 9, from 0, len 118784, first 0x2b7101361000:4096
    1: Advanced iov 81920 bytes, 9->3 iovs, 0 tail
    1: Error (criu/pagemap.c:491): Can't read async pr bytes (36864 need, 81920 off, 3 iovs): Bad addres
    1: Error (criu/pagemap.c:492): First dst address: 0x2b710185c000

IOW -- the preadv() reads 9 iovecs, cannot read the page from 7th, bails out, criu advances IOV array 6 items forward, then repeats the preadv which fails instantly. The failing address is 0x2b710185c000.

2. The memory into which the data is read is premmap area. Here's the region which covers failing address:

    1:     premap 0x007fff4f94e000-0x007fff4fa72000 -> 00002b710177d000-00002b71018a1000 (291 pages)
    1: `- growsdown!

the ...77d000:...8a1000 covers the ...85c000 address AND (!) it's a growsdown VMA.

**Comment by xemul** [comment]
Yup, this is dup of #322 , the 1M guard size is not taken into account and the data is read from pages.img into wrong place.
