### ISSUE TITLE
Execution of action-scripts with empty path

### ISSUE THREAD

**Issue by timohl** [xemul/criu#327]
Hi.

I am working on migration of LXC containers and I am currently trying to figure out a strange error.
When I try to migrate, the process fails at the restore step.
The restore.log says:
```
(00.011318) Running pre-restore scripts
(00.011326)     []
(00.011610) Error (criu/util.c:656): exec failed: No such file or directory
(00.011890) Error (criu/util.c:670): exited, status=1
(00.011925) Error (criu/action-scripts.c:95): Script  exited with -1
(00.011936) Error (criu/action-scripts.c:142): One of more action scripts failed
(00.011937) Error (criu/cr-restore.c:1762): Aborting restore due to pre-restore script ret code -1
```

As a dirty fix I added an "if" condition in action-scripts.c checking if the script path is an empty string causing to skip the script and write that to log.
This made the migration work and revealed that criu attempts to execute 7 action-scripts with empty path (pre-restore, setup-namespaces, post-setup-namespaces, post-restore, network-unlock, pre-resume, post-resume).

This is the call of criu by LXC:

```
/home/ohliger/shared/cluster/libvirt-lxctools/sbin/criu restore --tcp-established --file-locks --link-remap --manage-cgroups=full --ext-mount-map auto --enable-external-sharing --enable-external-masters --enable-fs hugetlbfs --enable-fs tracefs -D /home/ohliger/shared/cluster/libvirt-lxctools/var/lib/lxc/migrate_tmpfs/0 -o /home/ohliger/shared/cluster/libvirt-lxctools/var/lib/lxc/migrate_tmpfs/0/restore.log --cgroup-root name=systemd:/lxc/cont1 --cgroup-root perf_event:/lxc/cont1 --cgroup-root cpu,cpuacct:/lxc/cont1 --cgroup-root cpuset:/lxc/cont1 --cgroup-root freezer:/lxc/cont1 --cgroup-root net_cls:/lxc/cont1 --cgroup-root memory:/lxc/cont1 --cgroup-root hugetlb:/lxc/cont1 --cgroup-root pids:/lxc/cont1 --cgroup-root blkio:/lxc/cont1 --cgroup-root devices:/lxc/cont1 -vvvvvv --ext-mount-map sys/fs/fuse/connections:/sys/fs/fuse/connections --root /home/ohliger/shared/cluster/libvirt-lxctools/lib/lxc/rootfs --restore-detached --restore-sibling --ext-mount-map console: --external veth[eth0]:vethRPEAVK@br0 
```

Does anybody know, how those scripts containing an empty path are added?
I mean the dirty fix works so far, but I would rather like to know the source of the problem.
Hope you can help me.

Greetings
Tim Ohliger

Edit: Using criu 3.0, centos7 with linux 4.9.15, and a modified lxc 2.0.7.

**Comment by timohl** [comment]
Using criu 3.0, centos7 with linux 4.9.15, and a modified lxc 2.0.7.

**Comment by xemul** [comment]
@timohl , actually action scripts are added with the --action-script command and I don't see one if your example :\ Where did you get the command that LXC uses when launches criu?

**Comment by timohl** [comment]
@xemul OK, I searched where the action-script option might be set and found that the application I am using passes a partially uninitialized migrate_opts struct to LXC. Especially, action-script was uninitialized causing the empty paths.
I do not know why the LXC log did not show the action-script option, but who knows what those uninitialized variables did.
Fixing the application resolves this issue so I am happy.
Thanks for the hint and sorry for bothering with a bug not concerning criu code.
