### ISSUE TITLE
docker ps can't find the successfully restored container(between two virtual machine)

### ISSUE THREAD

**Issue by xubo123** [xemul/criu#362]
Firstly, I run this on source virtual machine:

~sudo docker run --security-opt=seccomp:unconfined --name cr -d busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
~sudo docker checkpoint create -checkpoint-dir=/home/xubo/checkpoints cr crpoint

looks normal here
Then I transmit the checkpoint file (crpoint) to the destinate virtual machine with the same configuration(the same docker version 17.06.0,and the same criu version 3.2.1) by this CLI

~scp -r c85acf361cf8d87cd04fa0efd2e28433ee38025b4103b0041f2982b613b3000e xubo@192.168.58.130:/home/xubo/checkpoints

I get the checkpoint file(crpoint),Then I run this on the destinate virtual machine:
~sudo docker run --security-opt=seccomp:unconfined --name cr -d busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
~sudo docker stop cr
~sudo docker start --checkpoint-dir=/home/xubo/checkpoints/ dc4b571a4522564f8c4eb38e80767445cadd63d0aeab056ba31c621a7f909536/checkpoints --checkpoint crpoint cr

Then ,I get nothing wrong reported,and I see the restore.log,it looks OK too:
(00.415573)pie: 74: restoring seccomp mode 0 for 74
(00.415598)pie: 74: restoring lsm profile changeprofile docker-default
(00.415670)pie: 1: restoring seccomp mode 0 for 1
(00.415689)pie: 1: restoring lsm profile changeprofile docker-default
(00.415734) Restore finished successfully. Resuming tasks.
(00.415895) Running pre-resume scripts
(00.415901) 	RPC
(00.425236) Writing stats
(00.425294) Running post-resume scripts
(00.425297) 	RPC

But I run the 'sudo docker ps' on the destination virtual machine,find that no container is alive.

Can you explain this problem for me ,Thank you!!

**Comment by xemul** [comment]
You should report this issue to Docker guys. @kolyshkin , would you help us to find the proper repo for this?

**Comment by xubo123** [comment]
ok，thanks a lot~
