### ISSUE TITLE
Auto test for p.haul - fail to start

### ISSUE THREAD

**Issue by pallelagnanadeep** [xemul/criu#367]
Failed to start.. please find the error as below. What can be the issue?
root@ubuntu:~/criu/p.haul/test/zdtm# ./run.sh
+ CRIU_PATH=../../../criu/
+ CRIU_TESTS=../../../criu//test/zdtm/
++ pwd
+ WDIR=/root/criu/p.haul/test/zdtm/wdir
++ realpath ../../p.haul
+ PH=/root/criu/p.haul/p.haul
++ realpath ../../p.haul-service
+ PHS=/root/criu/p.haul/p.haul-service
++ realpath ../../p.haul-wrap
+ PHWRAP=/root/criu/p.haul/p.haul-wrap
++ realpath ../../p.haul-ssh
+ PHSSH=/root/criu/p.haul/p.haul-ssh
+ trap exit_cleanup EXIT
+ '[' 0 -gt 0 ']'
+ rm -rf /root/criu/p.haul/test/zdtm/wdir
+ mkdir /root/criu/p.haul/test/zdtm/wdir
+ '[' x == xtrue ']'
+ make ct_init
make: 'ct_init' is up to date.
+ ./ct_init /root/criu/p.haul/test/zdtm/wdir/ct.log /root/criu/p.haul/test/zdtm/wdir/init.pid ./ct_init.py ../../../criu//test/zdtm/ tests
**Failed to start**
+ echo 'Start FAIL'
Start FAIL
+ exit 1
+ exit_cleanup
+ '[' x '!=' x ']'
+ return 0

**Comment by avagin** [comment]
@pallelagnanadeep you have to file this issue to the p.haul repo: https://github.com/xemul/p.haul/issues
