### ISSUE TITLE
docker criu in coreos

### ISSUE THREAD

**Issue by giper45** [xemul/criu#369]
Hi, I'm trying to configure coreos (alpha version, downloaded from the official site) to use docker + criu.

I've installed criu inside the toolbox coreos utility (that is a "virtual fedora OS" inside coreos that allow to install software for debugging purposes), then I've copied toolbox:/bin/criu  in /media/root/opt/bin directory (/opt/bin directory coreos, all coreos fs is read-only, then I'm forced to put criu in /opt/bin directory that is writable) and all shared library used by criu in /opt/lib64 (for the same reason as the criu command); 
then I used ldconfig to set the shared library path as /opt/lib64. 
If I give criu in any directory as coreos user it seems to work as showed:
<img width="591" alt="schermata 2017-07-31 alle 13 25 18" src="https://user-images.githubusercontent.com/18548727/28775714-bcee0bce-75f3-11e7-8aac-e9f863498cf0.png">
 
Anyway when I try to use criu with docker (after the experimental configuration) it gives the following error: 
```
core@localhost ~ $ docker run -d --name looper --security-opt seccomp:unconfined busybox  \
>          /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
0e5f89575e5467133b607920def05b3b7b3c2c367ccbd360ae220d52478c1a13
core@localhost ~ $ docker logs looper
0
1
2
3
4
5
core@localhost ~ $ docker checkpoint create looper checkpoint1
Error response from daemon: Cannot checkpoint container looper: rpc error: code = 2 desc = exit status 1: "Unable to execute CRIU command: criu\n"
core@localhost ~ $ 
```

Is there any way to better understand where is the problem? Does anyone have configured coreos with criu command enabled? 

Thanks in advance!

**Comment by avagin** [comment]
criu is called from dockerd. Could you show output for cat /proc/`pidof dockerd`/environ?

**Comment by giper45** [comment]
Hi @avagin it was a system environment path problem as discussed in https://github.com/coreos/docs/issues/1128 .
Thanks anyway for the answer!
Now I try to request coreos staff to natively integrate criu in coreos packages, so it can be installed in coreos easily and without any hack.
