### ISSUE TITLE
docker checkpoint error 

### ISSUE THREAD

**Issue by blondita** [xemul/criu#371]
Hi, i'm using rancherOS for testing in container live migration i'm trying looper container example when checkpointed the container:

 docker checkpoint create looper checkpoint1

i've this error:

Error response from daemon: Cannot checkpoint container looper: rpc error: code = 2 desc = exit status 1: "criu failed: type NOTIFY errno 0\nlog file: /var/lib/docker/containers/4ab5f9875d1ed050de60b4e2f0652006511aff4d479fdf153817da06bc612f64/checkpoints/checkpoint1/criu.work/dump.log\n"

Thanks in advance!

**Comment by avagin** [comment]
Could you show a content of /var/lib/docker/containers/4ab5f9875d1ed050de60b4e2f0652006511aff4d479fdf153817da06bc612f64/checkpoints/checkpoint1/criu.work/dump.log?

**Comment by xubo123** [comment]
Hi,guys,how you perform the live migration of docker container,can you show me the steps of live migration?thanks a lot .

**Comment by blondita** [comment]
It give this error:
(00.159409) mnt: Path `/sys/firmware' resolved to `./sys/firmware' mountpoint
(00.168708) Error (criu/util.c:652): exec failed: No such file or directory
(00.169253) Error (criu/util.c:666): exited, status=1
(00.169270) Error (criu/mount.c:1202): mnt: Can't dump tmpfs content
(00.169403) Unlock network
(00.169411) Running network-unlock scripts
(00.169415) 	RPC
(00.189671) Unfreezing tasks into 1
(00.189699) 	Unseizing 974 into 1
(00.189711) 	Unseizing 1135 into 1
(00.189731) Error (criu/cr-dump.c:1628): Dumping FAILED.
@avagin

**Comment by avagin** [comment]
@blondita you need to install "tar"
https://www.gnu.org/software/tar/

**Comment by blondita** [comment]
@avagin thanks it was correct but it works only with fedora console.
I don't know why but when i use ubuntu console (with also tar installed) it doesn't work!

**Comment by avagin** [comment]
@blondita how it doesn't work for an ubuntu console?

**Comment by blondita** [comment]
@avagin it gave me the same error, while with fedora console it resolve the issue

**Comment by avagin** [comment]
How do you install tar? When you say an ubuntu console, do you mean an Ubuntu container?

**Comment by blondita** [comment]
In RancherOs you can chance the console
http://rancher.com/docs/os/configuration/switching-consoles/

**Comment by avagin** [comment]
@blondita thank you for the link. I will try to understand what this means.

**Comment by blondita** [comment]
@avagin how do you know that the problem was 'tar' in my post?

**Comment by avagin** [comment]
```
(00.168708) Error (criu/util.c:652): exec failed: No such file or directory
(00.169253) Error (criu/util.c:666): exited, status=1
(00.169270) Error (criu/mount.c:1202): mnt: Can't dump tmpfs content
```
I know that criu uses tar to dump content of tmpfs mounts. I am going to improve the first error message and add a name of a file to it.
