### ISSUE TITLE
ppc64el mirrors

### ISSUE THREAD

**Issue by xnox** [xemul/criu#376]
`<avagin> Hi. I can't install a packages: Failed to fetch http://security.ubuntu.com/ubuntu/dists/trusty-security/main/binary-ppc64el/Packages  404  Not Found [IP: 91.189.91.23 80]. Does someone meet this problem?
<avagin> here is a full log: https://travis-ci.org/xemul/criu/jobs/263720066`

ppc64el is a ports architecture, and therefore the security pocket is hosts on ports.ubuntu.com/ubuntu-ports not on security.ubuntu.com domain.

**Comment by xemul** [comment]
Cc @avagin 

I wonder, who the one to fix this URL :) We don't have such in CRIU sources. Is it Travis or Docker?

**Comment by avagin** [comment]
@xnox we get this ubuntu trusty image from the Docker hub:
```
FROM ppc64le/ubuntu:trusty
ENV QEMU_CPU POWER8
COPY scripts/build/qemu-user-static/usr/bin/qemu-ppc64le-static /usr/bin/qemu-ppc64le-static
RUN apt-get update && apt-get install -y \
                build-essential \
                protobuf-c-compiler \
                libprotobuf-c0-dev \
                libprotobuf-dev \
                bsdmainutils \
                protobuf-compiler \
                python-minimal \
                libaio-dev \
                libcap-dev \
                iptables \
                libnl-3-dev \
                libnl-route-3-dev \
                libselinux-dev \
                pkg-config \
                git-core \
                libnet-dev \
                ccache \
                gcc
```

**Comment by xnox** [comment]
@avagin Thanks! Let me figure out if I can find the right people to fix that.

**Comment by avagin** [comment]
I tried to switch to ppc64le/ubuntu:xenial, but there is another issue
```
Unpacking libpython-stdlib:ppc64el (2.7.11-1) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
/sbin/ldconfig.real: 1: /sbin/ldconfig.real: Syntax error: end of file unexpected
/sbin/ldconfig.real: 1: /sbin/ldconfig.real: Syntax error: end of file unexpected
```
https://bugs.launchpad.net/cloud-images/+bug/1708516
