### ISSUE TITLE
crit explore

### ISSUE THREAD

**Issue by n0way0ut** [xemul/criu#381]
hi,

with criu-dev branch the files image are changed, some of them are merged, so crit can't explore the new files, for example:
$ crit x dir fds
...
IOError: [Errno 2] No such file or directory: './pipes.img'

but also reg-files.img and unixsk.img.

**Comment by xemul** [comment]
Ugh :( Thanks for reporting this.

**Comment by xemul** [comment]
Heh, in my criu-dev it complains another way (see issue #382 ). Anyway, patch for master will be sent out soon, the other thing is to be discussed.
