### ISSUE TITLE
Where to find the dumped images to complete the live migration? 

### ISSUE THREAD

**Issue by Silveryfu** [xemul/criu#5]
Hi,

I tried the pre-released docker-1.5.0 and it worked well with native checkpoint/restore. I am hoping to do is to locate the dumped images, send them to the other host, and restore the container there. However, I am not able to locate those images. 

Is the live migration part also going to be added to docker natively? Or we should follow the migration sequence as what we do for external criu?

Thanks!

**Comment by xemul** [comment]
Since this is a question about Docker, it's better to ask it in Docker project :) AFAIK it puts images in /var/run/docker, but I can be wrong.

As far as the livemigration is concerned,  yes, the plan is to add native live migration using p.haul (github.com/xemul/p.haul).

**Comment by avagin** [comment]
Cc: @boucher

**Comment by boucher** [comment]
You can find them wherever your driver storage is located, inside the container's directory, in a subfolder called criu.image. On my system, this is:

    /var/run/docker/execdriver/native/<id>

However, if you want to migrate a container, or care at all about where it's stored, I recommend using the --image-dir flag when checkpointing, which lets you control where the image is stored.

**Comment by Silveryfu** [comment]
Thank you, all. @boucher mine is located in the /var/run/docker/lib/containers/<id>/criu.image. However, as I tried the naive approach, namely scp the image to another host, putting the images under the same directory, but docker restore fails and reports:  
```
ERRO[0043] HTTP Error: statusCode=500 Cannot restore container elegant_mestorf: evalSymlinksInScope: /opt/webapp is not in /home/xxx
```

Btw, the --image-dir is still undefined for this pre-release.

**Comment by boucher** [comment]
Can you try building from the branch in this pull request:
https://github.com/docker/docker/pull/13602

You should be able to pass --image-dir on both sides, and, assuming you already have the same docker image, you can use the --force parameter when restoring to restore into a new container created from the same image (something like: docker create --name test busybox; docker restore --image-dir=/your/path/to/criu.image --force=true test)

**Comment by Silveryfu** [comment]
@boucher I built and tested it. What I found out was:

When tested with training/webapp, I froze it with --image-dir flag set and did: docker rm test; docker create --name test training/webapp; then I restarted it with docker restore and it works; However, when I tried to test with this script:

'''
#!/bin/bash
COUNT=0

while true; do
date
COUNT=$(( COUNT + 1 ))
done
'''

When simply checkpoint and restore, everything works fine. When checkpoint, remove the checkpointed container, and use docker create and docker restore, an error occur (with or without the --allow-shell enabled). The restore log says:

'''
(00.000051) Added /opt:/home/xxx ext mount mapping
(00.000085) Added /etc/resolv.conf:/var/lib/docker/containers/748bd1e22ce9cb22a021115ad8df5bd55cd96018eea4b48e26047a645f551059/resolv.conf ext mount mapping
(00.000093) Added /etc/hostname:/var/lib/docker/containers/748bd1e22ce9cb22a021115ad8df5bd55cd96018eea4b48e26047a645f551059/hostname ext mount mapping
(00.000098) Added /etc/hosts:/var/lib/docker/containers/748bd1e22ce9cb22a021115ad8df5bd55cd96018eea4b48e26047a645f551059/hosts ext mount mapping
(00.000213) TCP recv queue memory limit is 3145728
(00.000247) cpu: fpu:1 fxsr:1 xsave:1
(00.000374) vdso: Parsing at 7fffea1fe000 7fffea200000
(00.000385) vdso: PT_LOAD p_vaddr: ffffffffff700000
(00.000391) vdso: DT_HASH: 0xffffffffff700120
(00.000396) vdso: DT_STRTAB: 0xffffffffff700268
(00.000400) vdso: DT_SYMTAB: 0xffffffffff700160
(00.000404) vdso: DT_STRSZ: 94
(00.000408) vdso: DT_SYMENT: 24
(00.000412) vdso: nbucket 3 nchain 11 bucket 0x7fffea1fe128 chain 0x7fffea1fe134
(00.000421) vdso: rt [vdso] 7fffea1fe000-7fffea200000 [vvar] ffffffffffffffff-ffffffffffffffff
(00.000469) Reading image tree
(00.000510) Add mnt ns 11 pid 1
(00.000536) Will restore in 6c020000 namespaces
(00.000543) NS mask to use 6c020000
(00.000554) Collecting 36/21 (flags 0)
(00.000566)  `- ... done
(00.000574) Error (tty.c:1533): tty: Standard stream is not a terminal, aborting
'''
