### ISSUE TITLE
Closed TCP socket with peer-name blocks dump

### ISSUE THREAD

**Issue by xemul** [xemul/criu#62]
https://lists.openvz.org/pipermail/criu/2015-September/022257.html

If we open a connection, then peer closes one and we shutdown-write it, the resulting socket will stay in fdtable with peer name, but in closed state. CRIU fails to dump one.

Test from @avagin : https://lists.openvz.org/pipermail/criu/2015-September/022291.html

**Comment by hixichen** [comment]
I faced the same issue with CRIU 2.2

Log shows , the state get from the socket is 8. 
if (info.tcpi_state != TCP_CLOSE) {
			pr_err("Socket state %d obtained but expected %d\n",
			       info.tcpi_state, TCP_CLOSE);
			goto err;

**Socket state 8  obtained but expected 7"**
as the code set  sk->state = TCP_CLOSE;
after restore, the socket cannot be used anymore.

**Comment by xemul** [comment]
Yup :(

**Comment by hixichen** [comment]
To follow up:
My application didnot close the socket FD after finishing the task. 
Then the socket was left  in state 'TCP_CLOSING'. 
For my case, close the socket will bypass the issue.

**Comment by xemul** [comment]
Cc @avagin

**Comment by xemul** [comment]
@avagin would you be able to look at this in the nearest future?

**Comment by avagin** [comment]
Here are kernel and criu changes to support tcp sockets with closing states
https://github.com/avagin/linux-task-diag/tree/tcp-v3
https://github.com/avagin/criu/tree/tcp-closing-states

**Comment by xemul** [comment]
Dup for #194
