### ISSUE TITLE
Cross compilation fail because pie/piegen/piegen can not be used on host machine

### ISSUE THREAD

**Issue by eliams** [xemul/criu#63]
Hi,
I'am trying to cross compile criu for an x86_64 system with a uclibc using buildroot and my host machine is an x86_64 with a glibc.
During build process the pie/piegen/piegen binary is compiled and then used. Since I'm using a cross compiler the pie/piegen/piegen binary is linked to the uclibc which make it unusable on the host machine and lead the build of criu to fail.
What is the pie/piegen/piegen used for ?
Will it work if I compile it for my host machine before building criu ?

I've looked at https://github.com/xemul/criu/blob/master/Documentation/HOWTO.cross-compile#L31
but editing the CROSS_COMPILE variable will enforce the use of the crosscompiler but the latter will also be used for the pie/piegen/piegen binary.

Thanks

**Comment by xemul** [comment]
@cyrillos , please help us here too :)

**Comment by cyrillos** [comment]
@xemul sure, will take a look, thanks

**Comment by cyrillos** [comment]
@eliams piegen is a special tool we use to generate PIE code for own criu needs (in short).  More detailed here http://criu.org/Code_blobs

**Comment by cyrillos** [comment]
@eliams Could you please run
make clean
make V=1
and post output here

**Comment by cyrillos** [comment]
@eliams with all ARCH= and such flags I mean. I'm interested in V=1 make output

**Comment by eliams** [comment]
Here is the output of make. http://pastebin.com/tkueBFpY.

Hi edited the makefile so piegen will be compiled using the host gcc:
```
--- Makefile	2015-09-29 11:03:56.591117519 +0200
+++ /home/ismael/Makefile.criu.patched	2015-09-29 11:10:07.303116454 +0200
@@ -35,6 +35,8 @@
 
 CFLAGS		+= $(USERCFLAGS)
 
+HOST_CC		= /usr/bin/gcc
+
 #
 # Fetch ARCH from the uname if not yet set
 #
@@ -209,12 +211,12 @@
 
 ifeq ($(piegen-y),y)
 pie/piegen/%: config
-	$(Q) $(MAKE) $(build)=pie/piegen $@
+	$(Q) $(MAKE) CC="$(HOST_CC)" $(build)=pie/piegen $@
 pie/piegen: config
 	$(Q) $(MAKE) $(build)=pie/piegen all
 $(piegen): pie/piegen/built-in.o
 	$(E) "  LINK    " $@
-	$(Q) $(CC) $(CFLAGS) pie/piegen/built-in.o $(LDFLAGS) -o $@
+	$(Q) $(HOST_CC) $(CFLAGS) pie/piegen/built-in.o $(LDFLAGS) -o $@
 .PHONY: pie/piegen
 endif
```
It's not very clean but fixed the problem during  build. However I did not get the time to test if criu is working yet.

**Comment by cyrillos** [comment]
@eliams Yes, thanks. We indeed need something like that for cross-compile. I'll prepare a patch and send it out.

**Comment by xemul** [comment]
3ffad59e2ed24e79d52ab65e511b0c7c8c9d15e5
