### ISSUE TITLE
/dev/mqueue error restoring into new docker container.

### ISSUE THREAD

**Issue by boucher** [xemul/criu#64]
I'm now getting this error when trying to use the latest rebase of docker c/r and restoring into a new container: No mapping for /dev/mqueue mountpoint

full restore log:
https://gist.github.com/boucher/125cdf03366d0d58a0a7

**Comment by xemul** [comment]
This means that the mqueue filesystem is mounted from outside (it looks like it is) but it not given in --ext-mount-map (it looks like it's not either) and auto-detection of ext-mounts is not specified too.
