### ISSUE TITLE
Save files that can be lost in the future (temp dir) into images

### ISSUE THREAD

**Issue by krafczyk** [xemul/criu#65]
When attempting to restore a vim session, which uses you complete me, I get the following messages:

```
  2587: Error (files-reg.c:1109): Can't open file tmp/ycm_temp/server_59168_stdout.log on restore: No such file or directory
  2587: Error (files-reg.c:1052): Can't open file tmp/ycm_temp/server_59168_stdout.log: No such file or directory
  2580: Error (cr-restore.c:1234): 2587 exited, status=1
Error (cr-restore.c:1933): Restoring FAILED.
```

My machine clears the /tmp directory on each boot.

If criu detects that a process is using files from a non-persistent source (Which criu should either be able to detect, or the user should be able to specify the non-persistent directories), it should be able to copy them and then restore them when the process is restored, provided that the files aren't too large.

**Comment by xemul** [comment]
Hm. We save the contents of tmpfs mounts as tar archive when dump a mount namespace. We also save the contents of opened and unlinked (and mapped and unlinked) files on dump. Adding the possibility to save into image files, that can _potentially_ get lost in the future can be done, yes. But I don't see good automatic decision-maker, so an API option would be OK.

**Comment by avagin** [comment]
I don't think that we need to add this option in CRIU. An user can save/restore this files from pre-dump and post-restore actions scripts.

**Comment by xemul** [comment]
criu dump <options> --action-script '$CRIU_SCRIPTS_PATH/tmp-files.sh /tmp/ycm_temp /home/user/.tmpfile.txt.swp'
criu restore <options> --action-script $CRIU_SCRIPTS_PATH/tmp-files.sh

**Comment by geminijun** [comment]
I just tried to use "criu dump --action-script '$CRIU_SCRIPTS_PATH/tmp-files.sh /tmp/ycm_temp /home/user/.tmpfile.txt.swp'" And it doesn't work.

In the code:
```
        list_for_each_entry(script, &scripts, node) {
                int err;
                pr_debug("\t[%s]\n", script->path);
                err = cr_system(-1, -1, -1, script->path,
                                (char *[]) { script->path, NULL }, 0);
                if (err)
                        pr_err("Script %s exited with %d\n", script->path, err);
                retval |= err;
        }
```

It passed "'$CRIU_SCRIPTS_PATH/tmp-files.sh /tmp/ycm_temp /home/user/.tmpfile.txt.swp'" as cmd to ```cr_system```, all the way to ```execvp(cmd, argv);```

So how does criu "action script" support script with arguments?

**Comment by Snorch** [comment]
@geminijun You should likely use environment variables instead of arguments. As execvp inherits(does not change) them, your script receives same environment variables you give to criu process (in ideal world).

**Comment by geminijun** [comment]
> @geminijun You should likely use environment variables instead of arguments. As execvp inherits(does not change) them, your script receives same environment variables you give to criu process (in ideal world).

Thanks for your response! I just follow the example and think maybe I missed something. So I guess I should assign the files I want to an environment variable like ```$TMP_FILES``` and then replace ```$@``` in ```tmp-file.sh``` to ```$TMP_FILES```. Yes, that should work, I will try it out.
