### ISSUE TITLE
When dumping a screen session, the unix socket it was using is left behind

### ISSUE THREAD

**Issue by krafczyk** [xemul/criu#66]
After dumping the screen session, if I use `screen -ls`, I get:

```
There is a screen on:
	2941.Analysis1	(Dead ???)
Remove dead screens with 'screen -wipe'.
1 Socket in /run/screens/S-matthew.
```

This socket should probably be removed.

**Comment by xemul** [comment]
I wouldn't say it's criu job to clean stuff up after the dumped processes. We have a post-dump hook (http://criu.org/Action_scripts) that you can use to do whatever actions are required after successful dump.

**Comment by krafczyk** [comment]
So, just to be sure, there are situations where when a process using a unix socket is dumped, we *wouldn't* want to remove the unix socket.
Presumably because there might be other processes which we didn't dump that are still using the socket.

**Comment by xemul** [comment]
Well, actually I was thinking the other way. It's not criu's job to mess with what's-on-the-disk, since it's very app-specific.

**Comment by krafczyk** [comment]
Okay, that makes sense. I'll close this issue then, and try to go the hooks route.
