### ISSUE TITLE
Provide pre-dump and pre-restore hooks for callers.

### ISSUE THREAD

**Issue by krafczyk** [xemul/criu#67]
I'm not sure whether criu can do anything about this, but after restarting and before starting any additional screens, the /run/screen directory doesn't exist.

I don't know whether there's anything criu _should_ do about this, but maybe there is.

When I attemp to restore the screen, I get the following errors:

```
  2941: Warn  (sk-unix.c:1229): sk unix: Can't unlink stale socket 0xda53 peer 0 (name /run/screens/S-matthew/2941.Analysis1 dir -)
  2941: Error (sk-unix.c:920): sk unix: Can't bind socket: No such file or directory
Error (cr-restore.c:1236): 2941 killed by signal 9
Error (cr-restore.c:1933): Restoring FAILED.
```

This issue can be worked around by using `screen -ls` before restoring the screen session.

**Comment by xemul** [comment]
Hm... I would say that criu should do "mkdir -p" on the whole path of unix socket, but it's arguable which perms and user are to be put on the created directories. Thoughts?

**Comment by krafczyk** [comment]
I suppose that's possible, but you make a good point about the permissions.

I just checked, and `screen -ls` also creates the necessary directories, so perhaps a good idea is to have a 'pre-restore' hook like you mentioned in issue #66. That way it can be done the 'screen way' or however way the user sees as correct. Perhaps also a 'pre-dump' hook would be good as well, so that the user can identify and save non-persistent files which I mentioned in #65.

**Comment by xemul** [comment]
Yup. The pre-* hooks would be good, I'm renaming the issue then :) Not sure when we'll be able to get to this ourselves, but patches are always welcome.

**Comment by krafczyk** [comment]
I'll take a look at how the hooks are implemented, and see much work it'll be.

If it's not too involved, I'll probably send you a patch.

**Comment by xemul** [comment]
Thanks :)

Please, note, that the development is running on the criu@openvz.org mailing list since the project start, so code contributions should come there, not as github pull requests.

**Comment by krafczyk** [comment]
Okay, Thanks for letting me know.

On Mon, Oct 05, 2015 at 02:30:43AM -0700, Pavel Emelyanov wrote:
> Thanks :)
> 
> Please, note, that the development is running on the criu@openvz.org mailing list since the project start, so code contributions should come there, not as github pull requests.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/xemul/criu/issues/67#issuecomment-145475172

-- 
*****************
Matthew S. Krafczyk
Research Assistant
Massachusetts Institute of Technology
AMS-02 Collaboration,
Based at CERN, Geneva, Switzerland

**Comment by xemul** [comment]
29c08d86722150d5c43171d4faa5889597565464
