### ISSUE TITLE
The bug of the docker_cr.sh

### ISSUE THREAD

**Issue by YaoZengzeng** [xemul/criu#7]
When I verify the external C/R with docker_cr.sh ,I can dump the container successfully.

root@iZu1pbgsilbZ:/home/monster# ./docker_cr.sh -c -v 61002d6899a8007ff82e72906cd658a78b427d3c078c1374359fd263f301697a
docker binary: docker
dockerinit binary: /var/lib/docker/init/dockerinit-1.7.0-dev
criu binary: criu
image directory: /var/lib/docker/criu_img/61002d6899a8007ff82e72906cd658a78b427d3c078c1374359fd263f301697a
container root directory: /var/lib/docker/aufs/mnt/61002d6899a8007ff82e72906cd658a78b427d3c078c1374359fd263f301697a

criu dump -v4 -D /var/lib/docker/criu_img/61002d6899a8007ff82e72906cd658a78b427d3c078c1374359fd263f301697a -o dump.log --manage-cgroups --evasive-devices --ext-mount-map /etc/resolv.conf:/etc/resolv.conf --ext-mount-map /etc/hosts:/etc/hosts --ext-mount-map /etc/hostname:/etc/hostname --ext-mount-map /.dockerinit:/.dockerinit -t 18622 --root /var/lib/docker/aufs/mnt/61002d6899a8007ff82e72906cd658a78b427d3c078c1374359fd263f301697a

dump successful
(00.026438) Dumping finished successfully

But when I want to restore the container,I meet the bug .

restore failed
(00.051080)      1: Error (rst-malloc.c:130): BUG at rst-malloc.c:130
(00.063390) Error (cr-restore.c:1221): 19157 killed by signal 11
(00.063482) Error (cr-restore.c:1912): Restoring FAILED.

I don't know why.Please help me .Thanks!

**Comment by YaoZengzeng** [comment]
@xemul  @SaiedKazemi

**Comment by boucher** [comment]
I believe @xemul has a patch for this?

**Comment by xemul** [comment]
Yup, should be fixed by 7b20f42f785bafcc61c11adddcdbf2d5a54917cf commit.

**Comment by YaoZengzeng** [comment]
@xemul Thanks .The problem has been solved.But criu seems not work well with docker 1.8.0.When I test checkpoint and restore,It will report bug.The details you can see in another issue.

**Comment by xemul** [comment]
OK, I'll close this bug then :) Thanks!
