### ISSUE TITLE
Support Docker console

### ISSUE THREAD

**Issue by rohitju** [xemul/criu#76]
I followed the instructions by @kimh here: http://blog.circleci.com/checkpoint-and-restore-docker-container-with-criu/ and am able to checkpoint a busybox container. Trying to checkpoint an Ubuntu 12.04 container however gives the error:

    Error response from daemon: Cannot checkpoint container hopeful_blackwell: criu
    failed: type NOTIFY errno 0
    Error: failed to checkpoint one or more containers

I see the following in the Docker daemon logs:

    INFO[73727] POST /v1.21/containers/hopeful_blackwell/checkpoint
    ERRO[73727] Handler for POST /containers/{name:.*}/checkpoint returned error: Ca
    nnot checkpoint container hopeful_blackwell: criu failed: type NOTIFY errno 0
    ERRO[73727] HTTP Error                                    err=Cannot checkpoint
    container hopeful_blackwell: criu failed: type NOTIFY errno 0 statusCode=500

Are there any other logs I can look at to debug this issue?

**Comment by rohitju** [comment]
I noticed that I was running the Ubuntu box with the -t option. Removing that fixed the issue. Is this expected?

**Comment by xemul** [comment]
In the /var/run/docker (IIRC) there should be criu log for your container called dump.log. All criu-side errors are there.

As far as -t option is concerned -- what does it do?

**Comment by klesgidis** [comment]
The -t option allocates a pseudo-tty.. As far as I remember there was a bug with the pseudo-tty but I can't remember if it is fixed.

**Comment by xemul** [comment]
Ah, I see. Yes, there was some issue with ttys. Would you show the criu log please?

**Comment by rohitju** [comment]
The logs for CRIU are here: https://gist.github.com/rohitju/916ef0876de9a09b8954

**Comment by avagin** [comment]
(00.009050) Error (mount.c:630): 157:./dev/console doesn't have a proper root mount

It's the known issue. We can't dump a container with an external terminal.

**Comment by xemul** [comment]
Why not? Doesn't --ext-mount-map do the trick?

**Comment by avagin** [comment]
@xemul We can restore this mount, we can't restore descriptors for this terminal.

**Comment by xemul** [comment]
Is it something special to ttys? Or can't we restore descriptors for any external mountpoints?

**Comment by rajasec** [comment]
I could try to some extent of dumping terminal.  I have added /dev/console in runc code, so that criu able to get the /dev/console mount point. Post that criu failed later as it could not identify mnt_id mentioned part of file descriptors.

**Comment by xemul** [comment]
@avagin , you seem to know a lot about this issue about ttys. Can you shed more light on it for us, please?

**Comment by avagin** [comment]
I think CRIU finds a terminal, detects that it's a part of a tty pair and try to dump this pair, but we have only one end and a devpts mount point isn't here.

We need to add support of tty-s as Inheriting FDs.
https://criu.org/Inheriting_FDs_on_restore

Cc: @cyrillos

**Comment by cyrillos** [comment]
@avagin Yeah, I've this in my todo list :)

**Comment by xemul** [comment]
That's OK, but still "doesn't have proper root mount" message should be addressed with the --ext-mount-map.

**Comment by xemul** [comment]
@avagin , presumably it's finally handled by the new --external option in v2.0?

**Comment by phil294** [comment]
@xemul is it? If so, Docker does not make use of it.

https://criu.org/Docker#TTY still says 
> TTY: Checkpointing an interactive container is currently not supported.

And the error is (a little different than OP)
```
Error response from daemon: Cannot checkpoint container looper: rpc error: code = Unknown desc = exit status 1:
 "criu failed: type NOTIFY errno 0\nlog file: /var/lib/docker/containers/[id...]/checkpoints/cp/criu.work/dump.log\n"
```
Log file is big, contains error `(00.567171) Error (criu/tty.c:381): tty: Found slave peer index 0 without correspond master peer`.

So - is this functionality expected to work or not? Any clues to this? Thank you very much!
