### ISSUE TITLE
Unresolved fsnotify path

### ISSUE THREAD

**Issue by jcarnus** [xemul/criu#77]
Hi
I try to checkpoint a lxc container. After a SECCOMP issue, I am facing another issue : 

(00.174189) irmap: Scanning /no-such-path hint
(00.174192) irmap: Refresh stat for /no-such-path
(00.174208) Error (irmap.c:81): irmap: Can't stat /no-such-path: No such file or directory
(00.174213) Error (fsnotify.c:191): fsnotify:   Can't dump that handle
(00.174249) ----------------------------------------
(00.174253) Error (cr-dump.c:1255): Dump files (pid: 6054) failed with -1

I am not sure to understand why the criu is looking for this path ?

Thanks

**Comment by xemul** [comment]
Please, show full log. The message about /no-such-path is debugging one, dump cannot fail due to it.

**Comment by jcarnus** [comment]
Here the full log : 
http://pastebin.com/raw.php?i=L8dN5EQc

**Comment by xemul** [comment]
OK, on the device 0x26 there's an inode 0x3adb which has unknown path and CRIU failed to find one. Would you scan your container for this inode and tell us what the path is?

**Comment by jcarnus** [comment]
Euhh, yes if you explain me how to do this :)

**Comment by xemul** [comment]
Try the simple way -- enter the container and do 'find / -inum 15067' then 'stat %filename' for every file reported.

**Comment by jcarnus** [comment]
First : 
find / -inum 15067
find: `/proc/1230/task/1230/fd/5': No such file or directory
find: `/proc/1230/task/1230/fdinfo/5': No such file or directory
find: `/proc/1230/fd/5': No such file or directory
find: `/proc/1230/fdinfo/5': No such file or directory
/usr/share/dbus-1/system-services
find: `/sys/fs/cgroup/systemd/lxc': No such file or directory
find: `/sys/fs/cgroup/memory/lxc/101/memory.pressure_level': Permission denied
find: `/sys/fs/cgroup/memory/lxc/101/memory.force_empty': Permission denied
find: `/sys/fs/cgroup/memory/lxc/101/cgroup.event_control': Permission denied
find: `/sys/fs/cgroup/devices/lxc': No such file or directory
find: `/sys/fs/cgroup/blkio/lxc/101/blkio.reset_stats': Permission denied
/sys/devices/virtual/tty/tty5/power/runtime_active_time

**Comment by jcarnus** [comment]
root@CT101:~# stat /usr/share/dbus-1/system-services
  File: '/usr/share/dbus-1/system-services'
  Size: 2               Blocks: 1          IO Block: 512    directory
Device: 26h/38d Inode: 15067       Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-10-23 13:59:41.899396954 +0000
Modify: 2015-05-27 22:12:21.000000000 +0000
Change: 2015-10-22 01:07:53.323991935 +0000
 Birth: -

root@CT101:~# stat /sys/devices/virtual/tty/tty5/power/runtime_active_time
  File: '/sys/devices/virtual/tty/tty5/power/runtime_active_time'
  Size: 4096            Blocks: 0          IO Block: 4096   regular file
Device: 30h/48d Inode: 15067       Links: 1
Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-10-23 13:57:46.446758872 +0000
Modify: 2015-10-23 13:57:46.446758872 +0000
Change: 2015-10-23 13:57:46.446758872 +0000
 Birth: -

**Comment by jcarnus** [comment]
Is it enough ?

Thanks

**Comment by xemul** [comment]
Yup, thanks. This is the '/usr/share/dbus1-/system-services' one. It was recently added with the commit 7f44f1dbf9935582a21e8b1f24a5b4396f2c3795. You can either pull one into your sources, or switch to criu head.

**Comment by jcarnus** [comment]
Yes works now.
I close it.

**Comment by 2000yeshu** [comment]
I am getting the same error with `/usr/share/dbus-1/services`

**Comment by vikas-goel** [comment]
Observing this issue with criu-3.19-1.el9.x86_64 for /usr/bin/dbus-daemon.

**Comment by rst0git** [comment]
@vikas-goel I believe https://github.com/checkpoint-restore/criu/pull/2324 aims to fix the error for `/usr/bin/dbus-daemon`, and the corresponding patch has been merged in CRIU version 4.0.
