### ISSUE TITLE
Non inclusive sets of cgroups when dumping

### ISSUE THREAD

**Issue by aku163** [xemul/criu#78]
Hi all,

I got below failure with docker [docker-1.9.0-dev ](https://github.com/boucher/docker/releases/download/v1.9.0-experimental-cr.1/docker-1.9.0-dev).

```criu failed: type NOTIFY errno 0```
```Error: failed to checkpoint one or more containers```

Scenario:

* OS: CentOS Linux release 7.1.1503 (Core)
* Kernel: 3.18.4
* Docker: Docker version 1.9.0-dev, build 59c375a, experimental

Attached are the commands which I ran and dump logs.

[commands](https://github.com/aku163/artefacts/blob/master/commands.txt)
[dump log file] (https://github.com/aku163/artefacts/blob/master/dump.log)

Can you please help me with this issue?

PS : The same thing works fine if I use busybox image as [checkpoint_restore] (https://github.com/boucher/docker/blob/cr-combined/experimental/checkpoint_restore.md)

**Comment by avagin** [comment]
(00.123705) Error (sk-inet.c:158): Connected TCP socket, consider using tcp-established option.

**Comment by aku163** [comment]
@avagin : Thanks for pitching in. But I did not get `--tcp-established` in-built option with docker command. 

`Usage:  docker checkpoint [OPTIONS] CONTAINER [CONTAINER...]`

`Checkpoint one or more running containers`

`  --allow-ext-unix=false    allow checkpointing external unix connections`
`  --allow-shell=false       allow checkpointing shell jobs`
`  --allow-tcp=false         allow checkpointing tcp connections`
`  --help=false              Print usage`
`  --image-dir=              directory for storing checkpoint image files`
`  --leave-running=false     leave the container running after checkpoint`
`  --work-dir=               directory for storing log file`


Should I have to rebuild from tree?

**Comment by avagin** [comment]
You need to set --allow-tcp

**Comment by aku163** [comment]
Still no luck !!


I tried running below command to take dump

`docker checkpoint --allow-ext-unix=true --allow-shell=true --allow-tcp=true --image-dir=/opt/mule --work-dir=/opt/mule b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152`

Complete log is [here](https://github.com/aku163/artefacts/blob/master/dump1.log).

Below is the error snippet. 

`(02.829086) cg:  ``- Dumping 3 set (10 ctls)`
`(02.829121) Error (cgroup.c:758): cg: Set 3 is not subset of 2`
`(02.829411) Unlock network`
`(02.829505) Running network-unlock scripts`
`(02.829521)     RPC`
`(02.829964) Unfreezing tasks into 1`
`(02.829971)     Unseizing 21171 into 1`
`(02.829998)     Unseizing 21308 into 1`
`(02.830009)     Unseizing 21310 into 1`
`(02.830654) Error (cr-dump.c:1631): Dumping FAILED.`

**Comment by xemul** [comment]
> (02.829121) Error (cgroup.c:758): cg: Set 3 is not subset of 2

Would you show the cgroups layout for your Docker container?

**Comment by aku163** [comment]
Hi @xemul 
If I am not wrong, Below is the information (inside container) which you are looking for.

/sys/fs/cgroup/
├── blkio
│   ├── blkio.io_merged
│   ├── blkio.io_merged_recursive
│   ├── blkio.io_queued
│   ├── blkio.io_queued_recursive
│   ├── blkio.io_service_bytes
│   ├── blkio.io_service_bytes_recursive
│   ├── blkio.io_serviced
│   ├── blkio.io_serviced_recursive
│   ├── blkio.io_service_time
│   ├── blkio.io_service_time_recursive
│   ├── blkio.io_wait_time
│   ├── blkio.io_wait_time_recursive
│   ├── blkio.leaf_weight
│   ├── blkio.leaf_weight_device
│   ├── blkio.reset_stats
│   ├── blkio.sectors
│   ├── blkio.sectors_recursive
│   ├── blkio.throttle.io_service_bytes
│   ├── blkio.throttle.io_serviced
│   ├── blkio.throttle.read_bps_device
│   ├── blkio.throttle.read_iops_device
│   ├── blkio.throttle.write_bps_device
│   ├── blkio.throttle.write_iops_device
│   ├── blkio.time
│   ├── blkio.time_recursive
│   ├── blkio.weight
│   ├── blkio.weight_device
│   ├── cgroup.clone_children
│   ├── cgroup.procs
│   ├── notify_on_release
│   └── tasks
├── cpu -> cpu,cpuacct
├── cpuacct -> cpu,cpuacct
├── cpu,cpuacct
│   ├── cgroup.clone_children
│   ├── cgroup.procs
│   ├── cpuacct.stat
│   ├── cpuacct.usage
│   ├── cpuacct.usage_percpu
│   ├── cpu.cfs_period_us
│   ├── cpu.cfs_quota_us
│   ├── cpu.rt_period_us
│   ├── cpu.rt_runtime_us
│   ├── cpu.shares
│   ├── cpu.stat
│   ├── notify_on_release
│   └── tasks
├── cpuset
│   ├── cgroup.clone_children
│   ├── cgroup.procs
│   ├── cpuset.cpu_exclusive
│   ├── cpuset.cpus
│   ├── cpuset.effective_cpus
│   ├── cpuset.effective_mems
│   ├── cpuset.mem_exclusive
│   ├── cpuset.mem_hardwall
│   ├── cpuset.memory_migrate
│   ├── cpuset.memory_pressure
│   ├── cpuset.memory_spread_page
│   ├── cpuset.memory_spread_slab
│   ├── cpuset.mems
│   ├── cpuset.sched_load_balance
│   ├── cpuset.sched_relax_domain_level
│   ├── notify_on_release
│   └── tasks
├── devices
│   ├── cgroup.clone_children
│   ├── cgroup.procs
│   ├── devices.allow
│   ├── devices.deny
│   ├── devices.list
│   ├── notify_on_release
│   └── tasks
├── freezer
│   ├── cgroup.clone_children
│   ├── cgroup.procs
│   ├── freezer.parent_freezing
│   ├── freezer.self_freezing
│   ├── freezer.state
│   ├── notify_on_release
│   └── tasks
├── hugetlb
│   ├── cgroup.clone_children
│   ├── cgroup.procs
│   ├── hugetlb.2MB.failcnt
│   ├── hugetlb.2MB.limit_in_bytes
│   ├── hugetlb.2MB.max_usage_in_bytes
│   ├── hugetlb.2MB.usage_in_bytes
│   ├── notify_on_release
│   └── tasks
├── memory
│   ├── cgroup.clone_children
│   ├── cgroup.event_control
│   ├── cgroup.procs
│   ├── memory.failcnt
│   ├── memory.force_empty
│   ├── memory.kmem.failcnt
│   ├── memory.kmem.limit_in_bytes
│   ├── memory.kmem.max_usage_in_bytes
│   ├── memory.kmem.slabinfo
│   ├── memory.kmem.tcp.failcnt
│   ├── memory.kmem.tcp.limit_in_bytes
│   ├── memory.kmem.tcp.max_usage_in_bytes
│   ├── memory.kmem.tcp.usage_in_bytes
│   ├── memory.kmem.usage_in_bytes
│   ├── memory.limit_in_bytes
│   ├── memory.max_usage_in_bytes
│   ├── memory.memsw.failcnt
│   ├── memory.memsw.limit_in_bytes
│   ├── memory.memsw.max_usage_in_bytes
│   ├── memory.memsw.usage_in_bytes
│   ├── memory.move_charge_at_immigrate
│   ├── memory.numa_stat
│   ├── memory.oom_control
│   ├── memory.pressure_level
│   ├── memory.soft_limit_in_bytes
│   ├── memory.stat
│   ├── memory.swappiness
│   ├── memory.usage_in_bytes
│   ├── memory.use_hierarchy
│   ├── notify_on_release
│   └── tasks
├── net_cls
│   ├── cgroup.clone_children
│   ├── cgroup.procs
│   ├── net_cls.classid
│   ├── notify_on_release
│   └── tasks
├── perf_event
│   ├── cgroup.clone_children
│   ├── cgroup.procs
│   ├── cgroup.sane_behavior
│   ├── notify_on_release
│   ├── release_agent
│   └── tasks
└── systemd
    ├── cgroup.clone_children
    ├── cgroup.procs
    ├── notify_on_release
    └── tasks

Let me know if further info is required.

**Comment by avagin** [comment]
```
(00.048366) cg:  `- New css ID 2
(00.048376) cg:     `- [blkio] -> [/system.slice/docker-239683c87a15960cbbbaef714ecf2e5d7115a1a45d50775911278d30b98f2355.scope]
(00.048383) cg:     `- [cpu,cpuacct] -> [/system.slice/docker-239683c87a15960cbbbaef714ecf2e5d7115a1a45d50775911278d30b98f2355.scope]
(00.048388) cg:     `- [cpuset] -> [/system.slice/docker-239683c87a15960cbbbaef714ecf2e5d7115a1a45d50775911278d30b98f2355.scope]
(00.048393) cg:     `- [devices] -> [/system.slice/docker-239683c87a15960cbbbaef714ecf2e5d7115a1a45d50775911278d30b98f2355.scope]
(00.048398) cg:     `- [freezer] -> [/system.slice/docker-239683c87a15960cbbbaef714ecf2e5d7115a1a45d50775911278d30b98f2355.scope]
(00.048402) cg:     `- [hugetlb] -> [/system.slice/docker-239683c87a15960cbbbaef714ecf2e5d7115a1a45d50775911278d30b98f2355.scope]
(00.048407) cg:     `- [memory] -> [/system.slice/docker-239683c87a15960cbbbaef714ecf2e5d7115a1a45d50775911278d30b98f2355.scope]
(00.048412) cg:     `- [name=systemd] -> [/system.slice/docker-239683c87a15960cbbbaef714ecf2e5d7115a1a45d50775911278d30b98f2355.scope]
(00.048417) cg:     `- [net_cls] -> [/system.slice/docker-239683c87a15960cbbbaef714ecf2e5d7115a1a45d50775911278d30b98f2355.scope]
(00.048422) cg:     `- [perf_event] -> [/]

(00.179441) cg:     `- [blkio] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179448) cg:     `- [cpu,cpuacct] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179453) cg:     `- [cpuset] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179458) cg:     `- [devices] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179462) cg:     `- [freezer] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179467) cg:     `- [hugetlb] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179472) cg:     `- [memory] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179477) cg:     `- [name=systemd] -> [/system.slice/docker.service]
(00.179482) cg:     `- [net_cls] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179487) cg:     `- [perf_event] -> [/]
```

**Comment by avagin** [comment]
```
(00.088551) cg:  `- New css ID 2
(00.088599) cg:     `- [blkio] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.088613) cg:     `- [cpu,cpuacct] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.088621) cg:     `- [cpuset] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.088632) cg:     `- [devices] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.088642) cg:     `- [freezer] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.088653) cg:     `- [hugetlb] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.088661) cg:     `- [memory] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.088670) cg:     `- [name=systemd] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.088680) cg:     `- [net_cls] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.088688) cg:     `- [perf_event] -> [/]
(00.088695) cg: Set 2 is root one

(00.179194) cg: Dumping cgroups for 21308
(00.179422) cg:  `- New css ID 3
(00.179441) cg:     `- [blkio] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179448) cg:     `- [cpu,cpuacct] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179453) cg:     `- [cpuset] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179458) cg:     `- [devices] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179462) cg:     `- [freezer] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179467) cg:     `- [hugetlb] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179472) cg:     `- [memory] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179477) cg:     `- [name=systemd] -> [/system.slice/docker.service]
(00.179482) cg:     `- [net_cls] -> [/system.slice/docker-b8c437b15a6e6d66c8b1326d9673f3552fae0cd30100222b6e686829f354e152.scope]
(00.179487) cg:     `- [perf_event] -> [/]
```

**Comment by aku163** [comment]
There is always the case that dump fails when scenario is 

1. start container with sshd daemon
2. start application process (either httpd, or mule)

But If I take checkpoint/restore only with sshd daemon running in container. I don't see the logs complaining about any kind of error. 

Any clue, if this case can fall into a solution bucket?

**Comment by xemul** [comment]
The 21308 is, presumably, the app process started on step 2, isn't it?

**Comment by avagin** [comment]
Looks like a bug in docker exec:
```
[avagin@laptop ~]$ sudo docker exec 51ea0a987a66 sleep 1000
^Z
[1]+  Stopped                 sudo docker exec 51ea0a987a66 sleep 1000

 4680 ?        Ssl    0:16 /usr/bin/docker -d --selinux-enabled
11123 pts/2    Ss+    0:00  \_ bash
11701 ?        Ss     0:00  |   \_ /usr/sbin/httpd
11702 ?        S      0:00  |   |   \_ /usr/sbin/httpd
11703 ?        S      0:00  |   |   \_ /usr/sbin/httpd
11704 ?        S      0:00  |   |   \_ /usr/sbin/httpd
11705 ?        S      0:00  |   |   \_ /usr/sbin/httpd
11706 ?        S      0:00  |   |   \_ /usr/sbin/httpd
11846 pts/2    S      0:00  |   \_ /usr/sbin/sshd -D
12637 ?        Ss     0:00  \_ sleep 1000

[avagin@laptop ~]$ cat /proc/12637/cgroup 
10:perf_event:/
9:devices:/system.slice/docker-51ea0a987a6635d0e23854a3fcefa8a2d30a917bd7f716ab2a68d05a16dc306f.scope
8:freezer:/system.slice/docker-51ea0a987a6635d0e23854a3fcefa8a2d30a917bd7f716ab2a68d05a16dc306f.scope
7:hugetlb:/system.slice/docker-51ea0a987a6635d0e23854a3fcefa8a2d30a917bd7f716ab2a68d05a16dc306f.scope
6:net_cls,net_prio:/system.slice/docker-51ea0a987a6635d0e23854a3fcefa8a2d30a917bd7f716ab2a68d05a16dc306f.scope
5:memory:/system.slice/docker-51ea0a987a6635d0e23854a3fcefa8a2d30a917bd7f716ab2a68d05a16dc306f.scope
4:cpu,cpuacct:/system.slice/docker-51ea0a987a6635d0e23854a3fcefa8a2d30a917bd7f716ab2a68d05a16dc306f.scope
3:cpuset:/system.slice/docker-51ea0a987a6635d0e23854a3fcefa8a2d30a917bd7f716ab2a68d05a16dc306f.scope
2:blkio:/system.slice/docker-51ea0a987a6635d0e23854a3fcefa8a2d30a917bd7f716ab2a68d05a16dc306f.scope
1:name=systemd:/system.slice/docker.service
```

**Comment by aku163** [comment]
@xemul : That's correct, 21308  started at step 2 which further spawns another child process 21310.

@avagin : To clear the doubt of exec, I tried starting services using nsenter but result is same. No Success.

**Comment by xemul** [comment]
@aku163 , OK, then it's due to bug with entering the container -- task remains in the old set of cgroups. And doing this via nsenter is not expected to fix this ;)

**Comment by aku163** [comment]
Seeking help from @boucher.
Thanks.

**Comment by xemul** [comment]
You can also join the fun at https://github.com/docker/docker/pull/13602 where we try to push the C/R API natively into Docker.

**Comment by avagin** [comment]
Cc: @lk4d4

**Comment by LK4D4** [comment]
For now I personally would recommend to use `--exec-opt native.cgroupdriver=cgroupfs` because systemd cgroups doesn't work as expected and behavior differ from version to version of systemd. We need to fix it, but I don't see good generic solution now.

**Comment by aku163** [comment]
I tried with this option with docekr daemon start. But still checkpoint fails with same reason

`(02.055377) Error (cgroup.c:758): cg: Set 3 is not subset of 2`
`(02.057942) Error (cr-dump.c:1631): Dumping FAILED.`

**Comment by boucher** [comment]
Hi, sorry I just saw this thread. Unfortunately I don't have any suggestion, this isn't something I've seen before. Is there a reason you're spawning your second process with exec, and not just as part of your dockerfile/CMD?

**Comment by LK4D4** [comment]
Then could you post your `/proc/pid/cgroup` from both processes? They seem to be identical for me.

**Comment by aku163** [comment]
@boucher : That is behaviour of the process that it spawns other process by itself, we just call it from exec. 

We are managing all the processes from a shared-dir which is mounted to each of the containers and having multiple shell scripts responsible for respective containers.

There is a case that services of more than one containers are dependent only on one container till it gets up.


I tried using external way to take dump [docker_cr.sh](https://github.com/aku163/artefacts/blob/master/docker_cr.sh) but it seems the same implementation as that of using `docker checkpoint` option.


@LK4D4 : Below are the details


Inside containers:

`UID        PID  PPID  C STIME TTY          TIME CMD`

`root         1     0  0 Oct29 ?        00:00:00 /usr/sbin/sshd -D`

`mule       102     1  0 Oct29 ?        00:02:07 /apps/mule/mule-standalone-3.2.1/lib/boot/exec/wrapper-linux-x86-64 /apps/m...`

`mule       104   102  1 Oct29 ?        00:14:29 java -Dmule.home=/apps/mule/mule-standalone-3.2.1 -Dmule.base=/apps/mule/mu...`


PID: 102

			10:hugetlb:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			9:perf_event:/
			8:blkio:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			7:net_cls:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			6:freezer:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			5:devices:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			4:memory:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			3:cpu,cpuacct:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			2:cpuset:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			1:name=systemd:/system.slice/docker.service

PID: 104

			10:hugetlb:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			9:perf_event:/
			8:blkio:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			7:net_cls:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			6:freezer:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			5:devices:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			4:memory:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			3:cpu,cpuacct:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			2:cpuset:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			1:name=systemd:/system.slice/docker.service

PID : 1

			10:hugetlb:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			9:perf_event:/
			8:blkio:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			7:net_cls:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			6:freezer:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			5:devices:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			4:memory:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			3:cpu,cpuacct:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			2:cpuset:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope
			1:name=systemd:/system.slice/docker-e8d15222bdd8021ae06c272ca3e0bd31f09103338e5b4b5a80a14caafabb425d.scope

**Comment by LK4D4** [comment]
@aku163 hmm, it's same for me on docker master. Can you show `/proc/1/cgroup` from host?

**Comment by aku163** [comment]
10:hugetlb:/
9:perf_event:/
8:blkio:/
7:net_cls:/
6:freezer:/
5:devices:/
4:memory:/
3:cpu,cpuacct:/
2:cpuset:/
1:name=systemd:/

**Comment by aku163** [comment]
Below were the scenarios which I tried again 

1. container A is started with service S using Dockerfile -> Checkpoint was taken into directory D -> Restore was done from D to A [SUCCESS]
2. Assuming D does container the checkpoint image -> Started container B (from base image of container A) with no services running in it -> Restore failed when it was taken from D to B with below error.

[restore.log](https://github.com/aku163/artefacts/blob/master/restore.log)

Somewhere on a blog, I read that via criu feature, we can restore the filesystem to an empty container but it doesn't seems to be working.

**Comment by aku163** [comment]
[Blog](http://blog.circleci.com/checkpoint-and-restore-docker-container-with-criu/) states similar scenario where the restore was happened on a new container. But there seems to be no process state which was taken while checkpoint hence no issues.

@avagin , @ldu4 , @boucher : Looking for your views, If my assumption is correct that we can restore to container from filesystem(as part of checkpoint) or I missed anything?

**Comment by xemul** [comment]
Presumably after "native" Docker C/R support this is no longer an issue.
