### ISSUE TITLE
After Docker restore, web app no longer replies to requests

### ISSUE THREAD

**Issue by ilackarms** [xemul/criu#80]
I create a simple python webserver:
```
vagrant@mesos:~$ PORTMAP=31120:8080 NAME=foo IMAGE=python:3 COMMAND="python3 -m http.server 8080"
vagrant@mesos:~$ sudo docker run -d -p $PORTMAP --name $NAME $IMAGE /bin/sh -c "${COMMAND}"
85900905883f2a7099006f76dbba4b6fb4a01f3b2d14431916e07696aad1491f
```

After running, I can cURL on localhost:31120:
```
$ curl localhost:31120 -i
HTTP/1.0 200 OK
Server: SimpleHTTP/0.6 Python/3.5.0
Date: Fri, 23 Oct 2015 17:50:04 GMT
Content-type: text/html; charset=utf-8
Content-Length: 1034

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
...
```

Then, after very simple checkpoint/restore, I can no longer access the ports from the container:
```
vagrant@mesos:~$ sudo docker checkpoint $NAME
foo
vagrant@mesos:~$ sudo docker restore $NAME
foo
vagrant@mesos:~$ curl localhost:31120 -i
curl: (56) Recv failure: Connection reset by peer
```

`docker ps` shows the container is running, with ports (supposedly) exposed:
```
vagrant@mesos:~$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                     NAMES
85900905883f        python:3            "/bin/sh -c 'python3 "   5 minutes ago       Up 2 minutes        0.0.0.0:31120->8080/tcp   foo
```

Note that if I do a `docker stop $NAME && docker start $NAME` I can once again cURL the target port, and get the expected response. How can I achieve the same behavior with checkpoint/restore? I am using https://github.com/boucher/docker/releases/download/v1.9.0-experimental-cr.1/docker-1.9.0-dev release of docker.

**Comment by ilackarms** [comment]
checked and verified that `docker pause foo && docker unpause foo` also works (container is still accessible).

**Comment by xemul** [comment]
I'm not sure that Docker C/R API reconfigures the networking for container the right way. Asking @boucher for help.

**Comment by boucher** [comment]
Yes, it's a known issue that networking doesn't work after restore right now. However, you can try this branch: https://github.com/huikang/docker/tree/fix-restore-network-cr-combined-1006

**Comment by xemul** [comment]
I guess the networking is handled in Docker C/R nowadays.
Please, correct me if I'm wrong.
