### ISSUE TITLE
Support non-coinciding cg controllers on dump and restore sides

### ISSUE THREAD

**Issue by rohitju** [xemul/criu#83]
I am trying to restore a Docker container using CRIU v1.6 and Docker v1.9 (built from https://github.com/huikang/docker/tree/fix-restore-network-cr-combined-1006).
Checkpoint command (on Ubuntu 14.04 AWS):

`/bundles/1.9.0-dev/binary/docker-1.9.0-dev checkpoint --image-dir=/home/ubuntu/checkpoints/v4/ sharp_kowalevski`

Restore command (on a different Ubuntu machine from the same image):
`./bundles/1.9.0-dev/binary/docker-1.9.0-dev restore --force=true --image-dir ./v4/ --work-dir /tmp/ $(./bundles/1.9.0-dev/binary/docker-1.9.0-dev create --name=sharp_kowalevski fluid_sim_cont:v4)`

The restore fails with the last line in the log being this : "Error (cgroup.c:1189): cg: Can't mount .criu.cgyard.FPZHIC/net_cls cgyard: No such file or directory"

The complete log is here: https://gist.github.com/rohitju/0d74819e02f1537cf227

Am I missing any command line option? Or are there any other logs which might help figure out the cause?

**Comment by xemul** [comment]
Did you made dump and restore on the same host?
Cc @huikang and @boucher

**Comment by rohitju** [comment]
Yes, dump and restore on the same host worked fine. Moving the image dir to a different host and attempting a restore failed with the above error.

**Comment by xemul** [comment]
Can you show the contents of /proc/cgroups file on both nodes?

**Comment by rohitju** [comment]
The /proc/cgroups for the machine where snapshot was created is:
```
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	1	7	1
cpu	2	7	1
cpuacct	3	7	1
memory	4	13	1
devices	5	7	1
freezer	6	7	1
net_cls	7	7	1
blkio	8	7	1
perf_event	9	7	1
net_prio	10	7	1
hugetlb	11	7	1

```


The restore machine /proc/cgroups are here:
```
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	3	2	1
cpu	4	2	1
cpuacct	5	2	1
memory	6	2	1
devices	7	2	1
freezer	8	2	1
blkio	9	2	1
perf_event	10	2	1
hugetlb	11	2	1

```

I see the extra net_cls on the snapshot machine which is not present on the restore machine so it would seem to be an environment problem. I assumed that creating both machines from the same image would avoid this problem. Would you happen to know why one machine had it and the other did not?
Thanks!

**Comment by xemul** [comment]
The absence of the controller on the 2nd box is fully kernel issue, not the docker one -- you don't have it compiled in. This is something that CRIU could support, but it requires patching.

**Comment by xemul** [comment]
So, now we have native Docker C/R and the whole bunch of options to tune the way cgroups are managed (https://criu.org/CGroups)
