### ISSUE TITLE
No output for fdinfo on epoll with big number of entries

### ISSUE THREAD

**Issue by cyrillos** [xemul/criu#86]
When there is too many events assigned on the epoll descriptor (to be precise more than 78 entries) then fdinfo output is empty. This is due to nit in vanilla kernel, which should be fixed in commit https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=a3816ab0e8fe542a89a53b82506a8ddac063fbe

IOW, the issue should be fixed in 3.18 kernel. Need to test it via zdtm.

**Comment by cyrillos** [comment]
OK, with new Fedora 23 (4.2.5) all works as expected. IOW, please use the kernel 3.18 or above for epolls with big numbers of assignments.

**Comment by xemul** [comment]
OK, thank you.
