### ISSUE TITLE
Cannot checkpoint my docker container - criu failed: type NOTIFY errno 0

### ISSUE THREAD

**Issue by alldaudinot** [xemul/criu#89]
hi everybody

i am trying to checkpoint my container (containing a webapp) but the process is failing. 

i get the following messages:

Error response from daemon: Cannot checkpoint container web-app: criu
failed: type NOTIFY errno 0
log file:
/var/lib/docker/0.0/containers/c0c3927059ed6d0504fb01bbbbc1257fc052da6659cdd34d576e156dedae412e/criu.work/dump.log
Error: failed to checkpoint one or more containers

by exploring the dump.log file, i suspect that it is related with socket
connection

thanks a million, your work is great.

[dump.txt](https://github.com/xemul/criu/files/45946/dump.txt)

**Comment by xemul** [comment]
This is issue #62 . Quite nasty, yes, hopefully will have it fixed after 1.8 :)
