### ISSUE TITLE
criu to checkpoint/restore simple loop in ARM64 arch?

### ISSUE THREAD

**Issue by moypray** [xemul/criu#90]
Hi, does criu support arm64 architecture yet? I am using latest master branch criu to c/r the application in arm64 machines (just the simple loop in "https://criu.org/Simple_loop").

criu dump succeed but restore failed:

using strace -f to trace it:
[pid 20362] mremap(0x7fb7ab0000, 1249280, 1249280, MREMAP_MAYMOVE|MREMAP_FIXED, 0x7fb7e89000) = 0x7fb7e89000
[pid 20362] write(1023, "pie: Remap 0x7fb7941000->0x7fb7d"..., 51) = 51
[pid 20362] mremap(0x7fb7941000, 1503232, 1503232, MREMAP_MAYMOVE|MREMAP_FIXED, 0x7fb7d13000) = 0x7fb7d13000
[pid 20362] write(1023, "pie: Remap 0x7fb7940000->0x7fb7d"..., 49) = 49
[pid 20362] mremap(0x7fb7940000, 4096, 4096, MREMAP_MAYMOVE|MREMAP_FIXED, 0x7fb7d12000) = 0x7fb7d12000
[pid 20362] write(1023, "pie: Remap 0x7fb793f000->0x7fb7d"..., 49) = 49
[pid 20362] mremap(0x7fb793f000, 4096, 4096, MREMAP_MAYMOVE|MREMAP_FIXED, 0x7fb7d11000) = 0x7fb7d11000
[pid 20362] write(1023, "pie: Remap 0x7fb7919000->0x7fb7c"..., 50) = 50
[pid 20362] mremap(0x7fb7919000, 155648, 155648, MREMAP_MAYMOVE|MREMAP_FIXED, 0x7fb7ceb000) = 0x7fb7ceb000
[pid 20362] mmap(0x7fb7e82000, 28672, PROT_READ|PROT_EXEC, MAP_SHARED|MAP_FIXED, 3, 0) = 0x7fb7e82000
[pid 20362] close(3)                    = 0
[pid 20362] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x5c90} ---
[pid 20362] +++ killed by SIGSEGV +++
[pid 20318] <... mremap resumed> )      = 0x7fb7ff0000
[pid 20318] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_KILLED, si_pid=20362, si_status=SIGSEGV, si_utime=0, si_stime=0} ---
[pid 20318] write(1023, "pie: Task 20362  killed by signa"..., 38) = 38
[pid 20318] futex(0x22010, FUTEX_WAKE, 2147483647) = 1
[pid 20445] <... futex resumed> )       = 0
[pid 20318] getpid( <unfinished ...>
[pid 20445] kill(20318, SIGKILL <unfinished ...>
[pid 20318] <... getpid resumed> )      = 20318
[pid 20445] <... kill resumed> )        = 0

Full restore.log is below:
task_args->thread_args: 0x16540
pie: Switched to the restorer 20362
pie: Remap 0x7fb7c4b000->0x5555555000 len 0x19000
pie: Remap 0x7fb7c64000->0x555557d000 len 0x2000
pie: Remap 0x7fb7c66000->0x555557f000 len 0x1000
pie: Remap 0x7fb7c67000->0x5555580000 len 0x23000
pie: Remap 0x7fb78f1000->0x400000 len 0x5000
pie: Remap 0x7fb7dfb000->0x7ffffde000 len 0x22000
pie: Remap 0x7fb78f6000->0x415000 len 0x1000
pie: Remap 0x7fb78f7000->0x416000 len 0x1000
pie: Remap 0x7fb7df8000->0x7fb7fff000 len 0x2000
pie: Remap 0x7fb78f8000->0x417000 len 0x21000
pie: Remap 0x7fb7df7000->0x7fb7ffe000 len 0x1000
pie: Remap 0x7fb7c29000->0x7ffffde000 len 0x22000
pie: Remap 0x7fb7df6000->0x7fb7ffd000 len 0x1000
pie: Remap 0x7fb7c26000->0x7fb7fff000 len 0x2000
pie: Remap 0x7fb7df5000->0x7fb7ffc000 len 0x1000
pie: Remap 0x7fb7c25000->0x7fb7ffe000 len 0x1000
pie: Remap 0x7fb7df3000->0x7fb7ffa000 len 0x2000
pie: Remap 0x7fb7c24000->0x7fb7ffd000 len 0x1000
pie: Remap 0x7fb7df0000->0x7fb7ff0000 len 0x3000
pie: Remap 0x7fb7c23000->0x7fb7ffc000 len 0x1000
pie: Remap 0x7fb7dd4000->0x7fb7fd3000 len 0x1c000
pie: Remap 0x7fb7c21000->0x7fb7ffa000 len 0x2000
pie: Remap 0x7fb7dd0000->0x7fb7fcf000 len 0x4000
pie: Remap 0x7fb7c20000->0x7fb7ff9000 len 0x1000
pie: Remap 0x7fb7dce000->0x7fb7fcd000 len 0x2000
pie: Remap 0x7fb7c1f000->0x7fb7ff8000 len 0x1000
pie: Remap 0x7fb7dca000->0x7fb7fc9000 len 0x4000
pie: Remap 0x7fb7c1e000->0x7fb7ff7000 len 0x1000
pie: Remap 0x7fb7dbb000->0x7fb7fba000 len 0xf000
pie: Remap 0x7fb7c1d000->0x7fb7ff6000 len 0x1000
pie: Remap 0x7fb7c8a000->0x7fb7e89000 len 0x131000
pie: Remap 0x7fb7c1c000->0x7fb7ff5000 len 0x1000
pie: Remap 0x7fb7c1b000->0x7fb7ff4000 len 0x1000
pie: Remap 0x7fb7c1a000->0x7fb7ff3000 len 0x1000
pie: Remap 0x7fb7c17000->0x7fb7ff0000 len 0x3000
pie: Remap 0x7fb7c16000->0x7fb7fef000 len 0x1000
pie: Remap 0x7fb7bfa000->0x7fb7fd3000 len 0x1c000
pie: Remap 0x7fb7bf6000->0x7fb7fcf000 len 0x4000
pie: Remap 0x7fb7bf4000->0x7fb7fcd000 len 0x2000
pie: Remap 0x7fb7bf0000->0x7fb7fc9000 len 0x4000
pie: Remap 0x7fb7be1000->0x7fb7fba000 len 0xf000
pie: Remap 0x7fb7ab0000->0x7fb7e89000 len 0x131000
pie: Remap 0x7fb7941000->0x7fb7d13000 len 0x16f000
pie: Remap 0x7fb7940000->0x7fb7d12000 len 0x1000
pie: Remap 0x7fb793f000->0x7fb7d11000 len 0x1000
pie: Remap 0x7fb7919000->0x7fb7ceb000 len 0x26000
(00.060299) Error (cr-restore.c:1264): 20318 killed by signal 11
(00.060327) Error (cr-restore.c:1995): Restoring FAILED.

Does anyone help to have a look at this? thanks a lot.

**Comment by moypray** [comment]
And more,  I use -v4 to get more logs:

pie:    mmap(0x7fb7e82000 -> 0x7fb7e89000, 0x1 0x11 3)
pie: vdso: Parsing at 0x7fb7ffd000 0x7fb7ffe000
pie: vdso: PT_LOAD p_vaddr: 0x0
pie: vdso: DT_HASH: 0x120
pie: vdso: DT_STRTAB: 0x1f8
pie: vdso: DT_SYMTAB: 0x150
pie: vdso: DT_STRSZ: 0x77
pie: vdso: DT_SYMENT: 0x18
pie: vdso: nbucket 0x3 nchain 0x7 bucket 0x7fb7ffd128 chain 0x7fb7ffd1>
pie: 34
(00.037127) Error (cr-restore.c:1264): 20510 killed by signal 11
(00.037153) Error (cr-restore.c:1995): Restoring FAILED.

**Comment by xemul** [comment]
Well, we have a guy on the mailing list who plays with the arm port :) Unfortunately he doesn't have github account, so I cannot CC him here. I'll try to reach him over the e-mail.

**Comment by moypray** [comment]
hi @xemul ,  thanks for your response. Does he work on ARM64 or ARM32?

and do you have his/her email?? Or I can send E-mail to criu mail-list will find him??

thanks again.

**Comment by xemul** [comment]
It's Christopher Covington, you can find his e-mail either on the mailing list or in 871da9a111479a2b53071e60bfc3263458873867 commit (his one).

And he plays with both :)

**Comment by moypray** [comment]
@xemul , thanks, and see your e-mail.

**Comment by xemul** [comment]
@moypray , I've slightly lost the track of the ARM stuff happening out there. There have been some fixes for it, so do we consider this issue to be fixed already?

**Comment by xemul** [comment]
Presumably fixed. Feel free to re-open if smth is still bad with aarch64.
