### ISSUE TITLE
External fsroot mount doesn't work as external

### ISSUE THREAD

**Issue by x1022as** [xemul/criu#93]
Hi, all. I was trying to dump and restore docker containers with volumes mounted, and came across some problems with nfs and block device. here is the description:

criu version:
```
~# criu --version
Version: 1.7
GitID: v1.7-384-g12db8a4
```
distribution:
```
~# cat /etc/issue
Ubuntu 15.10 \n \l
~# uname -r
4.2.0-19-generic
```

here is my mount info:
```
/dev/sda5 on /home type ext4 (rw,relatime,data=ordered)
192.168.28.165:/nfs on /mnt/nfs type nfs4 ...
/dev/mapper/af603988-e20a-48ec-b104-bf0ca2519236 on /mnt/devmap type ext4 (rw,relatime,stripe=512,data=ordered)
```

I tried to run container with following command:
```
docker-1.10.0-dev run -v ${HOST_PATH}:/vol -d busybox:latest /bin/sh -c 'i=0; while true; do echo $i >> /vol/foo; i=$(expr $i + 1); sleep 1; done'
```
replace ${HOST_PATH} with /home, /home/test, /mnt/nfs, /mnt/nfs/test, /mnt/devmap and /mnt/devmap/test. to verify how nfs, device-mapper and block mount works in criu dump. here is the result:

/home:
    failed, dump.log is "Error (mount.c:680): mnt: FS mnt ./vol dev 0x800005 root / unsupported id 232"

/home/test
    ok

/mnt/nfs:
    failed, dump.log is "Error (mount.c:680): mnt: FS mnt ./vol dev 0x35 root / unsupported id 241"

/mnt/nfs/test:
    failed, dump.log is "Error (mount.c:680): mnt: FS mnt ./vol dev 0x35 root / unsupported id 241"

/mnt/devmap:
    failed, dump.log is "Error (mount.c:680): mnt: FS mnt ./vol dev 0xfc00001 root / unsupported id 241"

/mnt/devmap/test:
    ok

nfs and root path in block device(I am not sure about this, just get this from dump.log) not supported yet? if not , are there any thoughts about this? Because nfs and block devices are really useful in docker volume.

**Comment by xemul** [comment]
If this is about docker volume, then it's likely to be fixed by --ext-mount-map. Cc @boucher

**Comment by x1022as** [comment]
/home works fine and /home/test failed. So, maybe not a "--ext-mount-map" problem?

**Comment by xemul** [comment]
Ah, I see. The volume is mounted inside container with its root dir. Yes, this is an issue inside CRIU. OK, will take a look at this.

**Comment by xemul** [comment]
@x1022as , would you check whether this patch helps: https://lists.openvz.org/pipermail/criu/2015-December/024627.html ?

**Comment by x1022as** [comment]
@xemul Great! That patch works for nfs and block device root dir!

**Comment by xemul** [comment]
@x1022as thanks :) If you could go and acknowledge the patch on the mailing list that would be just great. But anyway, I'll commit the patch and close the issue within several days.

**Comment by xemul** [comment]
ea68c33fff2b1f4bebd5efb6893661e9c9c5ee60

Thanks!
