### ISSUE TITLE
task not stopped after seize

### ISSUE THREAD

**Issue by avagin** [xemul/criu#94]
CRIU-x86_64-dedup - Build # 422 - Failure:

Check console output at https://ci.openvz.org/job/CRIU-x86_64-dedup/422/ to view the results.

===================== Run zdtm/live/static/stopped02 in h ======================
Start test
./stopped02 --pidfile=stopped02.pid --outfile=stopped02.out
Run criu pre-dump
Run criu pre-dump
Run criu dump
=[log]=> dump/zdtm/live/static/stopped02/72/3/dump.log
------------------------ grep Error ------------------------
(00.004053) Error (ptrace.c:137): SEIZE 73: task not stopped after seize
(00.004084) Error (ptrace.c:284): Unable to detach from 73: No such process
------------------------ ERROR OVER ------------------------
Run criu restore
Wait for zdtm/live/static/stopped02 to die for 0.100000
############# Test zdtm/live/static/stopped02 FAIL at result check #############
Test output: ================================
04:27:25.611:    72: FAIL: stopped02.c:69: The process doesn't stopped (errno = 11 (Resource temporarily unavailable))

 <<< ================================

**Comment by avagin** [comment]
To: @cyrillos

**Comment by cyrillos** [comment]
@avagin Isn't it related to the ptrace issue you've fixed (trapping bit)? I need to access the testing machine, how can I do that?

**Comment by xemul** [comment]
Guys, what do we do about this issue?

**Comment by cyrillos** [comment]
Nothing. There is a bug in KVM kernel code. We can't do anything until it fixed.
