### ISSUE TITLE
Trash in most significant bytes after sys_getresgid(which calls in dump_creds) on armv7 platform

### ISSUE THREAD

**Issue by k-artem** [xemul/criu#95]
###### Description:
In static int dump_creds(...) function  sys_getresgid set up only 16 least significant bits and most significant bits don't change and contain trash. By this reason image is invalid (creds part) and restoring process is failed (in may_restore->check_gids).
###### Hotfix is: 
initialize parasite_dump_creds.gids to 0 value
###### Possible reason: 
using of  getresgid16 for fill this array.
###### Platform: 
armv7
###### Criu version: 
1.8

**Comment by xemul** [comment]
Cc @cyrillos

**Comment by cyrillos** [comment]
Wow, thanks!

**Comment by xemul** [comment]
@cyrillos is this still valid?

**Comment by cyrillos** [comment]
Seems so. I need to revisit.

**Comment by cyrillos** [comment]
[PATCH] criu: pie -- Zap parasite_dump_creds::gids

I think we rather should cleanup the memory area with some new builtin-memset helper. I put fixme into the code.
