### ISSUE TITLE
(20.112917) Error (cr-restore.c:1324): 72 killed by signal 11

### ISSUE THREAD

**Issue by avagin** [xemul/criu#97]
https://ci.openvz.org/job/CRIU-freezer/25/console

================== Run zdtm/live/transition/thread-bomb in h ===================
Start test
./thread-bomb --pidfile=thread-bomb.pid --outfile=thread-bomb.out
12:06:13.080:    71: 1024
Run criu dump
Run criu restore
=[log]=> dump/zdtm/live/transition/thread-bomb/72/1/restore.log
------------------------ grep Error ------------------------
(20.112917) Error (cr-restore.c:1324): 72 killed by signal 11
(20.116843) Error (cr-restore.c:2138): Restoring FAILED.
------------------------ ERROR OVER ------------------------
########## Test zdtm/live/transition/thread-bomb FAIL at CRIU restore ##########

**Comment by cyrillos** [comment]
@avagin suspect it might be related to creds changes
Tried to start it locally

[cyrill@uranus criu] sudo test/zdtm.py run -t zdtm/live/transition/thread-bomb
=== Run 1/1 ================

================== Run zdtm/live/transition/thread-bomb in h ===================
Start test
./thread-bomb --pidfile=thread-bomb.pid --outfile=thread-bomb.out
14:16:53.566:    71: 5
Run criu dump
=[log]=> dump/zdtm/live/transition/thread-bomb/72/1/dump.log
------------------------ grep Error ------------------------
(00.001187) Error (util.c:349): Can't open 421: No such file or directory
(00.001190) Error (proc_parse.c:813): Can't open 421/status on procfs: No such file or directory
(00.001191) Error (proc_parse.c:815): Can't open proc status: No such file or directory
(00.001193) Error (ptrace.c:284): Unable to detach from 421: No such process
(00.001226) Error (util.c:349): Can't open 425: No such file or directory
(00.001229) Error (proc_parse.c:813): Can't open 425/status on procfs: No such file or directory
(00.001230) Error (proc_parse.c:815): Can't open proc status: No such file or directory
(00.001232) Error (ptrace.c:284): Unable to detach from 425: No such process
(00.001292) Error (cr-dump.c:1574): Dumping FAILED.
------------------------ ERROR OVER ------------------------
########### Test zdtm/live/transition/thread-bomb FAIL at CRIU dump ############
Wait for zdtm/live/transition/thread-bomb to die for 0.100000
##################################### FAIL #####################################
[cyrill@uranus criu]

**Comment by cyrillos** [comment]
no, its not because of creds, still wonder why it fails on my local run

**Comment by avagin** [comment]
@cyrillos Here is a correct command to reproduce this issue
```
./test/zdtm.py run -t zdtm/live/transition/thread-bomb -f h --report report --freezecg zdtm:f 
```

**Comment by cyrillos** [comment]
72    mremap(0x7f0a9125f000, 647168, 655360, MREMAP_MAYMOVE) = 0x7f0a911bf000 <0.000013>
72    --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x7f0a912fcf98} ---
72    +++ killed by SIGSEGV (core dumped) +++
...
Will take a look.

**Comment by avagin** [comment]
```
eb5d84428e8654a7bc9458ed732704a00cfbe0f4 is the first bad commit
commit eb5d84428e8654a7bc9458ed732704a00cfbe0f4
Author: Cyrill Gorcunov <gorcunov@gmail.com>
Date:   Mon Dec 21 14:08:00 2015 +0300

    creds: restore -- Implement per-thread restore of credentials
    
    Because the creds parameters are to be passed inside pie/restorer
    code but read before thread_restore_args and task_restore_args
    structures are allocated we need a small trick and prepare
    creds int several stages
    
     - collect all creds data into separate private memory blobs
     - once all memory needed for restorer is allocated we relocate
       pointers in this blocks and setup
       thread_restore_args::thread_creds_args to appropriate
       address
     - restorer works as usual and setup creds parameters as before
    
    v2:
     - fix addressing in positioning of rst_ memory (I've occasionally
       zap pointers and when been sending patches forgot to merge changes
       back, so while I've the series successfully restoring containers
       with different creds, if been merged the series won't work. So
       all changes are merged as appropriate)
    
     - drop module's global @cap_last_cap from pie/restorer.c
    
    Signed-off-by: Cyrill Gorcunov <gorcunov@openvz.org>
    Acked-by: Tycho Andersen <tycho.andersen@canonical.com>
    Signed-off-by: Pavel Emelyanov <xemul@parallels.com>

```

**Comment by cyrillos** [comment]
Heh, have no clue what the heck is it :) Just kidding. Thanks, I'll investigate.

**Comment by xemul** [comment]
4a0351d76ec47d8dcee16ff6cf3069bf1b183fc9
