### ISSUE TITLE
criu dump/restore a LXC container,  but "criu restore" failed

### ISSUE THREAD

**Issue by CrystalQian** [xemul/criu#99]
Hi, what I what to do is:
1.checkpoint and restore a LXC container on the same host.
2.checkpoint a LXC container on one host and restore it on another host.(live migration)
3.criu pre-dump -> criu dump -> scp -> criu restore(Iterative migration)
But, I got stuck in the 1st step when execute "criu restore" command. The particular procedures are in the following:

ISO file of VＭ is:   ubuntu-15.04-server-amd64.iso
root@lxcsrc2:~# hostname
lxcsrc2
root@lxcsrc2:~# uname -r
3.19.0-15-generic
root@lxcsrc2:~# criu -V
Version: 1.8
root@lxcsrc2:~# man lxc | grep Version
Version 1.1.0                      Wed Dec 16 06:55:43 UTC 2015                            lxc(7)
root@lxcsrc2:~# criu check --ms
Warn  (cr-check.c:624): Skipping PTRACE_O_SUSPEND_SECCOMP check
Warn  (cr-check.c:672): Skipping PTRACE_SECCOMP_GET_FILTER checkWarn  (cr-check.c:799): fdinfo doesn't contain the lock field
Looks good.
root@lxcsrc2:~# lxc-create -t ubuntu -n u1 -- -r trusty -a amd64
root@lxcsrc2:~# cat | sudo tee -a /var/lib/lxc/u1/config << EOF
\# hax for criu
lxc.console = none
lxc.tty = 0
lxc.cgroup.devices.deny = c 5:1 rwm
lxc.seccomp =
EOF

root@lxcsrc2:~# lxc-start -n u1
root@lxcsrc2:~# lxc-info -n u1
Name:           u1
State:          RUNNING
PID:            16011
IP:             10.0.3.108
CPU use:        1.33 seconds
BlkIO use:      10.08 MiB
Memory use:     17.74 MiB
KMem use:       0 bytes
Link:           veth8OS9O6
 TX bytes:      1.77 KiB
 RX bytes:      1.93 KiB
 Total bytes:   3.70 KiB
root@lxcsrc2:~# ssh ubuntu@10.0.3.108
The authenticity of host '10.0.3.108 (10.0.3.108)' can't be established.
ECDSA key fingerprint is f7:e8:9c:8a:ec:91:e9:dd:83:b7:f5:8a:cd:db:12:5d.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.0.3.108' (ECDSA) to the list of known hosts.
ubuntu@10.0.3.108's password:
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-15-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

ubuntu@u1:~$ exit
logout
Connection to 10.0.3.108 closed.

root@lxcsrc2:~# criu dump -t 16011 --enable-external-masters --ext-mount-map auto --file-locks -o dump.log -v3
root@lxcsrc2:~# cat dump.log | grep successful
(00.175265) Dumping finished successfully
root@lxcsrc2:~# ls
cgroup.img      eventpoll.img     ids-1813.img        packetsk.img      restore.log
checkpoint.log  fdinfo-10.img     ids-1815.img        pagemap-1537.img  route6-8.img
...... ...... ......

root@lxcsrc2:~# lxc-info -n u1
Name:           u1
State:          STOPPED
root@lxcsrc2:~# ps -elf | grep 16011
0 S root     17955   896  0  80   0 -  2054 pipe_w 17:54 pts/0    00:00:00 grep --color=auto 16011
root@lxcsrc2:~# criu restore
Error (mount.c:2403): mnt: No mapping for /sys/fs/cgroup/perf_event mountpoint

Now, you see the "criu restore" failed~!
Can you tell me how to make it?

**Comment by xemul** [comment]
Cc @tych0 

BTW, if you want to live migrate a container you're welcome to join the P.Haul efforts (https://github.com/xemul/p.haul).

**Comment by tych0** [comment]
On Fri, Dec 25, 2015 at 02:22:46AM -0800, BecauseofLxcCheckpoint wrote:
> Hi, what I what to do is:
> 1checkpoint and restore a LXC container on the same host
> 2checkpoint a LXC container on one host and restore it on another host(live migration)
> 3criu pre-dump -> criu dump -> scp -> criu restore(Iterative migration)
> But, I got stuck in the 1st step when execute "criu restore" command The particular procedures are in the following:
> 
> ISO file of VＭ is:   ubuntu-1504-server-amd64iso
> root@lxcsrc2:~# hostname
> lxcsrc2
> root@lxcsrc2:~# uname -r
> 3190-15-generic
> root@lxcsrc2:~# criu -V
> Version: 18
> root@lxcsrc2:~# man lxc | grep Version
> Version 110                      Wed Dec 16 06:55:43 UTC 2015                            lxc(7)
> root@lxcsrc2:~# criu check --ms
> Warn  (cr-checkc:624): Skipping PTRACE_O_SUSPEND_SECCOMP check
> Warn  (cr-checkc:672): Skipping PTRACE_SECCOMP_GET_FILTER checkWarn  (cr-checkc:799): fdinfo doesn't contain the lock field
> Looks good
> root@lxcsrc2:~# lxc-create -t ubuntu -n u1 -- -r trusty -a amd64
> root@lxcsrc2:~# cat | sudo tee -a /var/lib/lxc/u1/config << EOF
> > # hax for criu
> > lxcconsole = none
> > lxctty = 0
> > lxccgroupdevicesdeny = c 5:1 rwm
> > lxcseccomp =
> > EOF
> root@lxcsrc2:~# lxc-start -n u1
> root@lxcsrc2:~# lxc-info -n u1
> Name:           u1
> State:          RUNNING
> PID:            16011
> IP:             1003108
> CPU use:        133 seconds
> BlkIO use:      1008 MiB
> Memory use:     1774 MiB
> KMem use:       0 bytes
> Link:           veth8OS9O6
>  TX bytes:      177 KiB
>  RX bytes:      193 KiB
>  Total bytes:   370 KiB
> root@lxcsrc2:~# ssh ubuntu@1003108
> The authenticity of host '1003108 (1003108)' can't be established
> ECDSA key fingerprint is f7:e8:9c:8a:ec:91:e9:dd:83:b7:f5:8a:cd:db:12:5d
> Are you sure you want to continue connecting (yes/no)? yes
> Warning: Permanently added '1003108' (ECDSA) to the list of known hosts
> ubuntu@1003108's password:
> Welcome to Ubuntu 14043 LTS (GNU/Linux 3190-15-generic x86_64)
> 
>  * Documentation:  https://helpubuntucom/
> 
> The programs included with the Ubuntu system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright
> 
> Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
> applicable law
> 
> ubuntu@u1:~$ exit
> logout
> Connection to 1003108 closed
> 
> root@lxcsrc2:~# criu dump -t 16011 --enable-external-masters --ext-mount-map auto --file-locks -o dumplog -v3
> root@lxcsrc2:~# cat dumplog | grep successful
> (00175265) Dumping finished successfully
> root@lxcsrc2:~# ls
> cgroupimg      eventpollimg     ids-1813img        packetskimg      restorelog
> checkpointlog  fdinfo-10img     ids-1815img        pagemap-1537img  route6-8img
>   
> 
> root@lxcsrc2:~# lxc-info -n u1
> Name:           u1
> State:          STOPPED
> root@lxcsrc2:~# ps -elf | grep 16011
> 0 S root     17955   896  0  80   0 -  2054 pipe_w 17:54 pts/0    00:00:00 grep --color=auto 16011
> root@lxcsrc2:~# criu restore
> Error (mountc:2403): mnt: No mapping for /sys/fs/cgroup/perf_event mountpoint
> 
> Now, you see the "criu restore" failed~!
> Can you tell me how to make it?

What kernel versions are on each host?

**Comment by BecauseofLxcCheckpoint** [comment]
3.19.0-15-generic

**Comment by BecauseofLxcCheckpoint** [comment]
@tych0  I have mentioned Kernel version in the issue, but it is strange missing some symbols, here it is:
Kernel:  3.19.0-15-generic
CRIU: Version: 1.8
LXC: Version 1.1.0

**Comment by tych0** [comment]
Hmm. But the target host doesn't have perf_event mounted it seems. Can you
mount it and try again?

**Comment by BecauseofLxcCheckpoint** [comment]
I dump and restore on the same host in this issue. And , can you tell me how to mount perf_event? @tych0

**Comment by tych0** [comment]
On Mon, Dec 28, 2015 at 05:10:11PM -0800, BecauseofLxcCheckpoint wrote:
> I dump and restore on the same host in this issue. And , can you tell me how to mount perf_event? @tych0 

[Sorry for the delay, I'm on holiday]

Can you post the output of `crit show mountpoints-$somenumber.img` for
whatever nsid your mountpoints are? Also, what's the full dump log
with debugging enabled?

Thanks!

**Comment by BecauseofLxcCheckpoint** [comment]
Oops~! I am sad to see that the criu show is depercated and even no command 'crit' found~!
Since I have installed the CRIU, why no command 'crit' found? So I find the install crit command in Makefile, 'python scripts/crit-setup.py install --root=$(DESTDIR) --prefix=$(PREFIX)', and execute 'python scripts/crit-setup.py install' without --root and --perfix to install crit, and it works, it is strange.
root@lxcsrc2:~# criu -V
Version: 1.8
root@lxcsrc2:~# criu show
The "show" action is deprecated by the CRIT utility.
To view an image use the "crit decode -i $name --pretty" command.
root@lxcsrc2:~# crit decode
No command 'crit' found, did you mean:
 Command 'clit' from package 'convlit' (universe)
 Command 'criu' from package 'criu' (universe)
 Command 'crip' from package 'crip' (universe)
crit: command not found
root@lxcsrc2:~/criu-1.8# python scripts/crit-setup.py install
root@lxcsrc2:~/log# crit decode -i creds-1725.img --pretty
{
    "magic": "CREDS",
    "entries": [
        {
            "uid": 0,
            "gid": 0,
            "euid": 0,
            "egid": 0,
            "suid": 0,
            "sgid": 0,
            "fsuid": 0,
            "fsgid": 0,
            "cap_inh": [
                0,
                0
            ],
            "cap_prm": [
                4261347327,
                60
            ],
            "cap_eff": [
                4261347327,
                60
            ],
            "cap_bnd": [
                4261347327,
                60
            ],
            "secbits": 0,
            "groups": [
                0
            ],
            "lsm_profile": "lxc-container-default"
        }
    ]
}
root@lxcsrc2:~/log#

The full dump log url is: https://gist.github.com/BecauseofLxcCheckpoint

**Comment by tych0** [comment]
On Tue, Dec 29, 2015 at 07:23:38PM -0800, BecauseofLxcCheckpoint wrote:
> Oops~! I am sad to see that the criu show is depercated and even no command 'crit' found~!
> Since I have installed the CRIU, why no command 'crit' found? So I find the install crit command in Makefile, 'python scripts/crit-setup.py install --root=$(DESTDIR) --prefix=$(PREFIX)', and execute 'python scripts/crit-setup.py install' without --root and --perfix to install crit, and it works, it is strange.
> root@lxcsrc2:~# criu -V
> Version: 1.8
> root@lxcsrc2:~# criu show
> The "show" action is deprecated by the CRIT utility.
> To view an image use the "crit decode -i $name --pretty" command.
> root@lxcsrc2:~# crit decode
> No command 'crit' found, did you mean:
>  Command 'clit' from package 'convlit' (universe)
>  Command 'criu' from package 'criu' (universe)
>  Command 'crip' from package 'crip' (universe)
> crit: command not found
> root@lxcsrc2:~/criu-1.8# python scripts/crit-setup.py install
> root@lxcsrc2:~/log# crit decode -i creds-1725.img --pretty

Right, you can use `crit show` as I described above, though. Can you
show the mountpoints-* images?

> {
>     "magic": "CREDS",
>     "entries": [
>         {
>             "uid": 0,
>             "gid": 0,
>             "euid": 0,
>             "egid": 0,
>             "suid": 0,
>             "sgid": 0,
>             "fsuid": 0,
>             "fsgid": 0,
>             "cap_inh": [
>                 0,
>                 0
>             ],
>             "cap_prm": [
>                 4261347327,
>                 60
>             ],
>             "cap_eff": [
>                 4261347327,
>                 60
>             ],
>             "cap_bnd": [
>                 4261347327,
>                 60
>             ],
>             "secbits": 0,
>             "groups": [
>                 0
>             ],
>             "lsm_profile": "lxc-container-default"
>         }
>     ]
> }
> root@lxcsrc2:~/log#
> 
> The full dump log url is: https://gist.github.com/BecauseofLxcCheckpoint 

Can you do a checkpoint/restore with -v?

Thanks and sorry for the delay, I am back now.

Tycho

**Comment by BecauseofLxcCheckpoint** [comment]
haha, I have mistoken 'crit show' for 'criu show', here it is~!
root@lxcsrc2:~/log# crit show mountpoints-11.img
{
    "magic": "MNTS",
    "entries": [
        {
            "fstype": 5,
            "mnt_id": 297,
            "root_dev": 65,
            "parent_mnt_id": 294,
            "flags": "0x20000e",
            "root": "/",
            "mountpoint": "/run/user",
            "source": "none",
            "options": "size=102400k,mode=755",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 5,
            "mnt_id": 296,
            "root_dev": 64,
            "parent_mnt_id": 294,
            "flags": "0x200006",
            "root": "/",
            "mountpoint": "/run/shm",
            "source": "none",
            "options": "",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 5,
            "mnt_id": 295,
            "root_dev": 63,
            "parent_mnt_id": 294,
            "flags": "0x20000e",
            "root": "/",
            "mountpoint": "/run/lock",
            "source": "none",
            "options": "size=5120k",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 5,
            "mnt_id": 294,
            "root_dev": 62,
            "parent_mnt_id": 477,
            "flags": "0x20000a",
            "root": "/",
            "mountpoint": "/run",
            "source": "none",
            "options": "size=50088k,mode=755",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 4,
            "mnt_id": 293,
            "root_dev": 61,
            "parent_mnt_id": 481,
            "flags": "0x20000e",
            "root": "/",
            "mountpoint": "/proc/sys/fs/binfmt_misc",
            "source": "none",
            "options": "",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 6,
            "mnt_id": 292,
            "root_dev": 60,
            "parent_mnt_id": 478,
            "flags": "0x200000",
            "root": "/",
            "mountpoint": "/dev/pts",
            "source": "devpts",
            "options": "gid=5,mode=620,ptmxmode=666,newinstance",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 508,
            "root_dev": 38,
            "parent_mnt_id": 492,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/fs/cgroup/perf_event",
            "source": "/var/lib/lxcfs/cgroup/perf_event",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 507,
            "root_dev": 38,
            "parent_mnt_id": 492,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/fs/cgroup/net_cls,net_prio",
            "source": "/var/lib/lxcfs/cgroup/net_cls,net_prio",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 506,
            "root_dev": 38,
            "parent_mnt_id": 492,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/fs/cgroup/systemd",
            "source": "/var/lib/lxcfs/cgroup/name=systemd",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 505,
            "root_dev": 38,
            "parent_mnt_id": 492,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/fs/cgroup/memory",
            "source": "/var/lib/lxcfs/cgroup/memory",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 504,
            "root_dev": 38,
            "parent_mnt_id": 492,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/fs/cgroup/hugetlb",
            "source": "/var/lib/lxcfs/cgroup/hugetlb",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 503,
            "root_dev": 38,
            "parent_mnt_id": 492,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/fs/cgroup/freezer",
            "source": "/var/lib/lxcfs/cgroup/freezer",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 502,
            "root_dev": 38,
            "parent_mnt_id": 492,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/fs/cgroup/devices",
            "source": "/var/lib/lxcfs/cgroup/devices",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 501,
            "root_dev": 38,
            "parent_mnt_id": 492,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/fs/cgroup/cpuset",
            "source": "/var/lib/lxcfs/cgroup/cpuset",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 500,
            "root_dev": 38,
            "parent_mnt_id": 492,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/fs/cgroup/cpu,cpuacct",
            "source": "/var/lib/lxcfs/cgroup/cpu,cpuacct",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 499,
            "root_dev": 38,
            "parent_mnt_id": 492,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/fs/cgroup/blkio",
            "source": "/var/lib/lxcfs/cgroup/blkio",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 498,
            "root_dev": 38,
            "parent_mnt_id": 479,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/proc/uptime",
            "source": "/var/lib/lxcfs/proc/uptime",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 497,
            "root_dev": 38,
            "parent_mnt_id": 479,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/proc/stat",
            "source": "/var/lib/lxcfs/proc/stat",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 496,
            "root_dev": 38,
            "parent_mnt_id": 479,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/proc/meminfo",
            "source": "/var/lib/lxcfs/proc/meminfo",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 495,
            "root_dev": 38,
            "parent_mnt_id": 479,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/proc/diskstats",
            "source": "/var/lib/lxcfs/proc/diskstats",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 15,
            "mnt_id": 494,
            "root_dev": 38,
            "parent_mnt_id": 479,
            "flags": "0x280006",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/proc/cpuinfo",
            "source": "/var/lib/lxcfs/proc/cpuinfo",
            "options": "user_id=0,group_id=0,allow_other",
            "shared_id": 0,
            "master_id": 92,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 5,
            "mnt_id": 493,
            "root_dev": 20,
            "parent_mnt_id": 492,
            "flags": "0x1080000",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/fs/cgroup/cgmanager",
            "source": "/sys/fs/cgroup/cgmanager",
            "options": "mode=755",
            "shared_id": 0,
            "master_id": 9,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 5,
            "mnt_id": 492,
            "root_dev": 59,
            "parent_mnt_id": 484,
            "flags": "0x200000",
            "root": "/",
            "mountpoint": "/sys/fs/cgroup",
            "source": "cgroup",
            "options": "size=12k,mode=755",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 14,
            "mnt_id": 491,
            "root_dev": 55,
            "parent_mnt_id": 478,
            "flags": "0x200000",
            "root": "/",
            "mountpoint": "/dev/mqueue",
            "source": "mqueue",
            "options": "",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 8,
            "mnt_id": 490,
            "root_dev": 22,
            "parent_mnt_id": 484,
            "flags": "0x28000e",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/fs/pstore",
            "source": "/sys/fs/pstore/",
            "options": "",
            "shared_id": 0,
            "master_id": 11,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 9,
            "mnt_id": 489,
            "root_dev": 11,
            "parent_mnt_id": 484,
            "flags": "0x28000e",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/kernel/security",
            "source": "/sys/kernel/security/",
            "options": "",
            "shared_id": 0,
            "master_id": 8,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 11,
            "mnt_id": 488,
            "root_dev": 7,
            "parent_mnt_id": 484,
            "flags": "0x280000",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/kernel/debug",
            "source": "/sys/kernel/debug/",
            "options": "",
            "shared_id": 0,
            "master_id": 25,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 10,
            "mnt_id": 487,
            "root_dev": 34,
            "parent_mnt_id": 484,
            "flags": "0x280000",
            "root": "CRIU:AUTOGENERATED",
            "mountpoint": "/sys/fs/fuse/connections",
            "source": "/sys/fs/fuse/connections/",
            "options": "",
            "shared_id": 0,
            "master_id": 26,
            "ext_mount": true,
            "sb_flags": "0x0"
        },
        {
            "fstype": 2,
            "mnt_id": 486,
            "root_dev": 58,
            "parent_mnt_id": 485,
            "flags": "0x20000e",
            "root": "/devices/virtual/net",
            "mountpoint": "/sys/devices/virtual/net",
            "source": "sysfs",
            "options": "",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 2,
            "mnt_id": 485,
            "root_dev": 58,
            "parent_mnt_id": 484,
            "flags": "0x200000",
            "root": "/",
            "mountpoint": "/sys/devices/virtual/net",
            "source": "sysfs",
            "options": "",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 2,
            "mnt_id": 484,
            "root_dev": 58,
            "parent_mnt_id": 483,
            "flags": "0x20000f",
            "root": "/",
            "mountpoint": "/sys",
            "source": "sysfs",
            "options": "",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 2,
            "mnt_id": 483,
            "root_dev": 58,
            "parent_mnt_id": 477,
            "flags": "0x20000e",
            "root": "/",
            "mountpoint": "/sys",
            "source": "sysfs",
            "options": "",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 1,
            "mnt_id": 482,
            "root_dev": 56,
            "parent_mnt_id": 479,
            "flags": "0x20000f",
            "root": "/sysrq-trigger",
            "mountpoint": "/proc/sysrq-trigger",
            "source": "proc",
            "options": "",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 1,
            "mnt_id": 481,
            "root_dev": 56,
            "parent_mnt_id": 479,
            "flags": "0x20000f",
            "root": "/sys",
            "mountpoint": "/proc/sys",
            "source": "proc",
            "options": "",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 1,
            "mnt_id": 480,
            "root_dev": 56,
            "parent_mnt_id": 481,
            "flags": "0x20000e",
            "root": "/sys/net",
            "mountpoint": "/proc/sys/net",
            "source": "proc",
            "options": "",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 1,
            "mnt_id": 479,
            "root_dev": 56,
            "parent_mnt_id": 477,
            "flags": "0x20000e",
            "root": "/",
            "mountpoint": "/proc",
            "source": "proc",
            "options": "",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 5,
            "mnt_id": 478,
            "root_dev": 57,
            "parent_mnt_id": 477,
            "flags": "0x200000",
            "root": "/",
            "mountpoint": "/dev",
            "source": "none",
            "options": "size=100k,mode=755",
            "shared_id": 0,
            "master_id": 0,
            "sb_flags": "0x0"
        },
        {
            "fstype": 0,
            "mnt_id": 477,
            "root_dev": 8388609,
            "parent_mnt_id": 291,
            "flags": "0x280000",
            "root": "/var/lib/lxc/u1/rootfs",
            "mountpoint": "/",
            "source": "/dev/disk/by-uuid/57e10447-7622-4cb3-bfbd-c9d8588c5fc9",
            "options": "errors=remount-ro,data=ordered",
            "shared_id": 0,
            "master_id": 1,
            "sb_flags": "0x0"
        }
    ]
}
root@lxcsrc2:~/log#

**Comment by tycho** [comment]
You mean @tych0. ;)

Common mistake.

**Comment by xemul** [comment]
So, gents, what are the plans about this?

**Comment by CrystalQian** [comment]
Sorry , I don't know sir , I haven't stdied the LXC for a long time.@xemul

**Comment by tych0** [comment]
Whoops, sorry, I totally spaced this. I think the problem was just that perf_event wasn't mounted, but anyway, we don't support the 3.19 kernel any more, so we can close this for now, and re-open it (or perhaps just file a new bug) if something else beaks :)

**Comment by xemul** [comment]
OK :)
